-- EAST ASIAN BEVERAGE SESSION — PHASE 1: REGIONS
-- 23 new beverage_regions across Japan, China, Taiwan, India

BEGIN;

-- ============================================================
-- JAPAN — SAKE REGIONS
-- ============================================================
INSERT INTO beverage_regions (name, country, beverage_family, designation_type, designation_name, terroir_profile, quality_trajectory, reputation_tier, description, key_producers, historical_context, authority_tier, source_text, is_published) VALUES
('Niigata', 'Japan', 'sake', 'prefecture', 'Niigata-ken',
 '{"water": "ultra-soft snow-melt water from the Echigo Mountains; low mineral content produces the tanrei karakuchi (light-dry) style", "climate": "heavy snowfall insulates the kura (brewery) and maintains natural cold fermentation temperatures; long cold winters extend fermentation slowly", "rice": "Gohyakumangoku is the signature variety; high-starch, low-protein composition ideal for ginjo and daiginjo; also Koshi Tanrei (Niigata original)", "elevation": "flat coastal plain and mountain valleys; snow-melt provides consistent cold-water supply year-round"}',
 'ascending', 'iconic',
 'Niigata is the capital of the tanrei karakuchi (light-dry) sake style and home to more premium sake breweries per capita than any other prefecture. Its ultra-soft snow-melt water — low in minerals that would accelerate fermentation — produces a sake of exceptional delicacy and length. The prefecture''s 85+ active kura (breweries) have made Niigata synonymous with refined, food-friendly sake across Japan and internationally.',
 'Asahi Shuzo (Kubota), Hakkaisan Shuzo, Ishimoto Shuzo (Koshi no Kanbai), Yoshinogawa Shuzo, Niigata Meijo (Kakurei)',
 'Niigata''s sake tradition stretches back centuries, but its modern prestige was established post-WWII as brewers leveraged the prefecture''s soft water and cold climate to pioneer the ginjo movement. The 1984 Niigata Sake Festival (Niigata Sake no Jin) became one of Japan''s most celebrated sake events.',
 1, 'Japanese Sake and Brewing Culture; Niigata Sake Brewers Association', true),

('Nada', 'Japan', 'sake', 'district', 'Nada-ku, Kobe',
 '{"water": "Miyamizu — the defining hard water of Nada; high potassium and phosphorus content promotes vigorous yeast activity, producing the masculine, full-bodied Nada style called otokozake (man''s sake)", "climate": "temperate maritime, moderated by Osaka Bay; the Rokko mountain range provides seasonal cold air (rokkō oroshi) ideal for winter brewing", "rice": "Yamada Nishiki from the Tojo district of Hyogo — the undisputed king of sake rice, grown 30km from the breweries that use it", "geography": "five-district cluster: Nishigō, Mikage, Uozaki, Nishinomiya, Imazu — all sharing Miyamizu aquifer access"}',
 'established', 'iconic',
 'Nada (Nada-Gogo, the five districts of Nada) is historically Japan''s most prolific sake-producing region, responsible at peak for over 30% of all Japanese sake output. The Miyamizu water — discovered in 1840 by Tazaemon Yamamoto — is the defining element: its mineral richness produces the full-bodied, assertive otokozake (man''s sake) in direct contrast to the light-dry tanrei of Niigata. Home to the headquarters of Hakutsuru, Kiku-Masamune, Ozeki, and Sawanotsuru.',
 'Hakutsuru Sake Brewing, Kiku-Masamune Sake Brewing, Ozeki Sake, Sawanotsuru Sake Brewing, Nihonsakari',
 'Nada''s rise as Japan''s sake capital began in the Edo period with improved water transport via the port of Kobe. The discovery of Miyamizu — and its impact on fermentation speed and flavour — was a transformative moment in Japanese brewing history. Nada survived the 1995 Kobe earthquake and rebuilt rapidly.',
 1, 'Nada Sake Brewers Association; John Gauntner Sake World', true),

('Fushimi', 'Japan', 'sake', 'district', 'Fushimi-ku, Kyoto',
 '{"water": "Fushimi no Mizu — ultra-soft alkaline water from the Momoyama Highland aquifer; mineral-poor, producing the feminine, gentle fushime style called onnazake (woman''s sake) in contrast to Nada''s otokozake", "climate": "inland Kyoto basin; cold winter fog settles into the Fushimi district, maintaining low fermentation temperatures in traditional wooden kura", "rice": "Yamada Nishiki and Gohyakumangoku primarily; proximity to Kyoto''s culinary culture demands a lighter, more refined style", "geography": "situated at the junction of the Uji and Kizu rivers; historically a major transport hub connecting Kyoto to Osaka via boat"}',
 'established', 'prestigious',
 'Fushimi is Japan''s second-great sake city after Nada, producing the onnazake (woman''s sake) — soft, fragrant, and elegant — in direct stylistic contrast to Nada''s assertive Miyamizu-driven style. The Fushimi water is among the softest in Japan, producing sake of great finesse. Over 30 breweries remain active in the district, many in traditional machiya (townhouse) kura that have operated for centuries. The Fushimi Inari-Taisha shrine, dedicated to Uka no Mitama (a rice deity), stands adjacent.',
 'Gekkeikan Sake, Kizakura Sake Company, Masuda Tokubee Shoten (Tsuki no Katsura), Tamanohikari Sake Brewing, Saito Shuzo (Tozai)',
 'Fushimi''s brewing tradition dates to the Momoyama period (late 16th century) when Toyotomi Hideyoshi built his castle there. The district became synonymous with refined Kyoto sake culture, serving the imperial court and tea ceremony tradition. Gekkeikan, founded 1637, is among Japan''s oldest continuously operating sake companies.',
 1, 'Gekkeikan Museum; Fushimi Sake Brewery Association; Philip Harper The Book of Sake', true),

('Yamaguchi', 'Japan', 'sake', 'prefecture', 'Yamaguchi-ken',
 '{"water": "granite-filtered mountain water from the Chugoku mountains; medium-soft mineral profile", "climate": "mild Seto Inland Sea climate; warmer than Niigata, requiring precise temperature control for premium ginjo production", "rice": "Yamada Nishiki from Hyogo; high-precision polish ratios down to 23% for Dassai''s flagship; Dassai Senbonishiki developed specifically for their production", "geography": "western tip of Honshu; isolated from major sake centres, which ironically allowed Dassai to innovate without traditional constraints"}',
 'ascending', 'prestigious',
 'Yamaguchi''s place in modern sake history is entirely defined by one brewery: Asahi Shuzo and its Dassai brand. Founded 1948 in the remote Nishiki river valley of Yamaguchi, Dassai transformed itself from a struggling rural brewery to the global standard-bearer for premium Junmai Daiginjo sake — pioneering 50%, 39%, and then an unprecedented 23% polishing ratio. Dassai single-handedly created international awareness of daiginjo-class sake.',
 'Asahi Shuzo (Dassai)',
 'Asahi Shuzo was nearly bankrupt in the 1980s when third-generation owner Hiroshi Sakurai decided to bet everything on premium sake production. The gambit succeeded spectacularly. Today Dassai is sold in 70+ countries and a Dassai brewery operates in the Hudson Valley of New York (Dassai Blue). The original Yamaguchi facility remains the production home of Dassai 23 and Dassai Beyond.',
 1, 'Dassai official materials; Sake: A Modern Guide by Melinda Joe', true),

('Yamagata', 'Japan', 'sake', 'prefecture', 'Yamagata-ken',
 '{"water": "soft snowmelt water from the Ou and Dewa mountain ranges; low mineral content comparable to Niigata", "climate": "inland basin with extreme seasonal variation; continental cold winters and hot summers create high-stress rice growing conditions that concentrate flavour compounds", "rice": "Dewasansan and Dewa Kirari are Yamagata''s proprietary rice varieties; also Yamada Nishiki and Miyama Nishiki", "geography": "surrounded by three mountain ranges: Ou, Dewa, Asahi — creating a protected microclimate"}',
 'ascending', 'respected',
 'Yamagata has emerged as one of Japan''s most exciting sake prefectures, combining traditional technique with modern ginjo philosophy. The prefecture designates its own GI (Geographical Indication) — the first sake GI recognised under Japanese law — requiring all Yamagata GI sake to use locally grown rice and local water. Home to Juyondai (Takagi Shuzo), one of the most allocated and sought-after sakes in Japan, and Dewazakura, a ginjo movement pioneer.',
 'Takagi Shuzo (Juyondai), Dewazakura Shuzo, Takasago Shuzo',
 'Yamagata''s GI status, achieved in 2016, marked a turning point in Japanese sake regionalism — for the first time, a prefecture had legally defined and protected its sake identity. Juyondai, despite (or because of) its extreme scarcity and allocation system, has achieved cult status comparable to premier cru Burgundy.',
 1, 'Yamagata Sake GI documentation; John Gauntner Sake World', true),

('Fukui', 'Japan', 'sake', 'prefecture', 'Fukui-ken',
 '{"water": "snowmelt from the Echizen mountain range; soft water comparable to Niigata", "climate": "Japan''s heaviest snowfall region (Echizen), maintaining natural cold storage conditions; persistent winter cold allows slow fermentation at natural temperature", "rice": "Gohyakumangoku; Katokichibee Shouten uses locally contracted rice fields at Inbe-gawa basin", "geography": "Sea of Japan coastline; remote from major sake centres, creating an isolated brewing culture focused on perfection"}',
 'ascending', 'respected',
 'Fukui''s sake culture is defined by precision and restraint. Its single most important brewery — Katokichibee Shouten, makers of Born — has set a standard for ultra-premium Junmai Daiginjo that competes with Niigata and Yamaguchi at the highest level. Born''s use of extreme polishing ratios (39%, 35%), pristine cold water, and traditional pressing methods has earned it global recognition among sake connoisseurs.',
 'Katokichibee Shouten (Born)',
 'Katokichibee Shouten has been producing sake in Fukui since 1848. The modern Born brand, launched in the 1990s, represented a conscious decision to compete only at the ultra-premium level. Born was among the first Japanese sakes to achieve wide distribution in Europe and the USA, particularly in fine dining.',
 2, 'Katokichibee Shouten official materials; Sake World', true);

-- ============================================================
-- JAPAN — TEA REGIONS
-- ============================================================
INSERT INTO beverage_regions (name, country, beverage_family, designation_type, designation_name, terroir_profile, quality_trajectory, reputation_tier, description, key_producers, historical_context, authority_tier, source_text, is_published) VALUES
('Uji', 'Japan', 'tea', 'district', 'Uji-shi, Kyoto Prefecture',
 '{"soil": "red clay and decomposed granite soil (tsuchizuri) drains rapidly yet retains moisture at root level; mineral complexity feeds amino acid development", "water": "Uji River water — pristine snowmelt from the Tamba Highlands; historically used for both tea growing and tencha processing", "climate": "morning mist from the Uji River provides natural humidity; spring temperature inversions create ideal conditions for slow bud development; shade cultivation for 20+ days before first harvest", "elevation": "200–400m in the surrounding hills; steep slopes provide drainage and temperature differential between day and night", "cultivars": "Okumidori, Saemidori, Uji Hikari, and Gokou — cultivars selected over centuries for Uji''s specific conditions"}',
 'established', 'iconic',
 'Uji is the spiritual capital of Japanese tea. Its 800-year matcha and sencha tradition has set the global standard for shade-grown, stone-ground tea. The district''s unique combination of river mist, red clay soil, and centuries of cultivar selection produces the umami depth (theanine concentration from shade stress) that defines premium Japanese green tea. Uji matcha is the only tea considered appropriate for the highest levels of chanoyu (tea ceremony). The designation "Uji-cha" carries a GI protection under Japanese law.',
 'Ippodo Tea Co. (founded 1717), Marukyu Koyamaen, Nakamura Tokichi Honten (founded 1854), Kyoto Obubu Tea Farms',
 'Tea cultivation in Uji traces to the 13th century when Zen priest Eisai brought tea seeds from China and planted them on the hillside at Toganoozan. The Muromachi-period development of shade cultivation (tana technique) transformed Uji''s tea into a distinctive product unlike any other in Japan. Sen no Rikyū, the 16th-century tea master who codified chanoyu, sourced his matcha from Uji. This relationship — between the greatest tea and the greatest tea ceremony — has never changed.',
 1, 'Uji City Tourism Association; Ippodo Tea Co. history; Eric Dunkel Modern Japanese Tea', true),

('Shizuoka', 'Japan', 'tea', 'prefecture', 'Shizuoka-ken',
 '{"soil": "volcanic loam from Fuji-san; well-drained, mineral-rich soils from ancient lava flows", "climate": "Pacific climate with warm temperatures and high humidity; Mt. Fuji moderates temperature extremes; annual rainfall 2,300mm — ideal for tea without supplemental irrigation", "elevation": "Makinohara Plateau at 150–200m (volume production); Kawane district at 400–600m (premium quality); Honyama sub-district produces some of Japan''s finest deep-steamed sencha", "cultivars": "Yabukita (planted on 70%+ of all Shizuoka fields); Kanayamidori, Okumidori for specialty lots"}',
 'established', 'prestigious',
 'Shizuoka produces approximately 40% of Japan''s total tea volume, making it the workhorse of Japanese tea agriculture. Yet within this scale lies remarkable quality variation: the Honyama and Kawane sub-districts produce deep-steamed (fukamushi) sencha of exceptional body and green intensity. Shizuoka''s Makinohara Plateau, developed after the Meiji Restoration when unemployed samurai were given land grants for tea cultivation, is the most extensive flat tea-growing terrain in Japan.',
 'Marushige Shimizu, Oshima Tea Farm, Kaneka Seicha (Honyama), Nishide Tea Garden',
 'Shizuoka''s modern tea industry dates to the Meiji Restoration (1868) when the government encouraged tea cultivation to generate export revenue. The Makinohara Plateau was cleared by former samurai who had lost their stipends. Shizuoka''s proximity to Yokohama (Japan''s primary export port) made it the dominant export tea prefecture throughout the Meiji and Taisho periods.',
 1, 'Japan Tea Export Council; Shizuoka Tea Association', true),

('Kagoshima', 'Japan', 'tea', 'prefecture', 'Kagoshima-ken',
 '{"soil": "volcanic Shirasu (volcanic ash) soils from Sakurajima eruptions; unique mineral signature; high potassium and silica", "climate": "southernmost tea region in Japan; warm subtropical climate allows year-round growth and multiple harvests; first harvest (ichiban-cha) typically 2–3 weeks before Shizuoka and Uji", "elevation": "Chiran district at 180–350m; Kirishima at 600–900m — higher altitude Kirishima teas command premium prices", "cultivars": "Yabukita, Saemidori (Kagoshima''s specialty — produces vivid green colour and umami), Okumidori"}',
 'ascending', 'respected',
 'Kagoshima has emerged as Japan''s rising-star tea prefecture, leveraging its unique volcanic soil signature, warm subtropical climate, and ambitious cultivar breeding programme to produce sencha and Tamaryokucha (guricha) of increasing refinement. The Chiran district produces a clean, delicate style; the highland Kirishima zone produces teas with greater complexity and body. Kagoshima''s Saemidori cultivar — producing vivid green colour and high theanine — is now the most sought-after in Japan for premium sencha production.',
 'Kagoshima Chiran Tea Cooperative, Kirishima Tea Garden Association, Marushige Tea (Kagoshima)',
 'Kagoshima''s tea history is relatively recent — commercial cultivation began in the Meiji period, much later than Uji or Shizuoka. Its rapid ascent to quality prominence mirrors that of New World wine regions: a willingness to experiment combined with natural advantages (Shirasu soil, warm climate) has produced a distinctive regional identity.',
 2, 'Kagoshima Prefectural Tea Industry Research and Development Center', true);

-- ============================================================
-- JAPAN — SPIRITS REGIONS (Shochu / Awamori)
-- ============================================================
INSERT INTO beverage_regions (name, country, beverage_family, designation_type, designation_name, terroir_profile, quality_trajectory, reputation_tier, description, key_producers, historical_context, authority_tier, source_text, is_published) VALUES
('Kagoshima Shochu', 'Japan', 'spirits', 'prefecture', 'Kagoshima-ken Imo Shochu',
 '{"base_material": "Kogane Sengan sweet potato (satsuma-imo); grown in volcanic Shirasu soil that imparts a distinctive earthy sweetness; the sweet potato''s natural sugars and terroir character survive into the spirit", "koji": "black koji (Aspergillus luchuensis var. awamori) — the traditional Kyushu black koji that produces strong citric acid, protecting the mash and giving imo shochu its characteristic tartness and body", "water": "soft mountain water from the Kirishima range; low mineral content preserves the sweet potato''s delicate character", "distillation": "single pot distillation (honkaku jochu otsurui); atmospheric pressure preserves maximum flavour compounds"}',
 'established', 'prestigious',
 'Kagoshima is the heartland of imo (sweet potato) shochu — Japan''s most characterful base-material spirit. The Satsuma peninsula''s volcanic soil produces Kogane Sengan sweet potatoes with a depth of earthy sweetness that transfers into the spirit through single distillation with black koji. Over 120 active shochu distilleries make Kagoshima the world''s most concentrated shochu production zone. The prefecture has GI status (Satsuma Shochu) requiring all constituent shochu to be made from Kagoshima sweet potato and water.',
 'Kirishima Shuzo, Nishi Shuzo (Toko), Komasa Jokamachi, Satsuma Shuzo, Kure Shuzo',
 'Shochu arrived in Kyushu via the Korean peninsula in the 15th century, and Kagoshima''s sweet potato cultivation — introduced to Japan via Okinawa in the early Edo period — created the perfect match of base material and distillation tradition. The GI protection for Satsuma Shochu was established in 2005 under the WTO TRIPS agreement.',
 1, 'Kagoshima Shochu Association; Stefan Persson Shochu; Japan Sake and Shochu Makers Association', true),

('Oita', 'Japan', 'spirits', 'prefecture', 'Oita-ken Mugi Shochu',
 '{"base_material": "two-row barley (mugi) from Oita and Fukuoka; lighter base character than sweet potato; higher amino acid content from barley malt koji interaction creates distinctive mellow sweetness", "koji": "white koji (Aspergillus kawachii) primarily for mugi shochu — produces a gentler acidity than black koji, allowing barley''s natural sweetness to dominate", "water": "Oita''s mountain water from the Aso caldera range; medium-soft mineral profile", "distillation": "both single (honkaku) and some vacuum-distilled (genshu) expressions; Iichiko pioneered ultra-clean modern barley shochu through proprietary filtration"}',
 'established', 'respected',
 'Oita is Japan''s mugi (barley) shochu capital. While Kagoshima dominates imo shochu, Oita''s brewers — led by Sanwa Shurui with their Iichiko brand — created the modern category of refined, approachable barley shochu that brought the spirit to urban Japanese consumers in the 1980s. Iichiko''s clean, slightly sweet character made barley shochu the spirit of choice in izakayas from Tokyo to Fukuoka. Premium expressions from smaller distilleries like Nikaido Shuzo pursue deeper complexity.',
 'Sanwa Shurui (Iichiko), Nikaido Shuzo (Naka Naka), Sanyoshi Shuzo',
 'Barley cultivation in Oita began in the Edo period, and shochu production followed naturally. Iichiko''s 1979 launch of a premium mugi shochu in distinctive packaging — moving away from the rough agricultural image of traditional shochu — was a pivotal marketing moment that repositioned barley shochu as an aspirational spirit category.',
 2, 'Japan Sake and Shochu Makers Association; Oita Prefecture Tourism', true),

('Okinawa', 'Japan', 'spirits', 'prefecture', 'Okinawa-ken Awamori',
 '{"base_material": "100% long-grain Thai indica rice (imported from Thailand) — unique among Japanese spirits; the starch structure of indica rice produces a different fermentation profile than Japanese japonica", "koji": "black koji (Aspergillus luchuensis) exclusively — the original home of black koji, which arrived in Okinawa from Southeast Asia before spreading to Kyushu as the basis for shochu production", "ageing": "clay pot (kame) ageing — traditional terracotta vessels absorb and release minor aromatic compounds over decades; aged expressions called koshu develop extraordinary depth", "water": "Okinawa''s coral limestone-filtered water; medium-mineral content contributes to the spirit''s distinctive character", "distillation": "single pot distillation; higher ABV than shochu (typically 25–43%); some expressions at 60%+ for dilution before service"}',
 'established', 'prestigious',
 'Awamori is Japan''s oldest distilled spirit and Okinawa''s indigenous liquid culture — predating shochu by over 100 years. The spirit arrived via trade with Siam (Thailand) in the 15th century, bringing with it Thai indica rice and black koji that would later seed shochu production throughout Kyushu. Awamori''s ageing tradition — in clay pots (kame) for 3, 5, 10, 25, or even 50+ years — produces the category called koshu (aged awamori) with a depth and complexity rivaling aged rum or brandy. Over 45 distilleries remain active in Okinawa Prefecture.',
 'Zuisen Distillery, Helios Distillery, Kumesen Shuzo, Chatan Distillery (Zanpa), Harusame',
 'Awamori''s history began with the Ryukyu Kingdom''s active maritime trade with Southeast Asia and China. The Ryukyu royal court used awamori as diplomatic tribute to the Japanese mainland — records of awamori presented to the Edo shogunate date to 1719. The tradition of kame ageing may predate written records; some distilleries claim lineage of aged stock stretching back centuries, though few can fully verify provenance.',
 1, 'Okinawa Awamori Distillers Association; Ian Rist Whisky and Spirits', true);

-- ============================================================
-- CHINA — TEA REGIONS
-- ============================================================
INSERT INTO beverage_regions (name, country, beverage_family, designation_type, designation_name, terroir_profile, quality_trajectory, reputation_tier, description, key_producers, historical_context, authority_tier, source_text, is_published) VALUES
('Yunnan', 'China', 'tea', 'province', 'Yunnan Province — Xishuangbanna, Lincang, Pu-er City',
 '{"soil": "ancient red laterite soils in sub-tropical valleys; pH 4.5–5.5; rich in iron and aluminium", "climate": "tropical highland monsoon; Xishuangbanna at 500–1,800m; dramatic wet/dry seasonality defines harvest character; dry season produces finest spring teas", "cultivars": "Da Ye (large-leaf) Camellia sinensis var. assamica — the original wild tea tree of South Asia; ancient trees (gushu) 300–1,000+ years old produce prized gu shu (ancient tree) pu-erh", "geography": "Mekong river basin; the Lancang (Mekong) corridor is the genetic homeland of Camellia sinensis; wild tea forests still exist at elevation", "fermentation": "post-fermentation (wei jiao) defines pu-erh; sheng (raw) ages naturally; shou (cooked) undergoes accelerated pile fermentation (wo dui) at 50–65°C for 30–45 days"}',
 'established', 'iconic',
 'Yunnan is the birthplace of all tea — the genetic homeland of Camellia sinensis. Its ancient gushu (old tree) forests, some containing trees over 1,000 years old, produce pu-erh tea: the only tea category designed for multi-decade ageing. Pu-erh''s unique identity rests on its post-fermentation and compression into cakes or bricks — a storage format that enables trade via the ancient Tea Horse Road (Cha Ma Gu Dao) to Tibet and Central Asia. Sheng (raw) pu-erh is considered an investment commodity; aged examples from legendary mountains like Lao Ban Zhang, Yi Wu, and Bing Dao command prices rivaling first-growth Bordeaux.',
 'Menghai Tea Factory (Da Yi), Yunnan Sourcing, Chen Sheng Hao, Bao He Xiang, CNNP',
 'Yunnan''s tea history is the oldest in the world — local Bulang, Dai, and Hani ethnic minorities have cultivated and consumed tea for over 2,000 years. The Tea Horse Road, which carried pressed pu-erh bricks from Yunnan to Tibet in exchange for horses, operated continuously from the Tang Dynasty until the 20th century. Modern pu-erh''s international collectibility emerged after Hong Kong and Taiwanese collectors began aging and trading vintage cakes in the 1990s.',
 1, 'A Tea Lover Guide to Pu-erh by Scott Wilson; Liquid Jade by Beatrice Hohenegger', true),

('Fujian', 'China', 'tea', 'province', 'Fujian Province — Wuyi Mountains, Anxi, Fuding',
 '{"soil": "Wuyi: volcanic conglomerate and red sandstone (Danxia landform) — the jyan tú (rock soil) that gives yancha its mineral backbone; Anxi: sandy clay loam; Fuding: yellow podzolic mountain soils", "climate": "Wuyi: subtropical mountain climate, 1,500m peaks, persistent cloud cover and high humidity produce slow leaf development; Anxi: warmer and lower, 600–900m; Fuding: coastal maritime", "cultivars": "Wuyi: Da Hong Pao, Rou Gui, Shui Xian, Tie Luo Han, Shui Jin Gui — all rock oolongs; Anxi: Tieguanyin (Iron Goddess of Mercy), Ben Shan, Mao Xie; Fuding: Da Bai (Large White) and Da Hao for white tea", "rock_terroir": "Wuyi''s zhengyan (authentic rock area) designation — tea grown within the nature reserve''s core rock formations — commands 10-100x price premium over neighbouring ban yan (half-rock) areas"}',
 'established', 'iconic',
 'Fujian is the world capital of oolong tea and white tea, home to three globally significant tea categories within one province. The Wuyi Mountains produce yancha (rock oolong) — arguably the world''s most complex tea, with its unique mineral terroir called yanwei (rock taste). Anxi produces Tieguanyin, China''s most famous oolong and the basis of gongfu cha culture across Southeast Asia. Fuding produces Bai Hao Yinzhen (Silver Needle) and Bai Mudan (White Peony) — the prestige white teas. All three UNESCO-adjacent tea cultures share this single province.',
 'Wuyi Xingcun Tea Industry, Zhengshan Xiaochong, An Xi Tea Research Institute, Fuding Baicha Cooperative',
 'The Wuyi Mountains are the documented origin of gongfu cha (skill tea) practice — the small-vessel, high-leaf-to-water, multiple-infusion method that defines Chinese connoisseur tea culture. The Wuyi Rock Tea varieties were documented by Qing Dynasty botanical surveys and were among the first Chinese teas to reach Europe via the Dutch East India Company in the 17th century.',
 1, 'A Tea Lover Guide to Chinese Tea; Wuyi Mountain World Heritage Site documentation', true),

('Zhejiang', 'China', 'tea', 'province', 'Zhejiang Province — West Lake District, Anji, Tianmu',
 '{"soil": "Longjing: sandy clay loam over granite bedrock near West Lake; slightly acidic pH 5.0–5.5; unique mineral signature from proximity to the lake", "climate": "subtropical maritime; West Lake moderates temperature extremes; spring mists and consistent rainfall create ideal conditions for delicate pre-Qingming (first flush) teas", "elevation": "Longjing: 200–600m on West Lake hillsides; Anji: 700–900m mountain valleys for Anji Bai Cha (white tea cultivar)", "cultivars": "Longjing 43 (modern selection); Long Ye (dragon leaf) heirloom for Dragon Well; Anji Bai Cha — the albino cultivar that produces chartreuse-colored leaves with extreme amino acid content"}',
 'established', 'prestigious',
 'Zhejiang produces China''s most celebrated green tea: Longjing (Dragon Well) from the West Lake district of Hangzhou. Longjing''s pan-firing technique — the flat-leaf roasting in hot iron woks — produces its distinctive chestnut sweetness and toasty character, utterly unlike the steamed green teas of Japan. The pre-Qingming (before the Pure Brightness festival, early April) harvest is among the most expensive in the world. Anji Bai Cha — technically a white-leaf cultivar green tea — offers extraordinary amino acid concentration and delicate character.',
 'West Lake Longjing Tea Cooperative, Anji Bai Cha Association, Zhuyeqing Tea',
 'Longjing''s imperial prestige dates to the Qing Dynasty when Emperor Qianlong visited West Lake and designated 18 tea trees as imperial tribute trees — still growing and harvested today. The West Lake Longjing GI established strict terroir boundaries; teas grown outside the designated zone cannot be sold as Xi Hu Longjing.',
 1, 'West Lake Longjing GI documentation; The Story of Chinese Tea by Wang Ling', true),

('Guangdong', 'China', 'tea', 'province', 'Guangdong Province — Chaozhou/Phoenix Mountain (Fenghuang)',
 '{"soil": "granitic mountain soils at Phoenix Mountain (Fenghuangshan); poor nutrient soils stress the tea plants, concentrating aromatic compounds", "climate": "subtropical maritime; Phoenix Mountain at 1,000–1,497m (the summit) creates a distinct microclimate; frequent cloud cover, high humidity, temperature inversion traps cool air at elevation", "cultivars": "Dan Cong (single-trunk) — genetically distinct named cultivars propagated from individual exceptional trees: Mi Lan Xiang (honey orchid), Ya Shi Xiang (duck excrement/ammonia — now rebranded from the ironic earthiness), Ba Xian (Eight Immortals), Xing Ren Xiang (almond), Song Zhong (Song Dynasty variety — the oldest documented)", "processing": "heavy roasting over charcoal in traditional drums; multi-stage roasting develops deep caramel, longan, and chocolate notes without bitter roast character"}',
 'ascending', 'respected',
 'Guangdong''s Phoenix Mountain (Fenghuangshan) produces Dan Cong oolong — named for the practice of harvesting individual cultivar trees separately (dan = single, cong = bush/group). Each named Dan Cong variety carries a distinct aromatic profile: Mi Lan Xiang smells of honey and orchid, Ya Shi Xiang (Duck Excrement) of stone fruit and mineral, Ba Xian of longan and spice. The Chaozhou gongfu cha tradition — serving these complex oolongs in tiny cups with very hot water — is the epicentre of southern Chinese tea ceremony culture.',
 'Phoenix Village Tea Association, Wudong Mountain Tea Cooperative, Fenghuangshan Dan Cong Producers',
 'The Chaozhou people of Guangdong have practiced gongfu cha since at least the 17th century, and their tea culture has spread with the Chaozhou diaspora throughout Southeast Asia — forming the basis of tea culture in Malaysia, Thailand, and Singapore. The Song Zhong (Song Dynasty) variety is claimed to descend from trees planted over 900 years ago, though the unbroken lineage cannot be fully verified.',
 2, 'Chaozhou Tea Culture Research; Gongfu Cha by Warren Peltier', true);

-- ============================================================
-- CHINA — BAIJIU REGIONS
-- ============================================================
INSERT INTO beverage_regions (name, country, beverage_family, designation_type, designation_name, terroir_profile, quality_trajectory, reputation_tier, description, key_producers, historical_context, authority_tier, source_text, is_published) VALUES
('Guizhou', 'China', 'spirits', 'province', 'Guizhou Province — Zunyi, Maotai Town',
 '{"base_material": "sorghum (gaoliang) and wheat; Maotai uses a 1:1 ratio of locally grown hong ying zi sorghum (small red kaoliang) — its waxy starch resists over-saccharification", "qu": "medium-high temperature qu (fermentation starter) made from wheat; Maotai''s qu is produced in summer at 60°C+ — creating unique heat-tolerant bacterial communities", "water": "Chishui River — clean, medium-mineral; the specific microbiology of the Maotai river valley is considered non-replicable; multiple attempts to relocate production have failed", "geography": "river valley at 400m; encircled by cliffs that trap humidity and warmth; natural microbial terroir in the earth, walls, and air of the production valley", "fermentation": "solid-state fermentation in earthen pits (jiaoqiu); 8 rounds of fermentation over 1 year; each round adds new sorghum and qu while preserving previous round''s dregs"}',
 'ascending', 'iconic',
 'Guizhou produces Moutai (Maotai) — China''s national spirit and the world''s most valuable spirits brand by market capitalisation. The sauce aroma (jiangxiang) style produced in Maotai town''s river valley is characterised by deep umami, dried fruit, and roasted notes — completely unlike Western spirits paradigms. The Chishui River''s specific microbial ecology and the unique earth pit microbiology of Maotai town are considered essential and irreproducible terroir elements. Multiple attempts to replicate Moutai production elsewhere have failed.',
 'Kweichow Moutai Group, Lang Jiu (Lang Liquor), Guizhou Jinsha',
 'Moutai''s diplomatic history is remarkable: it was served at Richard Nixon''s 1972 state dinner in Beijing, effectively introducing Chinese culture to the Western world through a spirit. Henry Kissinger reportedly said he had more fear of Moutai than of nuclear weapons at negotiating tables. During the 1935 Long March, Communist forces reportedly used Moutai from the local distillery to treat wounds. Today, Kweichow Moutai''s market capitalisation exceeds the combined value of all Scotch whisky producers.',
 1, 'Derek Sandhaus Baijiu: The Essential Guide; Kweichow Moutai official history', true),

('Sichuan', 'China', 'spirits', 'province', 'Sichuan Province — Yibin, Luzhou',
 '{"base_material": "five-grain blend (wujia) for Wuliangye: sorghum, rice, glutinous rice, wheat, corn — each grain contributing distinct aromatic compounds; single-grain sorghum for most Luzhou expressions", "qu": "medium-temperature qu; sorghum-based pit fermentation using active earths from pits in continuous use since the Ming Dynasty (some pits 600+ years active)", "water": "Minjiang and Tuo River tributaries for Yibin; Luzhou draws from the Tuo River — medium-mineral, low-hardness", "earthen_pits": "Luzhou Laojiao''s oldest pit cellar dates to 1573 — continuous operation for 450+ years creates a unique microbial community irreplaceable elsewhere; the pit mud is itself a registered intangible cultural heritage", "geography": "Sichuan basin creates a warm, humid microclimate shielded from cold northern air by the Qinling-Daba mountains"}',
 'established', 'prestigious',
 'Sichuan is the home of strong aroma (nongxiang) baijiu — the most consumed baijiu style globally, accounting for over 70% of China''s total baijiu production. Wuliangye (five-grain liquor), produced in Yibin, is China''s second-most prestigious baijiu brand after Moutai, achieving its distinctive pineapple, ethyl acetate, and rich grain character through its unique five-grain blend and centuries-active earthen pit fermentation. Luzhou Laojiao''s 1573 pit cellars — in continuous operation since the Ming Dynasty — are China''s most historically significant fermentation infrastructure.',
 'Wuliangye Group, Luzhou Laojiao, Jiannanchun, Tuopai Shede',
 'The strong aroma style originated in Sichuan, where the unique combination of earthen pit microbiology and multi-grain fermentation created ethyl acetate-dominant aromatics unlike any other spirits tradition. Luzhou Laojiao''s 1573 pits were declared a national intangible cultural heritage in 2006. Wuliangye''s five-grain recipe is documented to the Qing Dynasty, though the company claims an 800-year lineage.',
 1, 'Derek Sandhaus Baijiu: The Essential Guide; Luzhou Laojiao Heritage documentation', true);

-- ============================================================
-- TAIWAN — TEA REGIONS
-- ============================================================
INSERT INTO beverage_regions (name, country, beverage_family, designation_type, designation_name, terroir_profile, quality_trajectory, reputation_tier, description, key_producers, historical_context, authority_tier, source_text, is_published) VALUES
('Central Taiwan Highlands', 'Taiwan', 'tea', 'region', 'Alishan, Lishan, Dayuling, Shanlinxi',
 '{"elevation": "Alishan: 1,000–1,800m; Lishan: 1,600–2,200m; Dayuling: 2,200–2,600m — Taiwan''s highest cultivated tea; each 100m additional elevation adds approximately one week to flush development", "soil": "mountain clay and granite decompose soils; high organic matter from forest litter; excellent drainage on steep slopes", "climate": "cool temperatures (average 12–18°C at Lishan elevation), diurnal temperature range of 15°C+; frequent cloud cover and morning mist; monsoon rain June–September; frost possible above 2,000m in winter", "cultivars": "Qingxin (Green Heart) — Taiwan''s prestige cultivar; thin leaves, delicate character; Jinxuan (TRES #12) — natural milky note; Cuiyu (TRES #13) — green floral", "altitude_effect": "slow growth at high elevation concentrates theanine, EGCG, and aromatic compounds; lower leaf output per plant = higher cost; gaoshan (high mountain) designation requires 1,000m+ elevation"}',
 'ascending', 'prestigious',
 'Taiwan''s Central Mountain Range produces the world''s finest high-mountain (gaoshan) oolong tea — a category unique to Taiwan''s geography, culture, and competitive auction system. The altitude effect is not merely symbolic: each 100m of elevation adds approximately one week to bud development, concentrating amino acids, polyphenols, and aromatic compounds. Alishan, Lishan, Dayuling, and Shanlinxi represent progressively higher and more prestigious elevations. Taiwan''s biannual government-sanctioned tea competitions (run by the Lugu Farmers'' Association for Dong Ding and by regional bodies for high mountain) create a graded quality hierarchy with transparent pricing.',
 'Alishan Farmers Association, Lishan Tea Cooperative, Wang Family Tea Farm (Dayuling), Dong Ding Tea Research',
 'High-mountain tea cultivation in Taiwan expanded dramatically in the 1970s–1990s as the Taiwan Road infrastructure project opened previously inaccessible mountain areas. Early settlers discovered that altitude produced exceptional oolong quality, and the gaoshan (high mountain) category emerged organically. Taiwan''s tea competition system — unique in the world — creates a meritocratic quality hierarchy and sets the market price for each grade.',
 1, 'Floating Leaves Tea educational materials; Ian Bersten and the Taiwan Tea Study Circle', true),

('Dong Ding', 'Taiwan', 'tea', 'district', 'Dong Ding Mountain, Lugu Township, Nantou County',
 '{"elevation": "800–1,200m on Dong Ding Mountain (Frozen Summit)", "soil": "mountain clay soils of Dong Ding; slightly acidic, well-drained on steep slopes", "climate": "temperate mountain climate; cooler and wetter than lowland Taiwan; mist-covered mornings provide natural humidity for leaf development", "cultivars": "Qingxin (Green Heart) — the traditional Dong Ding cultivar; full-oxidation, medium-roast processing is the traditional style", "processing": "medium oxidation (25–40%); traditional charcoal roasting in cloth-wrapped balls produces the classic roasted oolong style; competition-grade re-roasting adds depth and longevity", "competition": "Lugu Farmers Association biannual competition (spring and winter) grades teas into: Special Grade, First Grade, Second Grade, Third Grade — each with distinctive coloured ribbons; Special Grade commands 10–20x price premium"}',
 'established', 'respected',
 'Dong Ding Mountain gave its name to Taiwan''s most historically significant oolong style. The traditional Dong Ding oolong — medium-to-dark oxidation, charcoal-roasted, balled and rolled — is the foundation from which Taiwan''s tea culture grew. While high-mountain oolongs have surpassed it in prestige and price, Dong Ding remains the classic reference: deeply satisfying, roasted, with stone fruit and caramel notes that develop further with re-roasting. The Lugu Farmers Association competition is one of Taiwan''s most prestigious and longest-running agricultural competitions.',
 'Lugu Farmers Association, Dong Ding Tea Cooperative, traditional family farms of Dong Ding',
 'Dong Ding oolong is credited to a Fujian immigrant, Lin Feng Chi, who returned from China''s Wuyi Mountains in the 1850s with Qingxin oolong seedlings and planted them on Dong Ding Mountain. This origin story — though partially mythologised — captures the real lineage: Taiwanese oolong is Fujianese oolong adapted to Taiwan''s unique mountain terroir. The competition system began in 1975.',
 2, 'A Tea Lover Guide to Taiwanese Tea; Floating Leaves Tea', true);

-- ============================================================
-- INDIA — TEA REGIONS
-- ============================================================
INSERT INTO beverage_regions (name, country, beverage_family, designation_type, designation_name, terroir_profile, quality_trajectory, reputation_tier, description, key_producers, historical_context, authority_tier, source_text, is_published) VALUES
('Darjeeling', 'India', 'tea', 'district', 'Darjeeling District, West Bengal — GI Protected',
 '{"elevation": "600–2,100m on Himalayan slopes; steep terrain creates rapid drainage and cool growing conditions", "soil": "loamy mountain soils over gneiss bedrock; pH 5.0–5.5; low fertility forces plants to search deep and concentrate character", "climate": "three distinct growing seasons produce three flushes: spring (first flush March–May), summer (second flush May–June), autumn (autumnal October–November); monsoon (July–September) produces lower quality Banjhi/rain tea", "cultivars": "Chinese sinensis var. sinensis predominates (unlike Assam''s assamica variety); Chinese plants at Himalayan altitude produce the delicate, complex character unique to Darjeeling; clonal varieties TV1, B157, AV2 for specific characteristics", "muscatel": "second flush muscatel character — a unique combination of aromatic compounds including geraniol and DMNT triggered by leafhopper feeding and elevated temperature — is Darjeeling''s most prized and analysed flavour compound"}',
 'established', 'iconic',
 'Darjeeling is the Champagne of tea — the most prestigious and GI-protected single-origin tea in the world. Its three annual flushes produce tea of radically different character: the first flush (March–April) is pale, delicate, and floral; the second flush (May–June) produces the legendary muscatel — a grape-like, complex character unique on earth and triggered by specific environmental conditions. The district''s 87 registered tea estates span the Himalayan foothills, each with distinct microclimate. Makaibari, established 1859, is the world''s oldest tea estate. The GI protection, awarded in 2004, was India''s first agricultural GI.',
 'Makaibari Tea Estate, Castleton Tea Estate, Glenburn Tea Estate, Jungpana Tea Estate, Margaret''s Hope Tea Estate',
 'Darjeeling tea cultivation began in the 1840s when British botanist Archibald Campbell planted Chinese tea seeds from seeds smuggled out of China. The colonial development of over 100 tea estates by the 1880s established Darjeeling''s global reputation. The 2004 GI designation followed decades of battles against fraudulent labelling — estimates suggest that 10 times more "Darjeeling tea" is sold worldwide than Darjeeling actually produces.',
 1, 'Tea Board of India; Makaibari Tea Estate history; Tea: A User Guide by Tony Gebely', true),

('Assam', 'India', 'tea', 'state', 'Assam State — Brahmaputra Valley',
 '{"elevation": "river plain at 45–120m — the world''s only major low-elevation premium tea region; the Brahmaputra Valley''s extreme heat and humidity is the terroir", "soil": "rich alluvial deposits from the Brahmaputra; high organic matter; excellent water retention", "climate": "monsoonal with extreme heat (up to 38°C in summer); enormous annual rainfall (2,000–3,000mm); high humidity year-round; the heat and humidity drive rapid, intense growth that creates Assam''s malty, full-bodied character", "cultivars": "Camellia sinensis var. assamica — the indigenous wild variety discovered in Assam by Robert Bruce in 1823; large leaves, high caffeine, robust tannin; produces a black tea of power and body unmatched anywhere", "processing": "orthodox (whole-leaf rolling) for premium estates; CTC (crush-tear-curl) for the volume market; second flush produces tipping (golden tip content) that signals quality"}',
 'established', 'prestigious',
 'Assam is the world''s largest single tea-growing region, producing 50% of India''s total tea output from its Brahmaputra Valley estates. Assam''s Camellia sinensis var. assamica — the indigenous variety discovered growing wild in the jungle in 1823 — produces tea of unmatched body and malt character, forming the backbone of every British-style breakfast blend. Yet premium estate Assam, particularly second flush orthodox from the best estates (Halmari, Mokalbari, Rajgarh), reveals a complexity that transcends its breakfast-blend reputation: pure Assam malt, muscatel character, golden tips, and tremendous depth.',
 'Halmari Tea Estate, Mokalbari Tea Estate, Mangalam Tea Estate, Rajgarh Tea Estate',
 'Assam''s discovery changed global tea history: it proved that tea could grow outside China. Robert Bruce''s 1823 identification of wild Assam tea plants provided Britain an alternative to dependence on Chinese tea — a geopolitical necessity during the First Opium War. Commercial Assam tea production began in 1840, and by 1900 the Brahmaputra Valley had over 1,000 estates employing hundreds of thousands of workers.',
 1, 'Tea Board of India; The Unusual History of Assam Tea; Victor Mair Tea', true),

('Nilgiri', 'India', 'tea', 'district', 'Nilgiri Hills, Tamil Nadu and Kerala',
 '{"elevation": "Ooty plateau and surrounding hills at 1,200–2,500m (Blue Mountains); tea grown at all elevations with distinct quality variation", "soil": "rich red laterite and loam soils; good drainage on slopes; iron and aluminium rich", "climate": "unique bi-monsoonal pattern allows year-round production; southwest monsoon (June–September) and northeast monsoon (November–January); cool temperatures year-round moderated by altitude; the frost phenomenon: rare December/January frost produces ''frost tea'' of extraordinary intensity", "cultivars": "Camellia sinensis var. assamica primarily (high elevation) and hybrid cultivars; UPASI clonal varieties developed for Nilgiri conditions", "frost_tea": "frost-damaged leaves, when processed, concentrate aromatic compounds including geraniol — creating the ''frost tea'' phenomenon analogous to Botrytis concentration in wine"}',
 'ascending', 'respected',
 'The Nilgiri Hills — the Blue Mountains of South India — produce tea year-round, making them unique among India''s tea regions. While Darjeeling and Assam dominate prestige, Nilgiri''s best teas reveal a distinctive floral-fruity character, bright colour, and quick-brewing quality that makes them ideal for iced tea and flavoured blends. The frost tea phenomenon — a rare winter occurrence where overnight frost causes leaf cell damage, concentrating aromatic compounds — produces a small annual quantity of extraordinary Nilgiri tea with Darjeeling-like complexity. Nilgiri''s year-round production also enables fair labour practices unachievable in seasonal-harvest regions.',
 'Kairbetta Tea Estate, Glendale Tea Estate, Chamraj Tea Estate, Dunsandle Estate',
 'Nilgiri tea cultivation began in the 1830s under British colonial development, using the Ooty plateau''s cool climate and the new Madras Nilgiri Railway (completed 1908) for transport. The blue haze that gives the mountains their name — attributed to the oils released by the native Nilgiri shola forests — creates the atmospheric moisture that moderates Nilgiri''s growing conditions.',
 2, 'Nilgiri Tea Association; Tea Board of India; Jeff Koehler Darjeeling', true);

COMMIT;
