-- East Asian Phase 11d: Pairing Intelligence — Taiwan Tea (279–287) + India Tea (288–298)
-- ~80 entries

BEGIN;

INSERT INTO pairing_intelligence
  (beverage_product_id, beverage_category, beverage_style, beverage_description,
   food_category, food_flavour_profile, food_description,
   pairing_type, flavour_logic, meal_context, confidence, authority_tier, is_published)
VALUES

-- ============================================================
-- TAIWAN HIGH MOUNTAIN OOLONG (279-287)
-- ============================================================

-- 279: Alishan Spring Harvest
(279,'tea','oolong_high_mountain','Alishan Spring Oolong — cream, jasmine, milky sweetness; 1,400m',
 'seafood','delicate, sweet','Steamed scallop with mild ginger — clean and sweet',
 'complement','Alishan''s natural milk-cream note resonates with scallop''s natural glycine sweetness; both are produced at altitude''s pace — slow and precise','starter','established',2,true),
(279,'tea','oolong_high_mountain','Alishan Spring',
 'pastry','milky, light','Cream puff with light vanilla cream (choux pastry)',
 'complement','Alishan''s natural creamy texture echoes cream puff''s dairy character; the jasmine note lifts above the richness','dessert','established',2,true),
(279,'tea','oolong_high_mountain','Alishan Spring',
 'cheese','mild, cream','Fresh cream cheese with honey',
 'complement','Alishan''s milky character and cream cheese''s dairy share the same register; honey mediates between the floral tea and the sweet dairy','starter','adventurous',2,true),
(279,'tea','oolong_high_mountain','Alishan Spring',
 'confection','floral, sweet','Pineapple cake (feng li su) — Taiwanese pastry specialty',
 'complement','Alishan oolong with Taiwanese pineapple cake: the most classically Taiwanese tea-confection pairing','casual','classic',1,true),
(279,'tea','oolong_high_mountain','Alishan Spring',
 'fish','delicate, white','White fish en papillote with herbs — steamed in parchment',
 'complement','Spring Alishan''s floral freshness complements herb-steamed fish; both are expressions of spring''s clean abundance','fish_course','established',2,true),

-- 280: Alishan Winter Harvest
(280,'tea','oolong_high_mountain','Alishan Winter Oolong — osmanthus-honey; deeper sweetness than spring',
 'confection','osmanthus, honey','Osmanthus jelly with wolfberry — classic Chinese dessert',
 'complement','Winter Alishan''s osmanthus character resonates directly with osmanthus jelly; a direct flavour-ingredient match','dessert','classic',1,true),
(280,'tea','oolong_high_mountain','Alishan Winter',
 'pastry','honey, warm','Honey tart or honey cake — rich and warm',
 'complement','Winter harvest''s deeper honey sweetness matches honey-centric pastry; both are autumn/winter comfort expressions','dessert','established',2,true),
(280,'tea','oolong_high_mountain','Alishan Winter',
 'cheese','mild, honey-dressed','Aged fresh ricotta with wildflower honey',
 'complement','Osmanthus-honey oolong beside honey-dressed ricotta: multiple layers of floral sweetness in harmony','cheese','adventurous',2,true),
(280,'tea','oolong_high_mountain','Alishan Winter',
 'fruit','dried, sweet','Dried osmanthus and wolfberry infusion plate',
 'complement','Winter Alishan with the actual dried flowers whose name describes its character; a meditation on the flower','dessert','adventurous',2,true),

-- 281: Lishan 2,200m Wang Family
(281,'tea','oolong_high_mountain','Lishan Wang Family — mineral-crystalline; 2,200m; sharper than Alishan',
 'seafood','cold mineral, briny','Pacific oysters — no garnish; pure terroir expression',
 'complement','Lishan''s crystalline mineral character mirrors oyster''s mineral brine; both are expressions of their specific geography','starter','adventurous',2,true),
(281,'tea','oolong_high_mountain','Lishan Wang Family',
 'fish','clean, cold','Sashimi of cold-water white fish — hirame or kanpachi',
 'elevate','The crystalline clarity of 2,200m oolong elevates delicate cold-water sashimi by adding mineral dimension without weight','fish_course','adventurous',2,true),
(281,'tea','oolong_high_mountain','Lishan Wang Family',
 'vegetables','spring, mineral','White asparagus with mineral water reduction',
 'complement','Lishan''s mineral precision beside white asparagus with mineral water: terroir-to-terroir pairing of geological coherence','starter','experimental',2,true),
(281,'tea','oolong_high_mountain','Lishan Wang Family',
 'pastry','light, floral','Chrysanthemum and almond tart — delicate and precise',
 'complement','The precision of high-altitude oolong beside a precision-crafted delicate pastry; both reward careful attention','dessert','adventurous',2,true),

-- 282: Dayuling 2,500m
(282,'tea','oolong_high_mountain','Dayuling Ultra-High Mountain — the apex; glacial mineral, silk, 20-minute finish',
 'seafood','extreme premium','Oscietra caviar on warm potato blini',
 'elevate','Dayuling as a caviar companion: the mineral precision of 2,500m oolong complements caviar''s mineral brine without competition; exceptional pairing','amuse','adventurous',2,true),
(282,'tea','oolong_high_mountain','Dayuling',
 'fish','pristine, live','Ise ebi (Japanese spiny lobster) sashimi — alive to plate',
 'elevate','Dayuling deserves only the most pristine seafood; live-to-plate lobster provides the quality parity the tea demands','fish_course','adventurous',2,true),
(282,'tea','oolong_high_mountain','Dayuling',
 'confection','utterly minimal','Single piece of Kyoto first-grade namagashi wagashi',
 'elevate','The most restrained possible pairing: a single perfect wagashi beside the world''s most elevated oolong; a meditative pairing for the informed palate','pre_dessert','classic',1,true),
(282,'tea','oolong_high_mountain','Dayuling',
 'vegetables','pure, single','A single perfect piece of white radish with flake salt',
 'elevate','Dayuling''s complexity is so complete that the food companion should not compete; pure radish provides a clean, neutral amplification','amuse','experimental',2,true),

-- 283: Oriental Beauty
(283,'tea','oolong_oriental_beauty','Oriental Beauty — muscatel, wild honey; 70% oxidation; named by Queen Elizabeth',
 'pastry','stone fruit, honey','Apricot tart — ripe apricot, honey glaze, almond cream',
 'complement','Oriental Beauty''s muscatel-apricot character and apricot tart share the same stone-fruit aromatic compound; a direct resonance','dessert','classic',1,true),
(283,'tea','oolong_oriental_beauty','Oriental Beauty',
 'cheese','aged, sweet','Aged manchego with quince paste — nutty and sweet-sour',
 'complement','Oriental Beauty''s honey-muscatel beside manchego and quince: the stone-fruit character of quince bridges to the wine-grape note in the oolong','cheese','established',2,true),
(283,'tea','oolong_oriental_beauty','Oriental Beauty',
 'chocolate','honey, milk','Honey milk chocolate — natural sweetness',
 'complement','Wild honey character in Oriental Beauty and honey in the chocolate; beeswax bridges the two',  'dessert','established',2,true),
(283,'tea','oolong_oriental_beauty','Oriental Beauty',
 'pastry','dried fruit, complex','Panettone or stollen — complex dried fruit holiday bread',
 'complement','Oriental Beauty''s dried fruit complexity is amplified by fruit-bread''s own dried fruit content; a holiday pairing of warmth and richness','dessert','adventurous',2,true),
(283,'tea','oolong_oriental_beauty','Oriental Beauty',
 'wine','wine-like context','Served beside a late harvest Riesling comparison — educational',
 'bridge','Oriental Beauty is the tea most commonly compared to wine; side-by-side with a German Auslese Riesling reveals the muscatel compound they share','any','adventurous',2,true),

-- 284: Dong Ding Traditional Charcoal-Roasted
(284,'tea','oolong_dong_ding','Dong Ding Traditional — heavy charcoal roast; honey, aged wood, 1855 Wuyi lineage',
 'meat','roasted, caramelised','Crispy-skin pork belly — Cantonese siu yuk, lacquered',
 'complement','Traditional charcoal-roasted Dong Ding and roasted pork belly share the maillard reaction''s caramel-fat transformation','main','classic',1,true),
(284,'tea','oolong_dong_ding','Dong Ding Traditional',
 'cheese','aged, complex','Aged Comté 18+ month or Beaufort d''Alpage',
 'complement','The depth of traditional Dong Ding''s charcoal roasting resonates with the cave-aged complexity of mountain Swiss cheese','cheese','adventurous',2,true),
(284,'tea','oolong_dong_ding','Dong Ding Traditional',
 'chocolate','dark, roasted','70% dark with roasted cacao nibs on top',
 'complement','Charcoal roasting in the tea and roasted nibs in the chocolate: shared roast character across categories','dessert','adventurous',2,true),
(284,'tea','oolong_dong_ding','Dong Ding Traditional',
 'meat','braised, soy','Lu rou fan (Taiwanese braised pork rice) — slow-braised pork belly on rice',
 'complement','Dong Ding and lu rou fan is Taiwan''s most classical tea-food pairing; the roasted honey oolong complements the dark soy braise perfectly','main','classic',1,true),

-- 285: Dong Ding Modern Light Roast
(285,'tea','oolong_dong_ding','Dong Ding Modern — light roast; buttery, lily, clean',
 'seafood','delicate, steamed','Steamed clams in garlic and white wine butter',
 'complement','Light Dong Ding''s buttery note complements clam butter sauce; both are light preparations that reward attention','starter','established',2,true),
(285,'tea','oolong_dong_ding','Dong Ding Modern',
 'vegetables','mild, steamed','Silken tofu with mild dashi and spring onion',
 'complement','Light-roast Dong Ding''s buttery quality pairs with silken tofu''s clean protein; both are expressions of gentle restraint','starter','established',2,true),
(285,'tea','oolong_dong_ding','Dong Ding Modern',
 'pastry','buttery, cream','Custard tart — Taiwanese-Portuguese egg tart style',
 'complement','Modern Dong Ding and Taiwanese egg tart: a contemporary pairing of Taiwan''s most popular confection and tea','casual','classic',1,true),
(285,'tea','oolong_dong_ding','Dong Ding Modern',
 'cheese','fresh, mild','Mild cream cheese or fromage blanc',
 'contrast','Light Dong Ding''s floral butter contrasting cream cheese''s neutral dairy; the tea''s mild structure makes it one of the more cheese-compatible oolongs','cheese','adventurous',2,true),

-- 286: Jin Xuan Milk Oolong
(286,'tea','oolong_high_mountain','Jin Xuan Milk Oolong — natural cultivar cream; no additive; Floating Leaves sourcing',
 'pastry','creamy, light','Choux pastry with light pastry cream — profiterole style',
 'complement','Natural milk-cream character of Jin Xuan and pastry cream''s dairy: a pairing where the tea''s character mirrors the food''s primary flavour','dessert','classic',1,true),
(286,'tea','oolong_high_mountain','Jin Xuan Milk Oolong',
 'confection','taro, light','Taro mochi or taro ball dessert — Taiwanese specialty',
 'complement','Jin Xuan''s taro-cream note resonates with actual taro in dessert; a self-referential Taiwan pairing','dessert','classic',1,true),
(286,'tea','oolong_high_mountain','Jin Xuan Milk Oolong',
 'seafood','light, cream-sauced','Scallop with light cream sauce and herb',
 'complement','The cultivar''s natural cream note amplifies cream sauce while the oolong''s delicacy does not overwhelm the scallop''s sweetness','starter','established',2,true),
(286,'tea','oolong_high_mountain','Jin Xuan Milk Oolong',
 'pastry','taro, mild','Pan-fried taro cake (wu tao gou) — light and savory-sweet',
 'complement','Jin Xuan is the ideal tea for taro-based Taiwanese comfort food; the cream resonance is immediate and pleasant','casual','classic',1,true),

-- 287: Baozhong Pouchong
(287,'tea','oolong_baozhong','Baozhong — lightest Taiwan oolong; fresh orchid, gardenia; 15% oxidation',
 'vegetables','spring, fresh','Spring vegetable amuse — pea shoots, spring onion, edible flowers',
 'complement','Baozhong is the spring oolong; spring vegetable amuse is the spring food; a pairing of seasonal intentions','amuse','classic',1,true),
(287,'tea','oolong_baozhong','Baozhong',
 'fish','delicate, cured','Light-cured white fish with elderflower oil',
 'complement','Baozhong''s orchid-gardenia note resonates with elderflower''s own floral register; delicacy on all sides','starter','adventurous',2,true),
(287,'tea','oolong_baozhong','Baozhong',
 'pastry','light, floral','Elderflower panna cotta — light and barely set',
 'complement','Baozhong''s fresh garden-flower character beside elderflower panna cotta: floral resonance in food and beverage','dessert','established',2,true),
(287,'tea','oolong_baozhong','Baozhong',
 'confection','light, minimal','Fresh flower petal confection — Japanese namagashi with sakura',
 'complement','The lightest Taiwan oolong beside the lightest wagashi: a pairing of pure flower character','pre_dessert','classic',1,true),

-- ============================================================
-- INDIA TEA — DARJEELING (288-292)
-- ============================================================

-- 288: Makaibari First Flush Biodynamic
(288,'tea','darjeeling_first_flush','Makaibari First Flush — biodynamic, muscatel, spring; world''s oldest tea factory',
 'pastry','delicate, floral','Elderflower and lemon tart — pale and barely sweet',
 'complement','First flush Darjeeling''s floral-citrus note resonates with elderflower-lemon; both are early-spring expressions of floral delicacy','dessert','established',2,true),
(288,'tea','darjeeling_first_flush','Makaibari First Flush',
 'fish','very light, raw','Trout carpaccio with dill and lemon oil — barely dressed',
 'complement','First flush Darjeeling''s lightness (15-20% oxidation) can accompany very delicate raw fish without overwhelming','starter','adventurous',2,true),
(288,'tea','darjeeling_first_flush','Makaibari First Flush',
 'pastry','buttery, plain','Plain butter shortbread — minimal sweetness',
 'complement','First flush''s bright muscatel character is best revealed with a neutral, buttery backdrop; shortbread provides exactly this','casual','classic',1,true),
(288,'tea','darjeeling_first_flush','Makaibari First Flush',
 'confection','light, floral','Spring flower macarons — rose, violet, elderflower',
 'complement','Spring first flush and spring flower confections: a seasonal pairing for an afternoon tea menu','dessert','established',2,true),
(288,'tea','darjeeling_first_flush','Makaibari First Flush',
 'cheese','fresh, light','Fresh chèvre with light herb — clean and barely aged',
 'contrast','First flush Darjeeling''s brightness contrasting fresh chèvre''s lactic acid; the wine-like character of first flush makes it the most cheese-compatible Darjeeling','cheese','adventurous',2,true),

-- 289: Castleton Second Flush Muscatel
(289,'tea','darjeeling_second_flush','Castleton Second Flush — the apex muscatel; Muscat grape, apricot, full',
 'pastry','stone fruit, cream','Apricot tart with almond cream — Alsatian style',
 'complement','Castleton''s apricot-muscatel character with apricot tart: the most direct stone-fruit resonance in this collection','dessert','classic',1,true),
(289,'tea','darjeeling_second_flush','Castleton Second Flush',
 'cheese','aged, nutty','Aged gouda 3-year or mature Comté — complex, nutty',
 'complement','Second flush muscatel has enough structure for aged cheese; the apricot note meets the caramel of aged gouda','cheese','adventurous',2,true),
(289,'tea','darjeeling_second_flush','Castleton Second Flush',
 'pastry','honey, warm','Honey-almond cake — warm, rich, seasonal',
 'complement','The warm richness of honey-almond cake is complemented by the full body of second flush muscatel; both peak in warmth','dessert','established',2,true),
(289,'tea','darjeeling_second_flush','Castleton Second Flush',
 'chocolate','mild, fruity','Milk chocolate with dried apricot — complementary',
 'complement','The apricot note in Castleton muscatel beside milk chocolate with actual apricot; ingredient-echo pairing','dessert','established',2,true),

-- 290: Glenburn Second Flush
(290,'tea','darjeeling_second_flush','Glenburn Second Flush — more floral and softer than Castleton; estate story',
 'pastry','rose, cream','Rose petal and cream scone — British afternoon tea style',
 'complement','Second flush Darjeeling is the authentic afternoon tea beverage; Glenburn''s floral profile beside a rose petal scone creates narrative coherence','casual','classic',1,true),
(290,'tea','darjeeling_second_flush','Glenburn Second Flush',
 'cheese','medium, semi-hard','Mild cheddar 12-month or young Leicester',
 'complement','Second flush Darjeeling and British cheese: the cultural pairing of the most English tea and its traditional dairy companion','cheese','classic',1,true),
(290,'tea','darjeeling_second_flush','Glenburn Second Flush',
 'pastry','floral, light','Earl Grey shortbread (bergamot and butter)',
 'complement','Both Glenburn''s floral profile and Earl Grey shortbread''s bergamot share a floral-citrus register; a tea-family pairing','casual','established',2,true),
(290,'tea','darjeeling_second_flush','Glenburn Second Flush',
 'fruit','fresh, berry','Fresh strawberries with light cream — summer',
 'complement','Glenburn''s rose-petal note and fresh strawberries are a classic summer combination; the tea''s muscatel amplifies the berry''s own aromatic','dessert','classic',1,true),

-- 291: Jungpana Autumnal
(291,'tea','darjeeling_autumnal','Jungpana Autumn Flush — malty, dried fruit, woodsy; best with milk',
 'pastry','spiced, autumn','Autumn spice cake — cinnamon, nutmeg, raisin',
 'complement','Autumn flush Darjeeling and autumn spice cake: both are autumn expressions of warm, dried-fruit character','dessert','established',2,true),
(291,'tea','darjeeling_autumnal','Jungpana Autumnal',
 'cheese','sharp, aged','Extra mature cheddar — 24-month; sharp and full',
 'complement','Autumnal Darjeeling with a large splash of milk beside sharp cheddar: the traditional British cheese-tea pairing at its most direct','cheese','classic',1,true),
(291,'tea','darjeeling_autumnal','Jungpana Autumnal',
 'confection','dried fruit, rich','Christmas pudding or fruit cake — dense and complex',
 'complement','Autumn flush and fruit cake: both celebrate dried fruit and warmth; a winter celebration pairing','dessert','classic',1,true),
(291,'tea','darjeeling_autumnal','Jungpana Autumnal',
 'meat','light, savory','Chicken sandwich with mild mustard — afternoon tea classic',
 'complement','The autumnal malt structure (ideal with milk) creates a proper malty tea for a savoury afternoon tea sandwich','casual','classic',1,true),

-- 292: Jungpana Darjeeling White Tea
(292,'tea','white_tea','Jungpana Darjeeling White Silver Tips — muscatel in delicate white tea form',
 'confection','honey, floral','White honey and elderflower panna cotta',
 'complement','The delicate muscatel of Darjeeling white tea beside honey-elderflower: a floral-honey pairing of extraordinary delicacy','dessert','adventurous',2,true),
(292,'tea','white_tea','Jungpana Darjeeling White',
 'pastry','spring, light','Spring petits fours — pale, barely sweet',
 'complement','Darjeeling white tea is a discovery piece for an afternoon tea programme; pale, delicate petits fours match its register','dessert','suggested',2,true),
(292,'tea','white_tea','Jungpana Darjeeling White',
 'fish','very delicate','Cucumber and dill finger sandwich — British afternoon tea',
 'complement','The most delicate Darjeeling beside the most delicate afternoon tea sandwich; restraint in parallel','casual','established',2,true),
(292,'tea','white_tea','Jungpana Darjeeling White',
 'seafood','cold, clean','Cold poached shrimp with light citrus dip',
 'complement','Darjeeling white''s muscatel note with cold shrimp''s natural sweetness; a discovery pairing for the adventurous afternoon tea guest','starter','adventurous',2,true),

-- ============================================================
-- ASSAM (293-295)
-- ============================================================
(293,'tea','assam_orthodox','Halmari Assam First Flush — lighter, more floral than second flush',
 'pastry','buttery, light','Plain scone with clotted cream and light jam',
 'complement','Assam first flush is light enough to accompany a plain scone without overpowering the clotted cream','casual','classic',1,true),
(293,'tea','assam_orthodox','Halmari First Flush',
 'cheese','mild, mild','Young cheddar or mild Caerphilly',
 'complement','First flush Assam''s lighter body works with milder cheese than the classic second flush; a gentler British pairing','cheese','established',2,true),
(293,'tea','assam_orthodox','Halmari First Flush',
 'confection','light honey','Mild honey cake with lemon drizzle',
 'complement','First flush''s honey-malt note beside honey-lemon cake: the lighter Assam allows citrus to contribute without conflict','dessert','established',2,true),
(293,'tea','assam_orthodox','Halmari First Flush',
 'meat','light, sandwich','Cucumber and cream cheese sandwich — afternoon tea',
 'complement','First flush Assam is versatile enough for delicate afternoon tea sandwiches; its body sits without overpowering','casual','classic',1,true),

(294,'tea','assam_orthodox','Halmari Second Flush Classic — benchmark Assam; malt, caramel, full; world''s best',
 'pastry','fruity, dense','Victoria sponge with jam and cream — classic British',
 'complement','Second flush Assam with whole milk beside Victoria sponge is quintessentially British; the malt cuts the sponge cream','casual','classic',1,true),
(294,'tea','assam_orthodox','Halmari Second Flush',
 'cheese','sharp, aged','Extra mature cheddar 24+ month — sharp, full',
 'complement','The most classic British pairing: strong malty Assam with milk beside aged British cheddar; malt and sharpness in balance','cheese','classic',1,true),
(294,'tea','assam_orthodox','Halmari Second Flush',
 'pastry','warm, spiced','Warm ginger parkin — treacle, ginger, oat-based',
 'complement','Second flush Assam''s malt and caramel resonates with treacle-ginger parkin''s dark warmth','dessert','classic',1,true),
(294,'tea','assam_orthodox','Halmari Second Flush',
 'meat','savory, robust','Egg and watercress sandwich — high tea format',
 'complement','Second flush Assam is the correct tea for a robust savoury high tea; its malt handles the egg richness','casual','classic',1,true),

(295,'tea','assam_blend','Harney & Sons Irish Breakfast — CTC Assam; strong, consistent, for milk service',
 'pastry','everyday, British','Everyday scone and butter — morning service',
 'complement','Irish Breakfast is designed for morning service with milk; a plain scone beside a pot of this Assam is the accessible template','casual','classic',1,true),
(295,'tea','assam_blend','Harney Irish Breakfast',
 'meat','savory, breakfast','Full Irish breakfast — bacon, sausage, eggs, toast',
 'complement','Irish Breakfast Assam with milk beside a full cooked breakfast: the classic morning pairing that defined the tea''s name','casual','classic',1,true),
(295,'tea','assam_blend','Harney Irish Breakfast',
 'cheese','strong, accessible','Aged sharp cheddar or pub cheese',
 'complement','Strong CTC Assam with milk and aged cheddar: an everyday accessible British-tradition cheese-tea pairing','cheese','classic',1,true),
(295,'tea','assam_blend','Harney Irish Breakfast',
 'pastry','everyday, oat','Digestive biscuit or oat cracker — British standard',
 'complement','Irish Breakfast Assam and digestive biscuit: the fundamental, honest British pairing of daily tea service','casual','classic',1,true),

-- ============================================================
-- NILGIRI (296-297) + DARJEELING OOLONG (298)
-- ============================================================
(296,'tea','nilgiri_frost','Kairbetta Nilgiri Frost Tea — natural sweetness, menthol, frost-stress eucalyptus',
 'pastry','light, eucalyptus','Eucalyptus honey tart — Southern European style',
 'complement','Nilgiri frost tea''s natural eucalyptus-menthol note beside eucalyptus honey: a rare flavour-ingredient bridge across hemispheres','dessert','adventurous',2,true),
(296,'tea','nilgiri_frost','Kairbetta Nilgiri Frost',
 'confection','mint, cool','Peppermint and white chocolate bark',
 'complement','Frost tea''s cool menthol character beside peppermint chocolate: the cool register amplifies in both directions','dessert','established',2,true),
(296,'tea','nilgiri_frost','Kairbetta Nilgiri Frost',
 'cheese','mild, fresh','Fresh fromage frais with light honey',
 'contrast','The natural sweetness of frost tea and the light lactic of fromage frais: a gentle contrast of sugar and acid','cheese','adventurous',2,true),
(296,'tea','nilgiri_frost','Kairbetta Nilgiri Frost',
 'pastry','winter, spiced','Cardamom shortbread — South Indian spice tradition',
 'complement','Nilgiri''s frost tea from Tamil Nadu beside South Indian cardamom shortbread: regional pairing of shared terroir','casual','established',2,true),
(296,'tea','nilgiri_frost','Kairbetta Nilgiri Frost',
 'meat','light, curry','Mild chicken korma — gentle spice, cream sauce',
 'complement','Frost tea''s natural sweetness moderates mild curry spice while its clean eucalyptus note cuts through cream sauce','main','adventurous',2,true),

(297,'tea','nilgiri_orthodox','Harney Nilgiri Black — bright, clean, best for iced tea',
 'pastry','everyday','Lemon pound cake — simple, citrus-forward',
 'complement','Nilgiri''s citrus-bright character beside lemon cake: citrus resonance across tea and pastry','casual','established',2,true),
(297,'tea','nilgiri_orthodox','Harney Nilgiri',
 'fruit','tropical','Mango lassi (with Nilgiri as the base tea) — iced tea cocktail',
 'bridge','Nilgiri''s bright clean character makes it the ideal iced tea base for a mango-spiced tea drink; both are South Asian','casual','adventurous',2,true),
(297,'tea','nilgiri_orthodox','Harney Nilgiri',
 'meat','light, Indian','Chicken tikka — charred, mild spice',
 'complement','Nilgiri as a refreshing iced accompaniment to tandoor-grilled chicken: a South Asian regional pairing','casual','established',2,true),
(297,'tea','nilgiri_orthodox','Harney Nilgiri',
 'pastry','citrus, light','Lemon drizzle cake — bright and simple',
 'complement','Nilgiri''s bright character and lemon drizzle share the same refreshing citrus register','casual','classic',1,true),

-- 298: Glenburn Darjeeling Oolong
(298,'tea','oolong_darjeeling','Glenburn Darjeeling Oolong — muscatel in oolong form; 40-50% oxidation; multiple infusions',
 'seafood','delicate, fresh','Scallop with ponzu butter — East-West preparation',
 'complement','Darjeeling oolong''s muscatel-cream character beside scallop in ponzu butter: the East-West preparation matches the East-West tea style','starter','adventurous',2,true),
(298,'tea','oolong_darjeeling','Glenburn Darjeeling Oolong',
 'cheese','mild, fruity','Young Gouda with apricot jam',
 'complement','Darjeeling oolong''s muscatel-apricot note beside Gouda and actual apricot: a fruity cheese pairing with multiple resonances','cheese','adventurous',2,true),
(298,'tea','oolong_darjeeling','Glenburn Darjeeling Oolong',
 'pastry','muscatel, fruit','Muscat grape tart — Alsatian style',
 'complement','Darjeeling oolong''s defining muscatel note beside an actual muscat grape tart: the most direct flavour-ingredient pairing in this collection','dessert','adventurous',2,true),
(298,'tea','oolong_darjeeling','Glenburn Darjeeling Oolong',
 'vegetables','light, spring','White asparagus with light herb butter',
 'complement','Darjeeling oolong''s spring character and spring asparagus: a cross-cultural seasonal pairing','starter','established',2,true);

COMMIT;
