-- East Asian Phase 11c: Pairing Intelligence — China Tea (247–269) + Baijiu (270–277)
-- ~130 entries

BEGIN;

INSERT INTO pairing_intelligence
  (beverage_product_id, beverage_category, beverage_style, beverage_description,
   food_category, food_flavour_profile, food_description,
   pairing_type, flavour_logic, meal_context, confidence, authority_tier, is_published)
VALUES

-- ============================================================
-- PU-ERH: 247-251
-- ============================================================

-- 247: Dayi 7542 Sheng (Raw) Pu-erh Cake
(247,'tea','puerh_sheng','Dayi 7542 — young sheng pu-erh; astringent, grassy, ageing potential',
 'cheese','aged hard','Aged gouda 2-year — caramel note; medium intensity',
 'complement','Young sheng''s astringency is moderated by aged gouda''s fat; the caramel in the cheese bridges to the tea''s evolving sweetness','cheese','adventurous',2,true),
(247,'tea','puerh_sheng','Dayi 7542',
 'meat','fatty, roasted','Peking duck — skin-on, lacquered; fatty and rich',
 'cleanse','Young sheng pu-erh''s astringency cuts through Peking duck fat; an astringent-tannin that mirrors the function of red wine beside duck','main','adventurous',2,true),
(247,'tea','puerh_sheng','Dayi 7542',
 'dimsum','savory, pork','Char siu bao (bbq pork bao) — sweet-savory filling',
 'cleanse','Sheng pu-erh beside dim sum is a Hong Kong tradition; the astringency cuts through pork fat while the sweetness of the bao moderates the tea''s sharpness','casual','classic',1,true),
(247,'tea','puerh_sheng','Dayi 7542',
 'chocolate','dark, intense','80% dark chocolate — bitter, minimal sugar',
 'complement','Young sheng''s bitter-grassy tannin and dark chocolate''s bitter roast tannin share a structural resonance','dessert','adventurous',2,true),

-- 248: Dayi 7572 Shou (Ripe) Pu-erh
(248,'tea','puerh_shou','Dayi 7572 — ripe shou pu-erh; earthy, smooth, immediate drinking',
 'meat','braised, rich','Hong shao rou (red-braised pork belly) — Hunan or Shanghai style',
 'complement','Shou pu-erh''s earthy smoothness complements braised fatty pork; shared fermentation culture; classic southern Chinese pairing','main','classic',1,true),
(248,'tea','puerh_shou','Dayi 7572',
 'dimsum','various, rich','Dim sum — full table service including har gow, siu mai, cheung fun',
 'complement','Shou pu-erh as the dim sum yum cha tea is the authentic Cantonese tradition; earthy character clears palate between dishes','casual','classic',1,true),
(248,'tea','puerh_shou','Dayi 7572',
 'cheese','washed rind','Taleggio or Pont-l''Evêque — strong, earthy, creamy rind',
 'complement','Shou pu-erh''s earth and mushroom notes with washed rind cheese''s barn character: a cross-cultural earthy pairing','cheese','adventurous',2,true),
(248,'tea','puerh_shou','Dayi 7572',
 'chocolate','milk, earthy','Milk chocolate with hazelnut — Valrhona style',
 'bridge','Shou pu-erh''s caramel-earth and milk chocolate''s dairy bridge through hazelnut''s own nutty earth character','dessert','established',2,true),

-- 249: Yunnan Sourcing Yiwu Ancient Tree Sheng
(249,'tea','puerh_sheng','Yunnan Sourcing Yiwu Ancient Tree — honey-floral, elegant, traceable',
 'seafood','delicate, sweet','Crab and corn soup — Cantonese style; sweet and delicate',
 'complement','Yiwu''s honey-floral character echoes the sweetness of fresh crab; both are gentle expressions of natural sweetness','starter','adventurous',2,true),
(249,'tea','puerh_sheng','Yunnan Sourcing Yiwu',
 'fruit','tropical, fresh','Longan or lychee — fresh fruit; natural sweetness',
 'complement','Yiwu sheng''s distinctive longan-honey character resonates with fresh longan; origin and flavour converge','dessert','classic',1,true),
(249,'tea','puerh_sheng','Yunnan Sourcing Yiwu',
 'confection','floral, light','Chrysanthemum and wolfberry jelly — traditional Chinese dessert',
 'complement','The honey-floral note of Yiwu ancient tree with floral chrysanthemum jelly: complementary flower-honey register','dessert','established',2,true),
(249,'tea','puerh_sheng','Yunnan Sourcing Yiwu',
 'cheese','mild, fresh','Fresh chèvre with wild honey — light acidity',
 'contrast','Yiwu''s honey character and fresh chèvre''s lactic acid: a delicate contrast moderated by wild honey','cheese','experimental',2,true),

-- 250: Yunnan Sourcing Crimson Flame Dianhong Gold Tips
(250,'tea','black_tea','Yunnan Sourcing Dianhong — golden-tipped Yunnan black; no astringency, honey-malt',
 'pastry','honey, buttery','Croissant with honey butter — morning or afternoon',
 'complement','Dianhong''s natural honey-malt character pairs perfectly with honey butter; both warm and comforting without competing','casual','classic',1,true),
(250,'tea','black_tea','Dianhong Gold Tips',
 'chocolate','milk, honey','Honey milk chocolate — mild and sweet',
 'complement','The natural honey in Dianhong and honey in chocolate amplify each other; both feature golden malt warmth','dessert','classic',1,true),
(250,'tea','black_tea','Dianhong Gold Tips',
 'meat','light, savory','Duck confit with plum sauce — mild preparation',
 'complement','Dianhong''s dried fruit note resonates with plum sauce''s sweetness; duck''s fat is moderated by the tea''s clean finish','main','adventurous',2,true),
(250,'tea','black_tea','Dianhong Gold Tips',
 'cheese','aged, sweet','Aged manchego with quince paste',
 'complement','Honey-malt Dianhong and aged manchego-quince: a shared sweet-savory balance','cheese','adventurous',2,true),

-- 251: Yunnan Sourcing 2012 Aged Sheng Pu-erh
(251,'tea','puerh_sheng_aged','Yunnan Sourcing 2012 Aged Sheng — 12+ years dry storage; dried fruit, camphor, leather',
 'cheese','complex, aged','Aged Comté 24+ month or Gruyère — crystalline, complex',
 'elevate','Aged sheng pu-erh and aged cheese share the transformation language of time; both develop from sharp origins into complex maturity','cheese','adventurous',2,true),
(251,'tea','puerh_sheng_aged','Yunnan 2012 Aged Sheng',
 'meat','aged, cured','Aged prosciutto di Parma or Jamón Ibérico de Bellota',
 'complement','Aged sheng''s leather and tobacco notes meet aged cured ham''s complexity; both reach similar aromatic depths through different aging processes','casual','adventurous',2,true),
(251,'tea','puerh_sheng_aged','Yunnan 2012 Aged Sheng',
 'chocolate','dark, bitter','Single-origin 85% dark — no sweetness',
 'complement','Aged sheng''s complex tannins and dark chocolate''s tannins: a parallel structure at maximum expression','digestif','adventurous',2,true),
(251,'tea','puerh_sheng_aged','Yunnan 2012 Aged Sheng',
 'fruit','dried, complex','Prune, dried fig, and candied orange peel — a digestif fruit plate',
 'complement','The dried longan and dried plum aromatics in aged sheng resonate directly with the physical dried fruits; flavour-ingredient pairing','digestif','established',2,true),

-- ============================================================
-- WUYI ROCK OOLONG: 252-255
-- ============================================================
(252,'tea','oolong_rock','Wuyi Xingcun Da Hong Pao — Zhengyan yan yun; intense roasted mineral',
 'meat','roasted, fatty','Char siu (Cantonese BBQ pork) — lacquered with dark sweetness',
 'complement','The roasted complexity and mineral depth of Da Hong Pao mirrors the maillard reaction and caramelisation of char siu; both are products of high-heat transformation','main','classic',1,true),
(252,'tea','oolong_rock','Wuyi Da Hong Pao',
 'chocolate','dark, roasted','Dark chocolate with smoked salt — 72% single origin',
 'complement','Rock oolong''s charcoal-roasted character and dark chocolate''s roasted bitterness are parallel expressions of heat transformation','dessert','adventurous',2,true),
(252,'tea','oolong_rock','Wuyi Da Hong Pao',
 'cheese','aged, hard','Aged Manchego or Pecorino Romano — strong and crystalline',
 'complement','The mineral rock rhyme (yan yun) of Da Hong Pao finds its closest food parallel in the mineral depth of aged sheep cheese','cheese','adventurous',2,true),
(252,'tea','oolong_rock','Wuyi Da Hong Pao',
 'meat','braised, rich','Red-cooked duck (hong shao ya) — Shanghainese dark soy braise',
 'cleanse','Intense roasted oolong cuts through braised duck fat; the caramel-soy glaze resonates with the tea''s roast character','main','established',2,true),
(252,'tea','oolong_rock','Wuyi Da Hong Pao',
 'confection','dark, molasses','Nian gao (New Year cake) — glutinous rice with brown sugar',
 'complement','The caramel-mineral depth of Da Hong Pao resonates with the dark sweetness of nian gao; festive Chinese New Year pairing','celebration','classic',1,true),

(253,'tea','oolong_rock','Wuyi Xingcun Shui Xian — floral orchid rock oolong; approachable yancha',
 'vegetables','roasted, light','Roasted chestnuts — street-style, warm',
 'complement','Shui Xian''s creamy orchid note and the warm, earthy sweetness of roasted chestnuts: autumn coherence','casual','classic',1,true),
(253,'tea','oolong_rock','Wuyi Shui Xian',
 'pastry','light, honey','Egg tart (dan tat) — Cantonese pastry, warm',
 'complement','Shui Xian''s vanilla-orchid character complements egg tart''s custard sweetness; classic Cantonese tea pairing','casual','classic',1,true),
(253,'tea','oolong_rock','Wuyi Shui Xian',
 'cheese','semi-hard, mild','Fontina or mild Raclette — meltable, mild',
 'contrast','The orchid-floral note of Shui Xian contrasts interestingly with mild alpine cheese''s grassy nuttiness','cheese','adventurous',2,true),
(253,'tea','oolong_rock','Wuyi Shui Xian',
 'meat','roasted, light','Roast chicken with herbs — simple, clean',
 'complement','Shui Xian''s approachability means it pairs with less aggressive main courses than Da Hong Pao','main','established',2,true),

(254,'tea','oolong_rock','Wuyi Xingcun Rou Gui — cinnamon spice rock oolong; warming and aromatic',
 'meat','spiced, bold','Five-spice roast duck — with star anise, cinnamon crust',
 'complement','Rou Gui''s natural cinnamon character resonates with the cinnamon in five-spice; spice mirrors spice','main','classic',1,true),
(254,'tea','oolong_rock','Wuyi Rou Gui',
 'dessert','spiced, warm','Spiced apple tart with cinnamon pastry cream',
 'complement','The cinnamon-spice note of Rou Gui is a natural companion to a spiced apple dessert; warm-weather resonance','dessert','established',2,true),
(254,'tea','oolong_rock','Wuyi Rou Gui',
 'chocolate','dark, spiced','Mexican dark chocolate with chili — 70%, intense',
 'complement','Rou Gui''s warmth and spice beside spiced dark chocolate: a building complexity of warm flavours','dessert','adventurous',2,true),
(254,'tea','oolong_rock','Wuyi Rou Gui',
 'cheese','aged, spiced','Aged Gouda with cumin — Leyden cheese style',
 'complement','Cinnamon rock oolong and cumin-spiced gouda: bold spice-forward pairing for adventurous cheese service','cheese','adventurous',2,true),

(255,'tea','black_tea','Wuyi Xingcun Jin Jun Mei — all-bud Wuyi black; honey-sweet, no astringency',
 'pastry','honey, floral','Honey financier with dried chrysanthemum',
 'complement','Jin Jun Mei''s natural honey-chrysanthemum character and honey-chrysanthemum financier: self-referential pairing of extraordinary coherence','dessert','classic',1,true),
(255,'tea','black_tea','Wuyi Jin Jun Mei',
 'cheese','mild, fresh','Mild fresh chèvre — simple and clean',
 'contrast','Jin Jun Mei''s sweetness and chèvre''s light lactic acid: a refined and quiet contrast','cheese','adventurous',2,true),
(255,'tea','black_tea','Wuyi Jin Jun Mei',
 'chocolate','white, honey','White chocolate with honey ganache',
 'complement','Jin Jun Mei''s honey character and white chocolate''s dairy-honey: one of the most naturally sympathetic tea-chocolate pairings','dessert','established',2,true),
(255,'tea','black_tea','Wuyi Jin Jun Mei',
 'pastry','delicate, cream','Mille-feuille with jasmine cream',
 'complement','The floral honey note of Jin Jun Mei meets jasmine cream in a French-Chinese cross-cultural pairing of delicacy','dessert','adventurous',2,true),

-- ============================================================
-- WHITE TEA (256-257), TIEGUANYIN (258-259)
-- ============================================================
(256,'tea','white_tea','Song Tea Silver Needle Yin Zhen — Fuding white; pristine and delicate',
 'seafood','sweet, pristine','Oyster with cucumber granita — minimalist',
 'complement','Silver Needle''s cool cucumber-melon character resonates directly with the cucumber granita; the oyster provides the mineral anchor','starter','adventurous',2,true),
(256,'tea','white_tea','Silver Needle',
 'fish','delicate, raw','Hamachi crudo with yuzu oil and micro shiso',
 'complement','The delicacy of Silver Needle requires the most delicate food pairings; hamachi crudo in citrus oil is precise','starter','established',2,true),
(256,'tea','white_tea','Silver Needle',
 'pastry','light, floral','White peach and elderflower tart — pale, barely sweet',
 'complement','The white peach note of Silver Needle and actual white peach in the tart: a direct flavour-ingredient resonance','dessert','classic',1,true),
(256,'tea','white_tea','Silver Needle',
 'amuse','clean, minimal','Japanese cold tofu amuse with light dashi jelly',
 'complement','The neutrality of tofu provides the cleanest backdrop for Silver Needle''s delicate aromatics; neither competes','amuse','established',2,true),

(257,'tea','white_tea','Song Tea Bai Mu Dan White Peony — more body than Silver Needle',
 'pastry','honey, light','Honey madeleines or financiers',
 'complement','White Peony''s honey-hay character and honey-based pastries: natural sweetness alignment','casual','classic',1,true),
(257,'tea','white_tea','Bai Mu Dan',
 'fruit','fresh, clean','Honeydew melon — chilled, barely dressed',
 'complement','White Peony''s melon-rind note meets actual melon; a direct fruit-resonance pairing','dessert','established',2,true),
(257,'tea','white_tea','Bai Mu Dan',
 'cheese','mild, young','Fresh burrata with light herb oil',
 'contrast','White tea''s delicate grassy note contrasting burrata''s milky richness; the tea cleanses between bites','starter','adventurous',2,true),
(257,'tea','white_tea','Bai Mu Dan',
 'confection','light, soft','Pâte de fruit — fruit jellies with fine sugar coating',
 'complement','Both white tea and fruit pâtes are expressions of restrained natural sweetness; the pairing is a celebration of subtlety','dessert','established',2,true),

(258,'tea','oolong_tieguanyin','Song Tea Tieguanyin Traditional Roasted — charcoal-baked orchid-honey',
 'meat','roasted, light','Char siu pork (medium char) — Cantonese BBQ',
 'complement','Roasted Tieguanyin''s caramelised orchid-honey and char siu''s caramelised glaze: parallel roasting expressions','main','classic',1,true),
(258,'tea','oolong_tieguanyin','Tieguanyin Roasted',
 'pastry','baked, golden','Egg tart (Macanese style) — caramelised surface',
 'complement','Both have undergone caramelisation through heat; the pairing resonates through the maillard reaction','casual','classic',1,true),
(258,'tea','oolong_tieguanyin','Tieguanyin Roasted',
 'cheese','aged, hard','Aged Comte or Gruyère — nutty, complex',
 'complement','Traditional roasted Tieguanyin and aged Swiss cheese share the depth that only time and heat can produce','cheese','adventurous',2,true),
(258,'tea','oolong_tieguanyin','Tieguanyin Roasted',
 'chocolate','dark, complex','62% dark chocolate with orange peel',
 'complement','The roasted orchid and caramel of Tieguanyin complement dark chocolate''s orange-roast character','dessert','adventurous',2,true),

(259,'tea','oolong_tieguanyin','Song Tea Tieguanyin Jade Green — qingxiang style; intensely floral, buttery',
 'seafood','sweet, delicate','Scallop sashimi with yuzu vinaigrette — cold and clean',
 'elevate','Jade Tieguanyin''s orchid intensity elevates delicate scallop by adding aromatic dimension without weight','starter','adventurous',2,true),
(259,'tea','oolong_tieguanyin','Tieguanyin Green',
 'pastry','floral, creamy','Osmanthus cake — floral Chinese confection',
 'complement','Jade Tieguanyin''s gardenia-lily character and osmanthus cake''s flower character: a meeting of flowers','dessert','classic',1,true),
(259,'tea','oolong_tieguanyin','Tieguanyin Green',
 'vegetables','light, spring','Chilled white asparagus with light vinaigrette',
 'complement','The buttery green quality of jade Tieguanyin complements white asparagus''s vegetable butter character','starter','adventurous',2,true),
(259,'tea','oolong_tieguanyin','Tieguanyin Green',
 'cheese','fresh, cream','Cream cheese with lychee — light and sweet',
 'complement','The floral note of green Tieguanyin and the floral note of lychee converge; cream cheese provides the dairy bridge','starter','adventurous',2,true),

-- ============================================================
-- LONGJING (260-262), DANCONG (263-266), RISHI (267-269)
-- ============================================================
(260,'tea','green_tea_china','West Lake Longjing Mingqian — chestnut-sweet, no astringency, pre-Qingming',
 'vegetables','spring, delicate','Stir-fried pea shoots (dou miao) with garlic — spring',
 'complement','Pre-Qingming Longjing and the first spring pea shoots: the earliest produce and the earliest tea harvest converging','starter','classic',1,true),
(260,'tea','green_tea_china','Longjing Mingqian',
 'seafood','delicate, sweet','Steamed shrimp dumplings (har gow) — translucent, delicate',
 'complement','The chestnut-sweet character of tribute Longjing complements har gow''s shrimp sweetness; a Cantonese yum cha pairing','casual','classic',1,true),
(260,'tea','green_tea_china','Longjing Mingqian',
 'fish','poached, light','Poached Mandarin fish with ginger and scallion oil',
 'complement','One of Hangzhou''s classical pairings: West Lake Longjing beside Hangzhou-style poached fish (the tea and the fish are regional siblings)','fish_course','classic',1,true),
(260,'tea','green_tea_china','Longjing Mingqian',
 'pastry','delicate, neutral','Almond tuile — crisp, barely sweet',
 'complement','The chestnut-sesame note of tribute Longjing with the almond note of tuile: nut bridges nut across cultures','dessert','established',2,true),

(261,'tea','green_tea_china','West Lake Longjing Yuqian — spring grade; more body than Mingqian',
 'dimsum','savory, light','Har gow and crystal dumplings — standard dim sum selection',
 'complement','Longjing is the traditional Hangzhou tea for dim sum yum cha; Yuqian provides more body than Mingqian for this function','casual','classic',1,true),
(261,'tea','green_tea_china','Longjing Yuqian',
 'vegetables','stir-fried, clean','Longjing shrimp (Longjing xia ren) — Hangzhou speciality with tea leaves cooked in',
 'complement','The famous dish uses Longjing leaves in the wok; serving the tea beside the dish is the authentic Hangzhou experience','main','classic',1,true),
(261,'tea','green_tea_china','Longjing Yuqian',
 'cheese','mild, neutral','Mild Swiss cheese or young Comté',
 'contrast','Spring Longjing''s chestnut-butter character with mild Swiss: a light East-West contrast pairing','casual','adventurous',2,true),
(261,'tea','green_tea_china','Longjing Yuqian',
 'pastry','neutral, light','Plain shortbread or water cracker',
 'cleanse','A neutral cracker serves as a between-infusion cleanse that resets the palate for next cup''s slightly different character','any','established',2,true),

(262,'tea','green_tea_china','West Lake Longjing Late Spring — everyday grade; accessible and consistent',
 'noodles','savory, everyday','Cold sesame noodles — lunch or casual',
 'cleanse','Late-spring Longjing is an everyday tea; sesame noodles are an everyday lunch; together they represent accessible pairing quality','casual','established',2,true),
(262,'tea','green_tea_china','Longjing Late Spring',
 'dimsum','everyday','Rice congee with various toppings — morning yum cha',
 'complement','Longjing and congee: the traditional Cantonese morning pairing that has lasted a thousand years','casual','classic',1,true),
(262,'tea','green_tea_china','Longjing Late Spring',
 'vegetables','stir-fried, savory','Stir-fried bok choy with oyster sauce',
 'cleanse','Longjing''s clean astringency refreshes after oyster sauce''s sweetness-richness','main','established',2,true),
(262,'tea','green_tea_china','Longjing Late Spring',
 'pastry','everyday','Sesame flatbread (shao bing) — street food',
 'complement','Everyday street food and everyday tea: an accessible, coherent casual pairing','casual','classic',1,true),

-- Dancong 263-266
(263,'tea','oolong_dancong','Phoenix Village Mi Lan Xiang — honey orchid dancong; extraordinary aromatic',
 'pastry','honey, floral','Honey-glazed pastry with osmanthus — Cantonese style',
 'complement','Mi Lan Xiang''s honey-orchid intensity resonates directly with honey-osmanthus pastry; floral bridges floral','dessert','classic',1,true),
(263,'tea','oolong_dancong','Mi Lan Xiang Dancong',
 'fruit','tropical, sweet','Fresh lychee or rambutan — tropical sweetness',
 'complement','Mi Lan Xiang''s tropical honey note resonates with fresh lychee; both originate from the same tropical-subtropical latitude','dessert','classic',1,true),
(263,'tea','oolong_dancong','Mi Lan Xiang Dancong',
 'seafood','light, steamed','Steamed fish with ginger and scallion — Cantonese whole fish',
 'complement','Chaozhou cuisine and Phoenix Mountain dancong: the food and the tea share a regional origin from eastern Guangdong','fish_course','classic',1,true),
(263,'tea','oolong_dancong','Mi Lan Xiang Dancong',
 'confection','honeyed, mild','Bao bing (shaved ice) with honey and lychee jelly',
 'complement','Taiwan-style shaved ice with Mi Lan Xiang: the honey-tropical register of both creates a summer refreshment pairing','dessert','established',2,true),

(264,'tea','oolong_dancong','Phoenix Village Ya Shi Xiang — exotic floral, cool menthol finish',
 'seafood','cold, mineral','Sea urchin toast — warm brioche, fresh uni, sea salt',
 'elevate','Ya Shi Xiang''s exotic floral complexity elevates sea urchin''s ocean sweetness; both are exceptional ingredients that amplify each other','amuse','adventurous',2,true),
(264,'tea','oolong_dancong','Ya Shi Xiang Dancong',
 'vegetables','light, floral','Edible flower salad with light citrus dressing',
 'complement','The exotic flower character of Ya Shi Xiang beside actual edible flowers: a sensory garden pairing','starter','adventurous',2,true),
(264,'tea','oolong_dancong','Ya Shi Xiang Dancong',
 'dessert','cool, mint','Mint and lime sorbet — palate cleanser',
 'complement','The cool menthol finish of Ya Shi Xiang and the cool mint sorbet share a refreshing character; palate-cleansing function','pre_dessert','established',2,true),
(264,'tea','oolong_dancong','Ya Shi Xiang Dancong',
 'cheese','fresh, cool','Fromage frais with fresh herbs — cool and clean',
 'contrast','The complex exotic floral of Ya Shi Xiang contrasting with the clean simplicity of fromage frais; a deliberate sophistication gap','cheese','experimental',2,true),

(265,'tea','oolong_dancong','Phoenix Village Xing Ren Xiang — almond-orchid dancong; warm and nutty',
 'pastry','almond, warm','Frangipane tart — almond cream, pear or plum',
 'complement','Xing Ren Xiang''s almond blossom character and actual frangipane (almond cream): a direct flavour-ingredient resonance','dessert','classic',1,true),
(265,'tea','oolong_dancong','Xing Ren Xiang Dancong',
 'cheese','aged, nutty','Aged Gruyère — hazelnut and almond notes',
 'complement','The almond note in both the dancong and the aged Gruyère creates a nut-forward pairing of quiet sophistication','cheese','adventurous',2,true),
(265,'tea','oolong_dancong','Xing Ren Xiang Dancong',
 'chocolate','almond, mild','Milk chocolate with whole almonds',
 'complement','Almond dancong and almond chocolate: a self-referential pairing that works because the source compound (benzaldehyde) is shared','dessert','established',2,true),
(265,'tea','oolong_dancong','Xing Ren Xiang Dancong',
 'pastry','warm, nutty','Sesame and almond nougat — Chinese nian gao style',
 'complement','Almond-orchid dancong beside almond-sesame confection: warming nut resonance for a festive context','dessert','classic',1,true),

(266,'tea','oolong_dancong','Floating Leaves Fenghuang Old Bush — curated; floral-fruity-mineral',
 'seafood','clean, light','Crab and ginger broth — minimally dressed',
 'complement','Old bush dancong''s mineral complexity complements crab''s delicate ocean character; Chaozhou cuisine alignment','starter','established',2,true),
(266,'tea','oolong_dancong','Floating Leaves Dancong',
 'fruit','stone fruit','Ripe peach or apricot — simply served',
 'complement','Dancong''s stone fruit character resonating with actual stone fruit: ingredient and beverage sharing origin aromatic','dessert','established',2,true),
(266,'tea','oolong_dancong','Floating Leaves Dancong',
 'vegetables','roasted, caramelised','Roasted butternut squash with honey and thyme',
 'complement','Old bush dancong''s warm honey-mineral with autumn squash''s caramelised sweetness: seasonal autumn pairing','main','adventurous',2,true),
(266,'tea','oolong_dancong','Floating Leaves Dancong',
 'confection','tropical honey','Mango and passion fruit pavlova',
 'complement','The tropical-honey register of Fenghuang dancong beside tropical fruit pavlova: Pacific Northwest meets Pacific Asia','dessert','adventurous',2,true),

-- Rishi 267-269
(267,'tea','puerh_shou','Rishi Pu-erh Dante Blend — accessible shou pu-erh for hospitality',
 'dimsum','various, rich','Full dim sum service — yum cha format',
 'complement','Rishi Pu-erh Dante is the practical dim sum pu-erh for BC restaurants; earthy and smooth as a yum cha service staple','casual','classic',1,true),
(267,'tea','puerh_shou','Rishi Pu-erh Dante',
 'meat','braised, savory','Beef short rib braised in soy and five spice',
 'complement','Shou pu-erh''s earth and dark fruit complement five-spice braised beef; fermentation bridges fermentation','main','established',2,true),
(267,'tea','puerh_shou','Rishi Pu-erh Dante',
 'chocolate','dark, earthy','Dark chocolate with sea salt and pepper',
 'complement','Shou pu-erh''s earthy-chocolate note amplified by actual dark chocolate with salt; accessible digestif pairing','digestif','established',2,true),
(267,'tea','puerh_shou','Rishi Pu-erh Dante',
 'cheese','aged, semi-hard','Aged gouda — accessible, caramel, mid-intensity',
 'complement','Accessible shou pu-erh beside accessible aged gouda: a pairing that introduces both categories at an approachable level','cheese','adventurous',2,true),

(268,'tea','green_tea_china','Rishi Organic Dragon Well — Zhejiang longjing style; chestnut-butter',
 'dimsum','savory, everyday','Steamed bao and har gow — accessible dim sum',
 'complement','Organic longjing-style as a daily dim sum pairing; accessible price point for high-volume service','casual','established',2,true),
(268,'tea','green_tea_china','Rishi Dragon Well',
 'salad','light, vegetable','Spring green salad with sesame dressing',
 'cleanse','Clean longjing-style refreshes between salad bites; accessible pairing for everyday lunch service','casual','established',2,true),
(268,'tea','green_tea_china','Rishi Dragon Well',
 'seafood','light, fried','Fried calamari with light dipping sauce',
 'cleanse','The clean astringency of longjing-style cuts fried oil from calamari; accessible restaurant pairing','casual','classic',1,true),
(268,'tea','green_tea_china','Rishi Dragon Well',
 'pastry','everyday','Sesame crackers or shortbread',
 'complement','Everyday accessible pairing for an afternoon tea service; neutral cracker beside clean longjing style','casual','classic',1,true),

(269,'tea','black_tea','Rishi Organic Wuyi Black (Lapsang Souchong) — pine-smoked black tea',
 'cheese','aged, smoked','Smoked gouda or smoked cheddar — obvious smoke-smoke pairing',
 'complement','Lapsang Souchong''s pine smoke and smoked cheese''s smoke: direct resonance of smoking methods','cheese','established',2,true),
(269,'tea','black_tea','Rishi Lapsang Souchong',
 'meat','smoked, barbecue','Smoked brisket or pulled pork — American BBQ style',
 'complement','Smoked tea beside smoked meat: the smoke from different woods creates a harmonic rather than redundant pairing','main','adventurous',2,true),
(269,'tea','black_tea','Rishi Lapsang Souchong',
 'cheese','pungent, washed','Époisse or Munster — funky washed rind; bold',
 'complement','Pine-smoke tea and funky washed rind cheese: both are pungent, both are transformative; the pairing is for confident palates','cheese','adventurous',2,true),
(269,'tea','black_tea','Rishi Lapsang Souchong',
 'pastry','dark, molasses','Dark molasses gingerbread — winter spice, bold',
 'complement','Smoked tea''s camphor-dried fruit with gingerbread''s molasses-spice: winter warming pairing','dessert','adventurous',2,true),

-- ============================================================
-- BAIJIU (270-277)
-- ============================================================

-- 270: Kweichow Moutai Feitian
(270,'baijiu','jiangxiang','Moutai Feitian — China''s national spirit; 53% ABV; sauce-aroma style',
 'meat','fatty, luxury','Peking duck — whole roasted; skin-on ceremony',
 'complement','Moutai and Peking duck is China''s most celebrated luxury food-spirit pairing; the soy-umami sauce aroma mirrors the duck''s lacquered richness','main','classic',1,true),
(270,'baijiu','jiangxiang','Moutai Feitian',
 'seafood','premium','Fresh hairy crab (dazha xie) — Shanghai autumn luxury',
 'complement','Moutai with hairy crab is a Shanghai autumn tradition; the intense jiangxiang complexity matches crab''s extreme umami','main','classic',1,true),
(270,'baijiu','jiangxiang','Moutai Feitian',
 'meat','cured, aged','Jinhua ham — Chinese aged cured ham; intensely savory',
 'complement','Two of China''s most revered aged products: aged jiangxiang baijiu and aged Jinhua ham share fermentation depth','casual','classic',1,true),
(270,'baijiu','jiangxiang','Moutai Feitian',
 'celebration','formal','Ganbei toasting culture — formal Chinese banquet',
 'complement','Moutai IS the ganbei baijiu; no pairing is more essential than the formal Chinese banquet toast context','celebration','classic',1,true),
(270,'baijiu','jiangxiang','Moutai Feitian',
 'meat','braised, complex','Dongpo pork — Hangzhou pork belly braised 4 hours in Shaoxing wine',
 'bridge','Jiangxiang complexity bridges through Shaoxing wine (used in the braise) to the pork fat''s richness','main','adventurous',2,true),

-- 271: Moutai 15-Year Aged
(271,'baijiu','jiangxiang','Moutai 15-Year — deeper aged Moutai; dried fruit, aged wood, incense',
 'cheese','aged, complex','Long-aged Comté 30-month or Parmigiano Reggiano',
 'complement','15-year Moutai and 30-month aged cheese: both are masterclasses in long-aging transforming raw ingredients into complex expressions','cheese','adventurous',2,true),
(271,'baijiu','jiangxiang','Moutai 15-Year',
 'meat','slow roasted, premium','48-hour low-temperature lamb shoulder with Chinese spice',
 'complement','Aged Moutai''s complexity deserves food of equivalent depth; long-cooked lamb with ancient spice achieves this','main','adventurous',2,true),
(271,'baijiu','jiangxiang','Moutai 15-Year',
 'chocolate','dark, premium','Valrhona 70% with aged components — complex dark',
 'complement','15-year jiangxiang and premium dark chocolate: both are transformations of raw materials into something profound','digestif','adventurous',2,true),
(271,'baijiu','jiangxiang','Moutai 15-Year',
 'fruit','dried, complex','Preserved prune, dried fig, aged citrus peel — digestif plate',
 'complement','The dried fruit aromatics in aged Moutai are best illustrated by serving actual dried fruits alongside; a flight of aged-fruit flavours','digestif','established',2,true),

-- 272: Moutai Prince
(272,'baijiu','jiangxiang','Moutai Prince — accessible Moutai; same factory, approachable price',
 'meat','dim sum, savory','Peking duck wraps — modern casual format',
 'complement','Moutai Prince makes the Moutai-duck pairing accessible; casual format matches the accessible expression','casual','classic',1,true),
(272,'baijiu','jiangxiang','Moutai Prince',
 'seafood','grilled, savory','Grilled squid with soy and chili — Chinese BBQ',
 'cleanse','Jiangxiang cuts through grilled squid''s umami with its own fermentation depth; a casual street-food pairing','casual','established',2,true),
(272,'baijiu','jiangxiang','Moutai Prince',
 'vegetables','fermented, bold','Mapo tofu — Sichuan style, numbing and savory',
 'cleanse','Jiangxiang baijiu and Sichuan mapo tofu: the spirit''s fermentation depth handles the numbing spice and fermented black bean boldly','main','established',2,true),
(272,'baijiu','jiangxiang','Moutai Prince',
 'celebration','entry','Corporate banquet toast — business dinner context',
 'complement','Moutai Prince as the business banquet baijiu: the Moutai brand signals prestige at an accessible price point','celebration','classic',1,true),

-- 273: Wuliangye Classic Nongxiang
(273,'baijiu','nongxiang','Wuliangye — five-grain Sichuan; sweeter, fruitier than Moutai; 52% ABV',
 'meat','Sichuan spiced','Twice-cooked pork (hui guo rou) — Sichuan; broad-bean paste, bold',
 'complement','Wuliangye is the natural Sichuan baijiu; its five-grain sweetness moderates Sichuan spice while its fruit resonates with Pixian doubanjiang','main','classic',1,true),
(273,'baijiu','nongxiang','Wuliangye',
 'dimsum','savory, dim sum','Xiao long bao (soup dumplings) — Shanghai style',
 'complement','Nongxiang''s sweetness and anise note complement the pork-ginger filling of XLB; the sweetness bridges the hot soup interior','casual','classic',1,true),
(273,'baijiu','nongxiang','Wuliangye',
 'meat','fatty, braised','Dongpo pork or Sichuan red-braised pork',
 'cleanse','Wuliangye''s sweet-anise character cuts braised pork fat while its grain complexity bridges to the soy-sugar braise','main','classic',1,true),
(273,'baijiu','nongxiang','Wuliangye',
 'celebration','formal Chinese','Chinese New Year banquet — full table feast',
 'complement','Wuliangye is the second most prominent ganbei baijiu after Moutai; appropriate for any formal Chinese celebration','celebration','classic',1,true),

-- 274: Luzhou Laojiao National Cellar 1573
(274,'baijiu','nongxiang','Luzhou Laojiao 1573 — UNESCO heritage pit fermentation; floral nongxiang',
 'meat','mild, Cantonese','Steamed chicken (Cantonese bai qie ji) — poached, ginger-scallion oil',
 'complement','1573''s floral-delicate nongxiang is the most appropriate baijiu for Cantonese steamed preparations; the floral note resonates with ginger','main','established',2,true),
(274,'baijiu','nongxiang','Luzhou Laojiao 1573',
 'seafood','sweet, steamed','Steamed fish with Shaoxing wine and ginger',
 'complement','The most delicate nongxiang beside the most delicate Chinese fish preparation; both express clean umami with aromatic lift','fish_course','established',2,true),
(274,'baijiu','nongxiang','Luzhou Laojiao 1573',
 'cheese','floral, soft','Brie with floral honey — mild and aromatic',
 'contrast','1573''s jasmine-petal delicacy beside floral honey brie: a fragrant cross-cultural pairing for those discovering nongxiang style','cheese','adventurous',2,true),
(274,'baijiu','nongxiang','Luzhou Laojiao 1573',
 'confection','petal, delicate','Osmanthus jelly — traditional Chinese floral dessert',
 'complement','National Cellar 1573''s floral complexity with osmanthus jelly: florals resonating with florals','dessert','established',2,true),

-- 275: Luzhou Laojiao Zisha Touqu 68°
(275,'baijiu','nongxiang','Luzhou Laojiao 68° Touqu — first-run high-proof distillate',
 'cheese','very strong, aged','Roquefort or Stilton — intense, assertive blue',
 'contrast','68° raw distillate requires the most assertive food partner in the cellar; strong blue cheese is the only thing with enough intensity','cheese','adventurous',2,true),
(275,'baijiu','nongxiang','Luzhou Laojiao 68°',
 'chocolate','dark, intense','99% cacao tablet — almost pure cocoa mass',
 'contrast','The sheer intensity of 68° baijiu requires the most bitter chocolate available; they contrast without either dominating','digestif','experimental',2,true),
(275,'baijiu','nongxiang','Luzhou Laojiao 68°',
 'meat','smoked, intense','Heavily smoked brisket — peak smoke, maximum char',
 'bridge','High-proof nongxiang bridges through maximum smoke intensity in the food; the five-grain sweetness softens what pure spirits would clash with','main','experimental',2,true),
(275,'baijiu','nongxiang','Luzhou Laojiao 68°',
 'amuse','educational','1:1 diluted beside standard 1573 — educational comparison',
 'complement','Serving 68° diluted 1:1 alongside the standard 1573 is the most educational spirits pairing: same origin, same distillate, different development','any','established',1,true),

-- 276: Fenjiu 20-Year Fenxiang
(276,'baijiu','qingxiang','Fenjiu 20-Year Fenxiang — cleanest major baijiu; grain clarity; aged complexity',
 'fish','clean, mild','Steamed yellow croaker with light ginger broth',
 'complement','Fenxiang''s pristine clarity is the most versatile baijiu for delicate food; steamed fish is the ideal showcase','fish_course','established',2,true),
(276,'baijiu','qingxiang','Fenjiu 20-Year Fenxiang',
 'vegetables','fermented, Shanxi','Shanxi vinegar-braised vegetables — regional pairing',
 'complement','Fenjiu is from Shanxi; Shanxi vinegar is China''s premier vinegar culture; regional pairing of fermented products','main','classic',1,true),
(276,'baijiu','qingxiang','Fenjiu 20-Year Fenxiang',
 'cheese','mild, fresh','Young manchego or mild Swiss — gentle, accessible',
 'contrast','Fenxiang''s clear grain spirit versus mild cheese: the cleanest baijiu paired with the mildest cheese for an accessible Western introduction','cheese','adventurous',2,true),
(276,'baijiu','qingxiang','Fenjiu 20-Year Fenxiang',
 'confection','light, aged','Walnuts in honey — Shanxi speciality confection',
 'complement','Shanxi baijiu with Shanxi walnut-honey confection: regional completeness; both express the warm grain character of northern China','casual','classic',1,true),

-- 277: Guilin Sanhua
(277,'baijiu','mioxiang','Guilin Sanhua — rice-aroma; softest major baijiu; floral and light',
 'seafood','Cantonese, light','Steamed shrimp with Guilin-style dipping sauce',
 'complement','Guilin Sanhua and Cantonese-style shrimp: the softest baijiu beside the most delicate seafood preparation; rice base mirrors rice character','starter','classic',1,true),
(277,'baijiu','mioxiang','Guilin Sanhua',
 'vegetables','light, steamed','Steamed vegetables with light oyster sauce',
 'complement','Rice baijiu and steamed vegetable: the softest combination in the baijiu pairing collection','main','established',2,true),
(277,'baijiu','mioxiang','Guilin Sanhua',
 'sake','alternative context','Sake-adjacent introduction to baijiu for Japanese spirits drinkers',
 'bridge','Guilin Sanhua is the most sake-adjacent baijiu: rice base, floral notes, mild body — ideal gateway for a guest who knows sake but not baijiu','aperitif','adventurous',2,true),
(277,'baijiu','mioxiang','Guilin Sanhua',
 'pastry','rice-based, sweet','Nian gao — glutinous rice cake with mild sweetness',
 'complement','Rice baijiu and rice cake: the same grain, different transformations — a pairing of parallel processing','dessert','established',2,true);

COMMIT;
