-- East Asian Phase 11a: Pairing Intelligence — Sake (IDs 112–141)
-- 4–5 pairings per product × 30 products = ~130 entries
-- pairing_type: complement/contrast/bridge/cleanse/elevate
-- confidence: classic/established/suggested/adventurous/experimental
-- meal_context: aperitif/amuse/starter/fish_course/main/cheese/pre_dessert/dessert/digestif/celebration/casual/any

BEGIN;

INSERT INTO pairing_intelligence
  (beverage_product_id, beverage_category, beverage_style, beverage_description,
   food_category, food_flavour_profile, food_description,
   pairing_type, flavour_logic, meal_context, confidence, authority_tier, is_published)
VALUES

-- 112: Kubota Manju Junmai Daiginjo (Niigata, ultra-premium, fruity-delicate)
(112,'sake','junmai_daiginjo','Kubota Manju — the pinnacle of Niigata ginjo sake; rice-forward fruit with snow-water purity',
 'sashimi','delicate umami, clean brine','Hamachi (yellowtail) sashimi — clean-sliced, no garnish but yuzu kosho on the side',
 'complement','The snow-water purity of Manju amplifies the clean ocean note of yellowtail while its melon-pear fruit lifts the fat without masking it','fish_course','classic',1,true),
(112,'sake','junmai_daiginjo','Kubota Manju',
 'seafood','briny sweetness, mineral','Oysters on the half shell — Pacific or Kumamoto; no mignonette',
 'cleanse','The dry, clean finish of Niigata daiginjo cuts the oyster cream and mineral brine, resetting the palate for each successive shell','starter','classic',1,true),
(112,'sake','junmai_daiginjo','Kubota Manju',
 'seafood','delicate, sweet, neutral','Steamed prawn with ponzu — barely dressed; textural contrast between firm prawn and delicate sake',
 'bridge','Ponzu citrus bridges the sake''s fruity profile while the umami of prawn body mirrors the rice depth of Manju','starter','established',1,true),
(112,'sake','junmai_daiginjo','Kubota Manju',
 'pastry','light, buttery, clean','Yuzu financier — petite, barely sweet with citrus brightness',
 'elevate','The fruity aromatics of Manju transform under the yuzu note of the financier into a layered combination that reads above its components','pre_dessert','suggested',2,true),
(112,'sake','junmai_daiginjo','Kubota Manju',
 'vegetables','mineral, delicate','White asparagus with light dashi butter — spring seasonal',
 'complement','Niigata water purity and white asparagus share a mineral-vegetable register; sake''s rice sweetness lifts the dashi','fish_course','suggested',2,true),

-- 113: Kubota Senju Tokubetsu Honjozo (accessible, clean, versatile)
(113,'sake','honjozo','Kubota Senju — the everyday face of Niigata sake; clean, dry, food-friendly',
 'sushi','rice umami, light fish fat','Nigiri sushi selection — salmon, tuna, snapper; rice well-seasoned',
 'complement','Honjozo''s slight added distilled alcohol creates a cleaner, lighter body that sits beside sushi rice without competing with it','starter','classic',1,true),
(113,'sake','honjozo','Kubota Senju',
 'poultry','light umami, savory','Yakitori — chicken thigh, tare-glazed',
 'bridge','The caramelised tare glaze and rice-clean sake create a bridge through their shared maillard reaction sweetness','casual','classic',1,true),
(113,'sake','honjozo','Kubota Senju',
 'vegetables','earthy, savory','Agedashi tofu — light dashi broth, silken texture',
 'complement','Clean rice-forward sake mirrors the clean umami of dashi without asserting any character that would dominate the delicate tofu','starter','established',2,true),
(113,'sake','honjozo','Kubota Senju',
 'dumplings','savory, pork fat, ginger','Gyoza — pan-fried pork and ginger; vinegar dipping sauce',
 'cleanse','The dry honjozo finish cuts pork fat in gyoza cleanly; acidity from vinegar dipping sauce and sake''s clean alcohol are harmonious','casual','classic',1,true),

-- 114: Kubota Hyakuju Junmai Daiginjo
(114,'sake','junmai_daiginjo','Kubota Hyakuju — premium Niigata junmai daiginjo with elevated rice character',
 'seafood','light umami, clean','Scallop sashimi — raw Hokkaido hotate, minimal seasoning',
 'elevate','Hyakuju''s rice-derived sweetness elevates the natural glycine sweetness of raw scallop into a compound umami experience','fish_course','classic',1,true),
(114,'sake','junmai_daiginjo','Kubota Hyakuju',
 'fish','delicate, cold-smoked','Cold-smoked sablefish — thin sliced, light smoke',
 'bridge','Premium daiginjo fruit notes bridge over light smoke without clashing; rice purity provides neutral ground','starter','established',2,true),
(114,'sake','junmai_daiginjo','Kubota Hyakuju',
 'seafood','briny, mineral','Sea urchin (uni) on rice — warm rice, fresh uni, drop of soy',
 'elevate','Daiginjo fruitiness and rice depth are the natural companions to uni''s ocean-sweetness; warmth of rice activates the sake aromatics','amuse','classic',1,true),
(114,'sake','junmai_daiginjo','Kubota Hyakuju',
 'vegetables','clean, mild','Cucumber and white radish tsukemono (pickles) — lightly salted',
 'cleanse','Pickled vegetables reset the palate between sake pours; the sake''s clean finish extends the cleanse effect','any','established',2,true),

-- 115: Hakkaisan Junmai Ginjo
(115,'sake','junmai_ginjo','Hakkaisan Junmai Ginjo — fresh mountain water, balanced ginjo character',
 'sashimi','lean, clean umami','Tai (sea bream) sashimi — white flesh, delicate flavour',
 'complement','Mountain-water ginjo and white-fleshed fish share a clean, mineral-adjacent quality; sake amplifies the subtle sweetness of the flesh','fish_course','classic',1,true),
(115,'sake','junmai_ginjo','Hakkaisan Junmai Ginjo',
 'seafood','briny, mineral','Steamed clams with sake and butter — standard izakaya preparation',
 'bridge','Serving sake alongside steamed clams creates an amplifying loop — the sake in the broth and in the cup share terroir','starter','classic',1,true),
(115,'sake','junmai_ginjo','Hakkaisan Junmai Ginjo',
 'vegetables','delicate, light','Chilled silken tofu with dashi and grated ginger',
 'complement','Clean ginjo water-character mirrors the clean protein of silken tofu; ginger note echoes the sake''s subtle spice','starter','established',2,true),
(115,'sake','junmai_ginjo','Hakkaisan Junmai Ginjo',
 'cheese','mild, fresh','Burrata with light herb oil and flaky salt',
 'contrast','Rare pairing: the clean water-purity of Niigata ginjo contrasts beautifully with burrata''s fatty richness, cutting through dairy without flavour conflict','starter','adventurous',2,true),

-- 116: Hakkaisan Yukimuro Snow-Aged Junmai Ginjo
(116,'sake','junmai_ginjo_aged','Hakkaisan Yukimuro — aged 3 years in snow room at 0°C; deepened and rounded',
 'fish','delicate, subtle smoke','Soba noodles with yuzu-dashi and grilled nori',
 'complement','Snow-aging rounds the sake''s edges and creates a quietly complex middle profile that mirrors the subtle earthiness of nori and buckwheat','starter','established',2,true),
(116,'sake','junmai_ginjo_aged','Hakkaisan Yukimuro',
 'seafood','cold, briny, mineral','Whelks or periwinkles with ponzu — cold shellfish',
 'bridge','The cold-storage origin of this sake makes it a natural companion to cold-sea flavours; mineral-mineral bridge','starter','adventurous',2,true),
(116,'sake','junmai_ginjo_aged','Hakkaisan Yukimuro',
 'cheese','aged, complex','Aged Manchego or Comté 18-month — nutty, crystalline',
 'elevate','Snow-aging adds a complexity to the sake that meets aged cheese''s depth; both show crystal-clarity-within-richness','cheese','adventurous',2,true),
(116,'sake','junmai_ginjo_aged','Hakkaisan Yukimuro',
 'vegetables','earthy, umami','Matsutake mushroom clear soup (dobinmushi) — autumn',
 'complement','The deepening effect of snow aging brings the sake into the umami register of matsutake; rare harmonic convergence of seasonal timing','starter','suggested',2,true),

-- 117: Koshi no Kanbai Honjozo Sai
(117,'sake','honjozo','Koshi no Kanbai Sai — Niigata dry honjozo; austere and precise',
 'sashimi','lean, clean, cold','Ikura (salmon roe) gunkan — seasoned, cold',
 'complement','The dryness of honjozo Sai cuts through the richness of salmon roe while the rice flavour bridges to the seasoned rice base','starter','classic',1,true),
(117,'sake','honjozo','Koshi no Kanbai Sai',
 'fish','grilled, light soy','Grilled ayu (sweetfish) — salt-grilled, simple',
 'bridge','Dry honjozo''s minimal fruit profile is the textbook pairing for salt-grilled river fish; neither dominates','main','classic',1,true),
(117,'sake','honjozo','Koshi no Kanbai Sai',
 'seafood','savory, oceanic','Miso soup with clams (hamaguri)',
 'complement','Niigata dry sake and miso umami complement through shared fermentation character','casual','established',2,true),
(117,'sake','honjozo','Koshi no Kanbai Sai',
 'snack','salty, light','Edamame — lightly salted',
 'cleanse','Classic aperitif pairing: the clean, dry Sai washes salt from the palate after each edamame','aperitif','classic',1,true),

-- 118: Koshi no Kanbai Muku Junmai Daiginjo
(118,'sake','junmai_daiginjo','Koshi no Kanbai Muku — refined junmai daiginjo from legendary Niigata label',
 'sashimi','rich, buttery','Otoro (fatty bluefin tuna) sashimi — highest fat content',
 'cleanse','Muku''s pristine purity and high-polish rice character cuts through fatty tuna with precision while its fruit note complements the umami','fish_course','classic',1,true),
(118,'sake','junmai_daiginjo','Koshi no Kanbai Muku',
 'seafood','sweet, clean','Botan ebi (large sweet prawn) sashimi — raw',
 'complement','Sweet prawn and fruity daiginjo share a natural glycine sweetness that resonates in harmony','fish_course','classic',1,true),
(118,'sake','junmai_daiginjo','Koshi no Kanbai Muku',
 'celebration','light, elegant','Champagne reception appetiser: blinis with crème fraîche',
 'elevate','Muku as a champagne alternative at a celebration opening: same elegance, different expression','celebration','adventurous',2,true),
(118,'sake','junmai_daiginjo','Koshi no Kanbai Muku',
 'pastry','floral, delicate','Hanabiramochi — New Year wagashi, sweet miso and burdock',
 'complement','The seasonal wagashi pairing for premium daiginjo is a chanoyu-adjacent pairing of quiet sophistication','pre_dessert','suggested',2,true),

-- 119: Yoshinogawa Gensen Karakuchi Junmai
(119,'sake','junmai_karakuchi','Yoshinogawa Gensen — dry junmai; bracing and clean',
 'fish','grilled, smoky','Grilled mackerel (saba) with grated daikon',
 'cleanse','Dry junmai cuts through oily mackerel richness and refreshes with each sip','main','classic',1,true),
(119,'sake','junmai_karakuchi','Yoshinogawa Gensen',
 'dumplings','pork, savory, crispy','Pan-fried gyoza — pork and cabbage',
 'cleanse','The bracing dryness of karakuchi junmai is classic with pan-fried meat dumplings; fat-cutting function','casual','classic',1,true),
(119,'sake','junmai_karakuchi','Yoshinogawa Gensen',
 'noodles','hearty, savory','Tonkotsu ramen — rich pork bone broth',
 'cleanse','The most demanding application: dry junmai must cut through concentrated pork fat; Gensen is bracing enough to succeed','main','established',2,true),
(119,'sake','junmai_karakuchi','Yoshinogawa Gensen',
 'seafood','bold, fermented','Squid shiokara (salted fermented squid) — intense umami condiment',
 'complement','Both are products of Japanese fermentation culture; the complementary umami of dry sake and aged seafood ferment is a traditional izakaya pairing','casual','classic',1,true),

-- 120: Yoshinogawa Winter Warrior Junmai Ginjo
(120,'sake','junmai_ginjo','Yoshinogawa Winter Warrior — winter-release ginjo; fruit and freshness',
 'seafood','cold-water, clean','Dungeness crab — steamed whole, with ponzu',
 'complement','Winter sake and cold-water Dungeness: seasonal synchronicity and shared ocean character','main','established',2,true),
(120,'sake','junmai_ginjo','Yoshinogawa Winter Warrior',
 'fish','cold, raw, clean','Flounder (hirame) usuzukuri — paper-thin winter sashimi',
 'complement','Winter flounder and winter sake share a seasonal thinness that is not weakness but precision','fish_course','classic',1,true),
(120,'sake','junmai_ginjo','Yoshinogawa Winter Warrior',
 'hotpot','light dashi, vegetables','Yudofu — simmered tofu in kombu dashi; simple winter dish',
 'complement','Winter warming sake beside winter tofu: a Japanese minimalist winter pairing of great coherence','main','established',2,true),
(120,'sake','junmai_ginjo','Yoshinogawa Winter Warrior',
 'cheese','fresh, cream','Fresh chèvre — mild acidity, clean dairy',
 'contrast','Fresh chèvre''s lactic acidity contrasts gently with the ginjo''s fruit richness; rare successful sake-fresh-cheese pairing','cheese','adventurous',2,true),

-- 121: Kakurei Tokubetsu Junmai
(121,'sake','tokubetsu_junmai','Kakurei Tokubetsu Junmai — Niigata clean and dry',
 'fish','lean, grilled','Salt-grilled trout (masu) — freshwater, simple',
 'bridge','Both clean and mountain-associated; the slight earthy note of freshwater fish finds resonance in junmai grain depth','main','established',2,true),
(121,'sake','tokubetsu_junmai','Kakurei Tokubetsu Junmai',
 'vegetables','fermented, tangy','Tsukemono mixed pickles — daikon, cucumber, carrot',
 'bridge','Fermented vegetables and junmai sake share lactic depth from their respective fermentation pathways','starter','classic',1,true),
(121,'sake','tokubetsu_junmai','Kakurei Tokubetsu Junmai',
 'poultry','savory, grilled','Chicken karaage — deep-fried, juicy',
 'cleanse','Classic izakaya combination: clean dry sake washes the oil from deep-frying off the palate','casual','classic',1,true),
(121,'sake','tokubetsu_junmai','Kakurei Tokubetsu Junmai',
 'seafood','savory, firm','Grilled squid (ika geso) — salt and lemon',
 'complement','Junmai grain character and the mineral-savory note of grilled squid are natural izakaya companions','casual','classic',1,true),

-- 122: Kiku-Masamune Kimoto Junmai (Nada)
(122,'sake','kimoto_junmai','Kiku-Masamune Kimoto — 400 years of lactic fermentation; textured and complex',
 'fish','aged, fermented','Narezushi — traditional fermented rice-fish (funazushi) — intense',
 'complement','The only sake pairing for funazushi: kimoto''s lactic acidity and aged complexity match the depth of this ancient fermented fish','casual','classic',1,true),
(122,'sake','kimoto_junmai','Kiku-Masamune Kimoto',
 'meat','savory, bold','Yakitori negima (chicken and scallion) — charcoal-grilled with tare',
 'complement','Kimoto''s body and savory lactic depth complement charcoal''s carbon notes and tare''s caramel-umami','main','classic',1,true),
(122,'sake','kimoto_junmai','Kiku-Masamune Kimoto',
 'cheese','washed rind, pungent','Taleggio or Époisse — strong, funky, bold',
 'complement','Kimoto is the rare sake with enough complexity and acid to stand beside washed-rind cheeses; lactic bridges the cheese character','cheese','adventurous',2,true),
(122,'sake','kimoto_junmai','Kiku-Masamune Kimoto',
 'meat','braised, rich','Kakuni (pork belly braised in soy-mirin) — Okinawa or Nagasaki style',
 'bridge','Kimoto''s structure bridges through the slow-braised fat and soy-mirin glaze; both are the products of long fermentation and patience','main','established',2,true),
(122,'sake','kimoto_junmai','Kiku-Masamune Kimoto',
 'seafood','fermented, pungent','Shuto (fermented skipjack tuna viscera) — intense umami condiment',
 'complement','Extreme pairing: kimoto''s age and complexity is the only sake with the backbone for this fermented umami bomb','casual','classic',1,true),

-- 123: Kiku-Masamune Taru Sake (cedar-barrel aged)
(123,'sake','taru_sake','Kiku-Masamune Taru — cedar-barrel aged sake; distinctive hinoki character',
 'fish','grilled, fatty','Grilled salmon fillet — cedar plank or direct heat',
 'complement','Cedar-in-sake and cedar-plank-for-fish: the aromatic bridge of hinoki wood creates a resonant pairing','main','established',2,true),
(123,'sake','taru_sake','Kiku-Masamune Taru',
 'meat','grilled, bold','Sumiyaki (charcoal-grilled) short rib — Japanese BBQ style',
 'bridge','The bold cedar note of Taru Sake cuts through charcoal''s bitterness and fat richness; wood bridges wood','main','suggested',2,true),
(123,'sake','taru_sake','Kiku-Masamune Taru',
 'cheese','aged, nutty','Aged gouda (5-year) — caramel, crystalline',
 'complement','Both aged gouda and cedar-aged sake develop the same lactone-forward sweet-woody aromatic; a remarkably coherent pairing','cheese','adventurous',2,true),
(123,'sake','taru_sake','Kiku-Masamune Taru',
 'snack','herbal, earthy','Cedar-cured olives or pickled herbal brine — aperitif snack',
 'complement','Aperitif context: the herbal and wood notes of the cedar sake meet herbal brine in a quietly coherent pre-dinner moment','aperitif','adventurous',2,true),

-- 124: Ozeki Junmai (Nada, classic)
(124,'sake','junmai','Ozeki Junmai — reliable Nada junmai; clean and approachable',
 'sushi','varied, light','Mixed maki rolls — everyday sushi',
 'complement','Classic sushi-sake combination; Ozeki Junmai is the workhorse pairing for a Japanese-inspired tasting menu','starter','classic',1,true),
(124,'sake','junmai','Ozeki Junmai',
 'vegetables','pickled, tangy','Sunomono — cucumber and wakame in rice vinegar dressing',
 'bridge','Shared acidity between rice vinegar sunomono and junmai creates a gentle, refreshing bridge','starter','established',2,true),
(124,'sake','junmai','Ozeki Junmai',
 'dumplings','pork, savory','Shumai — steamed pork dumplings with soy and mustard',
 'cleanse','Clean junmai cuts steamed pork fat; everyday pairing for casual dining','casual','classic',1,true),
(124,'sake','junmai','Ozeki Junmai',
 'noodles','cold, dipping','Zaru soba — cold buckwheat noodles with tsuyu dipping sauce',
 'complement','The earthy depth of buckwheat is complemented by junmai''s grain character; tsuyu''s dashi-soy mirrors fermentation umami','main','established',2,true),

-- 125: Sawanotsuru Junmai Daiginjo
(125,'sake','junmai_daiginjo','Sawanotsuru Junmai Daiginjo — elegant Nada premium',
 'seafood','delicate, sweet','Amaebi (sweet shrimp) sashimi — live or raw; intense sweetness',
 'complement','Sweet shrimp''s glycine sweetness resonates with daiginjo''s rice-derived fruit character','fish_course','classic',1,true),
(125,'sake','junmai_daiginjo','Sawanotsuru Junmai Daiginjo',
 'fish','clean, white flesh','Flounder carpaccio with yuzu oil and micro shiso',
 'elevate','Elegant daiginjo elevates a simple crudo into a sophisticated pairing by amplifying the citrus-herb notes of the dressing','starter','established',2,true),
(125,'sake','junmai_daiginjo','Sawanotsuru Junmai Daiginjo',
 'celebration','light canape','Caviar on blini — classic celebration format',
 'elevate','Premium daiginjo replaces champagne as caviar companion; rice-derived salinity resonates with caviar brine','celebration','adventurous',2,true),
(125,'sake','junmai_daiginjo','Sawanotsuru Junmai Daiginjo',
 'pastry','delicate sweet','Madeleine with yuzu cream',
 'complement','The delicate fruit of premium daiginjo meets the delicate fruit of a yuzu pastry; both refined, neither overwhelming','dessert','suggested',2,true),

-- 126: Nihonsakari Junmai Ginjo
(126,'sake','junmai_ginjo','Nihonsakari Junmai Ginjo — Nada house with long history',
 'seafood','briny, clean','Clams (asari) steamed with sake and butter',
 'bridge','This preparation literally uses sake in the broth — serving the same style alongside creates an immersive coherence','starter','classic',1,true),
(126,'sake','junmai_ginjo','Nihonsakari Junmai Ginjo',
 'fish','poached, delicate','Steamed sea bass with ginger scallion oil',
 'complement','Clean ginjo with delicately poached white fish — classic Cantonese-Japanese intersection','fish_course','established',2,true),
(126,'sake','junmai_ginjo','Nihonsakari Junmai Ginjo',
 'vegetables','savory, umami','Chawanmushi — silky steamed egg custard with dashi',
 'complement','Ginjo''s light umami complements dashi''s subtle depth in chawanmushi without competing','starter','classic',1,true),
(126,'sake','junmai_ginjo','Nihonsakari Junmai Ginjo',
 'meat','light, savory','Chicken and egg oyakodon — mild, savory, egg-rich',
 'complement','Ginjo''s fruit and clean body complement the mild egg-and-chicken richness without adding weight','main','established',2,true),

-- 127: Konishi Shirayuki Junmai Ginjo (Nada)
(127,'sake','junmai_ginjo','Konishi Shirayuki Junmai Ginjo — one of Japan''s oldest sake houses',
 'seafood','sweet, fresh','Live oysters — Pacific or Fanny Bay; no dressing',
 'cleanse','Ginjo''s clean finish and light fruit profile is the textbook pairing for raw oysters; resets the palate between shells','starter','classic',1,true),
(127,'sake','junmai_ginjo','Konishi Shirayuki Junmai Ginjo',
 'vegetables','light, steamed','Steamed soy-glazed gingko nuts',
 'bridge','The earthy-bitter note of gingko bridges through the sake''s grain character to a quiet, contemplative pairing','amuse','suggested',2,true),
(127,'sake','junmai_ginjo','Konishi Shirayuki Junmai Ginjo',
 'fish','miso-marinated','Gindara (black cod) saikyo miso — classic preparation',
 'complement','The sweetness of saikyo miso and ginjo sake are natural partners; both are Japanese ferment cultures expressing sweetness','main','classic',1,true),
(127,'sake','junmai_ginjo','Konishi Shirayuki Junmai Ginjo',
 'seafood','light, cold','Octopus sunomono — thinly sliced, vinegar dressing',
 'cleanse','Vinegar dressing and clean ginjo work in parallel to refresh the palate; light seafood is the ideal base','starter','established',2,true),

-- 128: Hakutsuru Tora no Ko Junmai Daiginjo
(128,'sake','junmai_daiginjo','Hakutsuru Tora no Ko — Tiger''s Cub; refined premium Nada daiginjo',
 'seafood','sweet, premium','Hokkaido sea urchin (uni) — fresh, on soy rice',
 'elevate','The richest sake pairing for uni: premium daiginjo''s fruit and rice purity provide a clean platform that elevates the sweetness of fresh uni','amuse','classic',1,true),
(128,'sake','junmai_daiginjo','Hakutsuru Tora no Ko',
 'fish','cured, delicate','Cured salmon with ikura and sour cream — Japanese-Nordic style',
 'bridge','Premium daiginjo bridges through the salmon cure''s salt and the ikura''s brine to the cream''s richness','starter','adventurous',2,true),
(128,'sake','junmai_daiginjo','Hakutsuru Tora no Ko',
 'celebration','elegant amuse','Cucumber cup with yuzu tobiko',
 'elevate','Celebration pairing: premium sake elevates a simple, beautiful amuse into a refined opening statement','celebration','established',2,true),
(128,'sake','junmai_daiginjo','Hakutsuru Tora no Ko',
 'vegetables','steamed, delicate','Bamboo shoot with kinome sauce — spring seasonal',
 'complement','Spring sake (fresh character of premium daiginjo) and spring bamboo: seasonal resonance is a foundational principle of Japanese pairing','starter','classic',1,true),

-- 129: Tsuki no Katsura Iwai Junmai Daiginjo (Fushimi, Iwai rice)
(129,'sake','junmai_daiginjo','Tsuki no Katsura Iwai — Fushimi soft water; Iwai rice; refined fruit',
 'fish','delicate, white','Satsuma-age (fried fish cake) with grated ginger and soy',
 'bridge','Soft water sake mirrors the delicate sweetness of fish cake; ginger''s warmth bridges to the sake''s gentle spice','starter','established',2,true),
(129,'sake','junmai_daiginjo','Tsuki no Katsura Iwai',
 'seafood','clean, elegant','Sawara (Spanish mackerel) sashimi — lightly torched',
 'complement','Fushimi water''s softness produces sake with the exact balance to complement the gentle oiliness of torched sawara','fish_course','classic',1,true),
(129,'sake','junmai_daiginjo','Tsuki no Katsura Iwai',
 'vegetables','light, seasonal','Simmered kabocha with dashi — sweet winter squash',
 'complement','Sweet kabocha and Fushimi''s fruit-forward daiginjo share a natural sweetness that harmonises without redundancy','main','established',2,true),
(129,'sake','junmai_daiginjo','Tsuki no Katsura Iwai',
 'pastry','mild sweet','Ohagi (sweet rice ball with azuki bean paste)',
 'complement','Premium Kyoto-adjacent sake and traditional wagashi — a seasonal cultural pairing of quiet elegance','dessert','classic',1,true),

-- 130: Tsuki no Katsura Junmai Nigori
(130,'sake','nigori','Tsuki no Katsura Junmai Nigori — cloudy, unfiltered; rich and sweet',
 'food','spicy, bold','Korean-style spicy tteokbokki (rice cake in gochujang) or Thai green curry',
 'contrast','Nigori''s sweetness and residual rice starch are a classic spice moderator; the contrast reduces heat perception without quenching','main','classic',1,true),
(130,'sake','nigori','Tsuki no Katsura Junmai Nigori',
 'dessert','rich, creamy','Matcha panna cotta — bitter-sweet dairy dessert',
 'complement','The creamy rice texture of nigori and the cream of panna cotta create a textural complement; matcha bitterness cuts nigori sweetness','dessert','established',2,true),
(130,'sake','nigori','Tsuki no Katsura Junmai Nigori',
 'pastry','sweet, fruity','Strawberry daifuku — mochi with cream and strawberry',
 'complement','Nigori''s rice character is literally the mochi wrapper''s material; sake and wagashi in cultural harmony','dessert','classic',1,true),
(130,'sake','nigori','Tsuki no Katsura Junmai Nigori',
 'seafood','fried, crispy','Shrimp tempura with tentsuyu dipping sauce',
 'complement','The creamy nigori moderates frying''s textural intensity; rice starch matches rice-flour tempura batter','main','established',2,true),

-- 131: Tamanohikari Bizen Omachi Junmai Daiginjo (Fushimi, heirloom Omachi rice)
(131,'sake','junmai_daiginjo','Tamanohikari Bizen Omachi — heirloom Omachi rice from Okayama; earthy complexity',
 'mushroom','earthy, deep','Matsutake mushroom in clay pot — autumn premium ingredient',
 'complement','Omachi rice''s earthy depth resonates with matsutake''s piney earthiness; a seasonal pairing of rare precision','main','classic',1,true),
(131,'sake','junmai_daiginjo','Tamanohikari Bizen Omachi',
 'fish','aged, complex','Karasumi (dried mullet roe) — intense, savory, waxy',
 'complement','Omachi''s textured depth can stand beside karasumi''s intense concentrated savory; both are aged expressions of their medium','cheese','adventurous',2,true),
(131,'sake','junmai_daiginjo','Tamanohikari Bizen Omachi',
 'cheese','aged, complex','Aged pecorino or Manchego — sheep milk, nutty, crystalline',
 'complement','Heirloom rice daiginjo with aged sheep cheese: a cross-cultural pairing united by complexity and age expression','cheese','adventurous',2,true),
(131,'sake','junmai_daiginjo','Tamanohikari Bizen Omachi',
 'truffle','earthy, intense','Black truffle shavings on silken tofu with dashi',
 'elevate','Rare pairing: Omachi''s earthy depth and black truffle''s forest floor resonance elevate each other into something genuinely remarkable','amuse','experimental',2,true),

-- 132: Tamanohikari Junmai Ginjo
(132,'sake','junmai_ginjo','Tamanohikari Junmai Ginjo — clean Fushimi water expression',
 'seafood','light, clean','Tai (sea bream) carpaccio with ponzu jelly',
 'complement','Clean ginjo water character amplifies the delicate brine of white fish; ponzu''s citrus echoes the sake''s subtle acidic brightness','starter','classic',1,true),
(132,'sake','junmai_ginjo','Tamanohikari Junmai Ginjo',
 'vegetables','pickled, clean','Kyoto tsukemono — traditional Kyoto-style pickles (senmaizuke)',
 'bridge','Fushimi sake and Kyoto pickles: a regional pairing that reflects the soft-water cuisine culture of the region','starter','classic',1,true),
(132,'sake','junmai_ginjo','Tamanohikari Junmai Ginjo',
 'fish','steamed, light','Steamed flounder with chrysanthemum leaves and ponzu',
 'complement','Delicate white fish and clean ginjo in a seasonal autumn arrangement','fish_course','established',2,true),
(132,'sake','junmai_ginjo','Tamanohikari Junmai Ginjo',
 'amuse','elegant, light','Dashi jelly with seasonal garnish — kaiseki amuse',
 'complement','Premium Fushimi ginjo as an amuse companion to dashi jelly signals a kaiseki-level beverage programme','amuse','established',2,true),

-- 133: Tozai Snow Maiden Junmai Nigori (Fushimi)
(133,'sake','nigori','Tozai Snow Maiden Nigori — accessible, sweet, creamy; entry nigori',
 'food','spicy, Southeast Asian','Thai coconut curry — moderately spicy, aromatic',
 'contrast','Snow Maiden''s creamy sweetness is the classic Western pairing for spice; nigori moderates heat without suppressing aroma','main','classic',1,true),
(133,'sake','nigori','Tozai Snow Maiden Nigori',
 'cheese','creamy, mild','Fresh ricotta with honey and walnuts',
 'complement','Nigori''s milky rice texture pairs with fresh cheese''s lactic character; honey bridges the sweetness','dessert','established',2,true),
(133,'sake','nigori','Tozai Snow Maiden Nigori',
 'dessert','sweet, rice-based','Mochi ice cream — any flavour',
 'complement','Both nigori and mochi derive from rice; serving together is a cultural and flavour resonance','dessert','classic',1,true),
(133,'sake','nigori','Tozai Snow Maiden Nigori',
 'pastry','fruity, light','Mango sticky rice — Thai dessert',
 'complement','Tropical fruit and sweet sake share a fruit-forward character; sticky rice echoes the nigori texture','dessert','adventurous',2,true),

-- 134: Dassai 23 Junmai Daiginjo (Yamaguchi)
(134,'sake','junmai_daiginjo','Dassai 23 — 23% seimaibuai; the most polished junmai daiginjo in commercial production',
 'seafood','premium, cold','Live scallop sashimi (hotate) with yuzu and sea salt',
 'elevate','Dassai 23''s extreme polish produces a sake of pure fruit and water; it elevates the already-excellent scallop into a transcendent pairing','fish_course','classic',1,true),
(134,'sake','junmai_daiginjo','Dassai 23',
 'fish','premium sashimi','Bluefin chutoro (medium-fatty tuna) — warm-season harvest',
 'elevate','The pinnacle of sashimi meets one of sake''s most polished expressions; both are at their best without interference','fish_course','classic',1,true),
(134,'sake','junmai_daiginjo','Dassai 23',
 'celebration','premium amuse','Oscietra caviar with warm Japanese rice cake',
 'elevate','Premium sake with premium caviar: the rice character in Dassai 23 creates a natural connection with the warm rice cake base','celebration','adventurous',2,true),
(134,'sake','junmai_daiginjo','Dassai 23',
 'seafood','briny, cold','Hairy crab (kegani) — Hokkaido, steamed, clean sweet flesh',
 'elevate','Ultra-premium sake and ultra-premium cold-water crab: the restraint of both allows individual quality to speak','main','classic',1,true),
(134,'sake','junmai_daiginjo','Dassai 23',
 'pastry','refined sweet','White chocolate bonbon with yuzu filling',
 'complement','The sweet rice purity of Dassai 23 and the clean sweetness of white chocolate-yuzu share a restrained elegance','dessert','suggested',2,true),

-- 135: Dassai 39 Junmai Daiginjo
(135,'sake','junmai_daiginjo','Dassai 39 — accessible premium; 39% seimaibuai; Dassai''s entry daiginjo',
 'sashimi','varied','Omakase sashimi selection — chef''s choice',
 'complement','Dassai 39 is the benchmark for sashimi accompaniment at the premium level; sufficient fruit without obscuring any individual fish','fish_course','classic',1,true),
(135,'sake','junmai_daiginjo','Dassai 39',
 'seafood','briny, cold','Pacific oysters (Kumamoto or Minterbrook)',
 'cleanse','The clean polish of Dassai 39 cuts oyster brine and mineral cleanly','starter','classic',1,true),
(135,'sake','junmai_daiginjo','Dassai 39',
 'fish','delicate','Kyoto-style simmered fish (nishime) with taro root',
 'complement','The subtle sweetness of simmered fish in light dashi finds a companion in Dassai 39''s gentle rice sweetness','main','established',2,true),
(135,'sake','junmai_daiginjo','Dassai 39',
 'vegetables','light, seasonal','White peach amuse with light miso drizzle',
 'elevate','Peach echoes the sake''s signature stone-fruit aromatics; the pairing amplifies both','amuse','adventurous',2,true),

-- 136: Dassai Beyond Junmai Daiginjo (ultra-premium, no seimaibuai label)
(136,'sake','junmai_daiginjo','Dassai Beyond — Asahi Shuzo''s pinnacle; limitless polishing concept',
 'seafood','raw, pristine','White truffle shaved onto warm Japanese rice — winter',
 'elevate','Beyond''s purity provides a neutral-but-complex ground for white truffle to express itself fully; rare and extraordinary','amuse','experimental',1,true),
(136,'sake','junmai_daiginjo','Dassai Beyond',
 'fish','premium, live','Ise ebi (Japanese spiny lobster) — sashimi of live lobster',
 'elevate','Japan''s most prestigious sake with Japan''s most prestigious crustacean; the pairing is elemental — purity meeting purity','fish_course','classic',1,true),
(136,'sake','junmai_daiginjo','Dassai Beyond',
 'celebration','ultimate','Platinum-leaf amuse: single seasonal ingredient on a gold leaf',
 'elevate','Dassai Beyond as the beverage for a once-in-a-lifetime celebration moment; the sake is the statement','celebration','classic',1,true),
(136,'sake','junmai_daiginjo','Dassai Beyond',
 'pastry','minimalist','Singular piece of premium wagashi — Kyoto confection',
 'elevate','The traditional pairing for premium sake: one wagashi, one sake; the reduction of pairing to its most essential form','pre_dessert','classic',1,true),

-- 137: Juyondai Honmaru Junmai (rare, cult sake)
(137,'sake','junmai','Juyondai Honmaru — Yamagata cult sake; scarcity and refinement',
 'sashimi','premium, seasonal','Seasonal omakase sashimi by a certified itamae',
 'elevate','Juyondai is served at chef''s counter omakase in Tokyo and Kyoto; the pairing is the entire omakase format','fish_course','classic',1,true),
(137,'sake','junmai','Juyondai Honmaru',
 'mushroom','earthy, aromatic','Truffle-dusted enoki mushroom broth — simple but aromatic',
 'complement','The depth in Honmaru Junmai (no excessive polish — earthier than daiginjo) resonates with mushroom and truffle earth notes','starter','adventurous',2,true),
(137,'sake','junmai','Juyondai Honmaru',
 'fish','aged, cured','Buri (yellowtail) teriyaki — winter aged yellowtail',
 'complement','Winter yellowtail''s richer fat profile is balanced by Honmaru''s junmai body; teriyaki glaze bridges to sake''s caramel note','main','classic',1,true),
(137,'sake','junmai','Juyondai Honmaru',
 'celebration','intimate','Small gathering omakase — 4-6 guests; exceptional context',
 'elevate','Juyondai is poured at exclusive omakase to signal both the standard of the meal and the rarity of the occasion','celebration','classic',1,true),

-- 138: Born Gold Junmai Daiginjo (Fukui)
(138,'sake','junmai_daiginjo','Born Gold Junmai Daiginjo — Fukui premium; clean and mineral',
 'seafood','premium, sweet','Snow crab (zuwaigani) from the Sea of Japan — steamed',
 'elevate','Born Gold''s clean mineral character echoes the cold Sea of Japan from which Fukui''s snow crab is harvested; seasonal and regional resonance','main','classic',1,true),
(138,'sake','junmai_daiginjo','Born Gold',
 'fish','delicate sashimi','Aori ika (bigfin reef squid) sashimi — chewy, sweet',
 'complement','The mineral clarity of Born Gold complements squid''s glycine sweetness without interference','fish_course','classic',1,true),
(138,'sake','junmai_daiginjo','Born Gold',
 'seafood','umami-rich','Ikura (salmon roe) on warm rice — a donburi fragment',
 'bridge','Born Gold''s rice character bridges naturally to the warm rice base, letting ikura''s brine perform above','starter','established',2,true),
(138,'sake','junmai_daiginjo','Born Gold',
 'vegetables','seasonal, clean','Boiled fuki (butterbur) stems with miso',
 'complement','Spring vegetable bitterness is paired with clean daiginjo in the traditional seasonal table-setting of Japan','starter','classic',1,true),

-- 139: Born Dream Junmai Daiginjo
(139,'sake','junmai_daiginjo','Born Dream Junmai Daiginjo — Fukui prestige; ultra-refined',
 'seafood','extreme premium','Echizen crab (Fukui snow crab) — the regional specialty',
 'elevate','Born Dream is produced in Fukui; Echizen crab is Fukui''s most celebrated seafood; regional pairing of absolute integrity','main','classic',1,true),
(139,'sake','junmai_daiginjo','Born Dream',
 'fish','cold, clean','Nodoguro (blackthroat seaperch) sashimi — fatty and rich',
 'elevate','Nodoguro is one of Japan''s most prized fish; Born Dream''s refinement provides a suitable counterpart','fish_course','classic',1,true),
(139,'sake','junmai_daiginjo','Born Dream',
 'pastry','elegant, delicate','Wasanbon sugar wagashi — Shikoku refined sugar confection',
 'complement','The purity of wasanbon sugar and the purity of a premium junmai daiginjo: both express the philosophy of restraint','pre_dessert','classic',1,true),
(139,'sake','junmai_daiginjo','Born Dream',
 'celebration','special','Caviar amuse — small, cold, precious',
 'elevate','Japanese premium sake as champagne replacement for caviar service; rice character resonates with the briny sweetness','celebration','adventurous',2,true),

-- 140: Dewazakura Oka Cherry Bouquet Ginjo (Yamagata)
(140,'sake','ginjo','Dewazakura Oka — the sake that introduced ginjo to the world in the 1980s; floral icon',
 'seafood','delicate, sweet','White shrimp (shiro ebi) sashimi — Toyama speciality, tiny and sweet',
 'elevate','Dewazakura Oka defined the modern ginjo style; its cherry blossom aromatics elevate the natural sweetness of white shrimp','fish_course','classic',1,true),
(140,'sake','ginjo','Dewazakura Oka',
 'fish','light, steamed','Cherry blossom (sakura) salt-marinated sea bream — seasonal',
 'complement','Cherry blossom motif in both food and drink: seasonal sakura pairing of rare poetic coherence','starter','classic',1,true),
(140,'sake','ginjo','Dewazakura Oka',
 'pastry','floral, light','Sakura mochi — glutinous rice with red bean, cherry leaf wrap',
 'complement','Cherry blossom sake and cherry blossom wagashi: the definitive spring pairing','dessert','classic',1,true),
(140,'sake','ginjo','Dewazakura Oka',
 'vegetables','fresh, spring','Bamboo shoot with kinome pepper — spring seasonal',
 'complement','Dewazakura Oka''s spring-seasonal release timing and spring vegetables are synchronised; the pairing celebrates the same moment in the calendar','starter','established',2,true),

-- 141: Aramasa No. 6 X-type Junmai Ginjo (Akita, kimoto, aged white wine character)
(141,'sake','junmai_ginjo_kimoto','Aramasa No. 6 X-type — Akita natural fermentation; white wine character; acidic and complex',
 'seafood','acidic, citrus-dressed','Oysters with mignonette — Fanny Bay or Kumamoto with shallot vinegar',
 'complement','Aramasa''s wine-like acidity mirrors the vinegar in mignonette; its mineral depth speaks the same language as cold-Pacific oysters','starter','adventurous',2,true),
(141,'sake','junmai_ginjo_kimoto','Aramasa No. 6',
 'cheese','young, tangy','Young goat''s cheese — Chèvre — high lactic acidity',
 'bridge','Aramasa''s elevated acidity (wine-like structure) bridges naturally to the lactic acid of fresh chèvre — an unorthodox but remarkably coherent sake-cheese pairing','cheese','adventurous',2,true),
(141,'sake','junmai_ginjo_kimoto','Aramasa No. 6',
 'fish','acid-cured, citrus','Ceviche — white fish in citrus; Peruvian or Japanese-fusion style',
 'bridge','Aramasa''s citric-acid profile is the only sake with the structural acidity to sit alongside ceviche without seeming flat','starter','experimental',2,true),
(141,'sake','junmai_ginjo_kimoto','Aramasa No. 6',
 'vegetables','fermented, complex','Kimchi aged for 3+ months — deep, funky, acidic',
 'bridge','Both Aramasa and aged kimchi are products of complex lactic fermentation; their shared microbiology creates an unexpected but coherent bridge','casual','experimental',2,true);

COMMIT;
