-- East Asian Phase 11b: Pairing Intelligence — Shochu (155–170) + Japan Tea (203–222)
-- ~140 entries

BEGIN;

INSERT INTO pairing_intelligence
  (beverage_product_id, beverage_category, beverage_style, beverage_description,
   food_category, food_flavour_profile, food_description,
   pairing_type, flavour_logic, meal_context, confidence, authority_tier, is_published)
VALUES

-- ============================================================
-- SHOCHU — IMO (sweet potato): 155-160
-- ============================================================

-- 155: Kuro Kirishima Imo Jochu 25°
(155,'shochu','imo_shochu','Kuro Kirishima Imo 25° — Kirishima''s signature black koji imo shochu; earthy, complex',
 'pork','braised, rich','Kakuni pork belly braised in soy-mirin — Kyushu style',
 'complement','Black koji fermentation in Kuro Kirishima and braised soy-pork share caramel-umami complexity; both are Kyushu traditions','main','classic',1,true),
(155,'shochu','imo_shochu','Kuro Kirishima Imo 25°',
 'vegetables','grilled, charred','Yakiimo (charcoal-roasted sweet potato) — Kagoshima street food',
 'complement','The shochu''s sweet potato base resonates with the food''s sweet potato character; roasting amplifies the earthy-sweet bridge','casual','classic',1,true),
(155,'shochu','imo_shochu','Kuro Kirishima Imo 25°',
 'meat','grilled, fatty','Wagyu short rib — medium-high fat; Kagoshima kuro cattle',
 'cleanse','Imo shochu''s clean finish cuts through high-fat wagyu; regional pairing — Kagoshima beef with Kagoshima shochu','main','classic',1,true),
(155,'shochu','imo_shochu','Kuro Kirishima Imo 25°',
 'seafood','grilled, robust','Grilled bluefin tuna jaw (kama toro) — charcoal, bold',
 'complement','The bold character of Kuro Kirishima requires equally bold food; bluefin jaw has the fat density to match','main','adventurous',2,true),

-- 156: Red Kirishima Imo Jochu 25°
(156,'shochu','imo_shochu','Red Kirishima Imo 25° — lighter and sweeter than black koji; red koji expression',
 'pork','savory, grilled','Tonkatsu (breaded pork cutlet) with shredded cabbage',
 'cleanse','Red Kirishima''s lighter character cuts fried pork without overwhelming the simple freshness of cabbage','casual','classic',1,true),
(156,'shochu','imo_shochu','Red Kirishima Imo 25°',
 'vegetables','starchy, comforting','Satsuma-imo (sweet potato) tempura with light tentsuyu',
 'complement','Sweet potato in the shochu and sweet potato in the tempura; gentle resonance of shared ingredient','main','classic',1,true),
(156,'shochu','imo_shochu','Red Kirishima Imo 25°',
 'cheese','mild, cream','Cream cheese with honey — aperitif presentation',
 'contrast','Red Kirishima''s sweetness and light fruit character contrasts interestingly with cream cheese fat — uncommon but accessible','aperitif','adventurous',2,true),
(156,'shochu','imo_shochu','Red Kirishima Imo 25°',
 'dumplings','pork, fresh','Steamed shumai with yuzu ponzu',
 'cleanse','Light shochu cuts steamed dumpling fat cleanly; citrus ponzu mirrors the shochu''s delicate fruit','casual','established',2,true),

-- 157: Toko Imo Shochu 25° (Yamagata, less common imo region)
(157,'shochu','imo_shochu','Toko Imo 25° — Yamagata imo shochu; unusual northern expression',
 'meat','light, grilled','Grilled chicken meatball (tsukune) with egg yolk dip',
 'complement','Soft imo shochu character matches the gentle richness of chicken tsukune; egg yolk amplifies the shochu''s grain sweetness','casual','established',2,true),
(157,'shochu','imo_shochu','Toko Imo 25°',
 'seafood','savory, firm','Grilled squid with soy butter',
 'bridge','Imo shochu''s sweet potato earthiness bridges through soy''s fermentation depth to butter''s richness','casual','classic',1,true),
(157,'shochu','imo_shochu','Toko Imo 25°',
 'vegetables','pickled, fermented','Nukazuke (rice bran pickles) — Japanese summer pickles',
 'bridge','Both rice bran and shochu fermentation share a common microbial ecology; the pairing is internally coherent','casual','established',2,true),
(157,'shochu','imo_shochu','Toko Imo 25°',
 'noodles','savory, light','Cold somen noodles with tsuyu — summer dish',
 'complement','Light imo shochu on ice (oyawari style) beside cold noodles is a classic Japanese summer evening pairing','main','classic',1,true),

-- 158: Toko Premium Aged Imo Shochu 40°
(158,'shochu','imo_shochu_aged','Toko Premium 40° — aged imo shochu at high proof; approaching whisky territory',
 'meat','smoked, aged','Smoked duck breast — cherry wood; medium rare',
 'complement','The aged complexity of 40° imo shochu at high proof matches smoked duck''s deep flavour; both show the rewards of time','main','adventurous',2,true),
(158,'shochu','imo_shochu_aged','Toko Premium 40°',
 'cheese','aged, complex','Aged cheddar 3-year — sharp, crystalline',
 'complement','High-proof aged shochu and aged cheddar: both develop complexity through time; both need each other''s contrast','cheese','adventurous',2,true),
(158,'shochu','imo_shochu_aged','Toko Premium 40°',
 'chocolate','dark, bitter','70% dark chocolate — single origin, no sweetener',
 'complement','Aged imo shochu''s caramel-earth notes meet dark chocolate''s roasted bitterness; a digestif context','digestif','adventurous',2,true),
(158,'shochu','imo_shochu_aged','Toko Premium 40°',
 'meat','braised, dark sauce','Oxtail braised in red wine and soy — 8-hour cook',
 'bridge','40° aged shochu bridges through red wine''s tannin history in the braise and soy''s umami; a bold main course spirit','main','adventurous',2,true),

-- 159: Komasa Sakurajima Imo Shochu 25°
(159,'shochu','imo_shochu','Komasa Sakurajima — Kagoshima imo with active volcano island terroir',
 'seafood','rich, grilled','Grilled Kagoshima kurobuta pork neck with lemon',
 'complement','Kurobuta pork from Kagoshima and Kagoshima imo shochu: the same black pig breeds on the same sweet potatoes the shochu is made from — complete regional coherence','main','classic',1,true),
(159,'shochu','imo_shochu','Komasa Sakurajima',
 'vegetables','volcanic, mineral','Shirasu (baby whitebait) from Kagoshima Bay — mineral, briny, delicate',
 'bridge','Kagoshima shochu and Kagoshima bay shirasu: terroir pairing of place over style','starter','established',2,true),
(159,'shochu','imo_shochu','Komasa Sakurajima',
 'pork','grilled, simple','Shio koji (salt koji) marinated pork shoulder — simple grilled',
 'complement','Koji in the marinade and koji in the shochu fermentation: shared enzyme expression','main','classic',1,true),
(159,'shochu','imo_shochu','Komasa Sakurajima',
 'noodles','savory, cold','Kagoshima ramen — light pork and chicken broth',
 'bridge','Regional authenticity: Kagoshima ramen beside Kagoshima shochu is an expression of regional cuisine coherence','main','classic',1,true),

-- 160: Komasa Jozen Imo Shochu 25°
(160,'shochu','imo_shochu','Komasa Jozen — premium Komasa expression; cleaner and more refined than Sakurajima',
 'seafood','clean, premium','Premium sashimi selection — kinmedai (splendid alfonsino), hirame',
 'complement','Refined imo shochu''s clean character is the complement for premium white-fleshed sashimi; restraint allowing the fish to lead','fish_course','established',2,true),
(160,'shochu','imo_shochu','Komasa Jozen',
 'vegetables','seasonal, light','Spring mountain vegetables (sansai) lightly dressed with sesame',
 'complement','Spring mountain vegetables echo the wild, earthy origin of imo shochu''s terroir','starter','established',2,true),
(160,'shochu','imo_shochu','Komasa Jozen',
 'fish','miso-marinated','Saikyo miso black cod (gindara) — sweet, tender',
 'complement','Refined imo shochu and miso-marinated fish are natural izakaya companions; the sweetness of saikyo miso bridges the shochu''s sweet potato base','main','classic',1,true),
(160,'shochu','imo_shochu','Komasa Jozen',
 'cheese','mild fermented','Fromage blanc with yuzu jam',
 'contrast','Unusual: clean imo shochu contrasting with mild fresh cheese; yuzu bridges both','cheese','experimental',2,true),

-- ============================================================
-- SHOCHU — MUGI (barley): 162-165
-- ============================================================

-- 162: Iichiko Silhouette Mugi Jochu 25°
(162,'shochu','mugi_shochu','Iichiko Silhouette — the definitive accessible mugi shochu; clean, light, versatile',
 'sashimi','clean, light','Any sashimi selection — everyday context',
 'complement','Iichiko Silhouette is the universal sashimi shochu: clean enough for any fish, present enough to add value','fish_course','classic',1,true),
(162,'shochu','mugi_shochu','Iichiko Silhouette',
 'dumplings','gyoza-style','Gyoza and edamame — standard izakaya opening',
 'cleanse','The role of mugi shochu as the clean-slate drink between bites at an izakaya; Iichiko is the accessible benchmark','casual','classic',1,true),
(162,'shochu','mugi_shochu','Iichiko Silhouette',
 'noodles','savory, cold','Cold barley tea-dressed udon with cucumber',
 'complement','Barley in the noodle accompaniment and barley in the shochu: grain-to-grain resonance','main','suggested',2,true),
(162,'shochu','mugi_shochu','Iichiko Silhouette',
 'seafood','fried','Karaage squid (ika karaage) — lightly fried',
 'cleanse','Standard izakaya pairing: light mugi shochu cuts frying oil without dominating','casual','classic',1,true),

-- 163: Iichiko Frasco 30° Mugi Jochu
(163,'shochu','mugi_shochu','Iichiko Frasco 30° — wine-glass presentation; elevated mugi character',
 'cheese','mild, young','Fresh mozzarella with tomato and basil',
 'contrast','Iichiko Frasco is marketed for wine-glass service; pairing with Italian-style fresh cheese is the Western gateway','starter','adventurous',2,true),
(163,'shochu','mugi_shochu','Iichiko Frasco 30°',
 'vegetables','roasted, umami','Roasted Japanese eggplant with miso dengaku',
 'complement','Mugi shochu''s mild barley depth resonates with the miso''s grain fermentation; eggplant provides body','main','established',2,true),
(163,'shochu','mugi_shochu','Iichiko Frasco 30°',
 'fish','grilled, light','Grilled sanma (Pacific saury) — autumn seasonal',
 'complement','Frasco''s elevated character is suitable for seasonal fish pairing as a dinner shochu (not just izakaya)','main','established',2,true),
(163,'shochu','mugi_shochu','Iichiko Frasco 30°',
 'meat','light, savory','Chicken tatsuta-age (ginger-soy marinated fried chicken)',
 'cleanse','30° mugi shochu has the strength to cut through the richness of marinated and fried chicken while the ginger note echoes barley''s warmth','casual','classic',1,true),

-- 164: Naka Naka Mugi Shochu 25°
(164,'shochu','mugi_shochu','Naka Naka — premium single-distillation mugi with rich barley character',
 'cheese','aged, nutty','Comté 24-month — nutty, crystalline, complex',
 'complement','Premium mugi shochu''s barley depth and aged Comté''s nuttiness share a toasted grain register','cheese','adventurous',2,true),
(164,'shochu','mugi_shochu','Naka Naka',
 'meat','braised, dark','Beef tendon nikujaga — Japanese comfort stew with potato and soy',
 'bridge','The warm barley depth of Naka Naka bridges through the soy-sweet stew to potato''s starch; comfort food shochu','main','classic',1,true),
(164,'shochu','mugi_shochu','Naka Naka',
 'vegetables','earthy, savory','Kinpira gobo (burdock root and carrot stir-fry) — earthy, sesame',
 'complement','Burdock root''s earthy complexity resonates with single-distilled mugi shochu''s own earthy depth','main','established',2,true),
(164,'shochu','mugi_shochu','Naka Naka',
 'chocolate','medium, milk','Milk chocolate with a grain base (malted barley chocolate)',
 'complement','Barley shochu and malted barley chocolate: perfect grain resonance for a digestif context','digestif','adventurous',2,true),

-- 165: Iichiko Special Mugi Jochu 43°
(165,'shochu','mugi_shochu_aged','Iichiko Special 43° — high-proof aged mugi; spirit-class territory',
 'meat','smoked, rich','Smoked brisket — 12-hour oak smoke',
 'complement','43° high-proof mugi shochu matches smoked beef''s intensity; both are aged expressions developed through heat and time','main','adventurous',2,true),
(165,'shochu','mugi_shochu_aged','Iichiko Special 43°',
 'cheese','strong, aged','Roquefort — intense sheep blue cheese',
 'contrast','High-proof grain spirit and strong blue cheese: the spirit cuts through the fat while its grain sweetness contrasts the cheese''s salt','cheese','adventurous',2,true),
(165,'shochu','mugi_shochu_aged','Iichiko Special 43°',
 'meat','cured, fatty','Charcuterie board — aged ham, saucisson, terrine',
 'complement','Aged mugi shochu and aged charcuterie: both express the philosophy of time-developing complexity','casual','adventurous',2,true),
(165,'shochu','mugi_shochu_aged','Iichiko Special 43°',
 'chocolate','dark, intense','85% dark chocolate single origin — intense bitterness',
 'bridge','43° shochu bridges through dark chocolate''s roast bitterness; the grain base softens what pure spirits would clash with','digestif','adventurous',2,true),

-- ============================================================
-- AWAMORI: 166-170
-- ============================================================

-- 166: Helios Ryukyu Awamori 25°
(166,'shochu','awamori','Helios Ryukyu Awamori 25° — light entry awamori; accessible Okinawan style',
 'meat','braised, Okinawan','Rafute — Okinawan braised pork belly in awamori, soy, and brown sugar',
 'complement','Rafute is traditionally cooked with awamori; serving awamori alongside creates a cooking-and-table resonance','main','classic',1,true),
(166,'shochu','awamori','Helios Ryukyu Awamori 25°',
 'seafood','tropical, light','Okinawan-style ceviche — white fish with island citrus and chili',
 'bridge','Tropical character of Ryukyu awamori bridges to the tropical citrus and chili of this island-style ceviche','starter','established',2,true),
(166,'shochu','awamori','Helios Ryukyu Awamori 25°',
 'dumplings','Okinawan-style','Champuru (Okinawan stir-fry) — tofu, bittermelon, pork',
 'cleanse','The classic Okinawan pairing: awamori beside goya champuru cuts through tofu''s water and bittermelon''s bitterness','main','classic',1,true),
(166,'shochu','awamori','Helios Ryukyu Awamori 25°',
 'pork','grilled, tropical','Okinawan soba with braised pork and kamaboko',
 'complement','Okinawan soba and Okinawan awamori: the regional pairing is complete','main','classic',1,true),

-- 167: Zuisen Awamori Koshu 5-Year
(167,'shochu','awamori_koshu','Zuisen Koshu 5-Year — aged awamori; developing depth and roundness',
 'pork','braised, aged-sauce','Rafute with a richer, older sauce reduction',
 'elevate','5-year koshu awamori with an aged rafute sauce: the time invested in both elevates the pairing above the standard version','main','established',2,true),
(167,'shochu','awamori_koshu','Zuisen Koshu 5-Year',
 'cheese','aged, hard','Aged gouda or pecorino — firm, caramel, crystalline',
 'complement','Aged awamori and aged cheese: the shared transformation through time creates a cross-cultural pairing of depth','cheese','adventurous',2,true),
(167,'shochu','awamori_koshu','Zuisen Koshu 5-Year',
 'meat','slow-roasted','Slow-roasted duck with star anise and citrus',
 'complement','5-year aging adds vanilla and caramel to the awamori base; these notes complement duck''s rich fat and star anise aromatic','main','adventurous',2,true),
(167,'shochu','awamori_koshu','Zuisen Koshu 5-Year',
 'chocolate','dark, complex','Dark chocolate with sea salt and sesame',
 'bridge','Aged awamori''s caramel complexity bridges dark chocolate and sesame; tropical spirit DNA connects to the sesame''s oil richness','digestif','adventurous',2,true),

-- 168: Zuisen Awamori Koshu 10-Year
(168,'shochu','awamori_koshu','Zuisen Koshu 10-Year — deep aged awamori; approaching aged rum territory',
 'meat','complex, braised','Okinawan 8-hour rafute with grated turmeric and bitter melon reduction',
 'elevate','10-year koshu deserves a more complex preparation than standard rafute; the depth of the spirit amplifies the complexity of the dish','main','established',2,true),
(168,'shochu','awamori_koshu','Zuisen Koshu 10-Year',
 'cheese','blue, intense','Gorgonzola naturale — aged, complex blue',
 'contrast','10-year awamori''s sugar cane-adjacent sweetness contrasts the salt and funk of aged gorgonzola in a pairing that crosses the Pacific','cheese','experimental',2,true),
(168,'shochu','awamori_koshu','Zuisen Koshu 10-Year',
 'dessert','tropical fruit','Guava and coconut panna cotta — tropical',
 'complement','Awamori''s tropical terroir (subtropical Ryukyu Islands) resonates with tropical dessert; aged version provides enough structure','dessert','adventurous',2,true),
(168,'shochu','awamori_koshu','Zuisen Koshu 10-Year',
 'chocolate','70% dark, complex','Plantation rum chocolate — tropical notes',
 'complement','Aged awamori and rum-infused chocolate: both derive character from tropical terroir and barrel-time complexity','digestif','adventurous',2,true),

-- 169: Kumesen Kusu 3-Year Awamori
(169,'shochu','awamori_koshu','Kumesen Kusu 3-Year — entry koshu; approachable aged awamori',
 'pork','grilled','Grilled pork belly slice (kakuni-style) over white rice',
 'cleanse','Young koshu''s clean tropical base with slight age cuts through pork fat effectively','main','classic',1,true),
(169,'shochu','awamori_koshu','Kumesen Kusu 3-Year',
 'seafood','tropical-preparation','Grilled mahi-mahi (shiira) with Okinawan turmeric sauce',
 'bridge','Tropical fish and tropical spirit: the shared subtropical origin creates natural harmony','main','established',2,true),
(169,'shochu','awamori_koshu','Kumesen Kusu 3-Year',
 'vegetables','stir-fried, light','Stir-fried tofu and beansprouts with sesame',
 'complement','Entry koshu''s light character pairs well with mild stir-fry; age adds just enough depth to prevent the shochu from disappearing','casual','established',2,true),
(169,'shochu','awamori_koshu','Kumesen Kusu 3-Year',
 'dessert','mild, sweet','Okinawan tart (mango-passion fruit)',
 'complement','3-year koshu''s developing tropical character meets tropical fruit dessert in a Okinawan dessert pairing','dessert','established',2,true),

-- 170: Kumesen Kusu 25-Year Aged Awamori
(170,'shochu','awamori_koshu','Kumesen Kusu 25-Year — the apex of Ryukyu aged spirits; approaching single malt complexity',
 'chocolate','premium single origin','Araujo 72% Venezuelan dark chocolate — complex, tropical',
 'elevate','25 years of clay pot aging + tropical origin = a spirit deserving of the most complex chocolate; a meditation on time','digestif','adventurous',2,true),
(170,'shochu','awamori_koshu','Kumesen Kusu 25-Year',
 'cheese','aged, complex','Aged mimolette (French) 24-month — carotene-red, intense',
 'complement','25-year aged awamori and aged mimolette: the most ambitious cross-cultural aged pairing in this collection','cheese','experimental',2,true),
(170,'shochu','awamori_koshu','Kumesen Kusu 25-Year',
 'meat','celebratory','Okinawan 24-hour slow-roasted whole suckling pig (uchina-style)',
 'elevate','The rarest Okinawan spirit with the most ceremonial Okinawan food preparation: 25-year koshu kusu for a special celebration','celebration','classic',1,true),
(170,'shochu','awamori_koshu','Kumesen Kusu 25-Year',
 'dessert','tropical, complex','Passionfruit soufflé with Okinawan brown sugar',
 'complement','25-year aged spirit beside tropical soufflé: the developed caramel of long aging meets the natural sweetness of island sugarcane','dessert','adventurous',2,true),

-- ============================================================
-- JAPAN TEA — MATCHA (203–209)
-- ============================================================

-- 203: Ippodo Ummon Ceremonial Matcha
(203,'tea','matcha_ceremonial','Ippodo Ummon — Kyoto''s premier ceremonial matcha; deep umami, vivid colour',
 'confection','mild sweet, bean-based','Nerikiri wagashi — seasonal shaped confection, white bean paste',
 'complement','The classic chanoyu pairing: ceremonial matcha with precision-crafted wagashi; the sweet bean paste moderates matcha''s bitterness and amplifies the umami finish','pre_dessert','classic',1,true),
(203,'tea','matcha_ceremonial','Ippodo Ummon',
 'seafood','sweet, briny','Uni (sea urchin) on warm rice — light soy',
 'elevate','Both Ummon matcha and fresh uni express extreme umami; the pairing is a convergence of ocean and mountain umami that elevates both','amuse','experimental',2,true),
(203,'tea','matcha_ceremonial','Ippodo Ummon',
 'dairy','light cream','Crème brûlée with matcha sugar — subtle green tea crust',
 'bridge','Matcha bridges into the cream through both the garnish and the served tea; the pairing is self-referential and coherent','dessert','established',2,true),
(203,'tea','matcha_ceremonial','Ippodo Ummon',
 'chocolate','white, delicate','White chocolate with yuzu ganache',
 'complement','White chocolate''s dairy-sweetness and matcha''s umami-bitter are the classic matcha confection pairing; yuzu bridges both','dessert','classic',1,true),
(203,'tea','matcha_ceremonial','Ippodo Ummon',
 'pastry','minimal sweet','Daifuku mochi — soft rice cake with red bean paste',
 'complement','Mochi''s subtle sweetness is the daily companion to ceremonial matcha in Japan; the pairing has 500 years of tradition','pre_dessert','classic',1,true),

-- 204: Ippodo Kan-un Ceremonial Matcha
(204,'tea','matcha_ceremonial','Ippodo Kan-un — second-tier ceremonial; refined and accessible daily',
 'confection','light sweet','Yokan (red bean jelly) — cold, firm, barely sweet',
 'complement','Yokan''s clean sweetness perfectly moderates Kan-un''s umami-bitterness; classic daily wagashi companion','pre_dessert','classic',1,true),
(204,'tea','matcha_ceremonial','Ippodo Kan-un',
 'pastry','buttery, light','Madeleine with lemon zest',
 'contrast','French butter cake''s richness contrasts matcha''s clean bitterness; modern East-West pairing for a contemporary setting','dessert','adventurous',2,true),
(204,'tea','matcha_ceremonial','Ippodo Kan-un',
 'dairy','rich cream','Soft-serve matcha ice cream with black sesame',
 'complement','The ceremonial grade elevates even a simple matcha ice cream presentation; serving the tea alongside the ice cream creates meta-resonance','dessert','established',2,true),
(204,'tea','matcha_ceremonial','Ippodo Kan-un',
 'pastry','neutral base','Plain steamed bao with sesame oil',
 'bridge','Neutral steam bread is a clean canvas for ceremonial matcha; the sesame oil provides a fat-rich bridge to the tea''s umami','casual','suggested',2,true),

-- 205: Marukyu Koyamaen Wako Ceremonial Matcha
(205,'tea','matcha_ceremonial','Marukyu Koyamaen Wako — Uji ceremonial; intense colour, deep umami',
 'confection','sweet, floral','Higashi (dry wagashi) — pressed sugar flowers; spring seasonal',
 'complement','The formality of Wako matcha pairs with the formality of higashi (dry wagashi); the pairing signals a chanoyu context of highest register','pre_dessert','classic',1,true),
(205,'tea','matcha_ceremonial','Marukyu Koyamaen Wako',
 'vegetables','earthy, seasonal','Bamboo shoot gratin with light cream and bonito',
 'bridge','The deep umami of Wako matcha bridges to bonito''s katsuobushi depth; spring bamboo provides earthy grounding','starter','experimental',2,true),
(205,'tea','matcha_ceremonial','Marukyu Koyamaen Wako',
 'dairy','rich dessert','Matcha pavlova — meringue, cream, red beans',
 'complement','Wako''s intense colour and flavour is sustained even through the richness of pavlova cream; the red bean garnish reinforces wagashi tradition','dessert','established',2,true),
(205,'tea','matcha_ceremonial','Marukyu Koyamaen Wako',
 'chocolate','dark, complex','70% Valrhona with sesame praline',
 'contrast','The bitterness of premium dark chocolate and the umami bitterness of ceremonial matcha stand together without redundancy','dessert','adventurous',2,true),

-- 206-208: Remaining matcha (grouping for efficiency)
(206,'tea','matcha_ceremonial','Marukyu Koyamaen Aoarashi — slightly lighter than Wako; excellent daily ceremonial',
 'confection','mild sweet, seasonal','Ohagi (sticky rice balls with bean paste) — autumn',
 'complement','Autumn wagashi and autumn ceremonial matcha: seasonal resonance','pre_dessert','classic',1,true),
(206,'tea','matcha_ceremonial','Marukyu Aoarashi',
 'pastry','light, neutral','Shortbread with black sesame',
 'complement','The slightly lighter character of Aoarashi is complemented by sesame''s nutty depth in the shortbread','dessert','established',2,true),
(206,'tea','matcha_ceremonial','Marukyu Aoarashi',
 'dairy','cream, mild','Panna cotta with yuzu curd — clean and light',
 'complement','Aoarashi''s clean bitterness and panna cotta''s clean cream — a deconstructed matcha latte in food form','dessert','established',2,true),
(206,'tea','matcha_ceremonial','Marukyu Aoarashi',
 'chocolate','white, sweet','White chocolate bark with freeze-dried raspberry',
 'contrast','The berry acidity and white chocolate sweetness contrast Aoarashi''s green umami-bitter; a colourful modern pairing','dessert','adventurous',2,true),

(207,'tea','matcha_ceremonial','Nakamura Tokichi Uji Ceremonial — historic Uji house, limited production',
 'confection','sweet, complex','Kuzumochi — cold kuzu starch jelly with kinako and brown sugar syrup',
 'complement','One of Kyoto''s most traditional summer wagashi beside Uji''s most traditional tea house production','pre_dessert','classic',1,true),
(207,'tea','matcha_ceremonial','Nakamura Tokichi',
 'pastry','light sweet','Matcha roll cake — light sponge, cream filling',
 'complement','The self-referential matcha pairing: a matcha confection alongside a freshly prepared bowl amplifies the tea experience','dessert','classic',1,true),
(207,'tea','matcha_ceremonial','Nakamura Tokichi',
 'vegetables','light, mild','Light cucumber and radish tsukemono before matcha service',
 'cleanse','Pickles before matcha reset the palate; Nakamura Tokichi is served this way at the source in Uji','pre_dessert','classic',1,true),
(207,'tea','matcha_ceremonial','Nakamura Tokichi',
 'dairy','soft, mild','Mascarpone with matcha and brown sugar — Italian-Japanese fusion',
 'complement','Uji matcha''s terroir depth supports even mascarpone''s richness; the combination is found in some Kyoto-fusion preparations','dessert','adventurous',2,true),

(208,'tea','matcha_ceremonial','Kyoto Obubu Okumidori — single-cultivar; grape-like Okumidori notes',
 'confection','floral, light','Kinton (smooth sweet potato and bean paste mound) — autumn wagashi',
 'complement','Okumidori''s grape-like note resonates with the smooth sweetness of kinton; both are autumn expressions of nature''s sweetness','pre_dessert','established',2,true),
(208,'tea','matcha_ceremonial','Kyoto Obubu Okumidori',
 'pastry','floral, honey','Lavender honey madeleines',
 'contrast','Okumidori''s natural grape-floral note contrasts interestingly with lavender-honey; a contemporary pairing for a progressive tea programme','dessert','adventurous',2,true),
(208,'tea','matcha_ceremonial','Kyoto Obubu Okumidori',
 'fruit','mild, seasonal','Fresh fig with mild honey — autumn',
 'complement','The grape and stone-fruit notes in Okumidori resonate with fresh fig; both are expressions of the same autumn sweetness','pre_dessert','suggested',2,true),
(208,'tea','matcha_ceremonial','Kyoto Obubu Okumidori',
 'dairy','light, neutral','Fresh ricotta with honey',
 'contrast','Clean fresh cheese contrasts the single-cultivar matcha''s complexity; honey mediates','pre_dessert','adventurous',2,true),

-- 209: Yamamotoyama Culinary Matcha
(209,'tea','matcha_culinary','Yamamotoyama Culinary Matcha — high-volume culinary grade; robust and affordable',
 'baking','bitter, structured','Matcha financier, matcha tiramisu, matcha pound cake',
 'complement','Culinary-grade matcha is designed for baking integration; the deeper, more robust flavour holds through heat better than ceremonial','dessert','classic',1,true),
(209,'tea','matcha_culinary','Yamamotoyama Culinary',
 'dairy','ice cream, frozen','Matcha ice cream, matcha semifreddo',
 'complement','Culinary matcha''s assertive flavour cuts through the cream and sugar dilution of ice cream more effectively than delicate ceremonial grades','dessert','classic',1,true),
(209,'tea','matcha_culinary','Yamamotoyama Culinary',
 'pastry','sweet, creamy','Matcha cheesecake — dense, sweet base',
 'complement','Culinary grade''s bitterness structure cuts through cheesecake''s sweetness; the pairing is designed for this','dessert','classic',1,true),
(209,'tea','matcha_culinary','Yamamotoyama Culinary',
 'sauce','savoury, green','Matcha salt for tempura — savoury application',
 'bridge','Using culinary matcha in savoury application (matcha salt, matcha butter) alongside a served tea drink creates continuity across the menu','main','adventurous',2,true),

-- ============================================================
-- GYOKURO (210–212)
-- ============================================================
(210,'tea','gyokuro','Ippodo Gyokuro Sayamakaori — shaded 30 days; intense umami, silk texture',
 'seafood','briny, raw','Freshly shucked oysters — no dressing; pure brine',
 'complement','Both gyokuro and raw oysters are expressions of pure terroir in liquid form; the sea-mineral of oysters and the L-theanine umami of shaded tea share register','starter','adventurous',2,true),
(210,'tea','gyokuro','Ippodo Gyokuro Sayamakaori',
 'fish','raw, sweet','White fish sashimi — tai or hirame; no garnish',
 'elevate','Gyokuro cold brew (see service protocol) as a pre-starter beverage elevates the entire sashimi experience; umami before umami','amuse','adventurous',2,true),
(210,'tea','gyokuro','Ippodo Gyokuro Sayamakaori',
 'cheese','mild, fresh','Fresh ricotta or fromage frais — minimal salt',
 'contrast','The extreme umami of gyokuro contrasted with the clean neutral lactic acid of fresh cheese; an unusual but conceptually sound pairing','starter','experimental',2,true),
(210,'tea','gyokuro','Ippodo Gyokuro Sayamakaori',
 'vegetables','clean, delicate','White asparagus with light dashi butter',
 'complement','Spring vegetable''s mineral delicacy amplified by the L-theanine depth of gyokuro; spring on spring','starter','established',2,true),

(211,'tea','gyokuro','Marukyu Koyamaen Gyokuro Unkaku — full shading 30 days; profound depth',
 'fish','cold, sweet','Hotate (Hokkaido scallop) sashimi — naturally sweet, no garnish',
 'elevate','Unkaku''s extreme umami depth elevates the natural glycine sweetness of cold-water scallop; a convergence of ocean and mountain terroir','fish_course','adventurous',2,true),
(211,'tea','gyokuro','Marukyu Koyamaen Unkaku',
 'seafood','complex, umami','Chawanmushi with uni and dashi — double umami custard',
 'complement','Gyokuro''s umami and chawanmushi''s double-umami (dashi + uni): the most intensive umami beverage pairing in this collection','amuse','experimental',1,true),
(211,'tea','gyokuro','Marukyu Koyamaen Unkaku',
 'confection','mild, bean-based','Salty sakura mochi — cherry blossom, barely sweet, slightly salty',
 'contrast','Salt in the wagashi contrasts the sweet umami of gyokuro; the tension is pleasant and unusual','pre_dessert','adventurous',2,true),
(211,'tea','gyokuro','Marukyu Koyamaen Unkaku',
 'vegetables','seaweed, mineral','Nori-wrapped tofu with light dashi — simple',
 'complement','Nori''s ocean mineral and gyokuro''s mountain mineral: both are shade-produced forms of deep green umami','starter','classic',1,true),

(212,'tea','gyokuro','Kyoto Obubu Gyokuro — single-origin single-cultivar shaded tea',
 'seafood','light, clean','Miso soup with wakame and fu (wheat gluten)',
 'complement','Gyokuro''s seaweed-mineral note resonates with wakame''s ocean character; dashi provides umami continuity','starter','established',2,true),
(212,'tea','gyokuro','Kyoto Obubu Gyokuro',
 'confection','subtle, earthy','Sesame tofu (goma dofu) — smooth, barely sweet, nutty',
 'complement','Sesame tofu''s subtle nuttiness and gyokuro''s umami depth complement without competing; a Kyoto-temple pairing','pre_dessert','classic',1,true),
(212,'tea','gyokuro','Kyoto Obubu Gyokuro',
 'fish','light, delicate','Steamed sea bream with yuzu dashi',
 'complement','Delicate white fish and delicate gyokuro: restraint on both sides allows individual quality to lead','fish_course','established',2,true),
(212,'tea','gyokuro','Kyoto Obubu Gyokuro',
 'vegetables','blanched, umami','Blanched spinach with sesame dressing (gomaae)',
 'complement','Spinach''s iron-mineral note meets gyokuro''s deep green umami; sesame bridges the fat gap between tea and vegetable','starter','established',2,true),

-- ============================================================
-- SENCHA (213–217)
-- ============================================================
(213,'tea','sencha','Ippodo Sencha Shogyokuro — premium first-flush sencha',
 'fish','delicate, white','White fish carpaccio with yuzu olive oil — spring',
 'complement','Spring sencha and spring white fish: the same season''s expression in different media','starter','classic',1,true),
(213,'tea','sencha','Ippodo Shogyokuro',
 'vegetables','spring, fresh','Snap pea and asparagus salad with bonito flakes',
 'complement','Spring vegetables and spring first-flush sencha: a meal built around seasonal synchronicity','starter','classic',1,true),
(213,'tea','sencha','Ippodo Shogyokuro',
 'seafood','light, steamed','Chawanmushi with spring peas and clam',
 'complement','Premium sencha''s clean umami complements dashi-based custard without asserting itself','starter','established',2,true),
(213,'tea','sencha','Ippodo Shogyokuro',
 'seafood','fresh, briny','Cockle clams or hamaguri clams with miso',
 'cleanse','Sencha''s clean astringency resets the palate between bivalves; the grassy note mirrors the clams'' marine environment','starter','established',2,true),

(214,'tea','sencha','Marukyu Koyamaen Tsujikaze — refined sencha with elegant balance',
 'confection','light sweet','Castella — Japanese honey sponge cake',
 'complement','The classic afternoon tea pairing in Japan: sencha and castella; the honey of castella bridges to the tea''s sweetness','casual','classic',1,true),
(214,'tea','sencha','Marukyu Tsujikaze',
 'fish','grilled, light','Shishamo (smelt) grilled whole — tiny, seasonal',
 'complement','Light sencha and small grilled fish: both are precise and restrained; an autumn izakaya pairing','casual','classic',1,true),
(214,'tea','sencha','Marukyu Tsujikaze',
 'vegetables','spring, mild','Japanese-style potato salad with light mayo',
 'cleanse','Sencha''s clean astringency cuts through mayo''s fat in potato salad; the pairing is accessible and appealing','casual','established',2,true),
(214,'tea','sencha','Marukyu Tsujikaze',
 'noodles','cold, light','Soomen with yuzu tsuyu',
 'complement','Summer cold noodles and summer fresh sencha: cool and refreshing; the yuzu note echoes sencha''s citric brightness','main','established',2,true),

(215,'tea','sencha','Nishide Fukamushi — deep-steamed sencha; richer, more umami',
 'fish','fatty, grilled','Grilled salmon with shio koji',
 'cleanse','Fukamushi''s deeper umami cuts salmon fat; its green vegetable note contrasts the koji''s sweetness','main','established',2,true),
(215,'tea','sencha','Nishide Fukamushi',
 'vegetables','steamed, simple','Steamed edamame — lightly salted',
 'complement','Deep-steamed sencha and deep-steamed soybeans share a cooked-vegetable green depth','aperitif','classic',1,true),
(215,'tea','sencha','Nishide Fukamushi',
 'sushi','everyday','Tekka maki (tuna roll) and kappa maki (cucumber roll)',
 'cleanse','Fukamushi''s slightly heavier character handles tuna maki''s bold flavour better than delicate first-flush sencha','casual','classic',1,true),
(215,'tea','sencha','Nishide Fukamushi',
 'cheese','mild, nutty','Raclette or Gruyère — melted, mild, savory',
 'contrast','Unusual: the deep umami of fukamushi sencha versus melted Swiss cheese; the grassy note contrasts cheese''s nuttiness','casual','experimental',2,true),

(216,'tea','sencha','Kagoshima Chiran Saemidori — southern Japan''s premium cultivar',
 'fish','miso-marinated','Gindara saikyo miso — black cod with sweet white miso',
 'complement','Kagoshima sencha and Kyoto miso preparation: south meets north through the complementary sweetness of cultivar and miso','main','adventurous',2,true),
(216,'tea','sencha','Chiran Saemidori',
 'vegetables','tropical, light','Stir-fried seasonal greens with garlic and light soy',
 'complement','Kagoshima''s warmer-climate sencha (Saemidori) resonates with bolder vegetable preparations than delicate Kyoto sencha allows','main','established',2,true),
(216,'tea','sencha','Chiran Saemidori',
 'meat','light, chicken','Light chicken broth with Kagoshima sweet potato — warming',
 'complement','Kagoshima regional pairing: Kagoshima sencha with a Kagoshima-ingredient soup','casual','established',2,true),
(216,'tea','sencha','Chiran Saemidori',
 'confection','sweet, southern Japan','Karukan — light Japanese rice flour confection (Kagoshima speciality)',
 'complement','Regional confection and regional tea: Kagoshima''s defining tea and confection pairing','pre_dessert','classic',1,true),

(217,'tea','sencha','Kyoto Obubu Kabuse Sencha — 14-day shaded; between sencha and gyokuro',
 'seafood','delicate, fresh','Yudofu (simmered silken tofu in kombu dashi)',
 'complement','Kabuse''s shading depth adds umami to what would otherwise be too light a match for gyokuro-heavy dishes; sits perfectly beside tofu','starter','established',2,true),
(217,'tea','sencha','Kyoto Obubu Kabuse',
 'fish','delicate, raw','Hirame (flounder) sashimi with momiji oroshi (grated daikon-chili)',
 'complement','Kabuse''s delicate shade-umami and flounder''s delicate white flesh: a pairing where both are half-way to their respective richest selves','fish_course','established',2,true),
(217,'tea','sencha','Kyoto Obubu Kabuse',
 'vegetables','light, seasonal','Kinome-dressed spring vegetables — mountain pepper leaves',
 'complement','Spring kabuse sencha and spring kinome mountain pepper: the first gathering of mountain foods with the first shaded tea','starter','classic',1,true),
(217,'tea','sencha','Kyoto Obubu Kabuse',
 'confection','light, green tea','Uji matcha soft serve — green tea ice cream',
 'bridge','Serving kabuse sencha alongside a matcha confection creates a tea-family conversation between the shaded sencha and fully shaded matcha','dessert','adventurous',2,true),

-- ============================================================
-- SPECIALTY TEAS: Hojicha, Genmaicha, Tamaryokucha, Shincha, Tencha (218–222)
-- ============================================================
(218,'tea','hojicha','Ippodo Uji Hojicha — premium roasted green tea; caramel, low caffeine',
 'chocolate','milk chocolate, caramel','Milk chocolate with caramel — approachable, sweet',
 'complement','Hojicha''s roasted caramel note and milk chocolate''s caramel: natural resonance in both roast character and sweetness','dessert','classic',1,true),
(218,'tea','hojicha','Ippodo Hojicha',
 'meat','grilled, savory','Yakitori assorted — liver, hearts, gizzard on charcoal',
 'complement','Charcoal roasting in the yakitori and charcoal roasting in the hojicha: a smoking-methods bridge','casual','classic',1,true),
(218,'tea','hojicha','Ippodo Hojicha',
 'dessert','autumn, rich','Chestnut mont blanc — chestnut cream, meringue',
 'complement','Hojicha''s nutty roasted character and chestnut''s earthy sweetness are natural autumn companions','dessert','established',2,true),
(218,'tea','hojicha','Ippodo Hojicha',
 'confection','traditional','Kuzu-kiri — clear kuzu starch strips with kuromitsu (black sugar syrup)',
 'complement','Hojicha beside kuromitsu-dressed kuzu: the brown sugar note of hojicha echoes kuromitsu''s molasses richness','pre_dessert','classic',1,true),

(219,'tea','genmaicha','Yamamotoyama Genmaicha — classic roasted rice and green tea blend',
 'vegetables','savory, miso','Miso soup with fu and spinach — everyday Japanese comfort',
 'complement','Genmaicha beside miso soup: both are comfort staples of the Japanese table; rice in both creates warmth','casual','classic',1,true),
(219,'tea','genmaicha','Yamamotoyama Genmaicha',
 'noodles','savory, hot','Ochazuke — rice with pickles in hot tea (often genmaicha)',
 'complement','Genmaicha is the traditional tea for ochazuke; it can also be served beside the dish rather than in it','casual','classic',1,true),
(219,'tea','genmaicha','Yamamotoyama Genmaicha',
 'pastry','neutral','Onigiri (rice ball) with various fillings',
 'complement','Genmaicha and onigiri is the definitive Japanese convenience food pairing — approachable and authentic','casual','classic',1,true),
(219,'tea','genmaicha','Yamamotoyama Genmaicha',
 'cheese','mild, neutral','Mild cream cheese or brie — approachable',
 'contrast','Genmaicha''s roasted note and mild cheese''s neutral dairy: an approachable East-West pairing for casual settings','casual','adventurous',2,true),

(220,'tea','tamaryokucha','Kagoshima Chiran Tamaryokucha — curled leaf, mellow, slightly grassy-sweet',
 'fish','light, savory','Yellowtail (buri) carpaccio with ponzu and microgreens',
 'complement','Tamaryokucha''s less astringent, mellow character is appropriate for oily fish preparations where standard sencha might clash','starter','established',2,true),
(220,'tea','tamaryokucha','Chiran Tamaryokucha',
 'vegetables','raw, clean','Simple Japanese salad with sesame dressing and nori',
 'complement','Tamaryokucha''s mild green depth complements a simple dressed salad; the nori echoes the tea''s mineral','starter','established',2,true),
(220,'tea','tamaryokucha','Chiran Tamaryokucha',
 'seafood','light, fried','Kakiage fritter — mixed vegetable and seafood tempura',
 'cleanse','Tamaryokucha''s lighter astringency still effectively cleanses fried food oil without the sharpness of fukamushi sencha','main','established',2,true),
(220,'tea','tamaryokucha','Chiran Tamaryokucha',
 'confection','light, mild','Light castella with kinako (roasted soy flour)',
 'complement','The mild grassy sweetness of tamaryokucha with the mild nutty sweetness of kinako castella','casual','established',2,true),

(221,'tea','shincha','Nishide Shizuoka First Flush Shincha — new season tea; fresh, vivid, ephemeral',
 'vegetables','spring, tender','Spring pea and ricotta bruschetta — first spring ingredients',
 'complement','Shincha is the new tea of the year; pairing with the first spring ingredients is a seasonal statement of renewal','amuse','established',2,true),
(221,'tea','shincha','Nishide Shincha',
 'fish','raw, fresh','Sardine sashimi (iwashi) — spring sardines, briefly cured with salt',
 'complement','Spring shincha with spring sardines: the parallel freshness of the first seasonal harvest of each','starter','established',2,true),
(221,'tea','shincha','Nishide Shincha',
 'confection','spring, light','Sakura mochi — cherry blossom rice cake',
 'complement','Spring wagashi and spring tea: the entire aesthetic of Japanese spring celebration in two vessels','pre_dessert','classic',1,true),
(221,'tea','shincha','Nishide Shincha',
 'vegetables','spring, bitter','Butterbur fuki and mountain vegetable tempura',
 'bridge','Shincha''s spring freshness bridges through the mild bitterness of spring mountain vegetables; seasonal bridge','starter','classic',1,true),

(222,'tea','tencha','Marukyu Koyamaen Tencha — raw unground matcha leaf; rare and educational',
 'confection','mild, wagashi','Any classic wagashi for tea room service',
 'complement','Tencha is served in specialised tea settings; the pairing is with wagashi as the educational companion piece to understanding matcha''s precursor','pre_dessert','suggested',2,true),
(222,'tea','tencha','Marukyu Tencha',
 'vegetables','minimal','Cold silken tofu — a blank canvas for the delicate tea',
 'complement','Tencha''s extraordinary delicacy requires the most neutral food partner; silken tofu provides a food canvas without interference','starter','adventurous',2,true),
(222,'tea','tencha','Marukyu Tencha',
 'seafood','minimal, cold','Cold dashi jelly with a single clam — minimal Japanese haute',
 'elevate','The educational context of serving tencha elevates the simplest food to a meditation on quality','amuse','experimental',2,true),
(222,'tea','tencha','Marukyu Tencha',
 'confection','floral','Petite nerikiri in the shape of a leaf — self-referential wagashi',
 'complement','A leaf-shaped wagashi beside the leaf-stage of matcha: a conceptually complete pairing for a progressive tea programme','pre_dessert','adventurous',2,true);

COMMIT;
