-- EAST ASIAN SESSION — PHASE 3: SAKE PRODUCTS (30)
-- Producer IDs: Kubota=94, Hakkaisan=95, Ishimoto=96, Yoshinogawa=97, Niigata-Meijo=98
--               Kiku-Masamune=99, Ozeki=100, Sawanotsuru=101, Nihonsakari=102, Konishi=103
--               Masuda-Tokubee=104, Tamanohikari=105, Saito-Shuzo=106
--               Dassai=107, Takagi(Juyondai)=108, Katokichibee(Born)=109, Dewazakura=110, Aramasa=111
--               Hakutsuru=77, Gekkeikan=78, Kizakura=87
-- Region IDs: Niigata=45, Nada=46, Fushimi=47, Yamaguchi=48, Yamagata=49, Fukui=50

BEGIN;

-- ============================================================
-- NIIGATA SAKE (10 products)
-- ============================================================
INSERT INTO beverage_products (name, category, subcategory, producer_id, region_id, origin_country, description, is_vintage_specific, quality_tier, quality_hierarchy, deductive_profile, service_specs, flavour_markers, flavour_weight, flavour_profile_type, origin_brand, price_tier, price_range_cad, technical_specs, is_published) VALUES

('Kubota Manju Junmai Daiginjo', 'sake', 'junmai_daiginjo', 94, 45, 'Japan',
 'The pinnacle of the Kubota range and one of Japan''s most recognised premium sake expressions globally. Manju (meaning ''ten thousand'') is made from Yamada Nishiki rice polished to 33% remaining, fermented with Niigata''s ultra-soft snow-melt water at near-freezing temperatures. The result is the tanrei karakuchi (light-dry) ideal taken to its extreme: perfect clarity, crystalline delicacy, and a finish that extends like a long musical note. This is Niigata''s definitive statement.',
 false, 'reserve',
 '[{"tier": "Grand Cru", "criteria": "Niigata flagship expression; 33% seimaibuai; tanrei karakuchi apex"}, {"tier": "Estate", "criteria": "Kubota Hyakuju (40% polish)"}, {"tier": "Market", "criteria": "Kubota Senju Honjozo"}]',
 '{"appearance": "Water-clear with a faint silver tinge; legs are imperceptible — the hallmark of light-polished premium sake", "nose": "Extraordinary delicacy: melon, white flower, faint talc, soft pear. None of the gin-like fusel intensity of over-ripe fermentation. A whisper rather than a declaration", "palate": "Entry is pure and almost weightless; the tanrei (light) character is immediate. Sweetness and dryness coexist in perfect tension — nihonshu-do +1 (nearly neutral). Faint rice koji umami emerges mid-palate. The water''s softness is palpable: no grip, no mineral edge", "finish": "Exceptional length for a dry sake — 45 seconds of lingering rice-flower and faint melon. The karakuchi (dry) tail is clean and complete"}',
 '{"temperature_service": "10-12°C; serve in a white wine glass or sake glass to allow aromatic expression; never warm this expression — heat would destroy the delicacy", "glassware": "Zalto Universal or Riedel Vinum Sauvignon Blanc; alternatively traditional ochoko for ceremonial contexts", "bc_source": "Wismettac Asian Foods Canada; available for fine dining accounts through pre-order", "serving_volume": "60-90ml per pour; does not benefit from large pours"}',
 ARRAY['white melon', 'white flower', 'soft pear', 'rice flour', 'faint talc', 'spring water', 'light koji'],
 'light', 'dry_elegant', 'Kubota',
 'ultra_premium', '$120-$180 CAD (720ml)',
 '{"seimaibuai": "33% remaining (67% polished away)", "nihonshu_do": "+1 (near-neutral, very slightly dry)", "acidity": "1.2 (low — Niigata style)", "alcohol": "16.5%", "rice_variety": "Yamada Nishiki", "water": "Uono River snow-melt, Niigata — ultra-soft below 30mg/L hardness", "yeast": "Niigata GN yeast", "pressing_method": "Yabuta pressing"}',
 true),

('Kubota Senju Tokubetsu Honjozo', 'sake', 'tokubetsu_honjozo', 94, 45, 'Japan',
 'The everyday brilliance of the Kubota range — and arguably the most important sake in the lineup for restaurant by-the-glass programmes. Senju (Thousand Longevities) uses a small addition of distilled alcohol (honjozo style) to heighten aromatic lift while maintaining the Niigata tanrei character. At 55% polishing remaining, this is honest, food-first sake that does exactly what great house sake should: disappear behind the food until you need it, then refresh with exquisite precision.',
 false, 'market',
 '[{"tier": "House Recommendation", "criteria": "Best value-expression of Kubota range; ideal for by-the-glass programme"}, {"tier": "Food-First", "criteria": "Designed to complement rather than compete with cuisine"}]',
 '{"appearance": "Clear, light straw; clean", "nose": "Light: soft pear, faint white flower, subtle distilled alcohol lift (which is the point of honjozo — this lift opens the aromatic profile)", "palate": "Clean entry; the distilled alcohol addition perceptibly sharpens the dryness without adding heat. Gentle grain character; light acidity. Classic tanrei: not boring, but not distracting", "finish": "Clean and dry; 20-30 seconds; refreshing rather than complex"}',
 '{"temperature_service": "10-14°C; can be served slightly warmer (15°C) than the Daiginjo — the honjozo style is more temperature-forgiving", "glassware": "White wine glass; traditional tokkuri/ochoko equally appropriate", "bc_source": "Wismettac Asian Foods Canada; BC Liquor Stores (select locations)", "serving_volume": "60-90ml per pour; ideal for by-the-glass at $10-14 CAD per pour"}',
 ARRAY['pear', 'white flower', 'light grain', 'clean rice', 'crisp mineral', 'neutral finish'],
 'light', 'dry_crisp', 'Kubota',
 'mid_range', '$45-$65 CAD (720ml)',
 '{"seimaibuai": "55% remaining", "nihonshu_do": "+2 (slightly dry)", "acidity": "1.2", "alcohol": "15%", "rice_variety": "Gohyakumangoku", "style_note": "Tokubetsu (Special) designation indicates something beyond standard honjozo — here: higher grade rice polishing than standard honjozo minimum requires"}',
 true),

('Kubota Hyakuju Junmai Daiginjo', 'sake', 'junmai_daiginjo', 94, 45, 'Japan',
 'Kubota Hyakuju (One Hundred Longevities) occupies the middle position in the Kubota hierarchy — premium enough to anchor a special occasion but priced to allow regular service in fine dining contexts. At 40% seimaibuai (polishing remaining), it sits between the Senju''s accessibility and the Manju''s transcendence. Pure Yamada Nishiki rice, Niigata soft water, extended low-temperature fermentation. The classic Niigata profile with slightly more body and depth than Manju''s extreme refinement.',
 false, 'estate',
 '[{"tier": "Estate Flagship", "criteria": "40% seimaibuai; junmai purity; accessible premium pricing"}, {"tier": "Special Occasion", "criteria": "Ideal for private dining and special occasion sake service"}]',
 '{"appearance": "Crystal clear, faint greenish tinge of freshly pressed junmai", "nose": "More presence than Manju: melon, rice flour, faint banana (characteristic of Niigata GN yeast at low fermentation temperatures), white peach", "palate": "Body is medium-light; slightly more viscosity than Manju; the Yamada Nishiki''s natural sweetness is more present at 40% than at 33% polish. Clean finish with pleasant umami length", "finish": "35-40 seconds; slightly richer than Manju but still firmly in the tanrei (light) category"}',
 '{"temperature_service": "10-12°C", "glassware": "White wine glass or Riedel Vinum Sauvignon Blanc", "bc_source": "Wismettac Asian Foods Canada; BC Liquor select locations", "serving_volume": "60-90ml"}',
 ARRAY['white melon', 'white peach', 'banana blossom', 'rice flour', 'soft pear', 'Niigata mineral'],
 'light', 'dry_elegant', 'Kubota',
 'premium', '$80-$110 CAD (720ml)',
 '{"seimaibuai": "40% remaining", "nihonshu_do": "+1", "acidity": "1.3", "alcohol": "16%", "rice_variety": "Yamada Nishiki", "style_note": "Junmai (pure rice) — no added distilled alcohol; classified as Junmai Daiginjo (50%+ polished, junmai designation) despite 40% polish due to Kubota''s internal classification system"}',
 true),

('Hakkaisan Junmai Ginjo', 'sake', 'junmai_ginjo', 95, 45, 'Japan',
 'Hakkaisan''s signature ginjo expression — the most direct statement of what Mt. Hakkai''s snowmelt does to sake. At 50% seimaibuai, pure rice fermentation, and extended cold fermentation, this is a benchmark Niigata junmai ginjo: clean, light, slightly floral, with the characteristic delicacy of soft water sake. The quintessential introduction to premium Niigata sake.',
 false, 'estate',
 '[{"tier": "Signature Expression", "criteria": "50% seimaibuai; pure rice; quintessential Niigata Junmai Ginjo benchmark"}]',
 '{"appearance": "Crystal clear, faint silver", "nose": "Classic Niigata ginjo: apple, white flower, faint banana. Restrained — the Hakkai snowmelt character shows as absence (of minerals) as much as presence", "palate": "Light body; clean acidity; subtle sweetness of rice; the koji character is light and clean. Nihonshu-do +4 gives a perceptible dryness", "finish": "Clean, refreshing; 25-35 seconds; light rice note lingers"}',
 '{"temperature_service": "10-12°C", "glassware": "White wine glass; traditional ochoko for tableside pour", "bc_source": "Wismettac Asian Foods Canada; BC Liquor Stores", "bc_note": "One of the most widely available premium Japanese ginjo in BC — a reliable benchmark sake"}',
 ARRAY['green apple', 'white flower', 'light banana', 'rice', 'melon', 'snowmelt clarity'],
 'light', 'dry_crisp', 'Hakkaisan',
 'premium', '$55-$75 CAD (720ml)',
 '{"seimaibuai": "50% remaining", "nihonshu_do": "+4 (dry)", "acidity": "1.3", "alcohol": "15.5%", "rice_variety": "Gohyakumangoku and Yamada Nishiki blend", "water": "Mt. Hakkai snowmelt, Minamiuonuma — ultra-soft"}',
 true),

('Hakkaisan Yukimuro Snow-Aged Junmai Ginjo', 'sake', 'aged_junmai_ginjo', 95, 45, 'Japan',
 'Hakkaisan''s most philosophically compelling expression: a Junmai Ginjo aged for three years in the Yukimuro (Snow Warehouse) — a purpose-built structure where 3,000 tonnes of compacted natural Niigata snow maintain a constant 3°C temperature without mechanical refrigeration. The resulting sake is transformed: the typical bright ginjo character has softened and deepened, revealing texture and umami depth impossible in a young expression. This is sake and place inseparable.',
 false, 'reserve',
 '[{"tier": "Prestige Snow-Aged", "criteria": "3-year natural snow ageing; 3°C constant; no mechanical refrigeration"}, {"tier": "Cellaring Analogue", "criteria": "Demonstrates sake''s capacity for meaningful ageing in controlled cold-storage conditions"}]',
 '{"appearance": "Light straw, slightly deeper than young ginjo — a hint of amber beginning at the edge after 3 years", "nose": "The transformation from standard Hakkaisan Ginjo is immediately apparent: the bright apple and banana of the young sake has mellowed into honeyed melon, rice cake (mochi), gentle spice. No oxidation — the constant cold preserves freshness while allowing slow ester development", "palate": "Body is unmistakably fuller — 3 years of snow-cold ageing has allowed the sake''s components to integrate. Umami depth (from koji amino acids released over time) is the dominant mid-palate note: savory rice, gentle caramel, honeyed finish", "finish": "50+ seconds; the umami tail distinguishes this from any young ginjo: it''s a different category of experience"}',
 '{"temperature_service": "12-15°C — slightly warmer than young ginjo to allow the aged complexity to open; over-chilling masks the umami depth", "glassware": "White wine glass or large Burgundy glass to allow aromatic concentration", "bc_source": "Wismettac Asian Foods Canada — limited allocation; pre-order recommended", "ageing_context": "Present the snow-ageing story to guests: 3,000 tonnes of natural snow in a purpose-built warehouse, no electricity, 3°C constant — it is a genuine engineering and environmental achievement"}',
 ARRAY['honeyed melon', 'mochi rice cake', 'gentle spice', 'caramel', 'umami depth', 'snow-cold terroir', 'aged rice'],
 'medium-light', 'aged_elegant', 'Hakkaisan Yukimuro',
 'ultra_premium', '$150-$200 CAD (720ml)',
 '{"seimaibuai": "50% remaining", "ageing": "3 years in Yukimuro Snow Warehouse at 3°C constant temperature", "nihonshu_do": "+4 (dry, though aged umami perception makes it seem slightly sweeter)", "acidity": "1.3", "alcohol": "15.5%", "rice_variety": "Gohyakumangoku", "water": "Mt. Hakkai snowmelt"}',
 true),

('Koshi no Kanbai Honjozo Sai', 'sake', 'honjozo', 96, 45, 'Japan',
 'Koshi no Kanbai''s most accessible expression but not its least impressive: the Honjozo Sai (meaning ''Talent'' or ''Gift'' — an acknowledgment of Niigata''s natural brewing gifts) uses a small distilled alcohol addition to achieve the dry, clean profile that is Niigata''s signature. The Sai is the gate through which guests enter the Koshi no Kanbai world — and like all great entry expressions, it contains the DNA of everything above it.',
 false, 'estate',
 '[{"tier": "Entry to the Koshi no Kanbai Range", "criteria": "Honjozo; 65% seimaibuai; dry and clean"}, {"tier": "Benchmark", "criteria": "Reference point for the entire Niigata style"}]',
 '{"appearance": "Crystal clear, no colour", "nose": "Light and precise: rice grain, hint of white flower, clean distilled spirit note (the honjozo lift). The Koshi no Kanbai brand''s characteristic ''cold water'' quality is immediately apparent", "palate": "Dry and direct — nihonshu-do +5 gives genuine dryness. Body is very light but not thin; the Miyamizu equivalent of Niigata''s soft water provides a pure, clean platform. Minimal sweetness", "finish": "Short to medium; clean and dry; the archetypal Niigata tanrei karakuchi (light-dry)"}',
 '{"temperature_service": "10-15°C; excellent served slightly warm (nurukan, 45°C) — the honjozo style benefits more from moderate warming than ginjo", "glassware": "Traditional ochoko; white wine glass equally appropriate", "bc_source": "Wismettac Asian Foods Canada (limited)"}',
 ARRAY['rice grain', 'white flower', 'spring water', 'dry mineral', 'light cotton'],
 'light', 'dry_austere', 'Koshi no Kanbai',
 'premium', '$50-$70 CAD (720ml)',
 '{"seimaibuai": "65% remaining", "nihonshu_do": "+5 (dry)", "acidity": "1.2", "alcohol": "15.5%", "rice_variety": "Gohyakumangoku", "water": "Niigata city groundwater — ultra-soft"}',
 true),

('Koshi no Kanbai Muku Junmai Daiginjo', 'sake', 'junmai_daiginjo', 96, 45, 'Japan',
 'Muku (meaning ''Pure Innocence'' or ''Immaculate'') is Ishimoto Shuzo''s supreme expression — a junmai daiginjo of such refinement that it approaches the theoretical limit of what sake can be. Produced in tiny quantities from Yamada Nishiki rice polished to 35% remaining, using Niigata''s softest available water and the brewery''s most precise fermentation control, Muku is the expression that Niigata''s entire brewing tradition has been building toward. Extremely rare in BC.',
 false, 'reserve',
 '[{"tier": "Supreme Expression", "criteria": "35% seimaibuai; small production; the brewery''s highest statement"}, {"tier": "Allocated", "criteria": "Limited annual production; collector and fine dining allocation"}]',
 '{"appearance": "Utterly clear; no perceptible colour; the clearest sake visually short of Dassai 23", "nose": "Almost impossibly delicate: white flower (lily, jasmine), ghost of melon, something mineral like the inside of a glacier. The aromatic register is so restrained that it rewards slow nosing at room temperature before chilling the glass", "palate": "The softest texture in sake: water-soft, with the most gossamer body possible while retaining identity. The rice character is present but so refined that it reads as an idea rather than a flavour. Umami is the bass note beneath the delicacy", "finish": "60+ seconds of softly diminishing elegance — the longest finish in the Niigata style"}',
 '{"temperature_service": "10-12°C; the delicacy is most apparent at this temperature", "glassware": "Zalto Universal for maximum aromatic concentration; large bowl allows the whisper-light aromatic profile to accumulate", "bc_source": "Wismettac fine dining allocation (limited — pre-order essential); not available through general retail", "service_note": "Present context: Muku is made in limited quantities by a family that kept their sake as a local treasure for generations before international demand required export"}',
 ARRAY['white lily', 'jasmine', 'glacier mineral', 'ghost of melon', 'rice silk', 'pure water'],
 'light', 'sublime_delicate', 'Koshi no Kanbai',
 'ultra_premium', '$200-$300 CAD (720ml)',
 '{"seimaibuai": "35% remaining (65% polished away)", "nihonshu_do": "+1", "acidity": "1.2", "alcohol": "16%", "rice_variety": "Yamada Nishiki", "production_volume": "Very limited annual production"}',
 true),

('Yoshinogawa Gensen Karakuchi Junmai', 'sake', 'junmai', 97, 45, 'Japan',
 'Gensen Karakuchi (Source Dry) is Yoshinogawa''s statement of authentic Niigata karakuchi (dry): made from the brewery''s own contracted rice fields, with the brewery''s water, at the brewery''s temperature — nothing added or adjusted to chase style. This is honest sake: dry, clean, food-forward, and priced to allow regular service. One of the best-value authentic Niigata junmai expressions available in BC.',
 false, 'market',
 '[{"tier": "Best Value Niigata Junmai", "criteria": "Honest expression of tanrei karakuchi at accessible price"}]',
 '{"appearance": "Clear, faint straw", "nose": "Honest and direct: rice grain, light koji, faint apple skin. No theatrical perfume — this is sake as grain fermentation, transparent and clean", "palate": "Dry (nihonshu-do +8 — among the driest standard Niigata sakes) with clean acidity. Body is light but genuine. Pairs brilliantly with delicate fish, sashimi, and anything where the beverage should not compete", "finish": "Short and clean — a quick refreshing dry exit. The quintessential tanrei karakuchi finish"}',
 '{"temperature_service": "10-15°C; also excellent slightly chilled at 8°C for summer sashimi service; surprisingly good slightly warm (nurukan 40-45°C) with richer dishes", "bc_source": "Fujiya Japanese Market Vancouver; Wismettac select accounts"}',
 ARRAY['rice grain', 'light koji', 'apple skin', 'dry mineral', 'clean grain'],
 'light', 'dry_honest', 'Yoshinogawa Gensen Karakuchi',
 'mid_range', '$35-$50 CAD (720ml)',
 '{"seimaibuai": "58% remaining", "nihonshu_do": "+8 (very dry)", "acidity": "1.4", "alcohol": "15%", "rice_variety": "Gohyakumangoku", "water": "Nakatsu River watershed"}',
 true),

('Yoshinogawa Winter Warrior Junmai Ginjo', 'sake', 'junmai_ginjo', 97, 45, 'Japan',
 'The Winter Warrior (Fuyu Musha) is Yoshinogawa''s export-focused ginjo expression — named for the intense Niigata winters that make possible the slow, cold fermentation that defines the prefecture''s premium production. Lighter and more approachable than the Gensen Karakuchi''s extreme dryness, the Winter Warrior balances Niigata''s characteristic light-dry character with the aromatic appeal of ginjo fermentation.',
 false, 'estate',
 '[{"tier": "Export Flagship", "criteria": "Designed for Western market entry into Niigata sake"}, {"tier": "Balanced", "criteria": "More approachable than Gensen Karakuchi''s extreme dryness"}]',
 '{"appearance": "Clear, faint silver", "nose": "Classic ginjo profile: green apple, white flower, faint banana (ginjo yeast characteristic). More aromatic than the Gensen Karakuchi — the ginjo aromatics are the point of differentiation", "palate": "Light-medium body; slightly sweeter than the standard Yoshinogawa house style (nihonshu-do +2 vs +8 for Gensen) but still firmly dry. The ginjo yeast''s apple character frames the clean Niigata water base", "finish": "Clean, 30-40 seconds; delicate apple-dry tail"}',
 '{"temperature_service": "10-12°C", "bc_source": "Fujiya Japanese Market Vancouver; Wismettac"}',
 ARRAY['green apple', 'white flower', 'banana blossom', 'light melon', 'clean rice', 'winter mineral'],
 'light', 'dry_floral', 'Yoshinogawa',
 'premium', '$60-$80 CAD (720ml)',
 '{"seimaibuai": "50% remaining", "nihonshu_do": "+2", "acidity": "1.3", "alcohol": "15.5%", "rice_variety": "Gohyakumangoku"}',
 true),

('Kakurei Tokubetsu Junmai', 'sake', 'tokubetsu_junmai', 98, 45, 'Japan',
 'Kakurei (Crane Chill) is Niigata Meijo''s ambassador to the restaurant world — a Tokubetsu Junmai (Special Pure Rice) that achieves the lightness of a ginjo without the ginjo price. The name references the Japanese crane (tsuru), a symbol of longevity and pure water — and the sake delivers exactly that: crystalline water character, clean rice, and the Niigata signature of karakuchi (dry) refinement. The preferred house sake among Tokyo fine dining accounts that understand the tanrei style.',
 false, 'estate',
 '[{"tier": "Restaurant Flagship", "criteria": "Tokubetsu Junmai; refined house sake quality for fine dining"}, {"tier": "Best Niigata Value at Premium Tier", "criteria": "Quality-to-price peak for the Kakurei range"}]',
 '{"appearance": "Crystal clear", "nose": "Restrained and elegant: rice flower, faint melon, white mineral note. The Niigata soft water speaks through restraint", "palate": "Light body; gentle and polished; slightly drier than most Tokubetsu Junmai. The koji''s umami is subtle but present as a foundation. A sake that rewards attention without demanding it", "finish": "Clean, 25-35 seconds; dry, slightly mineral tail"}',
 '{"temperature_service": "10-14°C; this expression responds well to gentle warming (40°C) with kaiseki-style cuisine", "bc_source": "Wismettac Asian Foods Canada; some BC Liquor locations"}',
 ARRAY['rice flower', 'light melon', 'white mineral', 'clean koji', 'dry silk'],
 'light', 'dry_refined', 'Kakurei',
 'mid_range', '$45-$60 CAD (720ml)',
 '{"seimaibuai": "55% remaining", "nihonshu_do": "+3 (slightly dry)", "acidity": "1.3", "alcohol": "15.5%", "rice_variety": "Gohyakumangoku and Yamada Nishiki blend"}',
 true);

-- ============================================================
-- NADA SAKE (8 products)
-- ============================================================
INSERT INTO beverage_products (name, category, subcategory, producer_id, region_id, origin_country, description, is_vintage_specific, quality_tier, quality_hierarchy, deductive_profile, service_specs, flavour_markers, flavour_weight, flavour_profile_type, origin_brand, price_tier, price_range_cad, technical_specs, is_published) VALUES

('Kiku-Masamune Kimoto Junmai', 'sake', 'kimoto_junmai', 99, 46, 'Japan',
 'The essential expression of the kimoto (traditional wooden-pole moto) method in contemporary sake. Where modern sokujo-method sake achieves freshness and cleanliness through lactic acid addition, Kiku-Masamune''s Kimoto Junmai earns its character through three additional weeks of labour: the yamaoroshi (mountain echo grinding) process where brewery workers pound steamed rice with wooden poles in the cold brewery, stimulating natural lactic acid bacteria. The result is sake of exceptional depth, umami, and backbone — the otokozake (man''s sake) tradition at its most authentic.',
 false, 'estate',
 '[{"tier": "Kimoto Flagship", "criteria": "Traditional yamaoroshi kimoto production; 65% seimaibuai"}, {"tier": "Reference", "criteria": "Benchmark for kimoto method in Nada"}]',
 '{"appearance": "Slightly deeper than most sake — a faint golden tinge from the kimoto''s extended fermentation; indicative of the method", "nose": "The kimoto nose is immediately distinctive: yogurt, rice cake (mochi), faint earthiness, dried mushroom umami note, light caramel. Far more complex than a standard junmai — this smells like fermentation rather than distillation", "palate": "Body is medium — not the light tanrei of Niigata but the fuller otokozake (man''s sake) of Nada, amplified by kimoto''s natural lactic. Acidity is higher and more present than sokujo sake; the sourness is refreshing rather than sharp. Umami depth is remarkable", "finish": "Long and savoury — 45+ seconds; the dried mushroom and rice vinegar note of kimoto lactic is the final character"}',
 '{"temperature_service": "12-18°C; this is one of the few premium sake expressions that genuinely benefits from warming (kanzake: 50°C), which opens the umami and integrates the acidity beautifully", "food_pairing_special": "Exceptional with: aged cheese, robust umami-driven dishes, yakitori (grilled chicken), teriyaki, any dish with soy sauce-based glaze", "bc_source": "Wismettac Asian Foods Canada"}',
 ARRAY['yogurt', 'mochi', 'dried mushroom', 'rice vinegar', 'caramel', 'earthy umami', 'fermentation depth'],
 'medium', 'umami_savoury', 'Kiku-Masamune Kimoto',
 'premium', '$50-$70 CAD (720ml)',
 '{"seimaibuai": "65% remaining", "nihonshu_do": "+3", "acidity": "1.8 (high — kimoto characteristic)", "alcohol": "15.5%", "fermentation_method": "Kimoto (yamaoroshi) — traditional wooden-pole moto grinding; natural lactic acid development over 30+ additional days", "rice_variety": "Yamada Nishiki", "water": "Miyamizu — Nada hard water (potassium 55mg/L, phosphorus 5.4mg/L)"}',
 true),

('Kiku-Masamune Taru Sake', 'sake', 'taru_sake', 99, 46, 'Japan',
 'Taru Sake (Cedar Barrel Sake) is one of Japan''s most distinctive sake styles — and Kiku-Masamune is its most celebrated producer. Honjozo-class sake is stored in yoshino cedar (sugi) casks for a brief period (typically 10-20 days), during which the cedar imparts its distinctive aromatic signature: sawdust, resin, forest floor, faint spice. The result is a sake entirely unlike the modern clean style — a window into the Edo period when all sake was transported and stored in wooden casks. Traditionally served during Japanese New Year celebrations.',
 false, 'market',
 '[{"tier": "Cultural Heritage Expression", "criteria": "Cedar barrel style; unique aromatic profile distinct from all other sake"}, {"tier": "Seasonal", "criteria": "Traditional New Year (oshogatsu) sake in Japan"}]',
 '{"appearance": "Clear to faint gold; cedar colour is not necessarily apparent visually", "nose": "Unmistakable: fresh-cut cedar wood (sugi), sawdust, light forest resin, gentle spice. The sake background (grain, light flower) is present but the cedar dominates absolutely", "palate": "The cedar aromatics coat the palate in the most pleasant way — like walking into a freshly-sawn timber building. Light body; clean acidity; the cedar tannins (minimal) provide a slight astringency. Finishes dry and woody", "finish": "Long cedar resin tail; distinctive and completely unlike any modern sake. An education in aromatic diversity"}',
 '{"temperature_service": "12-15°C; cedar character is more pronounced at slightly warmer temperatures", "food_pairing_special": "Traditional Japanese: sashimi of robust fish (salmon, yellowtail), grilled fish, izakaya-style appetisers", "bc_source": "Wismettac; Japanese specialty stores in Metro Vancouver", "service_note": "Educate guests: taru sake is a historical style — all sake before the 20th century tasted somewhat like this"}',
 ARRAY['yoshino cedar', 'sawdust', 'forest resin', 'light spice', 'wood tannin', 'clean grain', 'Edo period'],
 'light', 'aromatic_cedar', 'Kiku-Masamune Taru',
 'mid_range', '$35-$50 CAD (720ml)',
 '{"seimaibuai": "70% remaining", "cedar_contact": "10-20 days in yoshino sugi (cedar) casks", "nihonshu_do": "+2", "acidity": "1.5", "alcohol": "15%", "historical_note": "Cedar barrel sake is a living link to pre-20th century sake — when all sake was transported and stored in wooden barrels"}',
 true),

('Ozeki Junmai', 'sake', 'junmai', 100, 46, 'Japan',
 'Ozeki Junmai is the honest, no-pretension expression of Nada''s otokozake (man''s sake) tradition — made with Miyamizu hard water, polished to 70%, and produced in volume without concession to trend. It is what sake actually tastes like when Nada''s mineral-rich water drives fermentation: fuller body, slightly assertive character, mineral backbone. An essential house sake for izakaya-style restaurants and the perfect benchmark against which to compare Niigata''s tanrei (light-dry) style.',
 false, 'market',
 '[{"tier": "House Sake", "criteria": "Volume production; accessible; authentic Nada Miyamizu character"}, {"tier": "Benchmark", "criteria": "Reference point for the otokozake (full-bodied Nada) style vs. Niigata tanrei"}]',
 '{"appearance": "Clear, faint straw; clean", "nose": "Straightforward: rice grain, faint Miyamizu mineral, light rice vinegar note. More assertive than Niigata sake at the same price point — the water''s hardness is apparent even on the nose", "palate": "Medium body — fuller than Niigata house sake. The Miyamizu''s mineral pushes fermentation vigor: slightly more extractive, more grip on the palate. Clean acidity. A sake that takes up space on the palate", "finish": "Clean, medium length; dry mineral tail. The otokozake character: firm rather than light"}',
 '{"temperature_service": "12-18°C; excellent slightly warm (nurukan 40-45°C) — the Nada otokozake style is designed for warming; the mineral backbone integrates beautifully with heat", "bc_source": "T&T Supermarket; Wismettac wholesale; BC Liquor Stores"}',
 ARRAY['rice grain', 'Miyamizu mineral', 'light rice vinegar', 'clean grain', 'dry mineral tail'],
 'medium-light', 'dry_mineral', 'Ozeki',
 'entry', '$20-$30 CAD (720ml)',
 '{"seimaibuai": "70% remaining", "nihonshu_do": "+4", "acidity": "1.4", "alcohol": "14.5%", "water": "Miyamizu — Nada hard water (potassium 55mg/L)", "rice_variety": "Yamada Nishiki and Gohyakumangoku blend"}',
 true),

('Sawanotsuru Junmai Daiginjo', 'sake', 'junmai_daiginjo', 101, 46, 'Japan',
 'Sawanotsuru''s Junmai Daiginjo demonstrates the case that Nada''s Miyamizu water, despite its hardness, can produce sake of genuine premium delicacy when the polishing ratio is extreme. At 40% seimaibuai, the mineral character of Miyamizu has been attenuated by the removal of 60% of the rice''s outer layers — leaving only the starchy core whose flavour is shaped more by yeast and fermentation temperature than by terroir. The result: a Nada daiginjo that converges toward Niigata''s tanrei character while retaining its Miyamizu identity.',
 false, 'estate',
 '[{"tier": "Premium Nada Daiginjo", "criteria": "40% seimaibuai; demonstrates Nada capability at premium polish"}, {"tier": "Style Convergence", "criteria": "At this polish level, Nada and Niigata styles converge — educational pairing with Niigata daiginjo"}]',
 '{"appearance": "Crystal clear; faint silver", "nose": "Unexpected from a Nada producer: white flower, melon, very light mineral. The Miyamizu''s assertiveness has been polished away at this level — what remains is the clean expression of yeast character on a mineral base", "palate": "Medium-light body; cleaner than all non-daiginjo Nada expressions. Faint Miyamizu mineral backbone provides a subtle firmness beneath the floral delicacy", "finish": "Clean, 35-40 seconds; slightly drier finish than comparable Niigata daiginjo — the Miyamizu''s final character"}',
 '{"temperature_service": "10-12°C", "bc_source": "Wismettac Asian Foods Canada (limited)", "educational_note": "Excellent teaching sake: compare with Kubota Manju at the same temperature to demonstrate how water hardness expresses itself even at extreme polishing ratios"}',
 ARRAY['white flower', 'melon', 'light mineral', 'clean rice', 'Miyamizu backbone'],
 'light', 'dry_elegant', 'Sawanotsuru',
 'premium', '$65-$85 CAD (720ml)',
 '{"seimaibuai": "40% remaining", "nihonshu_do": "+3", "acidity": "1.3", "alcohol": "16%", "water": "Miyamizu — Nada", "rice_variety": "Yamada Nishiki"}',
 true),

('Nihonsakari Junmai Ginjo', 'sake', 'junmai_ginjo', 102, 46, 'Japan',
 'Nihonsakari''s Junmai Ginjo is the reliable mid-market expression of Nada''s Miyamizu tradition — honest, consistent, and representative of the full-bodied Nada style at a price that enables regular service. The Miyamizu water''s mineral richness is present but not overwhelming at the ginjo polishing level, creating a sake with more presence than Niigata equivalents at the same price.',
 false, 'market',
 '[{"tier": "Mid-Market Nada Benchmark", "criteria": "Reliable quality; genuine Miyamizu character; accessible pricing"}]',
 '{"appearance": "Clear, light straw", "nose": "Rice grain, light flower, faint Miyamizu mineral. More grounded than Niigata ginjo — the water''s character persists through polishing", "palate": "Medium-light body; the Miyamizu assertiveness is present as a gentle firmness. Slightly fuller and more food-friendly than comparable Niigata ginjo", "finish": "Clean, medium; dry mineral tail — the Nada signature"}',
 '{"temperature_service": "10-15°C; good warm (nurukan)", "bc_source": "Wismettac (limited); Japanese specialty retailers"}',
 ARRAY['rice grain', 'light flower', 'Miyamizu mineral', 'grain backbone', 'dry mineral'],
 'medium-light', 'dry_mineral', 'Nihonsakari',
 'mid_range', '$40-$55 CAD (720ml)',
 '{"seimaibuai": "55% remaining", "nihonshu_do": "+4", "acidity": "1.4", "alcohol": "15%", "water": "Miyamizu"}',
 true),

('Konishi Shirayuki Junmai Ginjo', 'sake', 'junmai_ginjo', 103, 46, 'Japan',
 'Shirayuki (White Snow) is one of Japan''s oldest continuously produced sake brands — exported to Dutch East India Company traders in the 17th century, making it the first Japanese sake to reach Europe. The modern Junmai Ginjo maintains the clean, accessible Hyogo character while adding the fragrant aromatic lift of ginjo fermentation. A profound piece of drinking history: the sake category''s oldest export expression, still being produced.',
 false, 'market',
 '[{"tier": "Historical Significance", "criteria": "Oldest Japanese sake export brand; 470+ year lineage"}, {"tier": "Mid-Market Ginjo", "criteria": "Accessible quality at mid-range price"}]',
 '{"appearance": "Clear, faint straw", "nose": "Accessible ginjo: white flower, pear, faint rice grain. The Hyogo/Itami water character (similar to Miyamizu) provides a slightly firmer mineral base than Niigata", "palate": "Light-medium body; clean; the long history is not in the complexity but in the consistency. A sake that has been reliably good for centuries", "finish": "Clean, medium dry; good food pairing structure"}',
 '{"temperature_service": "10-15°C", "bc_source": "Wismettac Asian Foods Canada", "service_note": "The historical story is compelling: Shirayuki was the first Japanese sake to reach European shores — this bottle''s lineage reaches to Dutch East India Company trading ships of the 17th century"}',
 ARRAY['white flower', 'pear', 'light rice grain', 'Hyogo mineral', 'clean dry finish'],
 'light', 'dry_accessible', 'Shirayuki',
 'mid_range', '$40-$55 CAD (720ml)',
 '{"seimaibuai": "55% remaining", "nihonshu_do": "+3", "acidity": "1.3", "alcohol": "15%", "historical_note": "First Japanese sake exported to Europe via Dutch East India Company, 17th century"}',
 true),

('Hakutsuru Tora no Ko Junmai Daiginjo', 'sake', 'junmai_daiginjo', 77, 46, 'Japan',
 'Tora no Ko (Tiger Cub) is Hakutsuru''s supreme expression — the culmination of the Nada giant''s century of production refinement. Where Hakutsuru''s standard expressions produce the reliable, accessible sake that built the brand, Tora no Ko demands everything: 35% seimaibuai Yamada Nishiki, extended low-temperature ginjo fermentation, minimal intervention. The Miyamizu hard water at this polishing level reveals its mineral backbone as an asset: the structure that supports the delicacy rather than dominating it.',
 false, 'reserve',
 '[{"tier": "Hakutsuru Supreme", "criteria": "35% seimaibuai; flagship expression of a Nada icon"}, {"tier": "Nada-Niigata Comparison", "criteria": "Compare with Kubota Manju to understand how Miyamizu vs. soft water differ at extreme polish"}]',
 '{"appearance": "Crystal clear, microscopic gold hint", "nose": "Premium ginjo aromatic profile elevated by Miyamizu''s mineral backbone: white flower, pear, melon, faint mineral note that gives grip to the delicate aromatics", "palate": "The Miyamizu asserts itself even at 35%: medium-light body with clear mineral structure beneath the ginjo delicacy. More tension and grip than comparable Niigata daiginjo — the water''s character is indelible", "finish": "50+ seconds; the Miyamizu mineral lengthens the finish in a way soft-water sake cannot achieve — a different textural profile from the pure delicacy of Kubota Manju"}',
 '{"temperature_service": "10-12°C", "bc_source": "Wismettac fine dining accounts (allocation required); not general retail", "educational_note": "Definitive demonstration of Nada vs. Niigata water styles at the premium level"}',
 ARRAY['white flower', 'pear', 'melon', 'Miyamizu mineral', 'grain backbone', 'structured delicacy'],
 'medium-light', 'dry_structured', 'Hakutsuru Tora no Ko',
 'ultra_premium', '$120-$160 CAD (720ml)',
 '{"seimaibuai": "35% remaining", "nihonshu_do": "+2", "acidity": "1.3", "alcohol": "16%", "water": "Miyamizu — Nada hard water", "rice_variety": "Yamada Nishiki from Tojo district, Hyogo"}',
 true);

-- ============================================================
-- FUSHIMI SAKE (5 products)
-- ============================================================
INSERT INTO beverage_products (name, category, subcategory, producer_id, region_id, origin_country, description, is_vintage_specific, quality_tier, quality_hierarchy, deductive_profile, service_specs, flavour_markers, flavour_weight, flavour_profile_type, origin_brand, price_tier, price_range_cad, technical_specs, is_published) VALUES

('Tsuki no Katsura Iwai Junmai Daiginjo', 'sake', 'junmai_daiginjo', 104, 47, 'Japan',
 'Masuda Tokubee''s supreme expression using Iwai — Kyoto''s own sake rice variety, revived from near-extinction by the brewery in collaboration with Kyoto Prefecture. Iwai (meaning ''Celebration'') produces a distinctly rounder, more delicate character than Yamada Nishiki, with the Fushimi soft water amplifying its natural sweetness and floral depth. This is a sake that could only be made in Fushimi, by this brewery, with this rice: complete terroir identity.',
 false, 'reserve',
 '[{"tier": "Supreme Fushimi", "criteria": "Iwai rice; 35% seimaibuai; unique regional identity"}, {"tier": "Historical Significance", "criteria": "Revived Kyoto heritage rice variety; made exclusively at this brewery"}]',
 '{"appearance": "Crystal clear with the faintest gold tinge of premium pressed junmai", "nose": "Distinctly different from Yamada Nishiki-based daiginjo: more floral (gardenia, white rose), rounder, with a honeyed melon note. The Iwai rice''s character is apparent compared to any Niigata or Nada expression", "palate": "The Fushimi onnazake character at its peak: soft, round, almost creamy in texture compared to Nada''s mineral firmness or Niigata''s crystalline delicacy. Medium-light body with faint Iwai-rice sweetness. The softness of Fushimi water makes every component feel integrated", "finish": "Long, honeyed; 50+ seconds; faint white flower note lingers. The Fushimi soft water''s gentleness is the overriding sensation"}',
 '{"temperature_service": "10-12°C; this expression can also be served at 16-18°C (room temperature, Japanese style) to appreciate the Iwai rice''s fuller character", "glassware": "Zalto Universal; alternatively traditional handmade porcelain ochoko for ceremony-style service", "bc_source": "Wismettac fine dining allocation (very limited); specialist Japanese sake importers", "pairing": "Exceptional with delicate Kyoto kaiseki cuisine, especially dashi-based dishes that share the umami frequency"}',
 ARRAY['gardenia', 'white rose', 'honeyed melon', 'Iwai sweetness', 'rice cream', 'Fushimi water softness'],
 'light', 'elegant_honeyed', 'Tsuki no Katsura',
 'ultra_premium', '$180-$250 CAD (720ml)',
 '{"seimaibuai": "35% remaining", "nihonshu_do": "-1 (very slightly sweet)", "acidity": "1.2", "alcohol": "16%", "rice_variety": "Iwai — Kyoto heritage rice variety revived by Masuda Tokubee Shoten and Kyoto Prefecture", "water": "Fushimi Momoyama soft water — among Japan''s softest brewing waters"}',
 true),

('Tsuki no Katsura Junmai Nigori', 'sake', 'nigori', 104, 47, 'Japan',
 'Masuda Tokubee Shoten is historically responsible for rescuing nigori (cloudy sake) from commercial extinction — in 1964, they registered their own nigori formulation with Japanese tax authorities as a distinct product category, effectively saving a style that had been disappearing. Their Junmai Nigori is the reference expression of the category: creamy, full of suspended rice particles, with the natural sweetness and umami of lightly processed sake. The antithesis of the clear, refined daiginjo.',
 false, 'market',
 '[{"tier": "Nigori Category Reference", "criteria": "Historic first registrant of nigori as a commercial category (1964)"}, {"tier": "Accessibility", "criteria": "Ideal introduction to sake for guests intimidated by dry expressions"}]',
 '{"appearance": "Opaque white to cream; must be shaken gently before pouring to distribute the rice particles (ori) settled at the bottom", "nose": "Rice porridge (kayu), fresh rice milk, light banana, hint of vanilla. The sweetness is apparent on the nose — this is unfiltered sake retaining natural sugar and rice proteins", "palate": "Full, creamy texture; the suspended rice particles (ori) create a distinctive mouthfeel that no other sake category achieves. Sweet-tart balance (the natural lactic acid from fermentation provides counterpoint to the rice sweetness). Sake at its most primary and tactile", "finish": "Rich and lingering; the cream texture coats the palate beyond the flavour — 30+ seconds of rice cream"}',
 '{"temperature_service": "8-12°C; serve ice cold for maximum refreshment; shake gently before pouring to incorporate settled sediment", "glassware": "Opaque cup or masu (wooden box) to emphasize the rustic character; alternatively a clear glass to show the beautiful cloudiness", "bc_source": "Wismettac; Japanese specialty stores; some BC Liquor locations", "pairing": "Outstanding with fresh fruit, mochi, Japanese cheesecake, or as a standalone aperitif; also pairs with spicy food where the sweetness provides relief"}',
 ARRAY['rice porridge', 'fresh rice milk', 'banana', 'vanilla', 'cream', 'natural sweetness', 'suspended rice'],
 'medium', 'sweet_creamy', 'Tsuki no Katsura Nigori',
 'premium', '$50-$70 CAD (720ml)',
 '{"seimaibuai": "65% remaining", "nihonshu_do": "-6 (sweet)", "acidity": "1.6", "alcohol": "14%", "style": "Nigori (cloudy) — lightly filtered to retain suspended rice particles (ori); registered as a distinct commercial category by this brewery in 1964", "serving_note": "Shake bottle gently before pouring to distribute settled particles"}',
 true),

('Tamanohikari Bizen Omachi Junmai Daiginjo', 'sake', 'junmai_daiginjo', 105, 47, 'Japan',
 'The Bizen Omachi expression is Tamanohikari''s most distinctive achievement: using Bizen Omachi rice — an ancient Okayama heritage variety producing earthy, mineral, deeply savoury sake — in a Junmai Daiginjo format that brings the archaic rice''s character to the premium polishing tier. The combination is unusual and compelling: the refined clarity of daiginjo technique applied to a rice that refuses to fully refine away its primal umami. A sake for those who find modern daiginjo too delicate.',
 false, 'estate',
 '[{"tier": "Heritage Rice Statement", "criteria": "Bizen Omachi — ancient heritage rice with distinct earthy character"}, {"tier": "Style Outlier", "criteria": "Earthy, mineral character unusual for junmai daiginjo class"}]',
 '{"appearance": "Clear with a perceptible gold hue — the Bizen Omachi''s earthy character is hinted at in the colour", "nose": "Unexpected for daiginjo class: earth, dried mushroom, rice bran, white flower. The Bizen Omachi''s primal character pushes through even at high polish", "palate": "Medium body — more presence than typical daiginjo. The rice''s earthiness creates a savoury mid-palate note beneath the floral ginjo character. Complex and unusual in the best sense", "finish": "Long and savoury; 45-60 seconds; the Omachi rice''s umami is the final lingering note — completely different from standard daiginjo finish"}',
 '{"temperature_service": "12-15°C — slightly warmer than standard daiginjo to allow the Bizen Omachi''s earthy character to express fully; over-chilling mutes its distinctive quality", "bc_source": "Wismettac (limited); specialist sake importers", "pairing": "Exceptional with aged cheese, rich mushroom dishes, earthy truffled preparations — any dish with umami depth"}',
 ARRAY['earth', 'dried mushroom', 'rice bran', 'white flower', 'savoury umami', 'ancient rice character', 'mineral depth'],
 'medium-light', 'earthy_complex', 'Tamanohikari Bizen Omachi',
 'premium', '$65-$90 CAD (720ml)',
 '{"seimaibuai": "50% remaining", "nihonshu_do": "+1", "acidity": "1.5 (slightly elevated — Omachi characteristic)", "alcohol": "16%", "rice_variety": "Bizen Omachi — ancient Okayama heritage rice, distinct from modern varieties; produces earthy, mineral sake with strong umami", "water": "Fushimi Momoyama soft water"}',
 true),

('Tamanohikari Junmai Ginjo', 'sake', 'junmai_ginjo', 105, 47, 'Japan',
 'Tamanohikari''s 100% junmai commitment expressed at the ginjo level — produced with Yamada Nishiki and the brewery''s characteristic commitment to pure-rice fermentation only. The Fushimi water''s gentleness is the primary character element: a soft, round, onnazake (woman''s sake) style that makes this one of the most food-accommodating ginjo expressions in any region.',
 false, 'estate',
 '[{"tier": "Fushimi Junmai Reference", "criteria": "100% junmai; Fushimi water character; Yamada Nishiki"}, {"tier": "Food Pairing Versatility", "criteria": "Soft, round character pairs across cuisines"}]',
 '{"appearance": "Clear, faint straw-green", "nose": "Rounded and soft: melon, white flower, faint pear. Less piercing than Niigata equivalents — the Fushimi water''s softness rounds every aromatic edge", "palate": "Medium-light, genuinely round body — the onnazake character is immediately apparent. The absence of any mineral assertiveness means the sake is pure koji-yeast-rice expression. Gentle and accommodating", "finish": "Soft, 30-40 seconds; light melon note persists; clean dry exit"}',
 '{"temperature_service": "10-14°C; uniquely versatile: serves well at 40-45°C (nurukan) for warming", "bc_source": "Wismettac Asian Foods Canada", "pairing": "Exceptional versatility: Japanese, French, and Italian cuisines; particularly good with butter-based sauces (the sake''s roundness complements the fat)"}',
 ARRAY['melon', 'white flower', 'soft pear', 'round rice', 'gentle koji', 'Fushimi softness'],
 'light', 'dry_round', 'Tamanohikari',
 'premium', '$55-$75 CAD (720ml)',
 '{"seimaibuai": "55% remaining", "nihonshu_do": "+2", "acidity": "1.3", "alcohol": "15.5%", "rice_variety": "Yamada Nishiki", "commitment": "100% junmai — no added alcohol in any expression; brewery policy"}',
 true),

('Tozai Snow Maiden Junmai Nigori', 'sake', 'nigori', 106, 47, 'Japan',
 'Tozai Snow Maiden (Yuki no Bijin) is the most approachable and widely available nigori sake in the BC market — Saito Shuzo''s export-focused expression designed to introduce the category to Western consumers. The name references the pale beauty of snow — visually accurate for this cloudy, cream-white sake. Clean, slightly sweet, and immediately pleasurable, Snow Maiden is the gateway nigori that converts guests who claim not to like sake.',
 false, 'market',
 '[{"tier": "Export Nigori Gateway", "criteria": "Most widely available nigori in North America; entry point to the category"}, {"tier": "Volume Driver", "criteria": "Reliable sales performance in Western markets"}]',
 '{"appearance": "Cream-white opacity; beautiful in a clear glass; settle particles evident; shake before serving", "nose": "Rice milk, gentle banana, light vanilla, hint of yogurt. Clean and approachable — the conversion nigori", "palate": "Creamy, slightly sweet (nihonshu-do -12 — the sweetest sake in the BC portfolio), smooth. The sweetness is genuine rice sweetness not added sugar — very pure. Body is medium", "finish": "Short-medium; sweet cream; accessible and pleasant"}',
 '{"temperature_service": "8°C or colder; serve ice cold for maximum refreshment; shake before pouring", "bc_source": "BC Liquor Stores; Japanese specialty stores; widely available", "pairing": "Fresh fruit, mochi ice cream, spicy dishes (Thai, Indian), as an aperitif"}',
 ARRAY['rice milk', 'banana', 'vanilla', 'light yogurt', 'cream', 'gentle sweetness'],
 'medium-light', 'sweet_accessible', 'Tozai Snow Maiden',
 'mid_range', '$35-$50 CAD (720ml)',
 '{"seimaibuai": "60% remaining", "nihonshu_do": "-12 (sweet)", "acidity": "1.5", "alcohol": "14.5%", "water": "Fushimi soft water"}',
 true);

-- ============================================================
-- PREMIUM/ALLOCATED SAKE — OTHER REGIONS (8 products)
-- ============================================================
INSERT INTO beverage_products (name, category, subcategory, producer_id, region_id, origin_country, description, is_vintage_specific, quality_tier, quality_hierarchy, deductive_profile, service_specs, flavour_markers, flavour_weight, flavour_profile_type, origin_brand, price_tier, price_range_cad, technical_specs, is_published) VALUES

('Dassai 23 Junmai Daiginjo', 'sake', 'junmai_daiginjo', 107, 48, 'Japan',
 'Dassai 23 is the sake that changed global perceptions of what Japanese sake could be — the expression that brought junmai daiginjo to the world''s best restaurants, placed it on wine lists alongside Burgundy and Champagne, and demonstrated that a craft producer in a remote Japanese prefecture could redefine premium. The ''23'' designates that only 23% of the original rice grain remains after polishing — 77% has been milled away to leave only the pure starchy core. The result is the clearest possible expression of Yamada Nishiki''s character: pure, transparent, and achingly beautiful.',
 false, 'reserve',
 '[{"tier": "World Standard for Junmai Daiginjo", "criteria": "23% seimaibuai; international fine dining benchmark"}, {"tier": "Dassai Beyond", "criteria": "The next level — undisclosed polish, tiny production, $400+ CAD"}, {"tier": "Dassai 39", "criteria": "The more accessible entry to the Dassai range"}]',
 '{"appearance": "Perfectly transparent; ultra-clean; no visible texture — like looking into pure spring water", "nose": "Extraordinary aromatic purity: white peach, melon, white flower, faint pear. The refinement of 77% polishing is immediately apparent — there is nothing extraneous, nothing muddy, nothing that does not belong. This is the cleanest nose in sake", "palate": "Entry is soft, almost liquid-air: the body exists but does not assert itself. Sweetness and dryness are in such perfect equilibrium that the palate reads ''neither'' before ''both''. Yamada Nishiki''s natural sweetness is present as a delicate suggestion. The koji''s umami appears in the mid-palate as a whisper", "finish": "60+ seconds; an impossibly long, clean, diminishing finish of white peach and rice flour that remains clear-headed throughout"}',
 '{"temperature_service": "10-12°C; serve in the finest glassware available — Zalto Universal preferred; the transparent beauty of Dassai 23 deserves the best", "glassware": "Zalto Universal or Riedel Sommelier Burgundy Grand Cru — the large bowl allows the extraordinarily delicate aromatic profile to concentrate", "bc_source": "Wismettac fine dining allocation; BC Liquor premium stores (limited); direct contact with Wismettac required", "service_narrative": "Dassai 23: made in a remote Yamaguchi valley, 77% of each grain polished away over 120+ hours, fermented in cold mountain water, pressed by gravity. The most technically demanding sake in regular production."}',
 ARRAY['white peach', 'melon', 'white flower', 'faint pear', 'rice flour', 'spring water purity', 'transparent mineral'],
 'light', 'sublime_transparent', 'Dassai 23',
 'ultra_premium', '$200-$280 CAD (720ml)',
 '{"seimaibuai": "23% remaining (77% polished away over 120+ hours of polishing time)", "nihonshu_do": "+4", "acidity": "1.3", "alcohol": "16%", "rice_variety": "Yamada Nishiki from Tojo district, Hyogo (top agricultural classification)", "water": "Nishiki River granite-filtered mountain water, Yamaguchi", "polishing_time": "120+ hours per batch"}',
 true),

('Dassai 39 Junmai Daiginjo', 'sake', 'junmai_daiginjo', 107, 48, 'Japan',
 'Dassai 39 is the most commercially significant sake in the Dassai range: accessible enough to stock without allocation, refined enough to justify premium list placement, and specific enough (39% seimaibuai) to communicate quality clarity to educated guests. The 39 sits exactly between the luxury of Dassai 23 and the approachability of entry-level sake — a premium expression that has single-handedly educated the North American fine dining market about sake quality tiers.',
 false, 'estate',
 '[{"tier": "Dassai Accessible Premium", "criteria": "39% seimaibuai; best-selling Dassai expression globally"}, {"tier": "Below", "criteria": "Dassai 45 — the entry Dassai expression"}]',
 '{"appearance": "Crystal clear; no perceptible colour", "nose": "White peach, melon, white flower, clean pear. Less ethereal than Dassai 23 but still among the clearest, most precise ginjo aromatics available. The purity that defines the brand is present", "palate": "Light-medium body; slightly more texture than 23; the 39% remaining rice provides fractionally more extract and body. Sweetness-dryness balance is excellent. Yamada Nishiki''s natural richness is more present than in 23", "finish": "45-50 seconds; clean white peach and pear note; slightly more body in the finish than 23 but maintaining the Dassai transparency"}',
 '{"temperature_service": "10-12°C", "glassware": "White wine glass minimum; Zalto preferred", "bc_source": "Wismettac; BC Liquor Stores; fine dining accounts; generally available without allocation"}',
 ARRAY['white peach', 'melon', 'white flower', 'clean pear', 'soft rice', 'mountain water'],
 'light', 'dry_elegant', 'Dassai 39',
 'premium', '$80-$110 CAD (720ml)',
 '{"seimaibuai": "39% remaining", "nihonshu_do": "+4", "acidity": "1.3", "alcohol": "16%", "rice_variety": "Yamada Nishiki", "water": "Nishiki River, Yamaguchi"}',
 true),

('Dassai Beyond Junmai Daiginjo', 'sake', 'junmai_daiginjo', 107, 48, 'Japan',
 'Dassai Beyond is the most extreme sake produced commercially — the polishing ratio is not disclosed (''beyond'' numerical description, hence the name), production is in tiny quantities, and the price ($400+ CAD) represents the outer limits of what consumers will pay for a sake bottle. This is not a regular restaurant listing but a collector''s and special occasion expression: the sake made with no constraint except perfection. When Dassai Beyond appears on a wine list, it signals a beverage programme with the deepest sake knowledge and most discerning clientele.',
 false, 'reserve',
 '[{"tier": "Ultimate Expression — No Comparable", "criteria": "Undisclosed polishing ratio; tiny production; the theoretical limit of junmai daiginjo"}, {"tier": "Below", "criteria": "Dassai 23"}]',
 '{"appearance": "Absolute transparency; looking at pure mountain water", "nose": "So refined that the primary experience is the absence of impurity rather than the presence of character. An almost abstract aromatic experience: beyond melon, beyond flower — a kind of pure rice spirit-energy that does not resolve into familiar categories", "palate": "The softest possible texture; the lightest possible body that still constitutes a liquid. What remains at this polish level is the absolute essence of Yamada Nishiki — its innermost character. The experience is meditative rather than gustatory", "finish": "Indefinite; the finish''s length becomes philosophical — you are still experiencing the sake minutes after the sip"}',
 '{"temperature_service": "10-12°C; prepare the guest with context before the first sip", "bc_source": "Allocation-only through Wismettac fine dining programme; verify stock before listing", "service_narrative": "Dassai Beyond: when asked what the polishing ratio is, Mr. Sakurai said only ''beyond numbers.'' This bottle costs more than most bottles of first-growth Bordeaux. It is one of the most technically extraordinary fermented beverages on earth."}',
 ARRAY['pure rice essence', 'spring water', 'abstract floral', 'luminous mineral', 'absolute refinement'],
 'light', 'transcendent_pure', 'Dassai Beyond',
 'ultra_premium', '$400+ CAD (720ml)',
 '{"seimaibuai": "Undisclosed — beyond 23%", "nihonshu_do": "Not disclosed", "production_volume": "Extremely limited — global allocation", "rice_variety": "Yamada Nishiki (premium Tojo district grade)", "water": "Nishiki River, Yamaguchi"}',
 true),

('Juyondai Honmaru Junmai', 'sake', 'junmai', 108, 49, 'Japan',
 'Juyondai (Fourteen Generations) is Japan''s most mythologised sake — the Petrus of the category. Takagi Shuzo produces in tiny volumes in Yamagata, distributes exclusively through a lottery to approximately 100 selected domestic retailers, exports nothing officially, and maintains this structure regardless of demand. The result: a sake whose reputation has outrun its availability, whose quality genuinely justifies extraordinary prices, and whose possession signals the deepest sake knowledge network. Honmaru (Main Keep — referring to a castle''s central tower) is their most distributed expression, though ''distributed'' is relative when the annual production is in hundreds rather than thousands of cases.',
 false, 'reserve',
 '[{"tier": "Japan''s Most Allocated Sake", "criteria": "Lottery distribution; 100 retailers nationwide; zero official export"}, {"tier": "Quality Benchmark", "criteria": "Quality genuinely justifies mythological status by independent assessment"}]',
 '{"appearance": "Crystal clear, faint silver tinge of premium pure rice", "nose": "Yamagata''s soft mountain water and premium Yamada Nishiki at medium polish (60% remaining for Honmaru): fresh white rice, peach blossom, faint mineral, a distinctive floral note from Yamagata''s GI yeast programme", "palate": "The junmai character is fully present: more body and umami than daiginjo expressions, but absolute purity of execution. Yamagata''s clean mountain water creates a different base from either Niigata or Nada — cooler, more mineral, more precise. The reason for the cult status is apparent in the palate''s complete integration of all elements", "finish": "50+ seconds; gradual diminishment of peach blossom note; light umami tail that signals the junmai''s fermentation honesty"}',
 '{"temperature_service": "12-15°C; this expression can be served at room temperature (Japanese style) to appreciate the fuller junmai character", "bc_source": "Not available through standard BC channels; requires specialist grey-market import; prices significantly above Japanese retail; verify authenticity of any bottle claimed to be Juyondai", "service_note": "If you can source a bottle of Juyondai for a guest who has asked for it, you have demonstrated the highest level of sake network knowledge. Do not list without confirmed stock."}',
 ARRAY['fresh white rice', 'peach blossom', 'Yamagata mineral', 'soft mountain water', 'integrated umami', 'junmai depth'],
 'medium-light', 'pure_integrated', 'Juyondai',
 'ultra_premium', '$280-$400 CAD (720ml)',
 '{"seimaibuai": "60% remaining (Honmaru grade)", "nihonshu_do": "+1", "acidity": "1.5", "alcohol": "15%", "distribution": "Japan-only lottery allocation; no official export; any BC availability is grey-market import", "rice_variety": "Yamada Nishiki (premium contracted Hyogo farms)", "water": "Yamagata mountain water — soft, clean"}',
 true),

('Born Gold Junmai Daiginjo', 'sake', 'junmai_daiginjo', 109, 50, 'Japan',
 'Born Gold (Kinpaku Junmai Daiginjo) is the flagship expression of Katokichibee Shouten''s pursuit of perfection — produced from Yamada Nishiki polished to 35% remaining, pressed using the fukurotsuri (bag-hanging) gravity method, and rested in Fukui''s natural cold-storage conditions. The gold designation references both the quality tier and the literal gold leaf that traditionally appears in premium Japanese packaging. Born Gold is consistently cited alongside Dassai 23 and Juyondai as one of the three international benchmark premium Japanese sake expressions.',
 false, 'reserve',
 '[{"tier": "Born Supreme Expression", "criteria": "35% seimaibuai; fukurotsuri gravity pressing; Born''s flagship"}, {"tier": "International Benchmark", "criteria": "Cited alongside Dassai 23 as global standard for junmai daiginjo quality"}]',
 '{"appearance": "Crystal clear; perhaps the finest visual clarity of any sake on this list — the fukurotsuri gravity pressing leaves zero sediment or turbidity", "nose": "The cleanest possible expression of Yamada Nishiki at 35% polish: white peach, melon, faint pear, spring flower. Fukui''s granite-filtered water provides a mineral note that distinguishes this from Yamaguchi''s Dassai 23 — slightly more mineral lift", "palate": "Born Gold''s distinction from Dassai 23 is texture: slightly more body, more presence — the Yamada Nishiki at 35% retaining fractionally more extract than at 23%. The gravity pressing''s gentleness is apparent in the complete absence of harsh press character; every component is in its place", "finish": "60+ seconds; white peach and light mineral; among the finest sake finishes available"}',
 '{"temperature_service": "10-12°C; Zalto Universal mandatory for this expression — the aromatic delicacy requires concentration that smaller glasses cannot achieve", "bc_source": "Wismettac fine dining allocation (limited); advance order recommended", "pairing": "Classical Kyoto kaiseki; any delicate preparation where the beverage is meant to amplify rather than contrast"}',
 ARRAY['white peach', 'melon', 'spring flower', 'Fukui granite mineral', 'gravity-pressed clarity', 'ultimate refinement'],
 'light', 'sublime_precise', 'Born Gold',
 'ultra_premium', '$150-$200 CAD (720ml)',
 '{"seimaibuai": "35% remaining (65% polished away)", "pressing_method": "Fukurotsuri — gravity-only bag hanging; no mechanical pressing pressure; takes 48-72 hours for a single batch", "nihonshu_do": "+4", "acidity": "1.3", "alcohol": "16%", "rice_variety": "Yamada Nishiki", "water": "Echizen mountain snowmelt, Fukui — ultra-soft granite filtered"}',
 true),

('Born Dream Junmai Daiginjo', 'sake', 'junmai_daiginjo', 109, 50, 'Japan',
 'Born Dream occupies the accessible premium tier of the Born range — 50% seimaibuai, Gohyakumangoku rice, and the same commitment to Fukui snowmelt water and careful fermentation as Born Gold, but at a price that enables regular service in fine dining. For guests who have moved beyond standard ginjo and are ready for premium daiginjo character without allocation complexity, Born Dream is the ideal stepping stone.',
 false, 'estate',
 '[{"tier": "Born Premium Entry", "criteria": "50% seimaibuai; accessible premium; stepping stone to Born Gold"}, {"tier": "Best Value Born", "criteria": "Most value-per-yen of the Born range"}]',
 '{"appearance": "Crystal clear", "nose": "Green apple, white flower, light melon. Gohyakumangoku''s character (lighter, higher-starch than Yamada Nishiki) is apparent: cleaner, crisper, more apple than peach", "palate": "Light-medium body; Fukui water''s softness is the defining element at this tier. Clean, refined, precise — the Born philosophy in an accessible format", "finish": "40-50 seconds; clean apple-mineral; dry and complete"}',
 '{"temperature_service": "10-12°C", "bc_source": "Wismettac Asian Foods Canada; more readily available than Born Gold"}',
 ARRAY['green apple', 'white flower', 'light melon', 'Fukui snowmelt', 'clean grain', 'dry precision'],
 'light', 'dry_refined', 'Born Dream',
 'premium', '$90-$120 CAD (720ml)',
 '{"seimaibuai": "50% remaining", "nihonshu_do": "+4", "acidity": "1.3", "alcohol": "16%", "rice_variety": "Gohyakumangoku", "water": "Echizen mountain snowmelt, Fukui"}',
 true),

('Dewazakura Oka Cherry Bouquet Ginjo', 'sake', 'ginjo', 110, 49, 'Japan',
 'Dewazakura Oka (Cherry Bouquet Ginjo) is one of modern sake history''s most significant expressions — the 1981 release that proved ginjo-style sake could achieve commercial distribution and mass appreciation. When Dewazakura launched Oka, ginjo fermentation was considered an artisanal curiosity; within a decade, the ginjo movement had swept Japan. Oka''s fragrant, floral, apple-blossom character (achieved through low-temperature ginjo fermentation with added alcohol for aromatic lift) became the model that every mass-market ginjo has since attempted to replicate.',
 false, 'estate',
 '[{"tier": "Historical Pioneer", "criteria": "First commercially successful ginjo expression in Japan (1981); defined the category standard"}, {"tier": "Current Quality", "criteria": "Maintains the same aromatic profile that made it historically significant — not merely a museum piece"}]',
 '{"appearance": "Clear, light straw", "nose": "The iconic ginjo nose: apple blossom, white flower, light banana. This is the aromatics that ginjo is supposed to smell like — and because Dewazakura defined the category, it''s essentially smell this sake or smell everything that came after it", "palate": "Light body; the added distilled alcohol of ginjo class perceptibly lifts and clarifies the aromatic expression. Clean, food-friendly, fragrant. The Yamagata mountain water''s softness is apparent", "finish": "Clean, 30-40 seconds; apple blossom tail. Refreshing and precise"}',
 '{"temperature_service": "10-12°C; the fragrant ginjo aromatics are maximally expressed at this temperature", "bc_source": "Wismettac Asian Foods Canada", "historical_note": "Serve with context: in 1981, when Dewazakura released Oka as a widely distributed commercial ginjo, the style barely existed as a mass-market category. This bottle is the ancestor of every fragrant ginjo on the BC market today."}',
 ARRAY['apple blossom', 'white flower', 'light banana', 'Yamagata mountain water', 'fragrant ginjo', 'clean pear'],
 'light', 'floral_fragrant', 'Dewazakura Oka',
 'premium', '$55-$75 CAD (720ml)',
 '{"seimaibuai": "50% remaining", "nihonshu_do": "+5 (dry)", "acidity": "1.2", "alcohol": "15.5%", "rice_variety": "Dewa Sansan — Yamagata''s registered proprietary rice", "water": "Tendo city mountain water, Yamagata", "historical_significance": "1981: first commercially successful junmai ginjo in Japan; launched the modern ginjo movement"}',
 true),

('Aramasa No. 6 X-type Junmai Ginjo', 'sake', 'kimoto_junmai_ginjo', 111, 49, 'Japan',
 'Aramasa No. 6 is the most philosophically consequential sake of the 21st century''s first quarter — proof that a sake made with no modern brewing aids (no added lactic acid, no commercial yeast beyond the brewery''s own 1935 No. 6 strain, no added alcohol, 100% kimoto fermentation) could achieve quality levels competitive with the most technically precise modern daiginjo. Owner-brewer Yusuke Satou''s transformation of his family brewery into Japan''s leading natural sake producer has inspired a generation of young brewers to question the assumptions of modern production. The X-type Junmai Ginjo is the most accessible entry to the Aramasa world.',
 false, 'reserve',
 '[{"tier": "Natural Sake Philosophical Peak", "criteria": "100% kimoto; No. 6 yeast (isolated 1935); zero modern brewing aids"}, {"tier": "Japan''s Most Discussed Contemporary Sake", "criteria": "Most written-about new-wave sake in Japan 2015-present"}]',
 '{"appearance": "Slightly hazy — the natural production method and kimoto fermentation produce a slight cloudiness that filters would remove; Satou has rejected filtration as incompatible with his natural approach. The appearance communicates the philosophy", "nose": "Utterly unlike modern ginjo: the No. 6 yeast''s distinctive character is immediately apparent — lemon, yellow apple, faint yogurt, white flower, something clean and archaic that suggests pre-industrial fermentation. The aromatic profile is simultaneously ancient and new", "palate": "Lower acidity than modern sake (the natural kimoto lactic is gentler than added lactic acid); more texture; genuine complexity from the kimoto method''s extended moto production. The No. 6 yeast''s lower fermentation temperature produces a distinctive spritzy quality — there is a gentle CO2 presence that no modern sake reproduces", "finish": "50+ seconds; the lemon-yogurt note of kimoto lactic persists into the finish with remarkable clarity"}',
 '{"temperature_service": "12-16°C — slightly warmer than modern ginjo to allow the kimoto complexity to fully express; the natural production requires room to breathe", "bc_source": "Essentially unavailable through standard BC channels; requires specialist grey-market import; verify authenticity", "service_narrative": "Aramasa No. 6: made with no tools that did not exist in 1935. The yeast that ferments this sake was isolated here in that year and has been maintained continuously since. Every sip is a fermentation lineage that predates the Second World War."}',
 ARRAY['lemon', 'yellow apple', 'kimoto yogurt', 'white flower', 'ancient grain', 'natural CO2 spritz', 'No. 6 yeast character'],
 'medium-light', 'natural_complex', 'Aramasa No. 6',
 'ultra_premium', '$180-$250 CAD (720ml)',
 '{"seimaibuai": "55% remaining (X-type); lower polish than typical ginjo — the quality comes from method, not polish", "fermentation": "100% kimoto (traditional wooden-pole moto); No. 6 yeast isolated at Aramasa Shuzo in 1935 — oldest classified sake yeast in Japan", "nihonshu_do": "+5", "acidity": "1.6 (higher than modern sake — kimoto characteristic)", "alcohol": "13.5% (lower than modern sake — No. 6 yeast characteristic)", "zero_additives": "No added lactic acid, no commercial yeast, no added alcohol, no filtration beyond settling"}',
 true);

COMMIT;
