BEGIN;

INSERT INTO pairing_intelligence
  (beverage_product_id, beverage_category, beverage_style, beverage_description,
   food_category, food_flavour_profile, food_description,
   pairing_type, flavour_logic, meal_context, confidence, authority_tier, is_published)
VALUES

-- 389: Yirgacheffe YCFCU Grade 1 Washed
(389, 'coffee', 'Washed Yirgacheffe Single Origin',
 'Jasmine-bergamot florality over lemon verbena acidity; silky body and white-tea finish.',
 'pastry_dessert', 'delicate floral-citrus',
 'Lemon verbena financier or bergamot madeleines; ethereal patisserie that echoes the coffee''s florality without overpowering it.',
 'complement', 'Shared jasmine-citrus register; the financier''s butter richness smooths the coffee''s acidity.',
 'any', 'classic', 1, true),

(389, 'coffee', 'Washed Yirgacheffe Single Origin',
 'Jasmine-bergamot florality over lemon verbena acidity; silky body and white-tea finish.',
 'cheese', 'fresh mild',
 'Fresh chèvre with honey and lavender; goat''s milk freshness and floral honey mirror the coffee''s aromatic lift.',
 'complement', 'Light dairy fat tempers acidity; lavender and honey echo jasmine-bergamot florality.',
 'casual', 'established', 1, true),

(389, 'coffee', 'Washed Yirgacheffe Single Origin',
 'Jasmine-bergamot florality over lemon verbena acidity; silky body and white-tea finish.',
 'fruit', 'stone fruit fresh',
 'White peach and apricot slices with a cardamom dusting; the coffee''s stone-fruit brightness finds a natural partner.',
 'bridge', 'White peach note in coffee echoed in fresh stone fruit; cardamom spice adds complexity without clash.',
 'casual', 'suggested', 1, true),

(389, 'coffee', 'Washed Yirgacheffe Single Origin',
 'Jasmine-bergamot florality over lemon verbena acidity; silky body and white-tea finish.',
 'chocolate', 'white chocolate floral',
 'White chocolate bark with candied violet and yuzu zest; delicate sweetness amplifies the coffee''s floral register.',
 'complement', 'White chocolate''s mild sweetness and florality align perfectly with jasmine-dominant washed Yirgacheffe.',
 'dessert', 'adventurous', 1, true),

-- 390: Konga Natural Process Yirgacheffe
(390, 'coffee', 'Natural Yirgacheffe Single Origin',
 'Blueberry jam and rose water intensity; syrupy body with hibiscus-tea acidity and long winey finish.',
 'pastry_dessert', 'dark berry compote',
 'Blueberry clafoutis or dark berry tart with crème fraîche; the fruit-forward coffee finds a seamless match in warm berry desserts.',
 'complement', 'Shared blueberry-dark berry register; crème fraîche fat balances the coffee''s syrupy sweetness.',
 'dessert', 'classic', 1, true),

(390, 'coffee', 'Natural Yirgacheffe Single Origin',
 'Blueberry jam and rose water intensity; syrupy body with hibiscus-tea acidity and long winey finish.',
 'cheese', 'aged soft-ripened',
 'Aged Brie or Camembert with blackberry preserve; the wine-like coffee cuts through soft-ripened fat while echoing the berry note.',
 'cleanse', 'Natural ferment complexity pairs with soft-ripened earthiness; berry preserve bridges both.',
 'casual', 'established', 1, true),

(390, 'coffee', 'Natural Yirgacheffe Single Origin',
 'Blueberry jam and rose water intensity; syrupy body with hibiscus-tea acidity and long winey finish.',
 'chocolate', 'dark chocolate berry',
 'Dark chocolate (70%) with freeze-dried raspberry; the coffee''s winey berry intensity finds its ideal mirror in high-quality dark chocolate.',
 'complement', 'Winey fermented-fruit character of natural coffee aligns with dark chocolate bitterness and berry acidity.',
 'dessert', 'classic', 1, true),

(390, 'coffee', 'Natural Yirgacheffe Single Origin',
 'Blueberry jam and rose water intensity; syrupy body with hibiscus-tea acidity and long winey finish.',
 'grain', 'spiced baked good',
 'Rose-water and cardamom semolina cake (basbousa style); Middle Eastern pastry spice echoes the coffee''s rose-water aromatic.',
 'bridge', 'Rose water appears in both coffee and cake; cardamom lifts florality and anchors the pairing.',
 'casual', 'adventurous', 1, true),

-- 391: Worka Sidama Washed Grade 1
(391, 'coffee', 'Washed Sidama Single Origin',
 'Red currant and nectarine brightness over sweet-cream body; clean citrus-peel finish.',
 'pastry_dessert', 'citrus-cream',
 'Lemon posset or tarte au citron; the coffee''s citrus-cream axis finds a textural and aromatic mirror in classic citrus pastry.',
 'complement', 'Shared citrus-cream register; the dessert''s richness softens the coffee''s bright acidity.',
 'dessert', 'established', 1, true),

(391, 'coffee', 'Washed Sidama Single Origin',
 'Red currant and nectarine brightness over sweet-cream body; clean citrus-peel finish.',
 'grain', 'lightly sweetened baked',
 'Almond croissant or pain au lait; buttery enriched pastry with gentle sweetness complements the red-berry brightness of Sidama.',
 'complement', 'Sweet-cream body of coffee echoes enriched-dough richness; red currant notes brighten against buttery pastry.',
 'casual', 'classic', 1, true),

(391, 'coffee', 'Washed Sidama Single Origin',
 'Red currant and nectarine brightness over sweet-cream body; clean citrus-peel finish.',
 'fruit', 'stone fruit tangy',
 'Nectarine and red currant compote with Greek yoghurt; the coffee''s exact flavour markers appear in the dish.',
 'complement', 'Direct flavour echo: nectarine and red currant in the coffee appear literally in the dish; yoghurt fat bridges.',
 'casual', 'suggested', 1, true),

(391, 'coffee', 'Washed Sidama Single Origin',
 'Red currant and nectarine brightness over sweet-cream body; clean citrus-peel finish.',
 'chocolate', 'milk chocolate caramel',
 'Milk chocolate caramel bark with sea salt; caramel sweetness and milk fat harmonise with the coffee''s brown-sugar and cream notes.',
 'complement', 'Brown sugar note in coffee aligns with caramel; sea salt elevates both by contrast.',
 'casual', 'established', 1, true),

-- 392: Bensa Bore Honey Process Sidama
(392, 'coffee', 'Honey Process Sidama Single Origin',
 'Strawberry and dried apricot sweetness with cacao-nib depth; lingering maple finish.',
 'pastry_dessert', 'apricot-almond',
 'Apricot frangipane tart or almond-apricot Danish; stone-fruit sweetness and almond nuttiness echoes the coffee''s dried apricot and cacao profile.',
 'complement', 'Dried apricot note in coffee mirrors fresh apricot in pastry; almond frangipane echoes cacao nib depth.',
 'casual', 'classic', 1, true),

(392, 'coffee', 'Honey Process Sidama Single Origin',
 'Strawberry and dried apricot sweetness with cacao-nib depth; lingering maple finish.',
 'chocolate', 'dark chocolate fruity',
 'Dark chocolate (64%) with freeze-dried strawberry and a pinch of chilli; the coffee''s strawberry and cacao-nib markers find precise alignment.',
 'complement', 'Strawberry and cacao markers appear in both coffee and chocolate; chilli amplifies the lingering maple spice finish.',
 'dessert', 'established', 1, true),

(392, 'coffee', 'Honey Process Sidama Single Origin',
 'Strawberry and dried apricot sweetness with cacao-nib depth; lingering maple finish.',
 'grain', 'maple-walnut baked',
 'Maple-walnut biscotti or maple pecan muffin; the coffee''s long maple finish mirrors the baked good''s dominant sweetener.',
 'complement', 'Maple finish in coffee directly echoed in baked good; walnut nuttiness parallels cacao nib.',
 'casual', 'suggested', 1, true),

(392, 'coffee', 'Honey Process Sidama Single Origin',
 'Strawberry and dried apricot sweetness with cacao-nib depth; lingering maple finish.',
 'dairy', 'crème fraîche fruit',
 'Crème fraîche with fresh strawberries and a honey drizzle; honey sweetness and fresh berry align with the coffee''s honey-process fruit forwardness.',
 'bridge', 'Honey process fermentation character bridges with honey drizzle; crème fraîche fat rounds the coffee''s acidity.',
 'casual', 'adventurous', 1, true),

-- 393: Harrar Longberry Sun-Dried Natural
(393, 'coffee', 'Natural Harrar Longberry',
 'Wild-fermented; blueberry wine, dark chocolate and tobacco complexity with port-like finish.',
 'chocolate', 'dark chocolate wine-infused',
 'Port-and-dark-chocolate truffles or chocolate wine cake; the coffee''s port-like finish finds its ultimate partner in wine-chocolate confection.',
 'complement', 'Port character in both coffee and truffle creates a unified aromatic whole; dark chocolate bridges the tobacco depth.',
 'dessert', 'classic', 2, true),

(393, 'coffee', 'Natural Harrar Longberry',
 'Wild-fermented; blueberry wine, dark chocolate and tobacco complexity with port-like finish.',
 'cheese', 'aged hard',
 'Aged manchego or aged gouda with dried fig; the coffee''s tobacco and earth depth pairs well with aged hard cheese''s crystalline umami.',
 'complement', 'Tobacco and earth markers in coffee align with aged cheese complexity; dried fig bridges blueberry-wine notes.',
 'casual', 'established', 2, true),

(393, 'coffee', 'Natural Harrar Longberry',
 'Wild-fermented; blueberry wine, dark chocolate and tobacco complexity with port-like finish.',
 'pastry_dessert', 'spiced dark fruit',
 'Christmas cake or sticky date pudding with toffee sauce; the coffee''s dried-fruit depth and earthy spice mirror classic dark fruit bakes.',
 'complement', 'Dark fruit, spice and molasses shared between coffee and dessert; toffee sauce echoes the port-like sweetness.',
 'dessert', 'established', 2, true),

(393, 'coffee', 'Natural Harrar Longberry',
 'Wild-fermented; blueberry wine, dark chocolate and tobacco complexity with port-like finish.',
 'grain', 'spiced enriched bread',
 'Cardamom-spiced injera pancake with honey or spiced date bread; Ethiopian culinary heritage + the coffee''s wild-ferment character creates a sense of place pairing.',
 'bridge', 'Ethiopian origin creates sense-of-place alignment; cardamom spice bridges earthy tobacco and floral blueberry registers.',
 'casual', 'adventurous', 2, true),

-- 394: Harrar HFCU Cooperative Grade 1 Natural
(394, 'coffee', 'Natural Harrar Cooperative',
 'Dried cherry, mocha and black cardamom aromatics; full body, sweet spice finish.',
 'chocolate', 'mocha dark chocolate',
 'Mocha cake or espresso brownie; the coffee''s mocha core finds perfect symmetry in chocolate-coffee baked confection.',
 'complement', 'Mocha appears in both coffee and dessert creating unified depth; dark chocolate amplifies the dried cherry note.',
 'dessert', 'classic', 2, true),

(394, 'coffee', 'Natural Harrar Cooperative',
 'Dried cherry, mocha and black cardamom aromatics; full body, sweet spice finish.',
 'spice', 'black cardamom spiced',
 'Spiced lamb kofta with black cardamom yoghurt dip; the coffee''s dominant black cardamom spice note finds a savoury anchor in Middle Eastern preparation.',
 'complement', 'Black cardamom appears explicitly in both coffee aroma and dish spice; savouriness creates contrast that elevates both.',
 'main', 'adventurous', 2, true),

(394, 'coffee', 'Natural Harrar Cooperative',
 'Dried cherry, mocha and black cardamom aromatics; full body, sweet spice finish.',
 'pastry_dessert', 'cherry chocolate',
 'Black Forest gateau or cherry-chocolate tart; the coffee''s dried cherry and mocha markers find a classical partner in cherry-chocolate dessert.',
 'complement', 'Dried cherry note in coffee echoed in fresh-preserved cherry in dessert; mocha bridges chocolate element.',
 'dessert', 'established', 2, true),

(394, 'coffee', 'Natural Harrar Cooperative',
 'Dried cherry, mocha and black cardamom aromatics; full body, sweet spice finish.',
 'dairy', 'spiced cream',
 'Cardamom panna cotta with rose-hip coulis; spice-inflected cream dessert echoes the coffee''s sweet spice finish and dried fruit aromatics.',
 'complement', 'Cardamom in panna cotta directly echoes coffee''s black cardamom note; rose hip bridges dried cherry aromatic.',
 'dessert', 'suggested', 2, true),

-- 395: d'Arenberg The Dead Arm Shiraz
(395, 'wine_still', 'McLaren Vale Old-Vine Shiraz',
 'Liqueur plum, dark chocolate and anise concentration; supple tannins, 20-year trajectory.',
 'meat', 'red meat braised',
 'Slow-braised beef short rib with star anise and dark chocolate mole; the wine''s anise and chocolate markers find an ideal slow-cooked partner.',
 'complement', 'Anise and dark chocolate in wine mirror the mole''s spice and chocolate; braised meat fat tames the wine''s concentration.',
 'main', 'classic', 1, true),

(395, 'wine_still', 'McLaren Vale Old-Vine Shiraz',
 'Liqueur plum, dark chocolate and anise concentration; supple tannins, 20-year trajectory.',
 'charcuterie', 'aged cured meat',
 'Aged salami or fennel sausage; the wine''s anise note harmonises with fennel seed spice while the cured meat''s fat softens tannin.',
 'complement', 'Fennel seed in charcuterie echoes anise in wine; fat from cured meat integrates tannin structure.',
 'starter', 'established', 1, true),

(395, 'wine_still', 'McLaren Vale Old-Vine Shiraz',
 'Liqueur plum, dark chocolate and anise concentration; supple tannins, 20-year trajectory.',
 'cheese', 'aged hard sharp',
 'Aged cheddar or aged manchego; the wine''s concentration and tannin require a cheese with enough protein and fat to stand up to it.',
 'complement', 'Aged cheese crystalline protein matches tannic structure; shared earthiness and depth align.',
 'cheese', 'established', 1, true),

(395, 'wine_still', 'McLaren Vale Old-Vine Shiraz',
 'Liqueur plum, dark chocolate and anise concentration; supple tannins, 20-year trajectory.',
 'meat', 'game birds',
 'Roasted spiced duck breast with plum sauce; the wine''s plum intensity and spice find a natural match in richly sauced poultry.',
 'complement', 'Plum in both wine and sauce creates mirror; duck fat matches tannin weight; spice bridge between Shiraz pepper and duck seasoning.',
 'main', 'established', 1, true),

-- 396: Clarendon Hills Astralis Shiraz
(396, 'wine_still', 'McLaren Vale Clarendon Shiraz Grand Vin',
 'Black olive, blackberry, violet, white pepper, iron; 80-year-old vines. Age 10–30 years.',
 'meat', 'red meat grilled',
 'Dry-aged côte de boeuf or bone-in ribeye; the wine''s iron-mineral density and tannic authority require the simplicity of high-quality aged beef.',
 'complement', 'Iron and mineral in wine align with aged beef''s iron-rich myoglobin; dry-aged complexity matches wine''s depth.',
 'main', 'classic', 1, true),

(396, 'wine_still', 'McLaren Vale Clarendon Shiraz Grand Vin',
 'Black olive, blackberry, violet, white pepper, iron; 80-year-old vines. Age 10–30 years.',
 'meat', 'lamb roasted',
 'Rack of lamb with herb crust and black olive tapenade; the wine''s black olive tapenade note creates a direct flavour echo.',
 'complement', 'Black olive appears in both wine''s descriptor and the dish''s tapenade; herb crust''s savoury lift matches the wine''s pepper.',
 'main', 'classic', 1, true),

(396, 'wine_still', 'McLaren Vale Clarendon Shiraz Grand Vin',
 'Black olive, blackberry, violet, white pepper, iron; 80-year-old vines. Age 10–30 years.',
 'cheese', 'aged hard cave',
 'Cave-aged Gruyère or Comté; the wine''s iron and mineral density pairs with the crystalline umami of long-aged mountain cheese.',
 'complement', 'Mineral iron core of Astralis echoed in aged mountain cheese''s mineral complexity; the wine''s concentration matches the cheese''s intensity.',
 'cheese', 'established', 1, true),

(396, 'wine_still', 'McLaren Vale Clarendon Shiraz Grand Vin',
 'Black olive, blackberry, violet, white pepper, iron; 80-year-old vines. Age 10–30 years.',
 'meat', 'venison slow-cooked',
 'Braised venison with blackberry jus and juniper; the wine''s blackberry intensity and violet florality align with game meat''s wild character.',
 'complement', 'Blackberry appears in both wine and jus; violet florality in wine mirrors juniper''s botanical character; game and iron mineral are natural partners.',
 'main', 'adventurous', 1, true),

-- 397: Yering Station Reserve Pinot Noir
(397, 'wine_still', 'Yarra Valley Cool-Climate Pinot Noir',
 'Red cherry, forest floor, five-spice, rose hip; cool-climate savoury mineral.',
 'meat', 'duck roasted',
 'Roasted duck breast with cherry sauce and five-spice; the wine''s dominant five-spice note and cherry fruit find direct expression in classic duck preparation.',
 'complement', 'Five-spice appears explicitly in both wine descriptor and dish seasoning; cherry sauce mirrors the wine''s red cherry core.',
 'main', 'classic', 2, true),

(397, 'wine_still', 'Yarra Valley Cool-Climate Pinot Noir',
 'Red cherry, forest floor, five-spice, rose hip; cool-climate savoury mineral.',
 'mushroom', 'wild earthen',
 'Wild mushroom fricassée with thyme and butter; the wine''s forest-floor earthiness finds a natural partner in foraged fungi.',
 'complement', 'Forest floor in wine mirrors wild mushroom earthiness; thyme''s herbaceous note bridges the wine''s savoury mineral quality.',
 'main', 'established', 2, true),

(397, 'wine_still', 'Yarra Valley Cool-Climate Pinot Noir',
 'Red cherry, forest floor, five-spice, rose hip; cool-climate savoury mineral.',
 'fish', 'oily-rich salmon',
 'Salmon en croûte or pan-roasted salmon with beurre rouge; cool-climate Pinot''s acidity cuts through oily salmon while cherry fruit creates a classic pairing.',
 'cleanse', 'Cool-climate acidity cuts salmon oil; red fruit complements the fish''s rich flavour without overwhelming.',
 'main', 'established', 2, true),

(397, 'wine_still', 'Yarra Valley Cool-Climate Pinot Noir',
 'Red cherry, forest floor, five-spice, rose hip; cool-climate savoury mineral.',
 'meat', 'pork loin',
 'Pork tenderloin with cherry compote and celeriac purée; the wine''s red cherry and mineral quality are a textbook match for pork.',
 'complement', 'Red cherry in wine echoed in cherry compote; pork''s delicate flavour allows the wine''s complexity to shine.',
 'main', 'classic', 2, true),

-- 398: Coldstream Hills Reserve Chardonnay
(398, 'wine_still', 'Yarra Valley Cool-Climate Chardonnay',
 'White peach, nectarine, hazelnut, lemon curd; precise Burgundian acidity.',
 'fish', 'white-fleshed fine',
 'Pan-roasted barramundi or turbot with hazelnut beurre noisette; the wine''s hazelnut note finds a direct culinary bridge in the brown butter preparation.',
 'complement', 'Hazelnut appears in both wine and beurre noisette; white-fleshed fish delicacy matches the wine''s restrained elegance.',
 'main', 'classic', 2, true),

(398, 'wine_still', 'Yarra Valley Cool-Climate Chardonnay',
 'White peach, nectarine, hazelnut, lemon curd; precise Burgundian acidity.',
 'shellfish', 'lobster-langoustine',
 'Lobster bisque or langoustine with lemon butter; the wine''s peach-nectarine richness and acidity are ideal partners for sweet crustacean.',
 'complement', 'Stone fruit richness in Chardonnay echoes the natural sweetness of lobster; lemon butter bridges the wine''s lemon curd note.',
 'main', 'established', 2, true),

(398, 'wine_still', 'Yarra Valley Cool-Climate Chardonnay',
 'White peach, nectarine, hazelnut, lemon curd; precise Burgundian acidity.',
 'cheese', 'aged creamy soft',
 'Triple-cream brie or Brillat-Savarin; the wine''s creamy oak and lemon curd balance the richness of high-fat soft cheese.',
 'complement', 'Creamy oak in wine mirrors the high-fat richness of triple-cream cheese; lemon acidity cleanses the palate.',
 'cheese', 'established', 2, true),

(398, 'wine_still', 'Yarra Valley Cool-Climate Chardonnay',
 'White peach, nectarine, hazelnut, lemon curd; precise Burgundian acidity.',
 'poultry', 'chicken roasted',
 'Roasted free-range chicken with tarragon and cream sauce; the wine''s combination of stone fruit, hazelnut and cream mirrors the richness of classic French chicken preparation.',
 'complement', 'Cream sauce echoes the wine''s creamy texture; tarragon''s anise note bridges the wine''s stone fruit register.',
 'main', 'classic', 2, true),

-- 399: Te Mata Coleraine
(399, 'wine_still', 'Hawke''s Bay Bordeaux Blend',
 'Cassis, pencil shaving, cedar, black plum, dried herb, mineral; ages 15+ years.',
 'meat', 'lamb classic',
 'Rack of lamb with rosemary and garlic; the wine''s cassis and cedar register is the textbook Bordeaux-blend partner for herb-roasted lamb.',
 'complement', 'Cassis and cedar of Coleraine are the classic Bordeaux counterpart to herb-roasted lamb; dried herb in wine echoes rosemary.',
 'main', 'classic', 1, true),

(399, 'wine_still', 'Hawke''s Bay Bordeaux Blend',
 'Cassis, pencil shaving, cedar, black plum, dried herb, mineral; ages 15+ years.',
 'meat', 'beef grilled',
 'Aged beef sirloin or Wellington; the wine''s mineral depth and pencil-shaving tannic authority require quality aged beef to stand up to it.',
 'complement', 'Pencil-shaving tannin structure integrates with beef''s fat and protein; mineral note enhanced by the Maillard crust.',
 'main', 'established', 1, true),

(399, 'wine_still', 'Hawke''s Bay Bordeaux Blend',
 'Cassis, pencil shaving, cedar, black plum, dried herb, mineral; ages 15+ years.',
 'cheese', 'aged hard cave',
 'Aged Comté or vintage cheddar; the wine''s cedar and mineral complexity benefits from aged cheese''s crystalline protein and umami depth.',
 'complement', 'Cedar and mineral in wine mirror the aged cheese''s complex terroir character; tannin structure balanced by protein.',
 'cheese', 'established', 1, true),

(399, 'wine_still', 'Hawke''s Bay Bordeaux Blend',
 'Cassis, pencil shaving, cedar, black plum, dried herb, mineral; ages 15+ years.',
 'charcuterie', 'pâté de campagne',
 'Pâté en croûte or terrine de campagne; the wine''s cedar structure and cassis fruit create the classic Bordeaux-terrine partnership.',
 'complement', 'Classic bistro pairing: structured Bordeaux-style tannin binds with pâté''s fat and liver richness while cassis brightens.',
 'starter', 'established', 1, true),

-- 400: Craggy Range Le Sol Gimblett Gravels Syrah
(400, 'wine_still', 'Hawke''s Bay Gimblett Gravels Syrah',
 'Violet, smoked olive, white pepper, dark berry, iron, fine tannin; NZ benchmark Syrah.',
 'meat', 'lamb smoked',
 'Smoked rack of lamb with olive tapenade and herbs; the wine''s smoked olive and pepper match perfectly with the dish''s preparation and garnish.',
 'complement', 'Smoked olive note in wine directly mirrors olive tapenade; white pepper in wine echoes lamb seasoning; smoke in preparation bridges wine''s character.',
 'main', 'classic', 1, true),

(400, 'wine_still', 'Hawke''s Bay Gimblett Gravels Syrah',
 'Violet, smoked olive, white pepper, dark berry, iron, fine tannin; NZ benchmark Syrah.',
 'meat', 'beef dry-aged',
 'Dry-aged ribeye with bone marrow butter and pepper sauce; the wine''s iron and white pepper intensity are natural partners for premium aged beef.',
 'complement', 'Iron mineral in wine aligns with dry-aged beef''s iron-rich flavour; white pepper spice matches the pepper sauce; bone marrow softens fine tannin.',
 'main', 'established', 1, true),

(400, 'wine_still', 'Hawke''s Bay Gimblett Gravels Syrah',
 'Violet, smoked olive, white pepper, dark berry, iron, fine tannin; NZ benchmark Syrah.',
 'meat', 'wild boar braised',
 'Braised wild boar with dark berry reduction and juniper; the wine''s wild character and iron density meet their match in rustic game cookery.',
 'complement', 'Dark berry reduction echoes the wine''s berry fruit; juniper''s botanical lift matches violet florality; iron and game are natural companions.',
 'main', 'adventurous', 1, true),

(400, 'wine_still', 'Hawke''s Bay Gimblett Gravels Syrah',
 'Violet, smoked olive, white pepper, dark berry, iron, fine tannin; NZ benchmark Syrah.',
 'cheese', 'washed rind pungent',
 'Époisses or Taleggio; the wine''s smoked character and iron depth create an unexpected but compelling match with assertive washed-rind cheese.',
 'contrast', 'Pungent washed-rind cheese''s ferment notes contrast with the wine''s smoky mineral clarity; violet florality lifts and softens the cheese''s pungency.',
 'cheese', 'adventurous', 1, true);

COMMIT;
