BEGIN;
INSERT INTO pairing_intelligence
  (beverage_product_id, food_flavour_profile, food_category, food_description, pairing_type, flavour_logic, meal_context, confidence, authority_tier)
VALUES
-- Trappist ales (579-582)
(579,'Westvleteren XII, Trappist, Belgium, dark, complex','cheese','Aged Abbaye de Cîteaux with walnut bread and pear mostarda','complement','Westvleteren XII''s abbey dark ale complexity bridges the aged abbey cheese; the monastery makes both','cheese','classic',1),
(579,'Westvleteren XII, Trappist, quadrupel','casual','Dark chocolate fondant with salted caramel and vanilla cream','complement','Westvleteren XII''s dried fruit and dark malt bridges the chocolate fondant; Belgium''s rarest beer for Belgium''s finest dessert','dessert','classic',1),
(579,'Westvleteren XII, dark abbey ale','casual','Flemish beef stew (carbonnade à la flamande) with dark abbey beer','complement','Westvleteren XII belongs in the carbonnade; braising with Belgium''s greatest beer creates a flavour loop at the abbey','main','classic',1),
(579,'Westvleteren XII, celebration, rare','casual','Speculoos (Belgian spice cookie) with brown sugar and cinnamon butter','complement','Westvleteren XII''s spice and dark sugar bridges the speculoos; both come from Belgium''s monastic spice tradition','casual','classic',1),
(579,'Westvleteren XII, dark fruit, abbey','game','Hare braised in dark Belgian ale with juniper and thyme','complement','Westvleteren XII''s dark fruit character bridges the braised hare; Belgian abbey ale for Belgian game tradition','main','classic',2),
(579,'Westvleteren XII, dessert-like, malt','dessert','Tarte au sucre (Belgian brown sugar tart) with cream','complement','Westvleteren XII''s malt sweetness bridges the tarte au sucre; Belgium''s classic bake for Belgium''s rarest beer','dessert','established',2),

(580,'Rochefort 10, Belgian Trappist, dark, complex','cheese','Chimay à la Bière (Trappist washed rind) with dark rye and mustard','complement','Rochefort 10 and Chimay cheese is Belgium''s defining Trappist pairing; the abbey ale for the abbey cheese','cheese','classic',1),
(580,'Rochefort 10, Quadrupel, dried fruit','casual','Carbonnade flamande (Belgian beef beer stew) with Belgian fries','complement','Rochefort 10''s dark complexity belongs in the carbonnade; the Belgian classic cooked in and served with Trappist ale','main','classic',1),
(580,'Rochefort 10, Trappist, dark malt','dessert','Belgian praline chocolates (Neuhaus style) with hazelnut ganache','complement','Rochefort 10''s dark malt and dried fruit bridges the Belgian praline; the abbey pairing of beer and chocolate','dessert','classic',1),
(580,'Rochefort 10, complex, spiced','casual','Moules-frites aux herbes with Belgian leeks and white wine','complement','Rochefort 10''s complexity bridges the mussels and leeks; a Trappist ale for Belgium''s most beloved casual dish','main','established',2),
(580,'Rochefort 10, abbey, dark ale','game','Duck confit with Liège-style cherry reduction and potato croquette','complement','Rochefort 10''s dark fruit bridges the duck confit and cherry; a Wallonian Trappist for a Wallonian game preparation','main','classic',2),
(580,'Rochefort 10, celebration, prestige','casual','Pain d''épices (Dijon spice bread) with foie gras and fig confiture','complement','Rochefort 10''s spice character bridges the pain d''épices and foie gras; a prestige Belgian pairing of abbey and luxury','starter','established',2),

(581,'Rochefort 8, Belgian Trappist, amber, balanced','casual','Waterzooï (Ghent chicken stew) with vegetables and cream','complement','Rochefort 8''s balanced Trappist character bridges the waterzooï; a Belgian abbey ale for Belgium''s most beloved regional stew','main','classic',1),
(581,'Rochefort 8, dark amber, Belgian abbaye','cheese','Young Herve cheese (washed rind Liège) with dark bread','complement','Rochefort 8''s amber Trappist bridges the young Herve; a Liège abbey tradition of washed rind and monastery ale','cheese','classic',1),
(581,'Rochefort 8, malt, dark fruit, approachable','casual','Belgian waffles (gaufre de Liège) with brown sugar and butter','complement','Rochefort 8''s malt warmth bridges the Liège waffle; a Trappist ale for the pearl sugar tradition','casual','classic',1),
(581,'Rochefort 8, spice, abbey ale','game','Rabbit in Belgian ale sauce with thyme and mustard','complement','Rochefort 8''s Trappist character bridges the rabbit cooked in abbey ale; a Belgian game tradition for a Belgian table','main','classic',1),
(581,'Rochefort 8, moderate, food-friendly','casual','Cured Belgian pork sausage (boudin blanc de Liège) with apple sauce','complement','Rochefort 8''s approachability bridges the boudin blanc; a Trappist ale for a Belgian charcuterie tradition','casual','established',2),
(581,'Rochefort 8, dark, medium strength','dessert','Mousse au chocolat noir with Trappist beer reduction and cream','complement','Rochefort 8''s dark malt bridges the dark chocolate mousse; Belgian abbey ale for Belgium''s signature chocolate dessert','dessert','established',2),

(582,'Chimay Grande Réserve Blue, Belgian Trappist, dark','cheese','Chimay à la Bière (Chimay washed rind) paired with its own beer','complement','Chimay Grande Réserve is made in the same abbey as the Chimay cheese; the ultimate Trappist terroir pairing','cheese','classic',1),
(582,'Chimay Blue, Trappist, strong, dark ale','casual','Carbonnade à la chimay (beef braised in Chimay) with Trappist bread','complement','Chimay Blue is the beer for Chimay carbonnade; cooking with the same ale the monks brew creates direct Trappist unity','main','classic',1),
(582,'Chimay Grande Réserve, complex, fruit','casual','Endives au gratin (Belgian chicory gratin) with Chimay and ham','complement','Chimay Blue''s malt richness bridges the endives gratin; the abbey ale works with Belgium''s own bitter-and-cream classic','main','classic',1),
(582,'Chimay Blue, dark, warming','game','Wild boar terrine with Ardennes spices and dark bread','complement','Chimay''s dark strength bridges the Ardennes wild boar terrine; a Belgian Trappist for the Ardennes'' own hunting tradition','starter','established',2),
(582,'Chimay Grande Réserve, celebration','casual','Belgian speculoos crème brûlée with caramelised cinnamon sugar','complement','Chimay Blue''s spice complexity bridges the speculoos crème brûlée; a monastic spice tradition for a Belgian classic','dessert','established',2),
(582,'Chimay Blue, dark malt, food-friendly','casual','Flemish onion soup (soupe à l''oignon flamande) with Gruyère crostini','complement','Chimay Grande Réserve''s depth bridges the Flemish onion soup; both are expressions of Belgium''s slow-cooked winter tradition','casual','established',2),

-- Boon Gueuze (583 — already has 2 pairings, need 5 more)
(583,'Boon Gueuze, lambic, wild ferment, aged','seafood','Langoustines grillées with lemon, tarragon and Gueuze beurre blanc','complement','Boon Gueuze''s acidity and wild character bridges the langoustines; the Gueuze in the beurre blanc creates a direct flavour link','fish_course','classic',1),
(583,'Boon Gueuze, Mariage Parfait, oak-aged','cheese','Aged Ossau-Iraty with quince paste and walnut bread','complement','Boon Gueuze''s aged acidity bridges the Ossau-Iraty sheep cheese; the funky wild ferment suits the sheep milk''s nuttiness','cheese','established',2),
(583,'Boon Gueuze, Belgian, wild ale','seafood','Moules à la Gueuze (mussels in Boon Gueuze) with shallots and parsley','complement','Boon Gueuze belongs in the moules à la Gueuze; cooking with and drinking the same lambic beer is the Pajottenland tradition','main','classic',1),
(583,'Boon Gueuze, acetic, funky, aged','casual','Rillettes de Tours with cornichons and Dijon mustard on sourdough','complement','Boon Gueuze''s acidity bridges the pork rillettes richness; the tart carbonation cuts the fat exactly as it should','starter','established',2),
(583,'Boon Gueuze, old lambic, complex','dessert','Clafoutis aux cerises (cherry flan) with Gueuze-macerated sour cherries','complement','Boon Gueuze''s cherry-acidity bridges the clafoutis; the maceration in lambic enhances the tart Morello cherry connection','dessert','classic',1),

-- Paulaner Hefeweizen (585)
(585,'Paulaner Hefeweizen, Munich, yeast, banana-clove','casual','Weisswurst (Bavarian white sausage) with sweet mustard and a pretzel','complement','Paulaner Hefe-Weißbier and Weisswurst is Munich''s defining morning pairing; the banana-yeast suits the veal sausage''s delicacy','casual','classic',1),
(585,'Paulaner Hefe-Weißbier, hefeweizen, German wheat','casual','Obatzda (spiced Bavarian cream cheese) with radish and pretzel','complement','Paulaner Hefeweizen bridges the Obatzda and radish; a classic Biergarten pairing of Bavarian white beer and spiced cheese','casual','classic',1),
(585,'Paulaner Hefeweizen, yeasty, refreshing','casual','Grilled chicken (Hendl) with lemon and herbs at the Biergarten','complement','Paulaner''s refreshing Hefeweizen bridges the grilled chicken; Bavaria''s Biergarten classic of wheat beer and rotisserie fowl','casual','classic',1),
(585,'Paulaner Hefe-Weißbier, citrus, yeast','seafood','Steamed Bavarian river trout with herbs and lemon butter','complement','Paulaner Hefe-Weißbier''s yeast and citrus bridges the river trout; a Bavarian wheat beer for the Bavarian river fish tradition','fish_course','established',2),
(585,'Paulaner Hefeweizen, summer, casual','casual','Roast pork (Schweinsbraten) with Knödel and red cabbage','complement','Paulaner Hefeweizen''s body and carbonation bridges the Sunday Schweinsbraten; the wheat beer tradition at a Bavarian Wirtshaus','main','classic',2),
(585,'Paulaner Hefe, banana-clove, complex','dessert','Dampfnudeln (steamed yeast dumplings) with vanilla sauce','complement','Paulaner Hefe-Weißbier''s yeast and vanilla bridges the Dampfnudeln; both are Bavarian yeast traditions side by side','dessert','classic',1),

-- Schneider Weisse Aventinus (586)
(586,'Schneider Aventinus, Weizen-Doppelbock, strong wheat','casual','Krustenbraten (crispy roast pork) with Dunkelbrot and mustard','complement','Aventinus''s Weizen-Doppelbock intensity bridges the Krustenbraten; a powerful wheat beer for a substantial Bavarian pork','main','classic',1),
(586,'Schneider Tap 6, dark wheat doppelbock','cheese','Aged Emmental (18-month) with crusty bread and sweet mustard','complement','Aventinus''s rich dark wheat bridges the aged Emmental; a strong Bavarian wheat for an Alpine dairy tradition','cheese','established',2),
(586,'Schneider Aventinus, complex, dark fruit','casual','Beef goulash with Semmelknödel and sour cream','complement','Aventinus''s dark wheat complexity bridges the beef goulash; a Bavarian strong wheat beer for the paprika stew tradition','main','classic',1),
(586,'Weizen-Doppelbock, Aventinus, malt-forward','dessert','Schokoladensoufflé with dark wheat beer reduction and vanilla','complement','Aventinus''s dark wheat depth bridges the chocolate soufflé; using the beer in the reduction creates a Bavaria loop','dessert','established',2),
(586,'Aventinus, strong, German wheat tradition','casual','Leberkäse (Bavarian meatloaf) with fried egg and potato salad','complement','Aventinus''s robust character bridges the Leberkäse; a powerful wheat beer for Bavaria''s hearty lunch tradition','casual','classic',1),
(586,'Schneider Aventinus, celebration','casual','Wild mushroom (Pfifferling chanterelle) risotto with Parmesan and herbs','complement','Aventinus''s complexity bridges the chanterelle risotto; a prestige Bavarian wheat for an earthy forest mushroom dish','main','established',2),

-- Paulaner Salvator Doppelbock (584)
(584,'Paulaner Salvator, Doppelbock, Munich, strong lager','casual','Leberkäse (Bavarian meatloaf) with sweet mustard and a fried egg','complement','Paulaner Salvator and Leberkäse is Munich''s defining Doppelbock pairing; the strong lager for the hearty Bavarian snack','casual','classic',1),
(584,'Paulaner Salvator, malt-forward, dark, Munich','casual','Pork knuckle (Schweinshaxe) with sauerkraut and Bavarian mustard','complement','Salvator''s malt richness bridges the Schweinshaxe; a Doppelbock tradition since the monks of Saint Francis de Paula brewed it','main','classic',1),
(584,'Paulaner Salvator, sweet malt, lager','cheese','Aged Allgäu Emmental with dark mustard and rye sourdough','complement','Salvator''s malt sweetness bridges the aged Allgäu Emmental; a Munich strong lager for the Bavarian Alpine cheese tradition','cheese','established',2),
(584,'Salvator, strong, malt, traditional','casual','Roast pork Schweinsbraten with dark Doppelbock glaze','complement','Paulaner Salvator bridges the Schweinsbraten glaze; braising the pork in the beer and serving it alongside creates unity','main','classic',1),
(584,'Paulaner Salvator, Starkbier, celebration','casual','Bavarian Pretzelknödel (bread dumpling) with ham and mustard','complement','Salvator Doppelbock''s richness bridges the bread dumpling and ham; a Starkbier tradition for the Bavarian bread heritage','casual','established',2),
(584,'Paulaner Salvator, spring beer, seasonal','dessert','Bavarian cream (Bayerische Creme) with strawberry compote','complement','Salvator''s caramel malt bridges the Bavarian cream; a classic Munich Starkbier season dessert pairing','dessert','established',2),

-- Ayinger Celebrator (587)
(587,'Ayinger Celebrator, Doppelbock, Bavarian','casual','Smoked ham hock (Eisbein) with pea purée and mustard sauce','complement','Ayinger Celebrator''s dark malt bridges the smoked ham hock; a Bavarian Doppelbock for a Bavarian smoked pork classic','main','classic',1),
(587,'Celebrator, dark malt, toffee, Bavaria','cheese','Cambozola (German blue-brie) with pear and dark rye bread','complement','Celebrator''s toffee malt bridges the Cambozola; a Bavarian Doppelbock for a Bavarian blue-brie tradition','cheese','established',2),
(587,'Ayinger Celebrator, rich, sweet lager','casual','Kasspatzen (Bavarian cheese spaetzle) with fried onions and Alpine cheese','complement','Celebrator''s richness bridges the Käsespätzle; both are expressions of Bavarian Alpine comfort','casual','classic',1),
(587,'Celebrator, Ayinger, dark strong lager','casual','Zwiebelrostbraten (Austrian onion roast beef) with spaetzle','complement','Celebrator''s dark malt bridges the Zwiebelrostbraten; a Bavarian Doppelbock for the Austrian-Bavarian border table','main','classic',2),
(587,'Ayinger Celebrator, malt-forward, celebration','dessert','Bienenstich (bee sting cake) with vanilla custard and almond','complement','Celebrator''s malt sweetness bridges the Bienenstich''s honey and almond; a Bavarian strong lager for a Bavarian café classic','dessert','classic',1),
(587,'Celebrator, food-friendly, deep lager','game','Hirschgulasch (venison goulash) with Semmelknödeln and Preiselbeeren','complement','Ayinger Celebrator''s dark complexity bridges the venison goulash; a Bavarian Doppelbock for a Bavarian forest game tradition','main','classic',1),

-- Agave spirits (534-536)
(534,'Don Julio 1942, Añejo, aged tequila, luxury','casual','A5 Wagyu tacos al pastor with pineapple and cilantro','complement','Don Julio 1942''s aged oak complexity bridges the Wagyu tacos; a luxury tequila for a luxury Mexican taco preparation','casual','established',2),
(534,'Don Julio 1942, Jalisco, cooked agave','casual','Cochinita pibil (slow-roasted Yucatan pork) with habanero relish','complement','Don Julio 1942''s aged character bridges the cochinita pibil''s achiote and citrus; a prestige tequila for a Yucatan classic','main','classic',1),
(534,'Don Julio 1942, aged, caramel oak','dessert','Tres leches cake with Añejo caramel reduction and Mexican cinnamon','complement','Don Julio 1942''s caramel oak bridges the tres leches; a Mexican spirit for a Mexican celebration dessert','dessert','established',2),
(534,'Don Julio 1942, Añejo, premium, smooth','casual','Queso fundido (melted cheese) with chorizo and warm tortillas','complement','Don Julio 1942''s smooth oakiness bridges the queso fundido''s richness; a luxury tequila for a decadent Mexican snack','casual','established',2),
(534,'Don Julio 1942, celebration, prestige','casual','Smoked brisket tacos with pickled red onion and crema fresca','complement','Don Julio 1942''s aged depth bridges the smoked brisket; a celebration tequila for a celebration taco','casual','established',2),
(534,'Don Julio 1942, luxury, aged agave','casual','Guacamole tableside with pomegranate, pepitas and chips','complement','Don Julio 1942 pairs with the premium guacamole service; an aged tequila for Mexico''s most beloved condiment at its finest','casual','established',2),

(535,'Clase Azul Reposado, artisanal, luxury tequila','casual','Chiles en nogada (stuffed poblano with walnut cream and pomegranate)','complement','Clase Azul Reposado''s crafted complexity bridges the chiles en nogada; both are expressions of Mexican artisanal luxury','main','classic',1),
(535,'Clase Azul Reposado, aged, hand-crafted','casual','Carnitas (slow-confit pork) with pickled jalapeño and handmade tortillas','complement','Clase Azul''s smooth agave bridges the carnitas; a premium tequila for Mexico''s slow-cooked pork tradition','casual','established',2),
(535,'Clase Azul, Jalisco, premium, reposado','dessert','Flan napolitano with cajeta (goat milk caramel) and cinnamon','complement','Clase Azul''s oak-vanilla bridges the flan napolitano and cajeta; a Mexican artisan spirit for a Mexican artisan dessert','dessert','established',2),
(535,'Clase Azul Reposado, smooth, barrel aged','cheese','Oaxacan quesillo (string cheese) with pickled pasilla and tortilla','complement','Clase Azul''s smooth oak bridges the fresh Oaxacan quesillo; a luxury tequila for Oaxaca''s most artisan dairy','casual','established',2),
(535,'Clase Azul, heritage, Mexico artisan','casual','Tamales de rajas (chilli and cheese tamales) with sour cream','complement','Clase Azul Reposado''s crafted elegance bridges the rajas tamales; a luxury spirit for Mexico''s festive wrapped tradition','casual','established',2),
(535,'Clase Azul Reposado, celebration, Mexico','casual','Ceviche de camarón (shrimp ceviche) with mango and serrano','complement','Clase Azul''s clean agave bridges the shrimp ceviche; a premium tequila for Mexico''s Pacific coast ceviche tradition','starter','established',2),

(536,'El Silencio, Espadin Mezcal, Oaxaca, smoky','casual','Tlayuda (large Oaxacan crispy tortilla) with black bean, chapulines and quesillo','complement','El Silencio Espadin''s smoke bridges the tlayuda; an Oaxacan mezcal for Oaxaca''s largest signature street food','casual','established',2),
(536,'mezcal, Espadin, smoky, Oaxaca, accessible','casual','Tacos de lengua (beef tongue) with tomatillo salsa and cilantro','complement','El Silencio''s smoke bridges the beef tongue taco''s richness; a mezcal''s earthy smoke for slow-braised offal tacos','casual','established',2),
(536,'El Silencio Mezcal, smoke, agave, accessible','casual','Grilled elote (corn on cob) with cotija, chilli and lime butter','complement','El Silencio''s smoke bridges the grilled corn; mezcal and fire-roasted corn are the flavour languages of Oaxacan street life','casual','established',2),
(536,'mezcal, accessible, smoky, green','casual','Guacamole with charred jalapeño and mezcal-soaked tequila cherry','complement','El Silencio Espadin''s smoke bridges the charred jalapeño guacamole; the mezcal note extends naturally into the charred preparation','casual','established',2),
(536,'El Silencio, Oaxacan mezcal, smoke','casual','Mole negro (black mole) with chicken and Oaxacan tortillas','complement','El Silencio''s smoke bridges the mole negro''s deep complexity; a mezcal for Oaxaca''s most complex sauce tradition','main','classic',1),
(536,'mezcal, Espadin, smoke, everyday','casual','Quesabirria tacos (birria beef with consommé dipping) with cheese','complement','El Silencio''s smoke bridges the birria''s guajillo spice richness; mezcal for Mexico''s most popular street food revival','casual','established',2),

-- Armagnac (588-589)
(588,'Tariquet Bas-Armagnac 12-Year, aged, Gascony','cheese','Roquefort AOP with honey and walnut bread','bridge','Tariquet 12-Year''s Gascon depth bridges the Roquefort''s salt; a classic Gascony pairing of armagnac and sheep blue','cheese','classic',1),
(588,'Tariquet, armagnac, Bas-Armagnac, aged','dessert','Tarte aux pruneaux (Armagnac prune tart) with crème fraîche','complement','Tariquet 12-Year''s Armagnac belongs with the prune tart; the prunes are often macerated in Armagnac itself','dessert','classic',1),
(588,'Tariquet Bas-Armagnac 12, Gascony, caramel','casual','Garbure gasconne (Gascon vegetable and duck ham soup) with confit','complement','Tariquet''s Gascon character bridges the garbure; both come from the same Gers terroir of duck and grain','casual','classic',1),
(588,'Tariquet, aged, French brandy, rustic','casual','Canard à la Gasconne (Gascon roast duck) with pommes sarladaises','complement','Tariquet 12-Year''s Gascony origin bridges the Gascon roast duck; the region''s spirit for the region''s most beloved bird','main','classic',1),
(588,'Tariquet Bas-Armagnac, oak, Folle Blanche','casual','Foie gras entier with brioche and Armagnac jelly','complement','Tariquet''s Bas-Armagnac belongs with the foie gras entier; the Armagnac jelly on the foie gras is a Gascon tradition','starter','classic',1),

(589,'Tariquet Folle Blanche, single grape, pure','dessert','Baba au rhum (Armagnac baba) with Chantilly cream','complement','Tariquet Folle Blanche''s pure Gascon character bridges the Armagnac baba; the baba soaked in the same Armagnac makes it whole','dessert','classic',1),
(589,'Tariquet Folle Blanche, Bas-Armagnac, fresh','cheese','Comté 24-month with Armagnac-soaked raisins and dark rye','complement','Folle Blanche''s fresh Armagnac character bridges the aged Comté; the raisin maceration creates a direct armagnac-cheese bridge','cheese','classic',1),
(589,'Tariquet single grape, Folle Blanche, Gascony','casual','Gâteau basque (Basque cream tart) with pastry cream and cherry jam','complement','Folle Blanche''s clean Gascon freshness bridges the gâteau basque; the Basque borders the Gascon tradition','dessert','established',2),
(589,'Folle Blanche, pure, unaged-style, mineral','casual','Terrine de campagne (country pork terrine) with cornichons and sourdough','complement','Tariquet Folle Blanche''s freshness bridges the country terrine; a clean Gascon brandy for the Gascon charcuterie table','starter','established',2),
(589,'Tariquet Folle Blanche, single varietal, aged','casual','Pruneaux à l''Armagnac (prunes macerated in Armagnac) with vanilla cream','complement','Folle Blanche''s Bas-Armagnac bridges the macerated prunes; drinking the spirit used to macerate the fruit is a flavour loop','dessert','classic',1),

-- Rum (513-518)
(513,'Foursquare, Barbados, pot still, Exceptional Cask','cheese','Aged Montgomery Cheddar with Barbados sugar cane honey and dark bread','complement','Foursquare Exceptional Cask''s Barbados refinement bridges the aged Montgomery Cheddar; the cane sugar connects wine and cheese','cheese','established',2),
(513,'Foursquare rum, complex, double pot still','casual','Jerk chicken with Scotch bonnet, allspice and lime over rice and peas','complement','Foursquare''s Caribbean complexity bridges the jerk chicken''s Scotch bonnet heat; a Barbados rum for a Caribbean tradition','main','classic',1),
(513,'Foursquare, exceptional cask, oak aged','dessert','Dark rum and raisin bread pudding with Barbados rum sauce','complement','Foursquare Exceptional Cask in the bread pudding sauce creates direct unity; Barbados rum for a rum sauce tradition','dessert','classic',1),
(513,'Foursquare Exceptional, luxury rum, Barbados','casual','Ceviche de cangrejo (crab ceviche) with citrus and Caribbean herbs','complement','Foursquare''s elegant Barbados character bridges the crab ceviche; a prestige rum for a tropical Caribbean coast starter','starter','established',2),
(513,'Foursquare, prestige, Barbados cane','casual','Conch fritters with Caribbean hot sauce and lime aioli','complement','Foursquare''s pot still depth bridges the conch fritter; a Barbadian rum for the Caribbean''s signature shellfish snack','casual','established',2),
(513,'Foursquare Exceptional Cask, aged, complex','casual','Slow-roasted pork shoulder (lechón) with mojo criollo and plantains','complement','Foursquare''s complex oak bridges the lechón and mojo; Barbados rum for the Caribbean''s most celebratory pig roast','main','established',2),

(514,'Mount Gay XO, Barbados, oldest rum, complex','casual','Coconut shrimp with Creole dipping sauce and mango salsa','complement','Mount Gay XO''s aged Barbados complexity bridges the coconut shrimp; the world''s oldest rum for a tropical Caribbean bite','casual','classic',1),
(514,'Mount Gay XO, triple cask, sophisticated','cheese','Aged Mimolette 18-month with dark cherry conserve','complement','Mount Gay XO''s rich oak bridges the aged Mimolette''s nutty intensity; both require time to develop their character','cheese','established',2),
(514,'Mount Gay XO, Barbados, heritage rum','casual','Rum cake (black cake) with Barbadian cherries and Angostura bitters','complement','Mount Gay XO''s Barbados tradition bridges the black cake; the rum used in the cake and drunk alongside is Barbadian celebration','dessert','classic',1),
(514,'Mount Gay XO, sophisticated, aged 8-15yr','casual','Flying fish (Barbados national dish) with cou-cou and pickled cucumber','complement','Mount Gay XO''s Barbados heritage bridges the flying fish cou-cou; both are national expressions of Barbadian food culture','main','classic',1),
(514,'Mount Gay XO, luxury, oak, raisin','casual','Pineapple upside-down cake with rum caramel and vanilla','complement','Mount Gay XO''s caramel oak bridges the pineapple upside-down cake; a Caribbean rum for a Caribbean tropical dessert','dessert','established',2),
(514,'Mount Gay XO, complex, chocolate, tobacco','casual','Escovitch fish (Jamaican pickled fried fish) with onion and Scotch bonnet','complement','Mount Gay XO''s complexity bridges the escovitch''s vinegar and spice; both are the Caribbean''s most characterful preparations','casual','established',2),

(515,'Hampden Estate, Jamaica, high ester, funk','casual','Jamaican beef patties (beef and thyme in flaky pastry)','complement','Hampden''s high-ester funk bridges the Jamaican beef patty''s spicy warmth; a pot still rum for Jamaica''s most beloved snack','casual','classic',1),
(515,'Hampden Great House, pot still, dunder, funky','casual','Jerk pork with pimento wood smoke and Festival bread','complement','Hampden''s HLCF ester funk bridges the jerk pork''s allspice smoke; Jamaica''s most characterful rum for Jamaica''s defining dish','main','classic',1),
(515,'Hampden, high ester, pot still, complex','cheese','Aged Jamaican Blue Mountain coffee-rubbed aged cheddar','complement','Hampden Estate''s funkiness bridges the coffee-rubbed aged cheddar; Jamaica''s rum and Jamaica''s most famous export as cheese bridge','cheese','adventurous',2),
(515,'Hampden Estate, rum, Jamaica, celebration','casual','Rum punch (Jamaican bush bar recipe) with lime and nutmeg','complement','Hampden''s funky pot still belongs in a proper rum punch; the traditional Jamaican recipe showcases the rum''s complexity','casual','classic',1),
(515,'Hampden Great House, distillery edition, rare','casual','Curried goat with scotch bonnet, thyme and rice and peas','complement','Hampden''s intensity bridges the curried goat''s complexity; a Jamaican estate rum for Jamaica''s most beloved curry tradition','main','classic',1),
(515,'Hampden, ester-forward, wild ferment','dessert','Dark rum sticky toffee pudding with Jamaican rum sauce','complement','Hampden''s funky rum in the sticky toffee sauce creates an island tradition; a powerful pairing of ester and caramel','dessert','established',2),

(516,'Neisson Rhum Agricole Blanc, Martinique, sugarcane','seafood','Accras de morue (Martinique salt cod fritters) with chilli sauce','complement','Neisson Rhum Agricole Blanc''s pure cane bridges the salt cod accras; a Martinique AOC rhum for a Martinique favourite','casual','classic',1),
(516,'Neisson, Martinique AOC, agricole, dry','casual','Ti punch (Martinique rum punch with lime and cane syrup)','complement','Neisson Blanc is the rhum agricole for ti punch; Martinique''s AOC rhum for the island''s defining drink and its food pairings','casual','classic',1),
(516,'Neisson Rhum Blanc, fresh, cane, grassy','seafood','Boudin créole (Martinique blood sausage with chilli) with plantain','complement','Neisson''s fresh cane character bridges the boudin créole''s spice; a pure cane spirit for Martinique''s most beloved charcuterie','casual','classic',1),
(516,'Neisson Agricole Blanc, pure, Martinique','seafood','Grilled dorade (sea bream) with citrus, herbs and Martinique sea salt','complement','Neisson''s clean cane bridges the grilled dorade; a Martinique rhum for the island''s own Atlantic fishing tradition','fish_course','established',2),
(516,'Neisson, high proof, cane, fresh','seafood','Ceviche of Martinique flying fish with lime, chilli and microherbs','complement','Neisson Blanc''s clean cane acidity bridges the flying fish ceviche; a pure Martinique rhum for a Caribbean citrus tradition','starter','established',2),
(516,'Neisson Rhum Blanc, Martinique, AOC','casual','Colombo de poulet (Martinique curried chicken) with rice créole','complement','Neisson''s pure cane bridges the colombo''s curry spice; a Martinique rhum for Martinique''s most beloved hybrid curry dish','main','classic',1),

(517,'El Dorado 15-Year, Demerara, Guyana, complex','casual','Pepperpot stew (Guyanese Christmas dish) with cassava bread','complement','El Dorado 15-Year''s Demerara complexity bridges the pepperpot''s dark bitter cassareep richness; Guyana''s rum for Guyana''s Christmas','main','classic',1),
(517,'El Dorado, Demerara, aged 15yr, molasses','cheese','Aged Gouda (5-year Boerenkaas) with muscovado sugar and dark nuts','complement','El Dorado 15-Year''s Demerara richness bridges the aged Boerenkaas; the molasses note bridges the caramel Dutch cheese','cheese','established',2),
(517,'El Dorado 15, Guyana, tropical, wooden still','dessert','Guyana black cake with Demerara rum-soaked fruits and burnt sugar','complement','El Dorado 15-Year''s Demerara character belongs in the black cake; the rum used in the fruit soak and drunk alongside','dessert','classic',1),
(517,'El Dorado 15, complex, vanilla oak','casual','Garlic pork (Guyanese Christmas garlic pork) with roti flatbread','complement','El Dorado''s oak depth bridges the garlic pork''s vinegar and spice; a Guyanese rum for a Guyanese holiday tradition','casual','established',2),
(517,'El Dorado, Demerara, caramel, long-aged','casual','Jerk chicken wings with Guyanese pepper sauce and coconut rice','complement','El Dorado 15-Year''s caramel warmth bridges the jerk wings; a Caribbean rum with Caribbean heat and tropical flavours','casual','established',2),
(517,'El Dorado 15, heritage, Guyana rum estate','casual','Peach cobbler with Demerara sugar and rum cream','complement','El Dorado 15-Year''s Demerara caramel bridges the peach cobbler; a rum with the same sugar as the topping','dessert','established',2),

(518,'Appleton Estate 12-Year Rare Casks, Jamaica','casual','Brown stew chicken (Jamaican) with Scotch bonnet and allspice rice','complement','Appleton Estate 12-Year''s Jamaica complexity bridges the brown stew chicken; an island rum for an island comfort dish','main','classic',1),
(518,'Appleton 12, Jamaica, orange, spice, oak','dessert','Rum cake with Jamaican Appleton 12 soak and candied orange','complement','Appleton 12-Year in the rum cake creates a direct flavour loop; the orange character bridges both the cake and the rum','dessert','classic',1),
(518,'Appleton Estate, aged, Jamaican rum','casual','Jerk chicken with pimento wood coal and bammy (cassava cake)','complement','Appleton 12-Year''s Jamaica warmth bridges the jerk chicken; a Nassau Valley rum for the island''s defining grilled preparation','main','classic',1),
(518,'Appleton 12 Rare Casks, prestige, Jamaica','cheese','Aged Mimolette 24-month with rum raisin and walnut','complement','Appleton 12-Year''s complex rum bridges the aged Mimolette; the rum-soaked raisin echoes the Jamaican rum''s own dried fruit','cheese','established',2),
(518,'Appleton Estate 12, celebration, Jamaican','casual','Ackee and saltfish (Jamaica''s national dish) with fried dumplings','complement','Appleton Estate 12-Year belongs with Jamaica''s national dish; the island''s aged rum for the island''s defining breakfast tradition','casual','classic',1),
(518,'Appleton 12, warm spice, oak, cane','casual','Oxtail stew with butter beans and Jamaican scotch bonnet','complement','Appleton 12-Year''s warm spice bridges the oxtail stew''s collagen richness; Jamaican rum for Jamaica''s richest comfort food','main','classic',1)
;
COMMIT;
