BEGIN;
INSERT INTO pairing_intelligence
  (beverage_product_id, food_flavour_profile, food_category, food_description, pairing_type, flavour_logic, meal_context, confidence, authority_tier)
VALUES
-- 481 F.X. Pichler Dürnsteiner Kellerberg Grüner Veltliner Smaragd (Wachau, dry, complex)
(481,'GV, Smaragd, Wachau, white pepper','seafood','Wiener Schnitzel with lingonberry jam and potato cucumber salad','complement','FX Pichler''s Kellerberg GV Smaragd is the classic Schnitzel pairing; the white pepper notes bridge the breaded veal','main','classic',1),
(481,'asparagus, Austrian, spring classic','vegetable','White asparagus with Sauce Hollandaise and Viennese ham','complement','Grüner Veltliner and Austrian white asparagus is the nation''s defining spring pairing; both grown in the same Danube valley','starter','classic',1),
(481,'river fish, Danube, trout','fish','Grilled Danube pike-perch (Zander) with lemon butter sauce','complement','FX Pichler Kellerberg GV''s Wachau terroir pairs with Danube river fish; the riverbank vineyard and the river fish share a home','fish_course','classic',1),
(481,'seafood, versatile, mineral','seafood','Pacific oysters with ponzu and cucumber mignonette','cleanse','Pichler Smaragd''s mineral depth cleanses after oysters; the white pepper note creates a refreshing edge','starter','established',2),
(481,'sushi, Japanese, Austrian','seafood','Sashimi platter with tuna, salmon and yellowtail','complement','FX Pichler GV Smaragd is Austria''s answer to top white Burgundy; its mineral depth bridges delicate sashimi','fish_course','established',2),
(481,'cheese, soft, Austrian','cheese','Bergkäse (Alpine mountain cheese) with dark bread and butter','complement','Kellerberg GV''s mineral structure bridges the Alpine Bergkäse; both come from the same Austrian mountain tradition','cheese','established',2),
(481,'pork, roast, Austrian','pork','Tafelspitz (boiled beef) with chive sauce and apple horseradish','complement','FX Pichler GV Smaragd is Vienna''s greatest white wine companion; Tafelspitz is Vienna''s national dish','main','classic',1),

-- 482 Emmerich Knoll Loibner Ried Loibenberg Riesling Smaragd (Wachau, dry, mineral)
(482,'Riesling, Wachau, Smaragd, mineral, Knoll','seafood','Lobster with butter beurre blanc and fresh herbs','elevate','Emmerich Knoll Loibenberg Riesling Smaragd elevates lobster; the Wachau granite mineral and the lobster sweetness align','fish_course','classic',1),
(482,'Austrian, fish, Danube, classic','fish','Grilled Danube catfish (Wels) with lemon and capers','complement','Knoll Loibenberg''s Danube terroir pairs with the Danube catfish; both are expressions of the Wachau''s river culture','fish_course','classic',1),
(482,'Wiener Schnitzel, Austrian, heritage','veal','Wiener Schnitzel with lemon and Viennese potato salad','complement','A great Wachau Riesling Smaragd belongs with the finest Wiener Schnitzel; both represent Austria''s culinary heritage','main','classic',1),
(482,'pork, Austrian, complex','pork','Zwiebelrostbraten (Austrian roast beef with onions) with spaetzle','complement','Knoll''s complex Riesling Smaragd bridges the rich beef and onion preparation; spaetzle absorbs the wine''s flavour','main','established',2),
(482,'spice, Asian, mineral bridge','spicy','Pad Thai with tiger prawns, tamarind and peanuts','bridge','Wachau Riesling Smaragd''s mineral depth bridges Pad Thai''s sweet-sour complexity; Austrian Riesling and Thai food affinity','main','established',2),
(482,'cheese, Austrian alpine, aged','cheese','Vorarlberger Bergkäse with dark bread and apple mustard','complement','Loibenberg''s Riesling mineral bridges the Alpine Bergkäse; Vorarlberg cheese and Wachau wine share Austrian patrimony','cheese','classic',2),
(482,'dessert, moderate, Austrian','dessert','Apfelstrudel mit Sahne und Vanillesauce','complement','Wachau Riesling Smaragd''s apple and mineral character bridges the apple strudel; the dessert and the wine share the apple register','dessert','classic',2),

-- 483 Bründlmayer Zöbinger Heiligenstein Riesling (Kamptal, volcanic, complex)
(483,'Kamptal, Heiligenstein, Riesling, volcanic','seafood','Dover sole meunière with brown butter, lemon and capers','complement','Bründlmayer Heiligenstein''s volcanic Kamptal mineral bridges Dover sole; the lemon beurre bridges the wine''s own citrus','fish_course','classic',1),
(483,'Austrian cuisine, Riesling, Zöbing','fish','Truite au bleu (poached trout in court bouillon) with Hollandaise','complement','Heiligenstein Riesling''s volcanic mineral bridges the poached trout; the Hollandaise''s richness is cut by the wine''s acidity','fish_course','classic',1),
(483,'spicy, Indian, off-dry style','spicy','Butter chicken (murgh makhani) with basmati rice and naan','bridge','Bründlmayer Riesling''s complexity bridges the butter chicken''s spice and cream; Riesling is the world''s spice food wine','main','established',2),
(483,'sushi, delicate, Austrian','seafood','Sushi omakase — chef''s seasonal selection','complement','Heiligenstein''s volcanic depth and purity bridges the sushi omakase; an Austrian Riesling for the Japanese table','fish_course','adventurous',2),
(483,'asparagus, spring, Austria','vegetable','Green asparagus with poached egg, hollandaise and bottarga','complement','Bründlmayer Heiligenstein pairs with the spring asparagus tradition; the bottarga echoes the wine''s mineral depth','starter','established',2),
(483,'cheese, Kamptal, Austrian','cheese','Fresh Ziegenfrischkäse (Austrian goat cheese) with honey and walnuts','complement','Heiligenstein''s mineral character bridges the fresh goat cheese; both come from the Austrian winemaking regions','starter','established',2),
(483,'dessert, restrained, clean','dessert','Grapefruit granita with elderflower and fresh mint','complement','Bründlmayer''s mineral and citrus character bridges the grapefruit granita; a clean Alpine refreshment pairing','pre_dessert','established',2),

-- 484 Bründlmayer Langenlois Lamm Grüner Veltliner Reserve (Kamptal, rich, complex GV)
(484,'GV, Lamm, Kamptal, Reserve, complex','seafood','Grilled Adriatic langoustines with herb butter and saffron','complement','Bründlmayer Lamm GV Reserve''s rich Kamptal depth bridges the langoustines; the saffron echoes the wine''s warm complexity','fish_course','classic',1),
(484,'Austrian, pork, traditional','pork','Schweinsbraten (Austrian roast pork) with Semmelknödel and sauerkraut','complement','Lamm GV Reserve''s Kamptal richness suits the Austrian roast pork tradition; a classic Austrian Sunday lunch pairing','main','classic',1),
(484,'Austrian asparagus, spring, classic','vegetable','White asparagus with Tiroler Speck and Hollandaise sauce','complement','Bründlmayer''s GV Reserve is Kamptal''s spring asparagus partner; adding Tiroler Speck brings the Alpine elevation','starter','classic',1),
(484,'Schnitzel, heritage, Austria','veal','Wiener Backhendl (Viennese fried chicken) with potato salad','complement','Lamm GV Reserve''s rich Kamptal character suits the fried chicken as well as Schnitzel; Austria''s white wine for fried meats','main','classic',2),
(484,'Asian, spice, GV versatile','spicy','Japanese tonkatsu with cabbage slaw and tonkatsu sauce','bridge','GV Reserve''s pepper and mineral bridges the tonkatsu; Austrian Grüner Veltliner has a natural affinity with Japanese fried dishes','main','established',2),
(484,'cheese, aged, complex','cheese','Aged Gruyère de Comté with quince and dark bread','complement','Lamm GV Reserve''s complexity bridges aged Gruyère; the Kamptal terroir and the Swiss Alpine cheese share depth','cheese','established',2),
(484,'dessert, elegant, Austrian','dessert','Linzer Torte with raspberry jam and almond pastry','complement','Kamptal GV Reserve''s warm character bridges the Austrian Linzer Torte; a national dessert with its national wine','dessert','classic',2),

-- 485 Moric Lutzmannsburg Alte Reben Blaufränkisch (Burgenland, red, mineral, old vines)
(485,'Blaufränkisch, Burgenland, mineral, red','lamb','Lammrücken mit Kräuterkruste und Jus (lamb rack with herb crust)','complement','Moric Alte Reben Blaufränkisch''s mineral depth bridges the herb-crusted lamb; Burgenland old-vine red and Austrian lamb','main','classic',1),
(485,'Austrian red, game, Burgenland','game','Rotwild (red deer) im Wacholdersud mit Rotkraut und Knödeln','complement','Moric''s mineral Blaufränkisch bridges red deer with juniper; a classic Austrian game and red wine tradition','main','classic',1),
(485,'beef, Austrian, traditional','beef','Gulasch vom Ochsen mit Semmelknödeln — beef goulash','complement','Blaufränkisch and beef goulash is Austria''s most traditional pairing; the wine''s mineral acidity bridges the paprika-spiced stew','main','classic',1),
(485,'duck, Austrian, complex','duck','Ente à la sauce Burgenland mit Kraut und Erdäpfeln (duck with sauerkraut)','complement','Moric Alte Reben''s Burgenland character bridges the regional duck preparation; old vines demand old cooking traditions','main','classic',2),
(485,'cheese, Austrian, washed rind','cheese','Rotschmierkäse (Austrian red-washed rind) with dark sourdough','complement','Blaufränkisch''s mineral structure bridges the pungent washed rind; the red mold bridges the red wine tradition','cheese','established',2),
(485,'venison, Austrian, forest','game','Rehschnitzel mit Preiselbeersauce und Pilzen (venison cutlet with lingonberry)','complement','Moric''s old vine mineral bridges the delicate venison and lingonberry; a Burgenland forest and vineyard pairing','main','classic',2),
(485,'risotto, Austrian style','rice','Buschenschank-style risotto with Burgenland pumpkin and cheese','complement','Alte Reben Blaufränkisch''s earthiness bridges the pumpkin risotto; Burgenland''s oil pumpkin is the local vegetable treasure','main','established',2),

-- 486 Umathum Hallebühl Blaufränkisch (Burgenland, concentrated, Neusiedlersee)
(486,'Blaufränkisch, Umathum, Neusiedlersee, concentrated','beef','Roastbeef vom Rind mit Kräuterjus und Erdäpfelsalat','complement','Umathum Hallebühl''s Neusiedlersee power bridges the roast beef; Burgenland''s lake climate gives the wine its concentration','main','classic',1),
(486,'game, Austrian, dark berries','game','Wildschweingulasch mit Semmelknödeln und Preiselbeeren (wild boar)','complement','Umathum''s concentrated Blaufränkisch bridges wild boar goulash; the dark berry fruit matches the gamey depth','main','classic',2),
(486,'lamb, Austrian, herb','lamb','Niederösterreichisches Lammkarree mit Kräutern und Jus','complement','Hallebühl''s power suits the Austrian lamb rack; Niederösterreich lamb and Burgenland wine share the Austrian plains','main','established',2),
(486,'cheese, aged, concentrated','cheese','Aged Bergkäse mit Mostsenf und Kürbiskernöl (with pumpkin seed oil)','complement','Umathum''s concentration bridges the aged Bergkäse; Styrian pumpkin seed oil bridges the Austrian wine and cheese','cheese','established',2),
(486,'goulash, Viennese, paprika','beef','Wiener Saftgulasch (Viennese beef goulash) mit Semmelknödel','complement','Umathum Hallebühl Blaufränkisch and Vienna''s Saftgulasch is a national pairing institution; paprika beef and Burgenland red','main','classic',1),
(486,'venison, hunter''s preparation, forest','game','Hirsch in Jägerart mit Steinpilzen und Rotkraut (hunter''s venison)','complement','Hallebühl''s concentration bridges the hunter''s venison with porcini; a Burgenland red for the Austrian forest table','main','classic',2),
(486,'duck, Neusiedlersee, festive','duck','Burgenland Ente mit Äpfeln und Rotkraut (duck with apple and red cabbage)','complement','Umathum''s Neusiedlersee character bridges the Burgenland duck tradition; apple and red cabbage echo the wine''s fruit','main','classic',1);
COMMIT;
