BEGIN;
INSERT INTO pairing_intelligence
  (beverage_product_id, food_flavour_profile, food_category, food_description, pairing_type, flavour_logic, meal_context, confidence, authority_tier)
VALUES
-- 487 Quinta do Vale Meão (Douro Superior, red, premium)
(487,'Douro, Vale Meão, premium red','lamb','Borrego assado à transmontana (slow-roasted lamb) with wild herbs','complement','Quinta do Vale Meão''s Douro Superior terroir and the mountain lamb belong together; both come from Trás-os-Montes''s high altitude','main','classic',1),
(487,'bacalhau, salt cod, Portuguese classic','seafood','Bacalhau à Brás (shredded salt cod with eggs and potato crisps)','complement','Vale Meão''s structured Douro red bridges the salt cod''s cured intensity; a Portuguese icon wine with Portugal''s national dish','main','established',2),
(487,'game, Alto Douro, terroir','game','Javali (wild boar) estufado with olive oil and garlic','complement','Vale Meão''s Douro Superior character belongs with wild boar; the schist terroir and mountain game are inseparable','main','classic',1),
(487,'cheese, aged, Portuguese','cheese','Queijo da Serra da Estrela (washed rind sheep cheese) with quince jam','complement','Vale Meão''s structure bridges the Serra da Estrela''s pungent richness; quince jam softens the intensity','cheese','classic',2),
(487,'beef, slow-cooked, Douro','beef','Carne de vinha d''alhos (pork in garlic and wine marinade)','complement','Vale Meão''s tannin and fruit bridges the garlic-wine pork; using the same Douro grapes in the marinade echoes the glass','main','established',2),
(487,'celebration, port house, prestige','celebration','Bacalhau com todos — Christmas salt cod with potatoes and eggs','complement','Quinta do Vale Meão is a great Douro table wine; the Christmas bacalhau with all the trimmings is Portugal''s holiday tradition','celebration','classic',1),
(487,'duck, braised, Portuguese','duck','Arroz de pato (braised duck rice) with chouriço and olives','complement','Vale Meão''s Douro character bridges the rich duck rice and chouriço; a Portuguese Sunday lunch classic','main','classic',2),

-- 488 Niepoort Charme Tinto (Douro, elegant, Bastardo-based)
(488,'Douro, Niepoort, elegant, Bastardo','seafood','Percebes (barnacles) simply boiled with sea salt','complement','Niepoort Charme''s elegant Douro character pairs with the Atlantic barnacle; a contrast of inland wine and coastal seafood','starter','adventurous',2),
(488,'game, refined, Douro','game','Codorniz (quail) assada com migas de broa e bacon','complement','Charme''s elegant structure bridges the roasted quail with cornbread migas; a sophisticated Douro game pairing','main','classic',2),
(488,'lamb, Portuguese, mountain','lamb','Chanfana (slow-braised goat in red wine) with cornbread','complement','Niepoort Charme''s Douro elegance bridges the chanfana''s slow-braised intensity; the wine in the braise connects to the glass','main','classic',1),
(488,'cheese, elegant, Douro','cheese','Queijo de Azeitão (semi-soft sheep cheese) with black olives','complement','Charme''s refined Douro character bridges the delicate Azeitão; the olive''s bitterness is softened by the wine''s fruit','cheese','established',2),
(488,'pork, suckling, Bairrada adjacent','pork','Leitão da Bairrada (crispy suckling pig) with orange and garlic salt','complement','Niepoort''s elegant Douro red bridges the Bairrada suckling pig; a Douro wine for the neighbouring suckling pig tradition','main','established',2),
(488,'vegetable, Alentejo, migas','vegetable','Açorda de coentros (bread and coriander soup) with poached egg','complement','Charme''s mineral Douro character bridges the açorda''s coriander intensity; both are Portuguese soul food at different scales','casual','established',2),
(488,'beef, prestige, celebration','beef','Picanha at the Douro with garlic butter and salsa verde','complement','Niepoort Charme belongs with the Douro''s finest cuts; the riverbank vineyard and the quality beef share the same valley','main','established',2),

-- 489 Soalheiro Alvarinho Monção e Melgaço (Vinho Verde, white, aromatic)
(489,'Alvarinho, Monção, Vinho Verde, aromatic','seafood','Mariscos da Costa — Atlantic seafood platter with various shellfish','complement','Soalheiro Alvarinho''s vibrant aromatic character bridges the varied seafood; the mineral acidity cleanses between each shellfish','fish_course','classic',1),
(489,'bacalhau, white wine, fresh','seafood','Bacalhau à Gomes de Sá (salt cod with potato, onion and olives)','complement','Alvarinho''s bright acidity bridges the salt cod; a traditional white wine and bacalhau pairing from the Minho region','main','classic',1),
(489,'octopus, grilled, Galicia style','seafood','Polvo à lagareiro (oven-roasted octopus with olive oil and potatoes)','complement','Soalheiro''s Alvarinho character bridges the roasted octopus; a Minho wine with the region''s Atlantic seafood tradition','main','classic',1),
(489,'salada, fresh, light','seafood','Espetada de gambas (grilled prawn skewers with garlic and lemon)','complement','Alvarinho''s citrus brightness complements the grilled prawn; both express Atlantic coastal freshness','casual','established',2),
(489,'cheese, fresh, Portuguese','cheese','Queijo fresco (fresh cheese) with olive oil and herbs','complement','Soalheiro''s fresh mineral character bridges the simple fresh cheese; a Minho table''s casual pairing','casual','established',2),
(489,'sardines, grilled, Portuguese festival','fish','Sardinhas assadas (grilled sardines) with bread and lemon','complement','Vinho Verde Alvarinho and grilled sardines are the Portuguese summer festival pairing; Atlantic fish and Atlantic wine','casual','classic',1),
(489,'caldo verde, soup, Portuguese','vegetable','Caldo verde (kale soup with chouriço and potato)','complement','Soalheiro Alvarinho''s freshness bridges the comforting caldo verde; a Minho wine for the Minho''s national soup','casual','classic',2),

-- 490 Esporão Reserva Tinto (Alentejo, red, accessible, structured)
(490,'Alentejo, Esporão, Reserva, red, structured','pork','Porco preto à alentejana (Iberian black pork with clams and coriander)','complement','Esporão Reserva Tinto and porco preto à alentejana are Alentejo''s iconic pairing; the Iberian pig and the cork oak landscape','main','classic',1),
(490,'lamb, Alentejo, traditional','lamb','Borrego à alentejana (Alentejo-style lamb with olive oil and garlic)','complement','Esporão Reserva''s Alentejo warmth belongs with the regional lamb; an Alentejo terroir pairing of wine and pasture','main','classic',1),
(490,'game, migas, rustic','game','Ensopado de lebre (hare stew) with migas alentejanas','complement','Esporão Reserva''s structured Alentejo character bridges the slow-braised hare and cornbread migas; a rustic rural pairing','main','classic',2),
(490,'cheese, Serra, sheep','cheese','Queijo de Évora (aged sheep cheese) with medronho honey','complement','Esporão Reserva''s Alentejo origin pairs with the local Évora sheep cheese; medronho honey bridges both','cheese','classic',2),
(490,'tomato, Alentejo, summer','vegetable','Gaspacho alentejano (bread and tomato cold soup) with egg and ham','complement','Esporão''s warm Alentejo character bridges the cold gazpacho; the olive oil base echoes the wine''s sun-ripened fruit','casual','established',2),
(490,'beef, migas, black pork','beef','Pratos alentejanos — Alentejo mixed grill with various cured meats','complement','Esporão Reserva is the Alentejo''s most recognized wine; the mixed grill of local meats is its perfect table partner','casual','classic',2),
(490,'pork, chouriço, smoked','charcuterie','Chouriço assado na brasa with olive oil and bread','complement','Esporão Reserva Tinto bridges the smoky chouriço; the Alentejo produces both the wine and the finest smoked sausage','casual','classic',2),

-- 491 Luis Pato Quinta do Ribeirinho Pé Franco Bairrada (ungrafted, complex)
(491,'Bairrada, Luis Pato, ungrafted, complex','pork','Leitão da Bairrada (crispy suckling pig) with orange and sea salt','complement','Luis Pato Pé Franco''s Bairrada terroir belongs with leitão; the suckling pig and the wine are Bairrada''s defining creations','main','classic',1),
(491,'game, Bairrada, tannic','game','Perdiz (partridge) estufada com azeitonas e tomilho','complement','Pé Franco''s tannic old-vine structure bridges the braised partridge; Bairrada''s Atlantic character suits the game','main','classic',2),
(491,'seafood, Bairrada coast, unusual','seafood','Filetes de peixe espada com banana frita (scabbard fish with fried banana)','complement','Luis Pato''s Atlantic Bairrada character bridges the coastal scabbard fish; Bairrada''s wines have always paired with the sea','fish_course','adventurous',2),
(491,'cheese, Portuguese, aged','cheese','Queijo São Jorge (DOP hard yellow cheese from the Azores)','complement','Pé Franco''s tannic complexity bridges the firm São Jorge cheese; both are long-maturing Portuguese artisan expressions','cheese','established',2),
(491,'lamb, slow-cooked, herbs','lamb','Chanfana (goat in red wine) from Coimbra with rosemary bread','complement','Bairrada Pé Franco''s acidic structure bridges the slow-braised chanfana; the Coimbra tradition of goat and wine','main','classic',1),
(491,'pork, smoked, Bairrada charcuterie','charcuterie','Fumeiro da Bairrada — Bairrada smoked sausage selection','complement','Luis Pato''s Bairrada origin pairs with the local fumeiro; the wine''s tannin structure cuts through the smoked fat','casual','classic',1),
(491,'celebration, prestige, Portuguese','beef','Vitela assada da Bairrada (Bairrada-style roast veal)','complement','Pé Franco''s prestige Bairrada wine belongs with the region''s roast veal; both are expressions of Bairrada''s highest craft','main','classic',1),

-- 492 Quinta do Crasto Reserva Old Vines (Douro, concentrated, schist)
(492,'Douro, Crasto, old vines, concentrated','lamb','Chanfana transmontana (mountain goat braised in red wine)','complement','Crasto Old Vines'' Douro concentration bridges the rich braised goat; the wine used in the braise creates flavour unity','main','classic',1),
(492,'game, Douro, powerful','game','Javali assado à portuguesa (roast wild boar) with migas e orange','complement','Quinta do Crasto''s old vine power belongs with roast wild boar; the orange echoes the Douro''s schist mineral warmth','main','classic',1),
(492,'bacalhau, robust, Douro red','seafood','Bacalhau assado no forno com batatas a murro (oven-baked salt cod with smashed potatoes)','complement','Old Vines Crasto''s structured Douro character bridges the baked bacalhau; a Portuguese tradition of wine and salt cod','main','classic',1),
(492,'pork, prestige, Douro','pork','Leitão da Bairrada served with the Douro''s finest reds','complement','Crasto Reserva Old Vines'' concentration bridges the crispy leitão''s richness; a prestige pairing across Portugal''s regions','main','established',2),
(492,'cheese, Douro, mountain','cheese','Queijo da Serra aged 6 months with honey and walnuts','complement','Crasto''s power bridges the intensely flavoured Serra cheese; old vines for old cheese — a pairing of patience','cheese','established',2),
(492,'beef, slow, Douro traditional','beef','Cozido à portuguesa (Portuguese boiled dinner with meats and vegetables)','complement','Quinta do Crasto Old Vines'' Douro warmth bridges the cozido''s varied meats; a festive Portuguese table pairing','celebration','classic',2),
(492,'duck, Douro, prestige','duck','Pato com arroz (duck with rice in the Douro style with tomato and olives)','complement','Old Vines Crasto''s concentration bridges the rich duck rice; a classic Douro Sunday preparation','main','classic',2);
COMMIT;
