BEGIN;
INSERT INTO pairing_intelligence
  (beverage_product_id, food_flavour_profile, food_category, food_description, pairing_type, flavour_logic, meal_context, confidence, authority_tier)
VALUES
-- BAIJIU
(270,'celebration, banquet, luxury','seafood','Whole steamed grouper with ginger and soy at formal banquet','elevate','Feitian Moutai is the apex celebration spirit; a whole steamed fish is the most auspicious Chinese banquet finale','celebration','classic',1),

-- BEER ALE
(61,'smoked, bitter, roasted','meat','Smoked brisket with tangy BBQ sauce and dill pickles','complement','Sing Sing Porter''s dark roast and smoke character echoes the smoked brisket; the hop bitterness cuts through the fat','main','established',2),
(63,'hoppy, citrus, bold','burger','Classic double cheeseburger with pickles and mustard','complement','Superpower IPA''s West Coast bitterness cuts through the burger fat; the citrus hops brighten the caramelised beef','casual','classic',2),
(64,'tropical, soft, malt','spicy','Thai green curry with jasmine rice and fresh coriander','bridge','Lush IPA''s tropical notes and restrained bitterness bridge the coconut milk and galangal without amplifying heat','main','established',2),
(65,'fresh, malt, balanced','pizza','Thin-crust margherita with San Marzano tomato and fresh basil','complement','Mirror Pond''s balanced pale ale character complements pizza without competition; the hop cleanse cuts the mozzarella fat','casual','classic',2),
(66,'resinous, citrus, bitter','spicy','Buffalo wings with blue cheese dip and celery sticks','complement','Breakside IPA''s resinous bitterness cuts through the hot sauce; blue cheese and hops share a funky complexity','casual','classic',2),
(67,'malty, amber, fruity','ribs','Pork ribs slow-cooked with smoky bourbon glaze','bridge','Dead Guy''s malty amber character bridges the smoky bourbon glaze; Oregon craft and smoked pork are a natural pair','main','established',2),
(68,'tropical, bitter, juicy','fish tacos','Grilled fish tacos with mango slaw and chipotle crema','complement','Starburst IPA''s tropical fruit character bridges the mango slaw; the bitterness cleanses after each taco bite','casual','established',2),
(69,'chocolate, coffee, rich','dessert','Chocolate brownie with vanilla ice cream and salted caramel','complement','Double Stack Imperial Stout''s coffee and dark chocolate character mirrors a rich brownie; a dessert beer pairing','dessert','established',2),

-- BEER LAGER
(58,'roasted, dark, malt','sausage','Bratwurst with sauerkraut and whole-grain mustard','complement','Bench Dark Lager''s subtle roast notes complement the smoky sausage; the clean lager structure cuts through the fat','casual','established',2),
(59,'clean, crisp, neutral','seafood','Fish and chips with malt vinegar and tartar sauce','cleanse','Standard Lager''s clean crispness is the classic fish and chips partner; the carbonation refreshes after each fried bite','casual','classic',2),
(62,'malty, toasty, rich','pretzel','Bavarian soft pretzel with obatzda cheese spread and radish','complement','Oktoberfest''s maltiness is literally designed to match the Bavarian pretzel; a seasonal and cultural classic','casual','classic',1),

-- BEER WILD
(60,'tart, fruity, effervescent','oysters','Pacific oysters with Mignonette and lemon','cleanse','Nectarous Dry-Hopped Sour''s tart acidity cleanes the briny Pacific oyster; the dry-hop brings citrus freshness','starter','established',2),

-- COFFEE
(70,'dark chocolate, spice, brown sugar','dessert','Dark chocolate truffles with chipotle and sea salt','complement','Huehuetenango''s complex natural process depth complements smoky dark chocolate; the high altitude brings brightness','dessert','established',2),
(71,'floral, clean, fruit','dessert','Lemon tart with fresh raspberries and mint cream','complement','Yirgacheffe washed''s bright florality and citrus complement the lemon tart''s sharp clean sweetness','dessert','established',2),
(72,'black tea, grapefruit, bright','dessert','Cheesecake with blackcurrant glaze and shortbread base','complement','Kenya AA''s grapefruit and blackcurrant notes mirror the cheesecake glaze; washed Kenya and berry desserts are natural','dessert','established',2),
(73,'roasted, bitter, nutty','dessert','Tiramisu with espresso-soaked ladyfingers and mascarpone','complement','House Blend espresso''s roasted character is literally an ingredient in tiramisu; drinking it alongside doubles the coffee intensity','dessert','classic',1),
(74,'complex, sweet, dark','dessert','Pain au chocolat with almond paste and dark chocolate','complement','Hair Bender''s nuanced complexity bridges the rich pastry layers; a Portland café morning pairing','casual','classic',2),
(75,'complex, sweet, bright','dessert','Affogato — vanilla gelato drowned in a double espresso shot','complement','Stereo Blend works beautifully as an affogato base; the blend''s balance supports rather than overwhelms the gelato','dessert','classic',1),
(76,'balanced, sweet, aromatic','dessert','Cannoli siciliani with ricotta and dark chocolate chips','complement','Del Sol''s Italian-heritage roast pairs with the Sicilian classic; both express Italian craft culture','dessert','classic',2),
(77,'bright, blueberry, clean','dessert','Pavlova with mixed berries and whipped cream','complement','Shantawene''s natural blueberry and fruit sweetness bridge to the pavlova fruit topping; an East African berry pairing','dessert','established',2),
(78,'sweet, caramel, honey','dessert','Honey cake with walnuts and caramel glaze (medovik)','complement','Red Honey process brings caramel and honey notes that directly complement the medovik layering','dessert','established',2),
(79,'balanced, nutty, clean','dessert','Almond croissant with frangipane and flaked almonds','complement','Guatemala Antigua''s nutty character and bright acidity complement the almond croissant''s richness','casual','established',2),
(370,'cardamom, thick, sweet','confection','Turkish delight (lokum) with rose and pistachio','complement','Mehmet Efendi Turkish coffee is traditionally served with lokum; the cardamom in the coffee bridges to the rose delight','casual','classic',1),

-- NA CRAFTED
(81,'spiced, savoury, aromatic','snack','Spiced nuts with rosemary and smoked paprika','complement','Seedlip Spice 94 duplicate product — same as 189; spiced nuts echo the botanical complexity','aperitif','established',2),
(83,'crisp, apple, tart','cheese','Aged Cheddar with apple chutney and oatcakes','bridge','Cawston Press sparkling apple''s real apple juice bridges the Cheddar and chutney; all three are British autumnal classics','casual','established',2),
(85,'bitter, quinine, herbal','cocktail ingredients','Gin and tonic with lemon and cucumber','complement','Fever-Tree Indian Tonic is designed to pair with quality gin; its quinine bitterness enhances botanical gin aromatics','aperitif','classic',1),
(87,'herbal, vegetal, earthy','salad','Asian pear and rocket salad with toasted sesame dressing','complement','Coffee leaf tea''s vegetal character bridges the Asian pear and sesame; a health-conscious pairing with real harmony','casual','suggested',2),
(88,'orange, sparkling, citrus','aperitif','Bruschetta al pomodoro with fresh basil and olive oil','complement','Aranciata''s bitter orange freshness cleanses the tomato and basil; a classic Italian aperitivo combination','aperitif','classic',2),
(89,'herbal, complex, NA cocktail','snack','Marcona almonds with sea salt and thyme','complement','Curious Elixirs No. 1''s complex botanical structure pairs with the herbal salted almonds; a sophisticated NA aperitif pairing','aperitif','established',2),

-- NA DEALCOHOLISED
(82,'fruity, rosé, light','salad','Watermelon, feta and mint salad with balsamic glaze','complement','Gruvi Bubbly Rosé''s light fruit character bridges the watermelon sweetness; a casual summer pairing with real affinity','casual','established',2),

-- NA FERMENTED
(80,'tangy, ginger, probiotic','Asian noodles','Cold sesame noodles with ginger, cucumber and spring onion','complement','Seasoning Kombucha''s tangy fermented character bridges the ginger and sesame; both are naturally fermented preparations','casual','established',2),
(84,'dry, tart, complex','salad','Beetroot and goat cheese salad with candied walnuts','complement','Tonica''s dry original style pairs with the earthy beetroot; the kombucha acidity mirrors the balsamic dressing','starter','established',2),
(86,'floral, honey, fermented','dessert','Honey yogurt parfait with granola and fresh berries','complement','Wild Tonic Jun''s honey fermentation base directly complements honey yogurt; both are honey-based fermented preparations','casual','established',2),

-- SAKE (BC & USA producers)
(90,'grilled, seafood, savoury','seafood','Grilled prawn skewers with lemon and garlic butter','complement','Osake Junmai Ginjo''s BC-made sake bridges grilled seafood; the clean rice character complements without competing','fish_course','established',2),
(91,'delicate, white fish, steamed','seafood','Steamed halibut with sake broth and ginger','complement','Momokawa Diamond''s delicate ginjo character pairs with Pacific Northwest halibut; a Oregon sake with Pacific fish','fish_course','established',2),
(92,'sashimi, wasabi, clean','seafood','Salmon sashimi with pickled ginger and wasabi','complement','Hakutsuru Junmai Ginjo''s clean style pairs with Pacific salmon sashimi; a Japanese-American brewery tradition','fish_course','classic',2),
(93,'delicate, premium, fish','seafood','Sea bream sashimi (tai) with yuzu ponzu','elevate','Gekkeikan Horin''s premium daiginjo elevates delicate tai; a Napa Valley-adjacent sake matched to Japanese fine dining','fish_course','classic',2),
(94,'fresh, fruity, delicate','fruit','Fresh summer fruit with yuzu cream sauce','complement','Ninki-Ichi''s bright junmai ginjo character bridges the fruit platter; a versatile pairing for the dining room','pre_dessert','established',2),
(95,'clean, savoury, umami','soup','Miso soup with wakame and tofu','complement','Masumi Okuden''s Nagano terroir pairs with the clean umami of miso soup; a Japanese comfort food classic','starter','classic',2),
(96,'seafood, lemon, cream','seafood','Dungeness crab with lemon butter and sourdough','complement','Rihaku Wandering Poet''s Pacific Northwest sensibility pairs with Dungeness crab; sake and Pacific shellfish affinity','fish_course','established',2),
(97,'delicate, floral, light','seafood','Oyster on half-shell with yuzu mignonette','complement','G Joy Daiginjo''s Bay Area craft meets Pacific Northwest oysters; a California sake paired with Pacific terroir','starter','established',2),
(98,'clean, light, everyday','yakitori','Chicken yakitori with tare glaze and shichimi','complement','Kizakura Junmai''s everyday accessibility pairs with simple yakitori; a Fushimi sake for the izakaya tradition','casual','classic',2),
(99,'clean, floral, rice','tofu','Agedashi tofu in dashi broth with grated daikon','complement','Ben Kadoya''s Alameda craft sake bridges the delicate tofu and dashi; a California sake house pairing','starter','established',2),
(112,'fish, truffle, luxury','seafood','Premium sashimi with black truffle shaving and yuzu oil','elevate','Kubota Manju as Niigata''s apex wine elevates the most luxurious sashimi presentation; a celebration of Japanese craft','celebration','classic',1),
(122,'izakaya, varied, robust','izakaya','Izakaya mixed platter with yakitori, kushiyaki and gyoza','complement','Kimoto Junmai''s traditional fuller body bridges the bold izakaya flavours; the traditional method demands traditional food','casual','classic',2),
(134,'apex, luxury, kaiseki','kaiseki','Kaiseki opening course of seasonal sashimi and dashi','elevate','Dassai 23 is Japan''s most refined commercially available daiginjo; only a kaiseki opening matches its apex quality','celebration','classic',1),

-- SPIRITS BRANDY
(55,'apple, barrel, smooth','cheese','Aged Gouda with honeycomb and pear chutney','complement','BC brandy''s smooth spirit bridges the aged gouda and pear; a local pairing with Pacific Northwest character','cheese','suggested',2),
(317,'chocolate, dried fruit, rich','chocolate','Dark chocolate truffles with cognac and dried cherry','complement','Rémy Martin XO''s extraordinary richness is traditionally served with or in dark chocolate; a Cognac classic','digestif','classic',1),
(318,'dried fruit, orange, delicate','confection','Candied orange peel dipped in dark chocolate','complement','Delamain Pale and Dry''s Grande Champagne elegance pairs with the citrus-chocolate confection; subtle and refined','digestif','classic',1),
(319,'Christmas cake, rich, brandy','baked','Rich Christmas cake with royal icing and marzipan','complement','Hine Antique''s dark fruit, spice and nut character pairs perfectly with Christmas cake; brandy fruit cake is a British tradition','celebration','classic',1),
(320,'prune, Armagnac, casserole','duck','Cassoulet de canard aux pruneaux d''Armagnac — duck cassoulet with prunes','complement','The Armagnac spirit used in the prune marinade creates a direct flavour loop; drinking Darroze with its own cuisine','main','classic',1),
(321,'apple, caramel, Norman','dessert','Tarte tatin with crème fraîche and calvados drizzle','complement','Dupont VSOP Calvados and tarte tatin are Normandy''s greatest pairing; apple in the glass and on the plate','dessert','classic',1),
(324,'apple, pear, aged','cheese','Camembert de Normandie with apple compote and walnut bread','complement','Lemorton 15-Year''s pear and aged complexity pairs with the Norman Camembert; both age on the same landscape','cheese','classic',1),

-- SPIRITS GIN
(46,'citrus, sweet, juniper','dessert','Lemon posset with shortbread and candied lemon','complement','Old Tom Gin''s sweeter style pairs with the bright lemon posset; the juniper lift prevents cloying sweetness','dessert','established',2),
(47,'floral, berry, violet','aperitif','Elderflower panna cotta with blueberry compote','complement','Empress 1908''s violet-indigo colour and floral character pairs with elderflower panna cotta; BC''s most photogenic pairing','pre_dessert','established',2),
(48,'coastal, saline, herbal','seafood','Dungeness crab bisque with crème fraîche and dill','complement','Seaside Gin''s coastal botanical character mirrors the Dungeness crab bisque; a BC seaside terroir pairing','starter','established',2),
(50,'floral, herbal, balanced','cheese','Whipped ricotta with honey, pistachios and lavender oil','complement','Confluence Gin''s Pacific Northwest botanicals pair with the herb and honey cheese preparation; a Pacific floral pairing','aperitif','established',2),
(51,'delicate, floral, clean','seafood','Oyster on half-shell with cucumber granita and dill','complement','Ampersand Gin''s clean BC botanical style bridges the Pacific oyster and cucumber; a Cowichan Valley terroir pairing','starter','established',2),
(53,'juniper, citrus, fresh','snack','Smoked salmon blinis with crème fraîche and capers','complement','Freeland Gin''s Pacific Northwest spirit bridges the Northwest smoked salmon; gin botanicals and smoke share affinity','aperitif','established',2),

-- SPIRITS LIQUEUR
(322,'anise, pastis, water ritual','seafood','Socca (chickpea pancake) with tapenade and anchovy','complement','Ricard pastis is the Marseille aperitivo tradition; socca is the street food of the same Mediterranean culture','aperitif','classic',1),
(323,'anise, complex, herbal','seafood','Bouillabaisse de Marseille with rouille and grilled bread','complement','Henri Bardouin''s complex herb pastis pairs with bouillabaisse; both are concentrated expressions of Provence','main','classic',1),
(346,'grape, floral, delicate','dessert','Panna cotta with moscato grape jelly and vanilla bean','complement','Nonino Moscato grappa and the wine it comes from — Moscato — share the same aromatic terroir; drinking the source','dessert','established',2),
(347,'bitter, digestif, herbal','coffee','Espresso con Fernet — a small shot of Fernet in the espresso','complement','Fernet-Branca is traditionally consumed post-coffee or in coffee; the bitter-herbal digestif settles the stomach','digestif','classic',1),
(348,'sweet, herbal, amber','dessert','Panna cotta with orange blossom and candied violet','bridge','Amaro Montenegro''s sweet herbal amber pairs with the floral Italian panna cotta; both are expressions of Italian botanicals','dessert','established',2),
(349,'lemon, zesty, sweet','dessert','Deconstructed lemon meringue tart with limoncello cream','complement','Limoncello di Capri is directly used in the preparation; drinking the ingredient while eating the dessert — pure Amalfi','dessert','classic',1),
(350,'grape, earthy, grappa','cheese','Pecorino Sardo with honey and dried fig','bridge','Nardini Acquavite''s grape distillate bridges the aged sheep cheese and dried fig; a Veneto-Sardinian pairing','digestif','established',2),
(365,'anise, clean, Greek','seafood','Grilled octopus with lemon, olive oil and oregano','complement','Barbayanni Blue Ouzo and grilled octopus are Greece''s defining taverna pairing; anise and charred seafood','casual','classic',1),
(366,'anise, island, Lesvos','meze','Taramosalata with warm pita and cucumber tzatziki','complement','Plomari Ouzo from Lesvos is the island''s spirit; paired with meze before any meal on the island is tradition','aperitif','classic',1),
(368,'anise, complex, Lebanese','meze','Kibbeh nayyeh (raw lamb) with bulgur, onion and pine nuts','complement','Massaya Arak and kibbeh nayyeh are the Lebanese meze tradition; arak is always the kibbeh companion','starter','classic',1),

-- SPIRITS WHISKEY (BC/PNW)
(41,'smoked salmon, Pacific, cream','seafood','Hot-smoked Pacific salmon with cream cheese and capers','complement','American Single Malt''s Pacific Northwest character naturally bridges smoked salmon; both express local terroir','starter','established',2),
(42,'Douglas fir, northwest, herbal','game','Elk strip loin with Douglas fir berry sauce and celeriac','complement','Garryana''s Quercus garryana oak gives a Pacific Northwest native character; elk and native botanicals share the forest','main','established',2),
(43,'vanilla, caramel, sweet','dessert','Warm apple crumble with vanilla ice cream and caramel sauce','complement','American Single Malt''s approachable character pairs with the classic comfort dessert; both have a warming sweetness','dessert','established',2),
(44,'smoked, peaty, Oregon','cheese','Smoked Oregonzola blue cheese with candied hazelnuts','complement','Oregon Single Malt''s Pacific Northwest smokiness pairs with the local smoked blue cheese; a regional terroir expression','cheese','established',2),
(49,'fruity, light, Scottish','cheese','Isle of Mull Cheddar with oatcakes and chutney','complement','Laird of Fintry''s Scottish single malt provenance pairs with the island Cheddar; a Scottish terroir pairing','casual','established',2),
(52,'port finish, rich, sweet','dessert','Dark chocolate port cake with dried cherry and almond','complement','Port Finish American Single Malt''s fortified wine cask character pairs with the port cake; cask complements dessert format','dessert','established',2),
(54,'grain, malt, accessible','burger','BBQ bacon cheeseburger with smoked onion ring','complement','Noteworthy Canadian Whisky''s approachable grain character pairs with the casual BBQ burger; an everyday whisky pairing','casual','established',2),
(56,'peaty, maritime, Scottish','seafood','Smoked mussels on sourdough with whisky cream and dill','complement','Port Charlotte''s Islay DNA pairs with smoked shellfish; the whisky cream echoes the peat-and-sea maritime character','starter','established',2),

-- TEA (Japanese continued)
(205,'ceremonial, sweet, wagashi','confection','Higashi dry sweet with plum flower design','complement','Wako ceremonial matcha is paired with higashi in the formal tea ceremony; the dry sweet balances the whisked bitter tea','dessert','classic',1),
(208,'floral, sweet, spring','confection','Spring namagashi fresh sweet with cherry blossom filling','complement','Okumidori cultivar ceremonial matcha belongs with seasonal namagashi; both express the peak of Japanese spring craftsmanship','dessert','classic',1),
(211,'deep, umami, gyokuro','seafood','Ankimo monkfish liver with dashi ponzu and micro wasabi','complement','Gyokuro Unkaku''s extreme shade-grown umami bridges the rich monkfish liver; the most umami-forward pairing in Japanese cuisine','starter','established',2),
(215,'green, vegetal, deep','snack','Edamame with nori salt and sesame oil','cleanse','Fukamushi sencha''s deep steaming creates extra umami; edamame shares the same green amino acid character','casual','classic',2),
(219,'nutty, toasted, green','casual','Onigiri rice ball with salmon and nori','complement','Genmaicha''s roasted rice notes pair directly with the onigiri rice; both contain roasted rice as a base ingredient','casual','classic',1),
(220,'fresh, green, light','seafood','Chilled somen noodles with dipping sauce and shiso','cleanse','Tamaryokucha''s unique curled leaf and vegetal freshness pairs with cold somen; both are light and seasonal','starter','classic',2),
(249,'aged, earthy, pu-erh','meat','Slow-braised wagyu short ribs with aged soy and star anise','complement','Ancient tree sheng''s aged complexity mirrors the slow-braised wagyu; both require patience and yield profound depth','main','established',2),
(254,'mineral, spice, roasted','meat','Char siu BBQ pork with steamed rice and scallion oil','complement','Rou Gui (cinnamon) Rock Oolong''s warming spice complements char siu''s five-spice and honey glaze; a Fujian pairing','main','classic',2),
(258,'complex, roasted, mineral','dim sum','Roasted goose with plum sauce and spring onion pancake','complement','Traditional charcoal-roasted Tieguanyin''s complexity bridges the roasted goose and plum; a Guangdong luxury pairing','main','classic',2),
(259,'fresh, floral, jade green','dim sum','Steamed silk tofu with ginger soy and spring onion','complement','Jade Green Tieguanyin''s light oxidation and floral freshness complements the silken tofu; a delicate counterpoint','starter','classic',2),
(264,'duck, honey, orchid','poultry','Cantonese roast duck with plum sauce and steamed bun','complement','Ya Shi Xiang (Duck Shit) Dancong is traditionally paired with poultry; the ironic name obscures a classical pairing','main','classic',1),
(266,'aged, honey, complex','cheese','Young Brie with honey and toasted almond','bridge','Old Bush Dancong''s aged honey complexity bridges the young Brie''s cream and the almond toast; a modern tea-cheese pairing','casual','adventurous',2),
(267,'earthy, dark, pu-erh blend','digestif','Post-meal digestif service of pu-erh blend','complement','Pu-erh''s digestive properties are the reason for its traditional post-meal consumption; the blend makes this accessible','digestif','classic',2),
(279,'floral, spring, oolong','seafood','Lightly grilled sea bream with ginger and spring onion','complement','Spring Alishan''s fresh floral character pairs with the delicate grilled sea bream; a Taiwan mountain tea with ocean fish','fish_course','established',2),
(283,'honey, honey dew, oolong','dessert','Honey dew melon and prosciutto with mint','complement','Oriental Beauty''s exceptional honeydew character (caused by leafhopper biting) directly mirrors the melon dessert','pre_dessert','classic',1),
(288,'fresh, muscatel, biodynamic','dessert','Muscatel grape tart with cream and toasted hazelnut','complement','Makaibari''s biodynamic First Flush muscatel grape character mirrors a muscatel grape tart; a varietal complement','dessert','established',2),
(296,'frost, rare, Nilgiri','cheese','Malabar black pepper cheddar with orange marmalade','complement','Nilgiri Frost Tea''s rare character and the Malabar spiced cheese share South Indian mountain terroir','casual','adventurous',2),
(369,'mint, green, aromatic','mezze','Lamb kefta kebabs with harissa and preserved lemon yogurt','complement','Moroccan Atay mint tea is served throughout the meal with all food; lamb kefta is the most traditional meat pairing','main','classic',1),

-- WINE DESSERT
(313,'honeyed, riesling, late harvest','cheese','Roquefort AOP with walnut bread and honey','bridge','Hugel VT Riesling''s late-harvest sweetness bridges the Roquefort salt and the honey; sweet-salt pairing at its best','cheese','classic',1),

-- WINE FORTIFIED (Sherry)
(356,'briny, saline, delicate','seafood','Fresh langoustines with sea salt and lemon mayonnaise','complement','La Gitana Manzanilla is produced in Sanlúcar de Barrameda on the coast; the sea air in the wine mirrors fresh langoustines','starter','classic',1),
(357,'savoury, nutty, dry','aperitif','Ibérico ham (bellota grade) with crusty sourdough and olive oil','complement','Tio Pepe Fino is the definitive Ibérico ham partner; the flor yeast and almond notes of fino match the cured ham perfectly','aperitif','classic',1),
(358,'hazelnut, coffee, savoury','cheese','Aged Manchego 36 months with marcona almonds and quince','complement','Lustau Amontillado''s hazelnut and amber complexity matches aged Manchego''s crystalline sharpness; a classic sherry pairing','cheese','classic',1),
(359,'rich, walnut, amber','soup','Chilled gazpacho with micro herbs and olive oil drizzle','contrast','Palo Cortado''s unique character of fino freshness and oloroso richness contrasts with the cold gazpacho; unusual but rewarding','starter','adventurous',2),
(360,'pedro ximenez, raisin, chocolate','dessert','Chocolate cake with Pedro Ximénez reduction sauce and vanilla','complement','Noe PX is designed as a dessert wine; the same grape variety as a reduction sauce creates a closed flavour loop','dessert','classic',1),
(361,'oxidative, complex, Equipo','cheese','Aged Idiazabal smoked sheep cheese with Pedro Ximénez reduction','complement','La Bota Amontillado''s profound oxidative complexity matches the smoked sheep cheese; both come from the same Basque country region','cheese','classic',1),

-- WINE SPARKLING: Champagne
(241,'lobster, butter, luxury','seafood','Lobster thermidor with tarragon butter sauce and asparagus','elevate','Krug Grande Cuvée''s multi-vintage complexity elevates lobster thermidor; the most opulent Champagne demands the finest shellfish','fish_course','classic',1),
(242,'minerality, chalk, blanc de blancs','seafood','Fine de Claire oysters (No. 3) with lemon and sourdough','complement','Salon Blanc de Blancs is the purest expression of Le Mesnil chalk; oysters from the same limestone terrain are the pairing','starter','classic',1),
(243,'luxury, truffle, vintage','appetiser','White truffle risotto with aged Parmesan and truffle oil','elevate','Dom Pérignon P1 Vintage''s prestige vinification elevates white truffle risotto; both are luxury expressions of their year','starter','classic',1),
(244,'chalk, mineral, single vineyard','seafood','Sea scallops ceviche with yuzu and cucumber','complement','Pierre Péters Les Chétillons'' chalk-mineral character complements the clean ceviche; both share marine mineral freshness','starter','classic',2),
(245,'bold, rounded, vinous','meat','Roasted guinea fowl with chanterelles and Champagne sauce','complement','Bollinger Special Cuvée''s Pinot Noir dominance pairs with guinea fowl; the Champagne in the sauce creates flavour unity','main','classic',1),
(246,'powerful, Pinot Noir, Ambonnay','meat','Slow-roasted Challans duck with black cherry reduction','complement','Egly-Ouriet Blanc de Noirs Ambonnay''s powerful Pinot character pairs with duck; Ambonnay''s black grapes demand dark meat','main','classic',2),

-- WINE SPARKLING: Moscato d'Asti / Prosecco
(374,'moscato, peach, flowers','dessert','Fresh peach and almond tart with vanilla mascarpone','complement','La Spinetta Bricco Quaglia''s Moscato character and low alcohol matches fresh peach tart; a delicate Italian dessert pairing','dessert','classic',1),
(375,'light, sweet, floral','dessert','Strawberries with aged balsamic vinegar and vanilla cream','complement','Bera Moscato d''Asti''s gentle sweetness complements strawberries and aged balsamic; a Piedmontese dessert tradition','dessert','classic',2),
(376,'sparkling, sweet, fruit','dessert','Torta della Nonna (Italian grandmother''s custard tart)','complement','Bera Asti Spumante''s sweetness pairs with the Italian custard tart; a Piedmontese mother''s dessert with its region''s wine','dessert','classic',2),
(377,'floral, apricot, sweet','dessert','Cantucci biscotti with almond and vin santo dipping','complement','Nivole Moscato''s floral sweetness pairs with the almond cantucci; a variation on the Italian dessert wine tradition','dessert','classic',2),
(385,'ripe, apple, dry','seafood','Carpaccio di branzino with lemon oil and micro herbs','complement','Bisol Cartizze''s ripe apple and dry finish pairs with the delicate sea bass carpaccio; a Veneto luxury pairing','starter','classic',2),
(386,'extra brut, mineral, citrus','seafood','Raw Adriatic scallops with citrus zest and olive oil','complement','Ruggeri Extra Brut''s mineral tension and citrus brightness elevates the raw scallop''s sweetness','starter','established',2),
(387,'approachable, fresh, apple','aperitif','Bruschetta with heirloom tomato, basil and extra virgin olive oil','complement','Nino Franco Rustico''s approachable style makes it the ideal aperitivo Prosecco; tomato bruschetta is the classic Venetian partner','aperitif','classic',2),
(388,'floral, delicate, pear','starter','Prosciutto di San Daniele with melon and breadsticks','complement','Bisol Crede''s pear blossom delicacy pairs with the delicate San Daniele prosciutto and sweet melon; a Veneto aperitivo classic','aperitif','classic',2),

-- WINE STILL: BC wines (1-28)
(1,'bold, Okanagan, rich','beef','Osoyoos Indian Band grilled bison with Okanagan berry reduction','complement','Red Icon''s Osoyoos origin pairs with the desert terroir of South Okanagan bison; a BC Indigenous food pairing','main','established',2),
(3,'Bordeaux blend, Osoyoos, luxury','lamb','Rack of BC lamb with Okanagan herb crust and natural jus','complement','Osoyoos Larose''s Bordeaux-inspired blend pairs with the finest BC lamb; a collaboration between French expertise and Canadian terroir','main','classic',1),
(4,'Meritage, Okanagan, structured','beef','Black Sage Road aged beef tenderloin with forest mushroom jus','complement','Meritage''s Left Bank character suits the aged beef; Black Sage Bench mushrooms echo the Bordeaux earthiness','main','established',2),
(6,'Chardonnay, oak, butter','fish','Pan-seared BC halibut with beurre blanc and Okanagan apricot','complement','Perpetua Chardonnay''s Burgundian oak pairs with Pacific halibut; the Okanagan apricot bridges the wine''s stone fruit notes','fish_course','established',2),
(7,'Pinot Noir, silky, cherry','duck','Roasted BC duck breast with Okanagan cherry reduction','complement','Stewart Family Reserve Pinot Noir pairs with BC duck; the cherry reduction bridges the wine''s red fruit character','main','classic',2),
(8,'Pinot Noir, Naramata, complex','lamb','BC lamb chops with Similkameen herb crust and garlic confit','complement','Platinum Block 2 Pinot Noir''s Naramata Bench complexity pairs with BC lamb; a Naramata terroir pairing','main','established',2),
(9,'Pinot Noir, silky, BC premium','game','Grilled venison with elderberry reduction and celeriac purée','complement','Unparalleled Pinot Noir''s premium BC character pairs with local venison; the elderberry echoes the wine''s dark berry notes','main','established',2),
(10,'Cabernet Franc, herbal, graphite','duck','Duck confit with Okanagan cherry reduction and lentils','complement','Jackpot Cabernet Franc''s Loire-like herbaceous character bridges duck and cherry; a Naramata expression of the classic pairing','main','established',2),
(11,'Syrah, pepper, dark fruit','game','Grilled boar sausage with BC blackberry compote and mustard greens','complement','Qwam Qwmt Syrah''s northern Rhône character bridges the game sausage and berry; a Washington State Syrah influence','main','established',2),
(12,'red blend, bold, BC','beef','Yakima Valley beef short ribs braised in BC red wine','complement','Dead of Night''s big BC red character suits the slow-braised short ribs; braising in the wine creates flavour unity','main','established',2),
(13,'structured, red blend, Okanagan','cheese','Aged BC sheep cheese with wild BC berry preserves','complement','Signature''s structured blend pairs with aged sheep cheese and berry preserves; a Naramata cheese board pairing','cheese','established',2),
(14,'Pinot Noir, BC, everyday','casual','Charcuterie board with BC salami, cornichons and sourdough','complement','Pinot Noir''s versatility makes it the default charcuterie wine; a BC winery''s everyday expression with the classic board','casual','established',2),
(16,'luxury, Chardonnay, Okanagan','seafood','Dungeness crab with tarragon cream and Perpetua chardonnay butter','complement','CheckMate Queen Taken''s luxury Chardonnay pairs with Dungeness crab; using the same wine in the sauce creates unity','fish_course','classic',2),
(17,'Cabernet, WA, structured','beef','Snake River Farms wagyu with bone marrow and natural jus','complement','WA Cabernet Sauvignon''s Red Mountain warmth pairs with Snake River Farms wagyu; a Pacific Northwest luxury pairing','main','classic',2),
(18,'Cabernet, Okanagan, bold','lamb','Slow-roasted Okanagan lamb shoulder with Provençal herbs','complement','Black Sage Bench Cabernet''s bold warmth suits the Okanagan lamb; the Provençal herbs bridge the Bordeaux character','main','established',2),
(19,'Meritage blend, BC, structured','beef','Beef Wellington with duxelles and truffle jus','complement','Perigee''s blend structure suits Beef Wellington''s pastry and duxelles; a BC fine dining celebration pairing','main','established',2),
(20,'Syrah, Cailloux, Walla Walla','lamb','Columbia Valley rack of lamb with Walla Walla sweet onion jus','complement','Cailloux Vineyard Syrah from Pepper Bridge pairs with the local lamb; Walla Walla onions bridge the site character','main','classic',2),
(21,'Bordeaux blend, Chaleur, structured','beef','Dry-aged Columbia Valley beef côte de boeuf with bone marrow','complement','Chaleur Estate Red''s structured blend pairs with the finest Columbia Valley beef; a Pacific Northwest luxury pairing','main','established',2),
(22,'Champoux, Cab, Horse Heaven','beef','Horse Heaven Hills aged beef tenderloin with herb butter','complement','Champoux Vineyard is the heart of Horse Heaven Hills; the site''s cattle-country heritage makes beef the natural pairing','main','classic',2),
(23,'Cabernet, old vine, Wahluke','beef','Wahluke Slope beef short ribs with Columbia Valley red wine jus','complement','Old Vines Cab from Wahluke Slope has decades of vine age; the site''s beef history makes this a terroir pairing','main','established',2),
(24,'Riesling, Eroica, off-dry','seafood','Pacific halibut ceviche with Dungeness crab, lime and cilantro','complement','Eroica Riesling''s off-dry character bridges the citrus acid of ceviche; the Columbia Valley Rhine style pairs with Pacific fish','fish_course','classic',2),
(25,'Syrah, Walla Walla, spicy','game','Walla Walla sweet onion tart with Painted Hills beef','complement','John Lewis Syrah''s bold Walla Walla character pairs with the sweet onion tart; local beef echoes the wine''s depth','main','established',2),
(26,'red blend, OR/WA, accessible','casual','Smoked pulled pork sandwich with vinegar slaw on brioche','complement','Subduction Red''s accessible blend pairs with pulled pork; a casual Pacific Northwest pairing built for the table','casual','established',2),
(27,'red blend, Helix, everyday','casual','Beef burger with caramelised onion and sharp Cheddar','complement','CMS Red''s everyday Columbia Valley character pairs with the classic burger; an honest wine for an honest meal','casual','established',2),
(28,'Chester-Kidder, blend, luxury','beef','Columbia Valley lamb rib chops with rosemary and garlic','complement','Chester-Kidder''s premium blend pairs with the finest Columbia Valley lamb; a Champoux collaboration deserves fine meat','main','classic',2),

-- WINE STILL: Oregon Pinot Noir
(29,'Pinot Noir, Dundee Hills, elegant','duck','Oregon duck breast with willamette valley cherry jus','complement','Dundee Hills Pinot Noir and Oregon duck are the valley''s iconic pairing; volcanic soil gives the wine its cherry character','main','classic',2),
(30,'Pinot Noir, Chehalem, original','salmon','Wild Oregon salmon with pinot noir reduction and hazelnuts','complement','Original Vines Pinot Noir''s old-vine depth bridges wild salmon; hazelnuts echo the Willamette Valley floor','fish_course','classic',2),
(31,'Pinot Noir, Chehalem, floral','mushroom','Oregon chanterelle and truffle risotto with aged Parmesan','complement','Avni Pinot Noir''s floral depth pairs with Oregon''s wild chanterelles; the volcanic soil mirrors the earthy mushroom','main','established',2),
(32,'Pinot Noir, Seven Springs, limestone','game','Willamette Valley quail with fig and Oregon hazelnut','complement','Seven Springs Vineyard''s limestone character pairs with the delicate quail; fig bridges the Pinot''s fruit character','main','established',2),
(33,'Pinot Noir, Casteel Reserve, complex','duck','Willamette Valley duck confit with pinot noir reduction','complement','Casteel Reserve''s Washington Pinot complexity pairs with Oregon duck; the reserve level demands the finest preparation','main','classic',2),
(34,'Pinot Noir, Eileen, single vineyard','salmon','Pacific wild coho salmon with Oregon forest mushroom','complement','Eileen Vineyard''s single site intensity pairs with wild coho; both represent the finest Pacific Northwest has to offer','fish_course','classic',2),
(35,'Pinot Noir, Beaux Frères, powerful','beef','Oregon beef short ribs with Oregon pinot reduction and thyme','complement','Beaux Frères''s powerful Pinot Noir can handle braised short ribs; a modern Oregon interpretation of Burgundy pairing','main','established',2),
(36,'Pinot Noir, old stones, mineral','mushroom','Oregon porcini and truffle duxelles on toasted Oregon sourdough','complement','Old Stones Pinot Noir''s mineral depth pairs with the earthy Oregon porcini; volcanic and limestone soils echo the fungal','starter','established',2),
(37,'Pinot Noir, Savoya, volcanic','duck','Roasted Savoya Ranch duck with Willamette cherry compote','complement','Savoya Vineyard''s volcanic character and the duck''s richness belong together; the cherry compote bridges the Pinot','main','classic',2),
(38,'Pinot Noir, Elizabeth, reserve','game','Oregon venison loin with elderberry reduction and root purée','complement','Elizabeth''s Reserve Pinot Noir''s premium character pairs with venison; elderberry bridges the wine''s deep berry notes','main','established',2),
(39,'Tempranillo, Oregon, earthy','lamb','Oregon lamb chops with Rioja-style garlic and herbs','complement','Tempranillo Reserve''s Spanish variety in Oregon soil pairs with lamb; the Spanish heritage calls for the traditional pairing','main','established',2),

-- WINE STILL: French Burgundy Grand Cru tier
(191,'transcendental, Pinot Noir, Romanée','game','Roasted Bresse pigeon with black truffle and DRC Romanée jus','elevate','La Romanée-Conti is incomparable; only roasted Bresse pigeon with black truffle demands this level of wine','main','classic',1),
(192,'powerful, La Tâche, silky','game','Wild hare (lièvre à la royale) with its own blood sauce','elevate','La Tâche''s power belongs with the most demanding game preparation; lièvre à la royale is Burgundy''s most profound dish','main','classic',1),
(193,'muscular, Chambertin, Napoleon','beef','Pièce de boeuf Charolais rôtie — whole Charolais beef rib','complement','Napoleon''s favourite wine with the finest Burgundian beef; a pairing of historical and culinary significance','main','classic',1),
(194,'ethereal, Musigny, silky','poultry','Poularde de Bresse en demi-deuil — truffle-stuffed Bresse chicken','elevate','Roumier Musigny''s ethereal Pinot elevates the Mère Brazier''s greatest dish; both represent the summit of Burgundy culture','main','classic',1),
(195,'Montrachet, white Burgundy, apex','seafood','Sole meunière (classique) with brown butter, lemon and capers','elevate','Leflaive Montrachet is the greatest white wine in the world; sole meunière in brown butter is its perfect partner','fish_course','classic',1),
(196,'Meursault, Coche-Dury, mineral','seafood','Langoustines rôties with beurre noisette and Chablis vinaigrette','elevate','Coche-Dury Perrières is the most sought-after Meursault; langoustines in butter sauce are its destined companion','fish_course','classic',1),
(197,'Chablis, Grand Cru, Les Clos','seafood','Freshwater crayfish (écrevisses) à la nage with tarragon','elevate','Raveneau Chablis Les Clos''s mineral grandeur elevates the delicate écrevisse; both come from the same Kimmeridgean limestone','fish_course','classic',1),
(198,'Mugnier, Musigny, silky','poultry','Pintade de Bresse rôtie with morel mushrooms and vin jaune sauce','elevate','Mugnier Musigny''s silk and mineral elevates Bresse guinea fowl with morels; a pairing at the summit of Burgundy tradition','main','classic',1),
(199,'Jadot, Chambertin Clos de Bèze, power','game','Roasted wild boar saddle with Gevrey wine sauce and juniper','complement','Chambertin Clos de Bèze demands the most flavourful game; wild boar with juniper echoes the wine''s herbal earthiness','main','classic',1),
(200,'Dauvissat, Chablis, oysters','seafood','Belon flat oysters (No. 00) with lemon and rye bread','complement','Dauvissat Chablis 1er Cru La Forest''s precise mineral matches Belon oysters from the same Kimmeridgean seas','starter','classic',1),
(201,'Roulot, Meursault, butter','fish','Sole bonne femme avec champignons et sauce vin blanc','elevate','Roulot Meursault Les Charmes'' butter and mineral elevates the classic sole bonne femme; French gastronomy at its purest','fish_course','classic',1),
(202,'Faiveley, Corton-Charlemagne, mineral','seafood','Homard à l''américaine — lobster in tomato and tarragon sauce','elevate','Faiveley Corton-Charlemagne''s Grand Cru mineral weight matches the complexity of homard à l''américaine','fish_course','classic',1),

-- WINE STILL: French First Growths & Rhône
(223,'Lafite, first growth, cabernet','beef','Lamb saddle Navarraise with rosemary and Périgord truffle','elevate','Lafite''s Pauillac elegance demands lamb saddle with truffle; the most refined pairing of the Left Bank','main','classic',1),
(224,'Mouton, first growth, cabernet','beef','Côte de boeuf with bordelaise sauce and Périgord truffle','complement','Mouton Rothschild''s powerful Pauillac character pairs with the most prestigious beef cut; the Périgord truffle bridges','main','classic',1),
(225,'Latour, structured, Pauillac','beef','Whole roasted Pauillac lamb with garlic and herbs','elevate','Pauillac AOC lamb is designated specifically to pair with Pauillac Premier Cru; the greatest terroir pairing in Bordeaux','main','classic',1),
(226,'Margaux, feminine, elegant','lamb','Rack of lamb with herbs de Provence and jus grand veneur','elevate','Château Margaux''s legendary elegance belongs with the delicate rack of lamb; feminine tannins meet the finest preparation','main','classic',1),
(227,'Haut-Brion, Graves, earthy','truffle','Scrambled eggs with Périgord black truffle and Haut-Brion toast','complement','Haut-Brion''s Graves terroir brings an earthy, smoky character; the truffle scrambled eggs echo that quality in food','starter','classic',1),
(228,'Pétrus, Pomerol, Merlot','beef','Filet de boeuf Rossini with foie gras and Périgueux truffle sauce','elevate','Pétrus is arguably the world''s most famous wine; Tournedos Rossini matches its luxury and the iron of Pomerol clay','main','classic',1),
(229,'Cheval Blanc, Saint-Emilion, Cab Franc','truffle','Truffle risotto bianco with aged Comté and Périgord truffle','elevate','Cheval Blanc''s exceptional Cab Franc component bridges the truffle''s mineral depth; an iconic Right Bank pairing','starter','classic',1),
(230,'Pavillon Blanc, Margaux, white','seafood','Turbot en papillote with mushroom duxelles and Champagne sauce','elevate','Pavillon Blanc de Margaux is a great Bordeaux Blanc; turbot en papillote with mushroom demands this calibre of white','fish_course','classic',1),
(231,'Léoville Las Cases, Saint-Julien, second growth','beef','Carré d''agneau rôti avec jus d''herbes et purée de céleri','complement','Las Cases''s super-second character belongs with rack of lamb; Saint-Julien''s elegance is the natural lamb partner','main','classic',2),
(232,'Cos d''Estournel, Saint-Estèphe, spice','lamb','Navarin d''agneau printanier with spring vegetables','complement','Cos d''Estournel''s spice and structure bridges the spring lamb and young vegetables; a structured wine for a bright dish','main','classic',2),
(233,'La Mouline, Côte-Rôtie, Viognier','lamb','Gigot d''agneau rôti aux herbes avec jus Côte-Rôtie','complement','La Mouline contains 11% Viognier co-fermented; the floral lift and the lamb''s herb crust echo each other','main','classic',1),
(234,'La Landonne, Côte-Rôtie, Syrah pure','game','Venison (chevreuil) rôti avec sauce grand veneur et griottes','complement','La Landonne''s all-Syrah power demands the richest game; griotte cherries bridge the wine''s dark mineral character','main','classic',1),
(235,'Chave Hermitage, northern Rhône, apex','beef','Daube de boeuf à la provençale with Hermitage wine','complement','Braising in the same Hermitage appellation wine creates a closed terroir loop; Chave demands this preparation','main','classic',1),
(236,'La Chapelle, Hermitage, Jaboulet','game','Grouse rôtie avec foie gras toast and quince compote','complement','La Chapelle''s legendary vintages belong with autumn grouse; the foie gras bridge was established in the cellar books','main','classic',1),
(237,'Clape Cornas, Syrah, granite','game','Wild boar sausage with celeriac purée and Cornas wine reduction','complement','Clape Cornas''s granite-born Syrah demands wild boar; the wine reduction ties the terroir to the plate','main','classic',1),
(238,'Rayas, CdP, Grenache pure','truffles','Roasted quail stuffed with foie gras and Périgord truffle','elevate','Château Rayas''s legendary old-vine Grenache elevates foie-stuffed quail; both are rare and demand the highest respect','main','classic',1),
(239,'Beaucastel, CdP, complex blend','meat','Pieds et paquets (lamb tripe with trotters) à la marseillaise','complement','Beaucastel''s complex southern Rhône blend pairs with the bold Provençal offal preparation; a regional classic','main','adventurous',2),
(240,'Condrieu, Viognier, floral','seafood','Languedoc langoustines with saffron and Viognier beurre blanc','elevate','Vernay Coteau de Vernon Viognier elevates langoustines; the same Viognier used in the beurre blanc creates unity','fish_course','classic',1),

-- WINE STILL: Loire
(299,'Silex, Loire, mineral','seafood','Fine de Claire oysters with Sancerre frozen mignonette','complement','Dagueneau Silex''s flint mineral character pairs with de Claire oysters; the frozen Sancerre mignonette creates a total pairing','starter','classic',1),
(300,'Pur Sang, Pouilly, mineral','seafood','Marinated raw Loire salmon with lemon verbena and cucumber','complement','Pur Sang''s pure mineral expression pairs with river fish from the same Loire; a purist''s regional pairing','fish_course','classic',1),
(301,'Vouvray sec, Chenin, mineral','seafood','Rillettes de sandre (pike-perch) on sourdough with cornichons','complement','Huet Vouvray Sec''s mineral Chenin Blanc pairs with Loire pike-perch; the river fish tradition of the Touraine','starter','classic',2),
(302,'Vouvray demi-sec, Chenin, honey','cheese','Chèvre cendré with Loire honey and walnut bread','complement','Vouvray Demi-Sec''s gentle sweetness bridges the ash-covered goat cheese and Loire honey; a classic Touraine pairing','cheese','classic',1),
(303,'Coulée de Serrant, Chenin, biodynamic','seafood','Steamed Loire mussels with Muscadet and parsley','complement','Nicolas Joly''s biodynamic Chenin bridges the Loire mussel; both come from the same river''s ecosystem','fish_course','classic',1),
(304,'Sancerre, Cotat, Les Monts Damnés','cheese','Crottin de Chavignol AOP with Loire honey','complement','Cotat''s Sancerre and Crottin de Chavignol are the Loire''s defining terroir pairing; both produced in the same village','cheese','classic',1),
(305,'Sancerre, Vacheron, biodynamic','seafood','Loire asparagus with sauce mousseline and smoked Loire salmon','complement','Vacheron''s biodynamic Sancerre pairs with Loire asparagus; both express the terroir of the same valley floor','starter','classic',2),
(306,'Muscadet, Clisson, aged','seafood','Moules marinières à la crème with sourdough baguette','complement','Muscadet Clisson''s 10-year sur lie ageing creates complexity that matches the creamy mussel sauce; a Nantes classic','main','classic',1),

-- WINE STILL: Alsace
(307,'Clos Sainte Hune, Riesling, apex','seafood','Sandre en matelote with Riesling sauce and quenelles','elevate','Clos Sainte Hune is the greatest Alsace Riesling; the freshwater fish preparation with Riesling sauce is the Alsace tradition','fish_course','classic',1),
(308,'Cuvée Frédéric Emile, Riesling','seafood','Tarte flambée (flammekueche) with onion, lardons and crème','complement','Frédéric Emile''s richness and petrol notes pair with the onion and smoky lardons of flammekueche; the Alsace hearth pairing','casual','classic',1),
(309,'Clos Windsbuhl, Riesling, Colmar','seafood','Choucroute garnie with saucisses and smoked ham hock','complement','Zind-Humbrecht Riesling''s mineral freshness cuts through the choucroute''s richness; an Alsace tradition of wine and sauerkraut','main','classic',1),
(310,'Pinot Gris, Hengst, Grand Cru','poultry','Foie gras d''Alsace au torchon with Gewurztraminer gelée','complement','Hengst Grand Cru Pinot Gris''s broad richness pairs with the torchon foie gras; Gewurztraminer gelée bridges the local tradition','starter','classic',1),
(311,'Weinbach, Schlossberg, Riesling','seafood','Écrevisses à l''Alsacienne with Riesling and cream sauce','elevate','Sainte Catherine''s Schlossberg Grand Cru Riesling elevates écrevisses in Alsace Riesling sauce; a closed flavour loop','fish_course','classic',1),
(312,'Hugel Jubilee, Riesling, reliable','food','Munster AOP fromage with cumin seed and warm bread','complement','Hugel Jubilee Riesling and Munster cheese is Alsace''s essential pairing; the petrol and spice of the wine bridge the pungent cheese','cheese','classic',1),
(314,'Gewurztraminer, Trimbach, spice','food','Gewurztraminer foie gras terrine with Sauternes gelée','complement','Seigneurs de Ribeaupierre''s opulent Gewurztraminer pairs with foie gras terrine; the lychee character bridges the liver','starter','classic',1),
(315,'Muenchberg, Ostertag, Grand Cru','seafood','Ombre chevalier (Arctic char) meunière with brown butter','complement','Ostertag Muenchberg''s volcanic mineral character elevates the delicate Arctic char; an Alsace trout stream pairing','fish_course','classic',2),
(316,'Marcel Deiss, Bergheim, blend','cheese','Aged Alsace Munster with caraway bread and pickled vegetables','complement','Marcel Deiss''s field blend philosophy pairs with the complexity of aged Munster; an Alsace culinary philosophy pairing','cheese','established',2),

-- WINE STILL: Italy (325-345)
(325,'Gaja, Barbaresco, Nebbiolo','beef','Braised beef cheeks (brasato al Barolo) with polenta','complement','Gaja Barbaresco''s noble Nebbiolo character pairs with the classic Piedmontese braised beef; polenta absorbs the wine''s tannin','main','classic',1),
(326,'Sorì Tildìn, single vineyard, Gaja','truffle','Tajarin pasta with white truffle and butter — Alba','elevate','Sorì Tildìn''s single vineyard depth elevates the most precious pasta in Piedmont; white truffle demands this calibre','main','classic',1),
(327,'Falletto, Barolo, Giacosa','game','Wild hare (lepre in civet) with polenta and gremolata','complement','Bruno Giacosa Falletto''s Serralunga power demands wild hare; the civet sauce''s blood richness is balanced by the Nebbiolo','main','classic',1),
(328,'Monfortino, legendary, Conterno','beef','Stracotto al Barolo — long-braised beef in Barolo wine','complement','Braising in Barolo and drinking Barolo is Piedmont''s most authentic culinary tradition; Monfortino deserves the finest cut','main','classic',1),
(329,'Mascarello, traditional Barolo','truffle','White truffle shaved over scrambled eggs and butter','elevate','Bartolo Mascarello''s traditional Barolo is Piedmont''s conscience; the white truffle scrambled eggs shares that purity','starter','classic',1),
(330,'Vietti Castiglione, approachable Barolo','pasta','Risotto al Barolo with Castelmagno cheese and truffle','complement','Castiglione''s approachable style pairs with risotto al Barolo; drinking the wine used in the risotto creates unity','main','classic',2),
(331,'Bricco delle Viole, altitude, elegant','pasta','Tajarin al burro e tartufo bianco d''Alba','complement','Bricco delle Viole''s altitude and elegance bridge the delicate tajarin and white truffle; a Verduno hilltop pairing','main','classic',2),
(332,'Roagna, Barbaresco, traditional','truffle','Fonduta valdostana with white truffle and grissini','complement','Roagna''s Barbaresco Crichet Pajè pairs with the Piedmontese fondue; truffle bridges the Nebbiolo tannin and cheese','starter','classic',2),
(333,'Ceretto, Bricco Rocche, modern','beef','Agnolotti dal plin with meat filling and Barolo wine reduction','complement','Ceretto''s modern Barolo pairs with the agnolotti dal plin; the pasta''s three-meat filling bridges the wine''s complexity','main','classic',2),
(334,'Biondi-Santi, Brunello, Riserva','truffle','Pappardelle al cinghiale (wild boar pasta) with truffles','elevate','Biondi-Santi Riserva belongs at the summit of Italian gastronomy; wild boar pappardelle with truffle is its equal','main','classic',1),
(335,'Sassicaia, Bolgheri, Cabernet','beef','Florentine T-bone (bistecca alla fiorentina) at 1.2kg','complement','Sassicaia''s Cabernet precision and Bolgheri warmth belongs with the bistecca; both are Tuscan luxury without compromise','main','classic',1),
(336,'Ornellaia, Bolgheri Superiore, blend','truffle','Tagliolini al tartufo nero di Norcia with butter and sage','elevate','Ornellaia''s Bolgheri elegance elevates the Norcia black truffle pasta; both are expressions of Italian art','main','classic',1),
(337,'Tignanello, Super Tuscan, pioneer','pasta','Pappardelle al ragù di cinghiale with Pecorino Toscano','complement','Tignanello''s pioneering blend pairs with wild boar pappardelle; the Super Tuscan tradition began at the same table','main','classic',1),
(338,'Le Pergole Torte, Sangiovese pure, Montevertine','truffle','Risotto al tartufo bianco di San Miniato with Parmesan','complement','Le Pergole Torte''s pure Sangiovese character bridges the truffle risotto; Chianti Classico terroir in its purest expression','main','classic',1),
(339,'Flaccianello, Super Tuscan, Fontodi','beef','Bistecca di vitella bianca con salsa verde e capers','complement','Flaccianello''s velvety structure pairs with the veal bistecca; salsa verde bridges the wine''s herbal Sangiovese notes','main','classic',2),
(340,'Cepparello, Isole e Olena, Sangiovese','pasta','Ribollita (Tuscan bean soup) with black kale and sourdough','complement','Cepparello''s Florentine character belongs with ribollita; the earthy Sangiovese tannins bridge the bread and bean soup','main','classic',2),
(341,'Testamatta, Bibi Graetz, volcanic','meat','Porchetta toscana with fennel pollen and crispy crackling','complement','Testamatta''s volcanic Tuscany power pairs with the rich porchetta; fennel pollen bridges the wine''s herbal character','main','established',2),
(342,'Dal Forno, Amarone, Valpolicella','cheese','Aged Parmigiano-Reggiano 36 months with balsamic tradizionale','complement','Dal Forno Amarone''s extraordinary concentration matches aged Parmigiano''s crystalline umami; 12-year balsamic bridges both','cheese','classic',1),
(343,'Quintarelli, Amarone, legend','beef','Brasato all''Amarone with polenta taragna and bitter greens','complement','Quintarelli Amarone is braised in its own wine; drinking the same bottle beside the dish creates absolute culinary unity','main','classic',1),
(344,'Soave Classico, Pieropan, Calvarino','seafood','Risotto con capesante (scallop risotto) and saffron','complement','Calvarino''s volcanic white bridges the risotto''s rice starch and scallop sweetness; a Verona classic of volcanic and sea','main','classic',2),
(345,'Allegrini, Amarone, Classico','beef','Risotto all''Amarone with Amarone reduction and truffle oil','complement','Allegrini Amarone both in the glass and in the risotto; drinking the ingredient creates a complete flavour circle','main','classic',2),

-- WINE STILL: Spain
(351,'Unico, Vega Sicilia, iconic','beef','Lechazo asado — milk-fed lamb roasted in a wood-fired oven','elevate','Vega Sicilia Unico is Spain''s greatest wine; Ribera''s milk-fed lechazo is its ordained partner at the Castilian table','main','classic',1),
(352,'Pingus, Dominique, Tempranillo','beef','Slow-roasted Ribera del Duero suckling pig with herbs','complement','Pingus''s profound Tempranillo intensity belongs with Segovia suckling pig; Ribera del Duero''s most authentic pairing','main','classic',1),
(353,'Prado Enea, Gran Reserva, Rioja','beef','Chuletón de vaca vieja (aged Basque beef chop) with piquillo','complement','Prado Enea Gran Reserva''s decade of aging pairs with the aged Basque beef; both demand patience and reward it','main','classic',2),
(354,'Viña Tondonia, Lopez de Heredia, oxidative','cheese','Aged Manchego Curado with quince (membrillo) and almonds','complement','Viña Tondonia''s oxidative age-worthy character pairs with aged Manchego; both are traditional Rioja table fixtures','cheese','classic',1),
(355,'L''Ermita, Alvaro Palacios, Garnacha','beef','Grilled Priorat lamb chops with wood-ash and romesco sauce','complement','L''Ermita''s Garnacha from ancient schist vines belongs with Priorat lamb; the schist terroir is in both the soil and the meat','main','classic',1),

-- WINE STILL: Greece
(362,'Santorini, Assyrtiko, volcanic','seafood','Grilled octopus on Santorini with capers, lemon and fava dip','complement','Sigalas Santorini Assyrtiko is produced on the same volcanic island as the grilled octopus; the purest terroir pairing','casual','classic',1),
(363,'Nykteri, oxidative, complex','seafood','Sea urchin (achinos) on sourdough with olive oil and lemon','complement','Nykteri''s oxidative complexity bridges the iodine-rich urchin; both express the Santorini''s mineral volcanic character','starter','classic',1),
(364,'Ramnista, Naoussa, Xinomavro','beef','Arnaki sta karvounia — charcoal-grilled Greek lamb chops','complement','Kir-Yianni Ramnista''s Xinomavro tannin and acid structure is built for Greek lamb; the charcoal bridges the mineral','main','classic',1),

-- WINE STILL: Lebanon
(367,'Musar Rouge, Bekaa Valley, complex','lamb','Slow-roasted leg of lamb with Lebanese seven-spice and pomegranate','complement','Chateau Musar''s complex Levantine character pairs with Lebanese lamb; the seven-spice blend bridges Cinsault and Cabernet','main','classic',1),

-- WINE STILL: Italy more
(371,'Barbera, Uccellone, bold','pasta','Pappardelle al ragù di coniglio (rabbit ragu) with sage butter','complement','Bricco dell''Uccellone''s concentrated Barbera pairs with the rabbit ragu; the Asti terroir demands rich pasta preparation','main','classic',2),
(372,'Dolcetto, Vajra, everyday','pasta','Tajarin al burro with white truffle shavings — simple','complement','Dolcetto d''Alba''s soft tannins and cherry fruit complement tajarin butter pasta; truffle elevates the everyday to sublime','main','classic',2),
(373,'Barbera, La Court, luxury','beef','Risotto con fonduta di Castelmagno e tartufo nero','complement','La Court''s luxury Barbera bridges the rich Castelmagno cheese fonduta; truffle binds the Asti terroir','main','classic',2),
(378,'Gavi, La Scolca, elegant','seafood','Cappon magro — Ligurian seafood and vegetable salad','complement','La Scolca Black Label Gavi is made for Ligurian seafood; cappon magro is the grandest expression of that tradition','fish_course','classic',2),
(379,'Gavi, Broglia, mineral','seafood','Fritto misto di mare with aioli and lemon','complement','La Meirana''s mineral Gavi pairs with the classic fried seafood mix; the clean Cortese acidity cuts through the oil','fish_course','classic',2),
(380,'Asinone, Vino Nobile, apex','beef','Pappardelle al ragù di cinghiale (wild boar) with pecorino','complement','Poliziano Asinone''s Vino Nobile purity bridges the boar ragu and aged pecorino; Montepulciano''s finest with local game','main','classic',2),
(381,'Avignonesi, Vino Nobile, classic','pasta','Pici cacio e pepe con guanciale e pecorino','complement','Avignonesi''s classic Vino Nobile pairs with the Montepulciano pasta tradition; both express the local Sangiovese terroir','main','classic',2),
(382,'Rosso di Montepulciano, everyday','pasta','Tagliatelle al ragù bolognese con Parmigiano','complement','Poliziano Rosso''s approachable everyday character pairs with the classic Bolognese; a straightforward and satisfying pairing','main','established',2),
(383,'Vernaccia, traditional, mineral','seafood','Fritto di paranza (tiny mixed fried fish) with lemon','complement','Montenidoli Tradizionale''s bitter-mineral character pairs with the simple fried fish; a San Gimignano tradition','fish_course','classic',2),
(384,'Vernaccia, Teruzzi, clean','seafood','Linguine alle vongole (clam pasta) with white wine and herbs','complement','Teruzzi Vernaccia''s clean mineral freshness pairs with clam pasta; a white wine bridges the seafood and the pasta starch','main','classic',2);
COMMIT;
