BEGIN;
INSERT INTO pairing_intelligence
  (beverage_product_id, food_flavour_profile, food_category, food_description, pairing_type, flavour_logic, meal_context, confidence, authority_tier)
VALUES
-- Baijiu (270-277)
(270,'baijiu, Moutai, Feitian, celebration','celebration','Whole Peking duck banquet with pancakes, scallion and hoisin','complement','Feitian Moutai is China''s most celebrated banquet spirit; a whole Peking duck feast is the signature banquet pairing','celebration','classic',1),
(271,'baijiu, aged, Moutai 15-year','dessert','Osmanthus jelly with goji berry and longan','complement','15-Year Moutai''s floral complexity bridges the osmanthus jelly; both express aged Chinese elegance','dessert','established',2),
(272,'baijiu, Prince, accessible Moutai','pork','Red-braised pork belly (hong shao rou) with steamed buns','complement','Moutai Prince''s approachable sauce fragrance bridges hong shao rou; the fat and soy richness needs the spirit''s cut','main','classic',2),
(273,'baijiu, Wuliangye, Nongxiang, grain','seafood','Steamed whole sea bass with ginger, scallion and soy','complement','Wuliangye''s rich grain-nong aroma bridges the steamed sea bass; both express subtle complexity without heaviness','main','established',2),
(274,'baijiu, National Cellar 1573, premium nong','beef','Dongpo beef (slow-braised beef shin) with fermented bean curd','complement','National Cellar 1573''s rich nong fragrance cuts the collagen richness of Dongpo beef; a Sichuan banquet classic','main','classic',2),
(275,'baijiu, Zisha Touqu, high proof nong','game','Braised wild hare with Shaoxing wine and dark soy','complement','Zisha Touqu 68°''s intense nong character bridges the braised hare''s richness; the high proof tames the game intensity','main','adventurous',2),
(276,'baijiu, Fenjiu, Fenxiang, light grain','cheese','Yunnan milk cake (rubing) with chilli and herbs','complement','Fenjiu''s clean fen fragrance bridges the mild Yunnan milk cake; the light grain aroma suits the delicate dairy','casual','established',2),
(277,'baijiu, Sanhua, triple distilled, rice','vegetable','Cold wood ear mushroom salad with chilli oil and vinegar','complement','Sanhua''s triple-distilled rice spirit bridges the wood ear''s crunch and chilli oil; a Guilin pairing of lightness','casual','established',2),

-- Beer ale (61, 63-69, 187, 443, 444)
(61,'porter, dark ale, roast malt','dessert','Sticky date pudding with toffee sauce and vanilla cream','complement','Sing Sing Porter''s roasted malt and dried fruit bridges the sticky date pudding; dark beer and dark dessert harmony','dessert','established',2),
(63,'IPA, Superpower, hoppy','casual','Loaded nachos with jalapeños, guacamole and sour cream','complement','Superpower IPA''s aggressive hops cut through the nachos richness; the carbonation lifts the cheese and chilli','casual','established',2),
(64,'IPA, Lush, tropical hops','casual','Fish tacos with lime slaw and chipotle crema','complement','Lush IPA''s tropical hops bridge the fish tacos'' citrus and smoke; a West Coast IPA pairing for Baja flavours','casual','classic',2),
(65,'pale ale, Mirror Pond, balanced','casual','Classic cheeseburger with sharp cheddar and pickles','complement','Mirror Pond Pale Ale''s balanced hop character bridges the classic burger; a PNW brewery''s perfect casual pairing','casual','classic',1),
(66,'IPA, Breakside, Pacific Northwest','casual','Korean fried chicken with gochujang glaze and sesame','bridge','Breakside IPA''s resinous bitterness bridges the Korean fried chicken''s heat; carbonation resets the palate between bites','casual','established',2),
(67,'amber ale, Dead Guy, malty','pork','Pulled pork sandwich with apple slaw and bourbon BBQ sauce','complement','Dead Guy Ale''s malt backbone bridges the slow-cooked pork; the smoky bourbon BBQ echoes the ale''s depth','casual','classic',2),
(68,'IPA, Ecliptic, West Coast','casual','Spicy Thai basil pork with fried egg over jasmine rice','bridge','Starburst IPA''s citrus brightness bridges the Thai basil pork''s heat and fish sauce; IPA and Thai food affinity','casual','established',2),
(69,'imperial stout, Double Stack, dessert-like','cheese','Aged Rogue Creamery Caveman Blue with walnut and honey','complement','Great Notion''s Imperial Stout bridges the pungent Caveman Blue; dark beer''s roast and the cheese''s intensity align','cheese','established',2),
(187,'hefeweizen, Weihenstephan, Bavarian','casual','Obatzda (Bavarian spiced cheese spread) with pretzels and radishes','complement','Weihenstephan Hefeweizen and Obatzda is the Bavarian beer garden''s defining pairing; both are Munich classics','casual','classic',1),
(443,'Kölsch, Gaffel, Cologne','casual','Halve Hahn (Cologne-style rye bread with Dutch Gouda and mustard)','complement','Gaffel Kölsch and Halve Hahn is Cologne''s most traditional Kneipe pairing; the crisp Kölsch suits the mild Gouda','casual','classic',1),
(444,'Altbier, Uerige, Düsseldorf','casual','Düsseldorfer Senfrostbraten (mustard roast beef) with rye bread','complement','Uerige Altbier and Düsseldorf mustard roast beef is the Altstadt''s classic table pairing','casual','classic',1),

-- Beer lager (58, 59, 62)
(58,'dark lager, Bench, roasty','casual','Pork and sauerkraut Reuben sandwich with Swiss cheese','complement','Bench Dark Lager''s roasty malt bridges the Reuben''s sauerkraut tang; a BC craft lager''s deli pairing','casual','established',2),
(59,'lager, Standard, crisp','casual','Grilled corn on the cob with chilli lime butter and cotija','complement','Standard Lager''s crisp carbonation bridges the grilled corn''s sweetness; a clean lager for a classic summer bite','casual','established',2),
(62,'Oktoberfest, amber, Märzen','casual','Weisswurst with sweet mustard and a pretzel Breze','complement','Oktoberfest Märzen and Weisswurst is Munich''s most iconic morning pairing; amber lager for white sausage at the Wiesn','casual','classic',1),

-- Beer wild (60, 186)
(60,'sour, wild, dry-hopped','cheese','Vermont Creamery Bonne Bouche goat cheese with honey','bridge','Nectarous'' dry-hopped acidity bridges the goat cheese and honey; wild ale and fresh chèvre share terroir expression','cheese','established',2),
(186,'Gueuze, Cantillon, lambic, wild','cheese','Aged Mimolette (24-month) with dark rye and butter','complement','Cantillon Gueuze''s acetic lactic complexity bridges the intensely nutty aged Mimolette; a classic Brussels pairing','cheese','classic',1),

-- Coffee (70-79, 370, 389-394)
(70,'coffee, Huehuetenango, natural, bright','dessert','Flourless chocolate cake with raspberry coulis and cream','complement','El Injerto Natural''s fruity brightness bridges the dark chocolate cake; Huehuetenango berry notes echo the raspberry','dessert','established',2),
(71,'coffee, Yirgacheffe, washed, floral','dessert','Lemon posset with fresh blueberries and shortbread','complement','Yirgacheffe Washed''s jasmine and citrus bridges the lemon posset; both express bright clean acidity','dessert','established',2),
(72,'coffee, Kenya AA, washed, wine-like','dessert','Black Forest cake with morello cherries and dark chocolate','complement','Kenya AA''s blackcurrant and tomato acidity bridges the Black Forest cherry; a complex coffee for a complex dessert','dessert','established',2),
(73,'coffee, house blend, espresso, balanced','casual','Almond croissant with marzipan filling and apricot glaze','complement','House Blend Espresso''s balanced caramel bridges the almond croissant; a classic café breakfast pairing','casual','classic',1),
(74,'coffee, Hair Bender, espresso, complex','dessert','Tiramisu with espresso-soaked savoiardi and mascarpone','complement','Stumptown Hair Bender as the espresso in the tiramisu creates a direct flavour loop; the blend pairs with itself','dessert','classic',1),
(75,'coffee, Stereo, blend, sweet','casual','Pain au chocolat with dark Valrhona chocolate filling','complement','Heart Roasters Stereo''s sweet complexity bridges the pain au chocolat; a Portland café morning classic','casual','established',2),
(76,'coffee, Caffe del Sol, espresso, Italian','casual','Biscotti di Prato with almond and orange zest','complement','Caffe del Sol''s Italian-style espresso belongs with traditional biscotti; the almond and orange echo the coffee''s finish','casual','classic',1),
(77,'coffee, Ethiopia Shantawene, natural, funky','dessert','Poached pears with cardamom custard and pistachio','complement','Shantawene Natural''s fermented fruit complexity bridges the poached pear and cardamom; both are aromatic and perfumed','dessert','established',2),
(78,'coffee, Colombia Huila, honey, sweet','casual','Cinnamon roll with cream cheese frosting','complement','Colombia Huila Honey''s sweetness and body bridges the cinnamon roll; both share caramel and spice warmth','casual','established',2),
(79,'coffee, Guatemala Antigua, washed, balanced','casual','Tres leches cake with condensed milk and rum cream','complement','Antigua''s balanced chocolate bridges the tres leches'' sweetness; a Central American coffee with a Central American dessert','dessert','established',2),
(370,'coffee, Turkish, cardamom, traditional','casual','Turkish delight (lokum) with rosewater and pistachio','complement','Mehmet Efendi Turkish Coffee and Turkish delight is the classic Ottoman café pairing; coffee and lokum belong together','casual','classic',1),
(389,'coffee, Yirgacheffe YCFCU, washed, Grade 1','casual','Ethiopian injera with tibs (sautéed beef) and berbere','complement','YCFCU Grade 1 Yirgacheffe bridges the injera feast; a coffee from the same Ethiopian highlands as the cuisine','casual','classic',1),
(390,'coffee, Konga Natural, fermented fruit','dessert','Chocolate and raspberry tart with crème fraîche','complement','Konga Natural''s berry fermentation notes bridge the chocolate-raspberry tart; natural process coffee for fruit desserts','dessert','established',2),
(391,'coffee, Sidama washed, clean, citrus','casual','Honey cake with orange blossom and toasted sesame','complement','Worka Sidama Washed''s clean citrus bridges the honey cake''s floral sweetness; both are bright and aromatic','casual','established',2),
(392,'coffee, Sidama honey, sweet, complex','dessert','Basque burnt cheesecake with passion fruit coulis','complement','Bensa Bore Honey''s complex sweetness bridges the burnt cheesecake caramel; passion fruit echoes the coffee''s tropicality','dessert','established',2),
(393,'coffee, Harrar longberry, natural, wild','casual','Date and walnut loaf with butter and sea salt','complement','Harrar Longberry''s blueberry and wild fruit bridges the date loaf''s richness; Ethiopian natural coffees suit dense cakes','casual','established',2),
(394,'coffee, Harrar HFCU, natural, cooperative','casual','Banana bread with tahini and dark chocolate chips','complement','Harrar HFCU Natural''s berry brightness bridges the banana bread; the tahini''s nuttiness suits the coffee''s complexity','casual','established',2),

-- NA crafted (81, 83, 85, 87, 88, 89, 189)
(81,'NA, Seedlip Spice, aromatic, botanical','casual','Spiced Middle Eastern mezze platter with hummus and dukkah','complement','Seedlip Spice 94''s warm cardamom and allspice bridge the spiced mezze; botanical NA spirit for an aromatic table','casual','established',2),
(83,'NA, Cawston Press, sparkling apple, British','casual','Mini pork sausage rolls with apple and sage chutney','complement','Cawston Sparkling Apple''s orchard freshness bridges the pork sausage roll; a British afternoon pairing','casual','established',2),
(85,'NA, Fever-Tree, tonic, quinine','casual','Cucumber and smoked salmon canapés with dill cream','complement','Fever-Tree Tonic''s quinine bitterness bridges the smoked salmon and dill; a classic aperitif hour pairing','aperitif','established',2),
(87,'NA, Wize Monkey, coffee leaf tea, light','casual','Avocado toast with poached egg and Tajín chilli','complement','Wize Monkey Coffee Leaf''s light malt bridges the avocado and egg; a sustainable brunch pairing','casual','suggested',2),
(88,'NA, Sanpellegrino, Aranciata, orange','casual','Arancini (Sicilian rice balls) with tomato ragù and mozzarella','complement','Aranciata''s Sicilian orange bridges the arancini''s golden crust; a southern Italian table''s classic pairing','casual','established',2),
(89,'NA, Curious Elixirs No. 1, bittersweet','casual','Charcuterie board with cornichons, Dijon and sourdough','complement','Curious Elixirs No. 1''s bittersweet complexity bridges a classic charcuterie board; a sophisticated NA aperitif pairing','aperitif','established',2),
(189,'NA, Seedlip Spice, warm, botanical','casual','Cheese and chutney on seeded crackers with apple','complement','Seedlip Spice''s warm spice profile bridges the cheese and chutney; an NA aperitif alternative for a wine-style cheese board','casual','established',2),

-- NA dealcoholised (82, 188)
(82,'NA, Gruvi Rosé, dealcoholised, bubbly','casual','Strawberry and burrata salad with aged balsamic and basil','complement','Gruvi Bubbly Rosé''s berry freshness bridges the strawberry and burrata; a dealcoholised rosé for a summer salad','casual','established',2),
(188,'NA, Leitz Zero Riesling, dealcoholised, German','seafood','Smoked salmon with pickled cucumber and rye bread','complement','Leitz Zero Riesling''s mineral structure bridges the smoked salmon; a dealcoholised Riesling for a Riesling classic pairing','starter','established',2),

-- NA fermented (80, 84, 86, 190)
(80,'kombucha, Seasoning, fermented, umami','casual','Japanese tofu salad with ponzu, sesame and shiso','complement','Seasoning Kombucha''s fermented umami bridges the ponzu tofu salad; both express fermented depth with lightness','casual','established',2),
(84,'kombucha, Tonica Original, dry, probiotic','casual','Greek salad with Kalamata olives, feta and dried oregano','complement','Tonica Dry Kombucha''s acidity bridges the Greek salad''s brine; the fermented culture matches the olive and feta','casual','established',2),
(86,'kombucha, Wild Tonic, honey, Jun','casual','Grain bowl with roasted squash, tahini and pomegranate','complement','Wild Tonic Jun''s honey complexity bridges the grain bowl''s sweet and nutty elements; a wellness pairing','casual','suggested',2),
(190,'kombucha, GT Synergy, gingerade, fermented','casual','Sushi rice bowl (donburi) with salmon, avocado and pickled ginger','complement','GT''s Gingerade Kombucha bridges the sushi donburi; the ginger note connects the fermented drink to the pickled ginger','casual','established',2),

-- Sake — Niigata group (90-99, 112)
(90,'sake, Junmai Ginjo, Osake, Pacific NW','seafood','BC sablefish (black cod) with miso and kelp butter','complement','Osake Junmai Ginjo''s Pacific NW origin bridges BC sablefish; both are expressions of the same coastal terroir','fish_course','classic',1),
(91,'sake, Junmai Ginjo, Momokawa Diamond','seafood','Geoduck sashimi with ponzu and micro shiso','complement','Momokawa Diamond''s delicate ginjo character bridges the geoduck''s crisp oceanic sweetness; a Pacific NW sake pairing','fish_course','established',2),
(92,'sake, Junmai Ginjo, Hakutsuru','seafood','Yellowtail (hamachi) sashimi with yuzu kosho','complement','Hakutsuru Junmai Ginjo''s clean profile bridges the hamachi''s fatty richness; yuzu echoes the sake''s citrus lift','fish_course','classic',1),
(93,'sake, Junmai Daiginjo, Gekkeikan Horin','seafood','Uni (sea urchin) on warm rice with nori','complement','Gekkeikan Horin''s daiginjo elegance suits the oceanic richness of uni; the mineral clean finish prepares the next bite','fish_course','classic',1),
(94,'sake, Junmai Ginjo, Ninki-Ichi Gold','seafood','Hirame (flounder) sashimi with sudachi citrus','complement','Ninki-Ichi Gold''s elegant fruity character bridges the delicate flounder; sudachi links the sake''s subtle citrus note','fish_course','established',2),
(95,'sake, Junmai, Masumi Okuden, Nagano','seafood','Grilled Pacific oysters with sake and butter','complement','Masumi Okuden''s clean junmai character bridges the grilled oyster and butter; a sake farm''s oyster pairing tradition','fish_course','classic',1),
(96,'sake, Junmai Ginjo, Rihaku, Wandering Poet','seafood','Salmon tataki with ginger ponzu and sesame','complement','Rihaku Wandering Poet''s ginjo fragrance bridges salmon tataki; the ginger echoes the sake''s herbal complexity','fish_course','established',2),
(97,'sake, Junmai Daiginjo, G Joy, Fushimi','seafood','Creamy crab chawanmushi with dashi and mitsuba','complement','G Joy''s Fushimi elegance bridges the crab chawanmushi; the dashi''s umami reflects the sake''s clean mineral depth','starter','classic',1),
(98,'sake, Junmai, Kizakura, accessible','casual','Karaage chicken with kewpie mayo and lemon','complement','Kizakura Junmai''s clean approachable character bridges the karaage''s fried crunch; an everyday sake for everyday fried chicken','casual','classic',1),
(99,'sake, Junmai Ginjo, Ben Kadoya Orizuru','seafood','Hotate (scallop) sashimi with sudachi and sea salt','complement','Ben Kadoya Orizuru''s ginjo delicacy bridges the scallop''s sweet oceanic purity; a Yamaguchi sake for a pristine shellfish','fish_course','established',2),
(112,'sake, Junmai Daiginjo, Kubota Manju','seafood','Kuruma ebi (Japanese tiger prawn) with ponzu gel','complement','Kubota Manju''s prestige daiginjo elegance belongs with the finest Japanese tiger prawn; a Niigata benchmark pairing','fish_course','classic',1),

-- Sake Nada group (113-133)
(113,'sake, Honjozo, Kubota Senju, everyday','casual','Yakitori (chicken skewers) with tare sauce and shichimi','complement','Kubota Senju''s tokubetsu honjozo suits grilled yakitori; the tare''s sweet-soy echoes the sake''s clean depth','casual','classic',1),
(114,'sake, Junmai Daiginjo, Kubota Hyakuju','seafood','Ayu (sweetfish) shioyaki (salt-grilled) with sudachi','complement','Kubota Hyakuju''s daiginjo purity bridges the delicate ayu; salt and sudachi draw out the river fish''s natural sweetness','fish_course','classic',1),
(115,'sake, Junmai Ginjo, Hakkaisan','seafood','Kaki (oyster) nabe (hot pot) with tofu and hakusai','complement','Hakkaisan Junmai Ginjo''s Snow Country character bridges the oyster nabe; a Niigata sake for the winter hot pot tradition','main','classic',1),
(116,'sake, Yukimuro Snow-Aged, Hakkaisan, rare','seafood','Shabu-shabu with Wagyu beef and ponzu dipping sauce','complement','Yukimuro''s snow-aged refinement belongs with Wagyu shabu-shabu; both are peak Japanese culinary craft','main','classic',1),
(117,'sake, Honjozo, Koshi no Kanbai Sai','casual','Onigiri (rice ball) with pickled plum and nori','complement','Koshi no Kanbai Sai''s clean honjozo bridges the simple onigiri; a Niigata sake for Niigata''s finest rice tradition','casual','classic',1),
(118,'sake, Junmai Daiginjo, Koshi no Kanbai Muku','seafood','Kaiseki sashimi course — seasonal selection','complement','Muku''s daiginjo elegance belongs with kaiseki sashimi; the seasonal selection draws out the sake''s subtle complexity','fish_course','classic',1),
(119,'sake, Junmai, Yoshinogawa Gensen, dry','seafood','Grilled mackerel (saba shioyaki) with grated daikon','complement','Yoshinogawa Gensen''s dry junmai bridges the mackerel''s oily richness; daikon cleanses and the sake refreshes','main','classic',1),
(120,'sake, Junmai Ginjo, Yoshinogawa Winter Warrior','seafood','Kani (snow crab) with ponzu and momiji oroshi','complement','Winter Warrior''s Niigata character belongs with snow crab; a cold-country sake for the cold-country crab tradition','fish_course','classic',1),
(121,'sake, Tokubetsu Junmai, Kakurei','seafood','Saba (mackerel) oshizushi (pressed sushi) with pickled ginger','complement','Kakurei''s clean tokubetsu junmai bridges pressed mackerel sushi; Niigata rice and mackerel are a natural combination','fish_course','established',2),
(122,'sake, Kimoto Junmai, Kiku-Masamune','pork','Kakuni (braised pork belly) with mustard and Japanese mustard greens','complement','Kiku-Masamune Kimoto''s full-bodied lactic depth bridges the braised pork belly; kimoto method suits rich preparations','main','classic',1),
(123,'sake, Taru Sake, Kiku-Masamune, cedar','casual','Robatayaki assorted skewers with miso dip and salt','complement','Kiku-Masamune Taru Sake''s cedar fragrance bridges the robata smoke; the wood character links to the charcoal grill','casual','classic',1),
(124,'sake, Junmai, Ozeki, everyday','casual','Edamame with sea salt and a cold tofu (hiyayakko)','complement','Ozeki Junmai''s everyday accessibility suits the simple edamame and cold tofu; a sake for the izakaya table''s first courses','casual','classic',1),
(125,'sake, Junmai Daiginjo, Sawanotsuru, Kobe','seafood','Tai (sea bream) sashimi with fresh wasabi and ponzu','complement','Sawanotsuru Junmai Daiginjo''s Nada elegance bridges the sea bream sashimi; tai is Japan''s celebratory fish','fish_course','classic',1),
(126,'sake, Junmai Ginjo, Nihonsakari, Fushimi','seafood','Tempura course: shrimp, lotus root, shishito pepper','complement','Nihonsakari Ginjo''s Fushimi delicacy bridges the tempura''s light oil; the ginjo fragrance lifts the batter','main','established',2),
(127,'sake, Junmai Ginjo, Konishi Shirayuki','seafood','Grilled Kyoto-style yudofu (hot tofu) with yuzu and dashi','complement','Konishi Shirayuki''s Fushimi ginjo bridges the delicate yudofu; a Kansai sake for a Kansai temple vegetarian dish','main','classic',1),
(128,'sake, Junmai Daiginjo, Hakutsuru Tora','seafood','Prawn and water chestnut dumplings with XO sauce','complement','Hakutsuru Tora no Ko''s daiginjo elegance bridges the refined dumpling; XO sauce mirrors the sake''s umami depth','starter','established',2),
(129,'sake, Junmai Daiginjo, Tsuki no Katsura Iwai','seafood','Kyoto-style kaiseki soup: hamaguri clam with mitsuba','complement','Tsuki no Katsura Iwai''s Fushimi daiginjo bridges the delicate clam soup; both represent Kyoto''s refined minimalism','starter','classic',1),
(130,'sake, Nigori, Tsuki no Katsura, cloudy','dessert','Matcha panna cotta with red bean paste and kinako','complement','Tsuki no Katsura Nigori''s unfiltered creaminess bridges the matcha panna cotta; the red bean echoes the sake''s natural sweetness','dessert','established',2),
(131,'sake, Junmai Daiginjo, Tamanohikari Bizen Omachi','seafood','Hirame kobujime (flounder cured in kombu) with pickled sakura','complement','Bizen Omachi''s Fushimi terroir bridges the kombu-cured flounder; both draw on Japanese preservation and umami tradition','fish_course','classic',1),
(132,'sake, Junmai Ginjo, Tamanohikari','seafood','Grilled Pacific salmon with sake and mirin glaze','complement','Tamanohikari Junmai Ginjo''s Fushimi character bridges the sake-glazed salmon; drinking the wine used in the glaze','main','classic',1),
(133,'sake, Junmai Nigori, Tozai Snow Maiden','dessert','Yuzu sorbet with black sesame tuile and candied yuzu peel','complement','Snow Maiden Nigori''s light sweetness bridges the yuzu sorbet; the sesame adds depth to both the drink and dessert','dessert','established',2),

-- Sake Yamaguchi group (134-141)
(134,'sake, Junmai Daiginjo, Dassai 23, premium','seafood','Ikura (salmon roe) with warm rice and nori','complement','Dassai 23''s ultra-premium polish bridges the ikura''s briny richness; the rice echoes the sake''s rice origin','fish_course','classic',1),
(135,'sake, Junmai Daiginjo, Dassai 39','seafood','Steamed clams (asari) in sake and butter with shiso','complement','Dassai 39''s ginjo fragrance bridges the sake-steamed clams; the sake in the broth creates a direct flavour link','starter','classic',1),
(136,'sake, Junmai Daiginjo, Dassai Beyond, rare','celebration','Kaiseki full course with seasonal ingredients at the chef''s table','complement','Dassai Beyond is Japan''s most celebrated sake; a full kaiseki chef''s table experience is the only worthy pairing','celebration','classic',1),
(137,'sake, Junmai, Juyondai Honmaru, legendary','seafood','Shirako (cod milt) in light dashi with yuzu','complement','Juyondai Honmaru''s legendary clean character bridges the delicate shirako; both are revered Japanese delicacies','fish_course','adventurous',1),
(138,'sake, Junmai Daiginjo, Born Gold','seafood','Firefly squid (hotaru-ika) with miso and vinegar miso','complement','Born Gold''s Fukui refinement bridges the firefly squid''s oceanic intensity; a Fukui sake for a Fukui spring delicacy','starter','classic',1),
(139,'sake, Junmai Daiginjo, Born Dream','seafood','Nodoguro (blackthroat sea perch) sashimi with fresh wasabi','complement','Born Dream''s peak daiginjo elegance bridges the luxurious nodoguro; Japan''s most prized white fish for Japan''s finest sake','fish_course','classic',1),
(140,'sake, Ginjo, Dewazakura Oka Cherry','seafood','Kisu (Japanese whiting) tempura with tentsuyu dipping sauce','complement','Dewazakura''s delicate ginjo bridges the light kisu tempura; Yamagata''s gentle fruity sake suits the most delicate fish','fish_course','classic',1),
(141,'sake, Junmai Ginjo, Aramasa No. 6','seafood','Raw oysters from Miyagi with the barest squeeze of citrus','complement','Aramasa No. 6''s Akita character bridges Miyagi raw oysters; a minimal pairing of Japan''s most natural sake and ocean','starter','classic',1),

-- Shochu (155-170)
(155,'shochu, Kuro Kirishima, imo, black koji','casual','Yakitori negima (chicken and leek) with salt','complement','Kuro Kirishima''s roasty black koji imo character bridges the salted chicken and leek yakitori; Kagoshima casual pairing','casual','classic',1),
(156,'shochu, Red Kirishima, imo, elegant','seafood','Kagoshima kurobuta (black pork) shabu-shabu with ponzu','complement','Red Kirishima''s elegant imo profile bridges the Kagoshima kurobuta shabu-shabu; a Kyushu local pairing of prestige','main','classic',1),
(157,'shochu, Toko, imo, Yamagata','casual','Satsuma-age (fried fish cake) with grated ginger and soy','complement','Toko Imo Shochu''s Kyushu character bridges the fried fish cake; both are expressions of Japanese traditional craft','casual','established',2),
(158,'shochu, Toko Premium Aged 40°, complex','casual','Buta no kakuni (pork belly) with Japanese mustard','complement','Toko Premium Aged''s high-proof complexity bridges the braised pork belly; age in the shochu suits slow cooking','main','established',2),
(159,'shochu, Komasa Sakurajima, volcanic, imo','casual','Kibinago (silver-stripe herring) karaage with lemon','complement','Komasa Sakurajima''s volcanic mineral character bridges the delicate Kagoshima kibinago; a Sakurajima island pairing','casual','classic',1),
(160,'shochu, Komasa Jozen, light imo','seafood','Sashimi moriawase with various seasonal fish','complement','Komasa Jozen''s lighter imo profile bridges a mixed sashimi selection; the restraint suits delicate raw fish','fish_course','established',2),
(162,'shochu, Iichiko Silhouette, mugi, barley','casual','Niku-jaga (Japanese meat and potato stew)','complement','Iichiko Silhouette''s clean mugi character bridges niku-jaga''s comfort; barley shochu for Japan''s home-cooked potato stew','casual','classic',1),
(163,'shochu, Iichiko Frasco 30°, premium mugi','casual','Chicken nanban (fried chicken with tartar sauce) from Miyazaki','complement','Iichiko Frasco''s premium barley complexity bridges the nanban chicken; a Kyushu spirit for Kyushu''s comfort food','casual','classic',1),
(164,'shochu, Naka Naka, mugi, aged','casual','Mentaiko (spiced cod roe) on warm rice with butter','complement','Naka Naka''s aged barley character bridges the mentaiko richness; both are Kyushu products meeting on the rice bowl','casual','classic',1),
(165,'shochu, Iichiko Special 43°, premium, high proof','casual','Motsu nabe (offal hot pot) with garlic chives and tofu','complement','Iichiko Special 43°''s intensity bridges the rich offal hot pot; Fukuoka''s motsu nabe tradition demands a strong shochu','main','classic',1),
(166,'shochu, Helios Ryukyu Awamori, rice, tropical','casual','Champuru (Okinawan stir-fry) with goya (bitter melon) and tofu','complement','Helios Awamori''s tropical rice character bridges the champuru''s bitter melon; an Okinawan spirit for Okinawan food','casual','classic',1),
(167,'shochu, Zuisen Awamori Koshu 5-Year, aged','casual','Rafutē (Okinawan braised pork belly) with island tofu','complement','Zuisen 5-Year Koshu''s aged depth bridges the slow-braised Okinawan rafutē; aged awamori for aged pork preparation','main','classic',1),
(168,'shochu, Zuisen Awamori Koshu 10-Year, complex','casual','Okinawa soba (noodles) with pork belly and green onion','complement','Zuisen 10-Year''s deeper complexity bridges Okinawa soba''s rich pork broth; a decade of aging for Okinawa''s noodle culture','casual','classic',1),
(169,'shochu, Kumesen Kusu 3-Year, young awamori','casual','Mimiga (pig ear) with vinegar and chilli','complement','Kumesen 3-Year''s young awamori brightness bridges the vinegared pig ear; Okinawan spirit for Okinawan izakaya classic','casual','established',2),
(170,'shochu, Kumesen Kusu 25-Year, rare aged awamori','casual','Yakimiso with seasonal vegetables on the grill','complement','Kumesen 25-Year''s rare aged character bridges the miso-grilled vegetables; a long-aged spirit for a slow-fire dish','casual','adventurous',2),

-- Spirits agave (161, 171)
(161,'mezcal, Del Maguey Vida, Espadin, smoky','casual','Grasshopper tacos (chapulines) with guacamole and lime','complement','Del Maguey Vida''s smoke bridges the nutty grasshopper taco; a Oaxacan mezcal for Oaxacan pre-Hispanic tradition','casual','adventurous',2),
(171,'tequila, Fortaleza Blanco, Jalisco, agave forward','casual','Aguachile verde with shrimp, cucumber and serrano','complement','Fortaleza Blanco''s bright agave bridges the aguachile''s citrus and heat; a Jalisco tequila for a Pacific coast dish','casual','established',2),

-- Spirits brandy (45, 55, 317-321, 324)
(45,'brandy, pear, Pacific NW, eau de vie','dessert','Pear tarte Tatin with vanilla cream and almond praline','complement','Pear Brandy''s distilled orchard purity bridges the pear tarte Tatin; drinking the essence of the same fruit','dessert','classic',1),
(55,'brandy, table, aged, Crispin''s Table','casual','BC apple and aged cheddar board with seedy mustard','complement','Crispin''s Table Brandy''s approachable warmth bridges the apple and aged cheddar; a BC craft spirit for a local snack board','casual','suggested',2),
(317,'brandy, Remy Martin XO, Cognac, luxury','dessert','Crêpes Suzette with Grand Marnier and orange butter','complement','Remy XO''s Grande Champagne complexity bridges the Crêpes Suzette''s orange liqueur flame; a classic French cognac dessert','dessert','classic',1),
(318,'brandy, Delamain Pale Dry, Grande Champagne, aged','cheese','Comté 24-month with quince paste and walnut bread','complement','Delamain Pale Dry''s pale refined character bridges the aged Comté; both are expressions of the finest French tradition','cheese','classic',1),
(319,'brandy, Hine Antique XO, Grande Champagne','dessert','Tarte Tatin with Calvados-flambéed apples and crème fraîche','complement','Hine Antique XO''s Grande Champagne elegance bridges the caramelised Tarte Tatin; a cognac house''s apple dessert pairing','dessert','classic',2),
(320,'brandy, Darroze Bas-Armagnac, 10-year, vigorous','cheese','Roquefort with honey and toasted hazelnuts on rye','complement','Darroze Bas-Armagnac''s rustic intensity bridges Roquefort''s salt; a Gascon armagnac with Gascon sheep cheese','cheese','classic',1),
(321,'brandy, Dupont Calvados VSOP, apple, Norman','dessert','Tarte normande with apples, almonds and crème fraîche','complement','Dupont VSOP Calvados belongs with tarte normande; the apple brandy and the apple tart share the Norman orchard','dessert','classic',1),
(324,'brandy, Lemorton Calvados 15-Year, aged, pear-apple','cheese','Camembert de Normandie with calvados and apple chutney','complement','Lemorton 15-Year''s deep Domfrontais character bridges the Norman Camembert; calvados and Camembert are Norman tradition','cheese','classic',1),

-- Spirits gin (46-48, 50-51, 53)
(46,'gin, Old Tom, sweetened, botanical','casual','Gin fizz with lemon, egg white and botanical garnish','complement','Old Tom Gin''s sweetness elevates the gin fizz; the aromatic botanicals bridge the citrus and foam','casual','classic',2),
(47,'gin, Empress 1908, butterfly pea, indigo','casual','Cucumber and elderflower sandwiches with champagne butter','complement','Empress 1908''s BC floral character bridges the cucumber and elderflower sandwich; a Victoria afternoon tea pairing','casual','established',2),
(48,'gin, Seaside, coastal, BC botanicals','seafood','Oysters on the half shell with a gin-mignonette','complement','Seaside Gin''s coastal botanicals bridge the Pacific oyster; a BC craft gin for a BC tidal flat pairing','aperitif','classic',1),
(50,'gin, Confluence, Vancouver, citrus-forward','casual','Smoked salmon canapés with gin-cured gravlax cream','complement','Confluence Gin''s Vancouver citrus botanicals bridge the smoked salmon; using gin in the curing marinade creates unity','starter','established',2),
(51,'gin, Ampersand, BC, delicate','casual','Deviled eggs with smoked paprika and chive','complement','Ampersand Gin''s delicate BC botanical profile bridges the deviled egg''s richness; a gentle spirit for a gentle bite','aperitif','suggested',2),
(53,'gin, Freeland, Seattle, clean','casual','Prawn cocktail with Marie Rose sauce and avocado','complement','Freeland Gin''s clean Seattle botanical bridges the prawn cocktail; a Pacific NW gin for a classic American starter','starter','established',2),

-- Spirits liqueur (322-323, 346-350, 365-366, 368)
(322,'pastis, Ricard, anise, Marseille','casual','Tapenade with anchovies, capers and sourdough crostini','complement','Ricard Pastis and tapenade is Marseille''s classic aperitif pairing; both come from the same Provençal tradition','aperitif','classic',1),
(323,'pastis, Henri Bardouin, complex, Provençal herbs','casual','Brandade de morue (salt cod mousse) with garlic crostini','complement','Henri Bardouin''s complex Provençal herbs bridge the brandade; both come from the southern French Mediterranean tradition','aperitif','classic',1),
(346,'grappa, Nonino Moscato, monovitigno, aromatic','dessert','Moscato e pesche (peaches in Moscato wine syrup) with almond biscotti','complement','Nonino Moscato Grappa''s distilled Moscato bridges the peach Moscato syrup; a Friuli grape distilled into dessert unity','dessert','classic',1),
(347,'amaro, Fernet-Branca, bitter, medicinal','casual','Bitter chocolate truffle with espresso ganache and sea salt','complement','Fernet-Branca''s bitter herbal complexity bridges the espresso chocolate truffle; a post-dinner amaro for a Milan café tradition','digestif','classic',1),
(348,'amaro, Montenegro, balanced, Italian','casual','Tiramisu with amaretto and espresso','complement','Amaro Montenegro''s balanced bittersweet bridges the tiramisu; both are Italian after-dinner traditions of balance','digestif','established',2),
(349,'limoncello, Capri, sweet, Amalfi lemon','dessert','Semifreddo al limone with lemon curd and pistachio crumble','complement','Limoncello di Capri''s Amalfi lemon bridges the semifreddo; both are Capri''s gift to the Italian dessert table','dessert','classic',1),
(350,'grappa, Nardini, acquavite, Veneto','casual','Cantucci con Vin Santo e mandorle (almond biscotti)','complement','Nardini Acquavite''s clean Veneto spirit bridges the cantucci; an Italian digestif for an Italian dunking tradition','digestif','classic',1),
(365,'ouzo, Barbayanni Blue, aged, Lesvos','casual','Grilled octopus with olive oil, lemon and dried oregano','complement','Barbayanni Ouzo and grilled octopus is Lesvos''s defining taverna pairing; the anise bridges the charred octopus','aperitif','classic',1),
(366,'ouzo, Plomari, Lesvos, original','casual','Htapodi (octopus) in red wine vinegar with capers','complement','Plomari Ouzo''s clean Lesvos character bridges the vinegared octopus; both come from the Aegean sea tradition','aperitif','classic',1),
(368,'arak, Massaya Silver, Lebanon, anise','casual','Fattoush salad with sumac, purslane and toasted bread','complement','Massaya Arak Silver''s anise and grape bridges the fattoush''s sumac; a Bekaa Valley spirit for Lebanese mezze','aperitif','classic',1),

-- Spirits rum (174)
(174,'rum, Clairin Sajous, Haitian, sugarcane','casual','Griot (fried pork) with pikliz (spiced cabbage pickle) and plantain','complement','Clairin Sajous''s raw sugarcane intensity bridges the griot''s fried pork and pikliz heat; a Haitian spirit for Haitian food','casual','classic',1),

-- Spirits whiskey (41-44, 49, 52, 54, 56, 172-173, 183-185, 413-416)
(41,'whiskey, American Single Malt, Pacific NW','casual','Smoked brisket flat with pickled red onion and Texas toast','complement','Pacific NW American Single Malt''s malt depth bridges the smoked brisket; the smoke in both the whiskey and meat align','casual','established',2),
(42,'whiskey, Garryana, American Single Malt, oak','casual','Oregon blue cheese burger with Walla Walla onion jam','complement','Garryana''s oak character bridges the blue cheese burger; both are Pacific NW expressions of bold flavour','casual','established',2),
(43,'whiskey, American Single Malt, PNW, second','casual','Pacific NW cedar-plank salmon with whiskey glaze','complement','Pacific NW Single Malt''s smoked grain bridges the cedar-plank salmon; using whiskey in the glaze creates a flavour loop','main','established',2),
(44,'whiskey, Oregon Single Malt, pure grain','casual','Mushroom and aged cheddar grilled cheese with Oregon mustard','complement','Oregon Single Malt''s clean grain character bridges the mushroom cheddar grilled cheese; a PNW whiskey for a rainy day sandwich','casual','suggested',2),
(49,'whiskey, Laird of Fintry, Scottish-style, BC','casual','Highland shortbread with Okanagan honey and fleur de sel','complement','Laird of Fintry''s Scottish-style malt bridges the Scottish shortbread with BC honey; a BC-Scots affinity pairing','casual','established',2),
(52,'whiskey, Port Finish, American Single Malt, sweet','cheese','Aged Manchego with Bing cherry jam and marcona almonds','complement','Port Finish Single Malt''s sweet red fruit bridges the Manchego and cherry jam; the port cask suits fruited cheese pairings','cheese','established',2),
(54,'whiskey, Noteworthy, American, approachable','casual','Bourbon pecan pie with caramel sauce and vanilla ice cream','complement','Noteworthy''s approachable malt bridges the pecan pie''s caramel richness; a whiskey for America''s favourite pie','dessert','established',2),
(56,'whiskey, Bruichladdich Port Charlotte, Islay-style','casual','Smoked duck breast with blackberry glaze and watercress','complement','Port Charlotte''s Islay peat bridges the smoked duck; both carry a deep smoky character that speaks the same language','main','established',2),
(172,'whiskey, Buffalo Trace, bourbon, Kentucky','casual','Kentucky burgoo (slow stew) with lamb, corn and tomato','complement','Buffalo Trace Bourbon belongs with the Kentucky burgoo tradition; the bourbon''s corn sweetness bridges the slow stew','casual','classic',1),
(173,'whiskey, Uncle Nearest 1884, Tennessee, smooth','casual','Peach cobbler with brown sugar biscuit topping and cream','complement','Uncle Nearest''s smooth Tennessee character bridges the peach cobbler; a Southern spirit for the South''s favourite summer dessert','dessert','classic',1),
(183,'whiskey, Macallan 12 Sherry Oak, Highland, rich','dessert','Christmas pudding with brandy butter and glacé cherries','complement','Macallan 12 Sherry Oak''s dried fruit and sherry richness bridges the Christmas pudding; the dried fruit register aligns','dessert','classic',1),
(184,'whiskey, Ardbeg 10, Islay, intense peat','casual','Smoked haddock kedgeree with curried eggs and rice','complement','Ardbeg''s Islay peat bridges the smoked haddock kedgeree; both are expressions of smoking as a culinary tradition','main','classic',1),
(185,'whiskey, Springbank 10, Campbeltown, maritime','casual','Potted smoked mackerel with horseradish and rye crackers','complement','Springbank''s maritime Campbeltown character bridges the potted smoked mackerel; both come from Scotland''s Atlantic coast','starter','classic',1),
(413,'whiskey, Glenmorangie 18-Year, Highland, complex','dessert','Éclair au chocolat with vanilla crème pâtissière and chocolate glaze','complement','Glenmorangie 18-Year''s Highland elegance bridges the chocolate éclair; the vanilla cream echoes the whisky''s own vanilla oak','dessert','established',2),
(414,'whiskey, GlenDronach 18 Allardice, sherry, powerful','casual','Venison haggis with neeps and tatties and whisky cream sauce','complement','GlenDronach Allardice''s sherry power belongs with the venison haggis; a Speyside-Highland bridge of game and spirit','main','classic',1),
(415,'whiskey, Dalmore 18, Highland, rich, citrus','casual','Dark chocolate orange fondant with marmalade ice cream','complement','Dalmore 18''s orange peel and rich Highland character bridges the chocolate orange fondant; citrus and chocolate align','dessert','established',2),
(416,'whiskey, Clynelish 14, Highland, waxy, coastal','seafood','Smoked salmon and cream cheese bagel with capers and dill','complement','Clynelish 14''s waxy coastal character bridges the smoked salmon bagel; the wax and smoke share a language of preservation','casual','established',2)
;
COMMIT;
