BEGIN;
INSERT INTO pairing_intelligence
  (beverage_product_id, food_flavour_profile, food_category, food_description, pairing_type, flavour_logic, meal_context, confidence, authority_tier)
VALUES
-- BC wines (1, 3, 4, 6-28)
(1,'Okanagan, bold, red icon','lamb','Okanagan lamb rack with Black Sage herb crust and pinot reduction','complement','Red Icon''s Black Sage Bench origin pairs with the local lamb; the desert herb crust echoes the wine''s terroir depth','main','established',2),
(3,'Osoyoos Larose, Bordeaux-trained, desert','beef','Prime Okanagan beef tenderloin with Black Sage mushroom jus','elevate','Osoyoos Larose''s Mouton Rothschild DNA belongs with the finest BC beef; desert mushrooms bridge Bordeaux and Okanagan','main','classic',1),
(4,'Meritage, Okanagan, blend','lamb','Okanagan-style shepherd''s pie with local lamb and root vegetables','complement','Meritage''s Bordeaux-inspired blend bridges the comfort of shepherd''s pie; a BC winery''s local heritage dish','main','established',2),
(6,'Perpetua Chardonnay, Nk''Mip, Osoyoos','seafood','Dungeness crab ravioli with brown butter and lemon thyme','complement','Perpetua''s Burgundian oak bridges the rich crab ravioli; lemon thyme echoes the Chardonnay''s citrus character','fish_course','established',2),
(7,'Stewart Family Reserve, Pinot Noir, Naramata','duck','Pan-seared Okanagan duck breast with Okanagan cherry reduction','complement','Stewart Family Reserve Pinot Noir pairs with BC duck; the Naramata Bench''s volcanic soil adds mineral depth','main','classic',2),
(8,'Platinum Block 2, Naramata, Pinot','game','Grilled BC venison loin with foraged mushroom duxelles','complement','Platinum Block 2''s complexity bridges BC venison and foraged mushrooms; a Naramata wine for the BC wilderness','main','established',2),
(9,'Unparalleled, Naramata, Pinot premium','lamb','Similkameen lamb chops with wild rosemary and garlic confit','complement','Unparalleled''s premium expression pairs with the wild-herb Similkameen lamb; a Naramata terroir pairing of neighbour valleys','main','established',2),
(10,'Jackpot, Cabernet Franc, BC herbal','duck','Duck liver pâté on toasted sourdough with Okanagan cherry jam','complement','Jackpot Cab Franc''s herbal character bridges the duck pâté and cherry jam; a BC bistrot pairing at its simplest','starter','established',2),
(11,'Qwam Qwmt, Syrah, Black Sage','lamb','Black Sage Road lamb ribs with Harissa spice rub and yogurt','complement','Qwam Qwmt''s northern Rhône character bridges the harissa lamb; the spice and smoke echo the Syrah''s peppery depth','main','established',2),
(12,'Dead of Night, blend, bold BC','beef','Braised Okanagan beef short ribs with root vegetable purée','complement','Dead of Night''s bold BC red belongs with the slow-braised short ribs; a winery wine for a winery dinner','main','established',2),
(13,'Signature, Naramata, structured','game','Elk medallions with juniper berry sauce and celeriac gratin','complement','Signature''s structured blend bridges the elk and juniper; a Naramata wine for BC''s wilderness game','main','established',2),
(14,'Pinot Noir, Naramata, everyday','casual','Charcuterie board with BC salami, Okanagan fruit and Naramata cheese','complement','Naramata Bench Pinot Noir''s approachability makes it the perfect charcuterie board wine; all ingredients from the valley','casual','established',2),
(16,'CheckMate Queen Taken, Chardonnay, luxury','seafood','Pacific BC halibut cheeks with brown butter and capers','elevate','CheckMate Queen Taken''s luxury Chardonnay elevates halibut cheeks; the brown butter bridges Burgundy and Pacific Northwest','fish_course','classic',2),
(17,'Cabernet Sauvignon, WA, Columbia Valley','beef','Snake River Farms wagyu New York strip with herb butter','complement','Columbia Valley Cabernet pairs with Snake River wagyu; the Cascades influence and the Snake River share the same water','main','classic',2),
(18,'Cabernet Sauvignon, Okanagan, Black Sage','beef','Okanagan-raised Heritage Angus beef tenderloin with bordelaise','complement','Okanagan Black Sage Bench Cabernet belongs with the local Heritage Angus beef; a BC winery''s signature pairing','main','established',2),
(19,'Perigee, blend, Naramata, structured','beef','Beef Wellington with Okanagan black truffle duxelles and Dijon','complement','Perigee''s complex blend suits the Beef Wellington; a celebration of Naramata Bench''s Bordeaux-style ambition','main','established',2),
(20,'Cailloux, Syrah, Walla Walla, pepper','lamb','Walla Walla sweet onion and lamb kofta with tzatziki','complement','Cailloux Syrah''s Walla Walla pepper pairs with lamb kofta; the sweet onion bridges the Syrah''s dark fruit notes','casual','established',2),
(21,'Chaleur Estate, Columbia Valley, Bordeaux blend','beef','Dry-aged Columbia River Valley beef côte de boeuf with frites','complement','Chaleur Estate''s Bordeaux-trained winemaker brings this pairing; Columbia Valley beef demands Columbia Valley wine','main','classic',2),
(22,'Champoux, Cab, Horse Heaven Hills','beef','Horse Heaven Hills bison burger with caramelised onion','complement','Champoux Vineyard is Horse Heaven''s finest site; bison from the same plateau echoes the wine''s dry mineral character','casual','established',2),
(23,'Old Vines, Wahluke, Cabernet','beef','Columbia Valley beef pot roast with Wahluke wine reduction','complement','Braising with Old Vines Cab from Wahluke creates a flavour loop; drinking the same wine makes the sauce complete','main','established',2),
(24,'Eroica, Riesling, off-dry, Chateau Ste Michelle','seafood','Pacific Northwest crab cakes with Riesling and herb butter','complement','Eroica''s Chateau Ste Michelle-Loosen collaboration bridges Pacific crab; the off-dry Riesling complements the crab sweetness','fish_course','classic',2),
(25,'John Lewis, Syrah, Walla Walla, intense','lamb','Walla Walla rack of lamb with natural jus and mint gremolata','complement','John Lewis Syrah''s Walla Walla intensity belongs with the local lamb; mint gremolata bridges the wine''s herbal depth','main','established',2),
(26,'Subduction, red blend, Columbia Valley','casual','Columbia Valley charcuterie with local salami and dried fruit','complement','Subduction Red''s accessible Columbia Valley character bridges the casual charcuterie board; an everyday Walla Walla pairing','casual','established',2),
(27,'CMS Red, Helix, everyday Columbia','casual','Columbia Valley beef burger with sharp Cheddar and Walla Walla onion','complement','CMS Red''s everyday accessibility makes it the perfect burger wine; Walla Walla onion bridges the Columbia Valley character','casual','established',2),
(28,'Chester-Kidder, Cab blend, Champoux','beef','Champoux Vineyard-grown lamb saddle with rosemary and black truffle','complement','Chester-Kidder''s premium Champoux fruit belongs with the same vineyard''s raised lamb; a Champoux estate pairing','main','classic',2),

-- Oregon Pinot Noir (29-39)
(29,'Dundee Hills, volcanic, Pinot Noir','duck','Oregon roasted duck with Willamette cherry and hazelnut salad','complement','Dundee Hills Pinot''s volcanic red fruit bridges the roasted duck; cherries and hazelnuts are Oregon''s own pairing tradition','main','classic',2),
(30,'Original Vines, Chehalem, old vine','salmon','Wood-fired Oregon salmon with Willamette pinot reduction','complement','Original Vines'' old-vine character bridges the wood-fired salmon; both express Chehalem Mountain''s unique character','fish_course','classic',2),
(31,'Avni, Chehalem, floral','mushroom','Willamette Valley porcini mushroom and truffle risotto','complement','Avni Pinot''s floral depth pairs with the Willamette porcini; the volcanic soil mirrors the earthy mushroom terroir','main','established',2),
(32,'Seven Springs, limestone, Pinot','game','Oregon pheasant with Eola-Amity Hills cherry and forest herb','complement','Seven Springs'' limestone character bridges the pheasant''s delicate game; cherry and herb echo the Willamette terroir','main','established',2),
(33,'Casteel Reserve, WA, complex Pinot','duck','Willamette Valley duck confit with local pinot reduction','complement','Casteel Reserve''s Washington-Oregon complexity bridges the duck confit; a reserve-level wine for a reserve preparation','main','classic',2),
(34,'Eileen, single vineyard, Carlton, Pinot','salmon','Wild coho salmon with Oregon forest mushroom and herb crust','complement','Eileen Vineyard''s Carlton farm character bridges wild salmon; both are the finest expressions of the Willamette','fish_course','classic',2),
(35,'Beaux Frères, Ribbon Ridge, powerful Pinot','beef','Oregon beef short ribs braised in Beaux Frères with herbs','complement','Beaux Frères''s powerful Ribbon Ridge Pinot bridges the short ribs; braising in the wine creates Willamette terroir unity','main','established',2),
(36,'Old Stones, mineral, Pinot','mushroom','Oregon chanterelle and goat cheese tart with thyme','complement','Old Stones'' mineral Pinot bridges the Oregon chanterelles and goat cheese; all three come from the Willamette valley floor','main','established',2),
(37,'Savoya, volcanic, Eola-Amity, Pinot','duck','Savoya Ranch duck breast with Eola-Amity pinot cherry jus','complement','Savoya Vineyard''s volcanic site pairs with the ranch''s own duck; a single-farm terroir pairing of wine and game','main','classic',2),
(38,'Elizabeth''s Reserve, Ponzi, Chehalem','game','Oregon venison medallions with Cascade berry reduction','complement','Elizabeth''s Reserve Pinot Noir bridges Oregon venison; Cascade berries echo the wine''s wild fruit character','main','established',2),
(39,'Tempranillo Reserve, Abacela, Umpqua','lamb','Oregon Umpqua lamb chops with Rioja herb seasoning','complement','Abacela Tempranillo Reserve''s Spanish variety in Oregon pairs with Spanish-style lamb; the Umpqua valley as Rioja West','main','established',2);
COMMIT;
