BEGIN;
INSERT INTO pairing_intelligence
  (beverage_product_id, food_flavour_profile, food_category, food_description, pairing_type, flavour_logic, meal_context, confidence, authority_tier)
VALUES
-- Tuscany: Brunello, Supertuscans, Amarone, Soave (334-345)
(334,'Biondi-Santi, Brunello Riserva, Montalcino, legend','celebration','Bistecca alla Fiorentina (T-bone from Chianina) with sea salt and olive oil','complement','Biondi-Santi Brunello Riserva belongs with the Florentine steak; the greatest Tuscan wine for the greatest Tuscan cut','celebration','classic',1),
(335,'Sassicaia, Bolgheri, Cabernet, Super Tuscan','celebration','Lamb rack with Mediterranean herbs and Bolgheri olive oil','complement','Sassicaia''s Bolgheri Cabernet belongs with the herb-crusted lamb; the coastal Tuscan wine for the coastal Tuscan table','celebration','classic',1),
(336,'Ornellaia, Bolgheri Superiore, blend','celebration','Dry-aged Chianina rib-eye with truffle butter and Tuscan beans','complement','Ornellaia''s Bolgheri complexity belongs with the dry-aged Chianina; both are expressions of Tuscan perfection','celebration','classic',1),
(337,'Antinori, Tignanello, Sangiovese-Cabernet','game','Cinghiale (wild boar) ragù with pappardelle and Pecorino','complement','Tignanello''s Sangiovese-Cabernet bridges the wild boar pappardelle; the blend''s Tuscan structure for the Tuscan game tradition','main','classic',1),
(338,'Montevertine, Le Pergole Torte, Sangiovese, artisan','casual','Ribollita (Tuscan bread and bean soup) with aged olive oil','complement','Le Pergole Torte''s pure Sangiovese bridges the ribollita; a great Radda wine for the Chianti farmer''s most nourishing dish','main','classic',1),
(339,'Fontodi, Flaccianello, Sangiovese, Panzano','game','Pappardelle al ragù di lepre (wide pasta with hare sauce)','complement','Flaccianello''s Panzano Sangiovese bridges the hare pappardelle; the concentrated Chianti Classico hillside wine for braised game pasta','main','classic',1),
(340,'Isole e Olena, Cepparello, Sangiovese, balanced','casual','Arista di maiale (Florentine roast pork loin) with rosemary and garlic','complement','Cepparello''s balanced Sangiovese bridges the arista; the pork loin''s rosemary echoes the wine''s own herbal depth','main','classic',2),
(341,'Bibi Graetz, Testamatta, Sangiovese, modern','casual','Faraona al mattone (brick-pressed guinea fowl) with Chianti vinaigrette','complement','Testamatta''s modern Sangiovese bridges the brick-pressed guinea fowl; a contemporary Tuscan wine for a traditional Florentine method','main','established',2),
(342,'Dal Forno Romano, Amarone, Valpolicella, intense','celebration','Brasato all''Amarone (beef braised in Amarone) with polenta','complement','Dal Forno Amarone braised into the beef creates a loop of intensity; drinking what''s in the braise is the definitive Valpolicella tradition','celebration','classic',1),
(343,'Quintarelli, Amarone Classico, icon, complex','celebration','Pastissada de caval (Veronese horse ragù) with gnocchi di patate','complement','Quintarelli Amarone belongs with the ancient Veronese horse ragù; the most traditional Valpolicella wine for the most traditional Veneto dish','celebration','classic',1),
(344,'Pieropan, Soave Classico Calvarino, volcanic','fish_course','Baccalà mantecato (creamed salt cod) with polenta fritta and herbs','complement','Pieropan Calvarino''s volcanic Soave bridges the creamed baccalà; a Veronese wine for Venice''s favourite bacalà preparation','starter','classic',1),
(345,'Allegrini, Amarone Classico, accessible Amarone','casual','Risotto all''Amarone with Castelmagno and bone marrow','complement','Allegrini Amarone''s accessible intensity bridges the risotto all''Amarone; cooking with the same wine creates direct flavour unity','main','classic',2),

-- Spanish: Ribera del Duero, Rioja, Priorat (351-355)
(351,'Vega Sicilia, Unico, icon, Ribera del Duero','celebration','Roast suckling lamb (lechazo asado) from Aranda de Duero','complement','Vega Sicilia Unico belongs with Aranda''s lechazo; both are Ribera del Duero''s defining expressions of centuries of tradition','celebration','classic',1),
(352,'Pingus, Ribera del Duero, Tempranillo, legend','celebration','Cochinillo asado (roast suckling pig) from Segovia with bread-cut service','complement','Pingus''s legendary concentration belongs with the cochinillo from Segovia; both are Spain''s most prestige expressions of their kind','celebration','classic',1),
(353,'Muga, Prado Enea Gran Reserva, traditional Rioja','casual','Patatas a la riojana (Rioja-style potato and chorizo stew)','complement','Muga Prado Enea''s traditional Rioja character bridges the regional potato and chorizo stew; a Rioja wine for Rioja''s own dish','main','classic',1),
(354,'Lopez de Heredia, Viña Tondonia Gran Reserva, classic','casual','Morcilla de Burgos (blood sausage) with fried egg and peppers','complement','Tondonia''s aged Rioja classic bridges the morcilla de Burgos; an old-fashioned wine for a traditional Castilian table','casual','classic',1),
(355,'Álvaro Palacios, L''Ermita, Priorat, Grenache icon','celebration','Whole roasted rack of Pyrenean lamb with romesco and escalivada','complement','L''Ermita''s Priorat prestige belongs with the Pyrenean lamb and romesco; a Catalonian mountain wine for Catalan mountain food','celebration','classic',1),

-- Greek (362-364)
(362,'Sigalas, Santorini, Assyrtiko, volcanic, mineral','fish_course','Kolios (horse mackerel) grilled whole with lemon and capers','complement','Sigalas Santorini''s volcanic mineral bridges the grilled horse mackerel; a Cyclades wine for the Aegean''s daily catch','fish_course','classic',1),
(363,'Sigalas, Nykteri, Assyrtiko, aged, rich','cheese','Manouri cheese with thyme honey and walnuts from Pelion','complement','Sigalas Nykteri''s aged Assyrtiko richness bridges the Manouri and thyme honey; a celebration of Aegean dairy and wine','cheese','established',2),
(364,'Kir-Yianni, Ramnista, Naoussa, Xinomavro','game','Stifado (rabbit braised with pearl onions and cinnamon) with orzo','complement','Ramnista Xinomavro''s tannic acidity bridges the stifado''s sweet-spice braised rabbit; a classic northern Greek pairing','main','classic',1),

-- Lebanese (367)
(367,'Chateau Musar, Rouge, Lebanon, complex blend','celebration','Whole roast leg of lamb with Lebanese seven spice and pomegranate','complement','Château Musar''s complex Lebanese blend bridges the seven-spice lamb; the Bekaa Valley wine and Lebanese festive cooking','celebration','classic',1),

-- Piemonte Barbera/Dolcetto (371-373)
(371,'Braida, Bricco dell''Uccellone, Barbera d''Asti','casual','Pizza margherita with San Marzano tomato, fior di latte and basil','complement','Bricco dell''Uccellone''s Barbera acidity bridges the pizza''s tomato; Piemonte''s most food-friendly wine for Italy''s most casual dish','casual','classic',2),
(372,'G.D. Vajra, Dolcetto d''Alba, everyday Piemonte','casual','Vitello tonnato (veal with tuna sauce) as a Piemontese antipasto','complement','Vajra Dolcetto''s soft everyday character bridges the vitello tonnato; a classic Piemontese antipasto for the everyday table','starter','classic',1),
(373,'Chiarlo, Barbera d''Asti Superiore La Court','casual','Agnolotti del plin (small Piemontese pasta) with meat ragù','complement','La Court''s Asti Superiore bridges the agnolotti del plin; Piemonte''s pasta tradition with Piemonte''s Barbera table wine','main','classic',1),

-- Gavi, Vernaccia, Vino Nobile (378-384)
(378,'La Scolca, Gavi di Gavi, Black Label, mineral','fish_course','Grilled sea bream with Ligurian olive oil and fresh herbs','complement','La Scolca Black Label''s mineral Gavi bridges the sea bream; a Piemontese white for the Ligurian coast''s daily catch','fish_course','classic',1),
(379,'Broglia, La Meirana, Gavi di Gavi, fresh','seafood','Insalata di frutti di mare (warm seafood salad) with lemon and parsley','complement','Broglia La Meirana''s fresh mineral bridges the warm seafood salad; Gavi''s acidity cleanses the mixed shellfish richness','starter','classic',1),
(380,'Poliziano, Vino Nobile Asinone, Montepulciano','game','Pappardelle al cinghiale (wild boar) with Pici Toscana','complement','Poliziano Asinone''s Nobile complexity bridges the Tuscan wild boar pasta; a Montepulciano wine for Tuscan game tradition','main','classic',1),
(381,'Avignonesi, Vino Nobile, Montepulciano, classic','casual','Pici all''aglione (Tuscan thick pasta with garlic and tomato)','complement','Avignonesi Vino Nobile''s Sangiovese bridges the pici all''aglione; the Montepulciano wine for the Sienese pasta tradition','main','classic',1),
(382,'Poliziano, Rosso di Montepulciano, accessible','casual','Bistecca di manzo (grilled beef steak) with rocket and Parmesan','complement','Poliziano Rosso''s accessible Sangiovese bridges the simple grilled steak; an everyday Tuscan wine for the everyday Tuscan meal','casual','classic',2),
(383,'Montenidoli, Vernaccia, San Gimignano, traditional','seafood','Fritto misto di mare (mixed fried seafood) with lemon and aioli','complement','Montenidoli Vernaccia''s traditional mineral bridges the fritto misto; San Gimignano''s white wine is made for fried coastal seafood','main','classic',1),
(384,'Teruzzi, Vernaccia, San Gimignano, modern','seafood','Zuppa di pesce (Tuscan fish soup) with grilled bread and saffron','complement','Teruzzi Vernaccia''s modern freshness bridges the Tuscan fish soup; the saffron echoes the wine''s own mineral warmth','main','established',2),

-- Australian/NZ (395-400)
(395,'d''Arenberg, Dead Arm, Shiraz, McLaren Vale','game','Whole roasted kangaroo loin with wattle seed and quandong sauce','complement','Dead Arm''s McLaren Vale Shiraz bridges the kangaroo loin and wattle seed; Australian indigenous wine and indigenous ingredients','main','classic',2),
(396,'Clarendon Hills, Astralis, Shiraz, icon','celebration','Prime dry-aged Australian Wagyu côte de boeuf with bordelaise','elevate','Astralis''s concentrated McLaren Vale power elevates the Wagyu côte de boeuf; both are expressions of Australian excellence','celebration','classic',1),
(397,'Yering Station, Reserve, Pinot Noir, Yarra Valley','casual','Duck confit with Yarra cherry jus and potato gratin','complement','Yering Station Reserve''s Yarra Valley Pinot bridges the duck confit; the local cherry jus mirrors the wine''s fruit character','main','classic',2),
(398,'Coldstream Hills, Reserve, Chardonnay, Yarra','fish_course','Barramundi with lemon myrtle butter and Yarra Valley herbs','complement','Coldstream Hills Chardonnay''s Yarra complexity bridges the barramundi; the lemon myrtle echoes the wine''s citrus depth','fish_course','classic',2),
(399,'Te Mata, Coleraine, Hawke''s Bay, NZ blend','celebration','Hawke''s Bay lamb rack with native herb crust and Coleraine jus','complement','Te Mata Coleraine belongs with the Hawke''s Bay lamb rack; the estate''s Cabernet bridges the local lamb tradition','main','classic',1),
(400,'Craggy Range, Le Sol, Gimblett Gravels, Syrah','casual','Marlborough lamb shoulder slow-roasted with NZ native herbs','complement','Craggy Range Le Sol''s Gimblett Gravels Syrah bridges the slow lamb; northern Rhône character for a New Zealand approach','main','classic',2),

-- Chilean/South African (406-412)
(406,'Clos Apalta, Colchagua, blend, Carmenère-led','celebration','Asado de tira (flanken short rib) with chimichurri and Colchagua herbs','complement','Clos Apalta''s Colchagua complexity bridges the asado short rib; a Chilean estate wine for the Chilean barbecue tradition','celebration','classic',1),
(407,'Luis Felipe Edwards, Carmenère Gran Reserva','casual','Cazuela de vacuno (Chilean beef and vegetable stew) with corn','complement','LFE Carmenère''s accessible expression bridges the cazuela; Chile''s signature grape for Chile''s most comforting home dish','main','established',2),
(408,'Almaviva, Maipo, Cabernet-Carmenère, icon','celebration','Filete de res con salsa de Cassis and Chilean truffle','complement','Almaviva''s prestige Maipo character elevates the beef tenderloin; the Cassis note in the sauce mirrors the wine''s own structure','celebration','classic',1),
(409,'Don Melchor, Puente Alto, Cabernet, prestige','celebration','Whole roasted leg of Patagonian lamb with Maipo red wine sauce','complement','Don Melchor''s Puente Alto concentration belongs with the Patagonian lamb; Concha y Toro''s greatest wine for its most elegant table','celebration','classic',1),
(410,'Kanonkop, Paul Sauer, Stellenbosch, Pinotage blend','celebration','Cape Malay lamb bobotie with turmeric, apricot and egg topping','complement','Paul Sauer''s Stellenbosch complexity bridges the bobotie; a Cape blend for the Cape''s most celebrated heritage dish','main','classic',1),
(411,'Meerlust, Rubicon, Stellenbosch, Cabernet blend','casual','Karoo lamb chops with aromatic Cape Malay spice and apricot','complement','Meerlust Rubicon''s Stellenbosch Cabernet bridges the Karoo lamb; the Cape spice tradition adds a layer to the wine''s structure','main','classic',2),
(412,'Boekenhoutskloof, Syrah, Franschhoek, elegant','game','Cape ostrich fillet with South African wild mushroom cream sauce','complement','Boekenhoutskloof Syrah''s Franschhoek elegance bridges the Cape ostrich; both are Southern African expressions of wild character','main','classic',1),

-- Extended Burgundy (417-431, 433-434)
(417,'Ponsot, Clos de la Roche VV, grand cru, legend','celebration','Roast pigeon with Morey Saint-Denis morel sauce and potato galette','complement','Ponsot Clos de la Roche VV belongs with the roast pigeon; the grand cru''s depth for the most prized of game birds','celebration','classic',1),
(418,'Clos de Tart, grand cru, Mommessin, monopole','celebration','Roast woodcock on toast with liver sauce and Burgundy truffles','complement','Clos de Tart''s monopole grand cru belongs with the woodcock; a Morey monopole for Burgundy''s most treasured game','celebration','classic',1),
(419,'Leroy, Clos de Vougeot, grand cru, concentration','celebration','Faisan (pheasant) rôti with cèpe cream and Vougeot reduction','complement','Leroy Clos de Vougeot''s grand cru concentration belongs with the roast pheasant; Lalou Bize-Leroy''s philosophy for the finest game','celebration','classic',1),
(420,'Gouges, Nuits-Saint-Georges, 1er cru, classic','casual','Boeuf bourguignon with lardons, mushrooms and Nuits reduction','complement','Gouges Les Saint-Georges bridges the boeuf bourguignon; drinking the same appellation wine used in the braise is Burgundy tradition','main','classic',1),
(421,'Jadot, Beaune Clos des Ursules, 1er cru','casual','Coq au vin with Beaune wine and lardons from the Côte de Beaune','complement','Jadot Clos des Ursules bridges the coq au vin; cooking the chicken in the same Beaune appellation creates flavour unity','main','classic',1),
(422,'Comte Armand, Pommard Clos des Épeneaux, 1er cru','game','Saddle of venison with peppercorn jus and celeriac purée','complement','Comte Armand Clos des Épeneaux''s Pommard power bridges the venison saddle; the tannic structure for the gamey lean cut','main','classic',1),
(423,'Marquis d''Angerville, Volnay Clos des Ducs, 1er cru','game','Roast partridge with truffle jus and chestnut purée','complement','Angerville Clos des Ducs''s Volnay elegance bridges the roast partridge; the most feminine Volnay for the most delicate game','main','classic',1),
(424,'Marc Colin, Chassagne-Montrachet Caillerets, 1er cru','fish_course','Langoustines à la nage with Chassagne beurre blanc','complement','Marc Colin Caillerets'' Chassagne mineral bridges the langoustines; the wine in the beurre blanc creates direct unity','fish_course','classic',1),
(425,'Pierre Gonon, Saint-Joseph Rouge, Syrah, Northern Rhône','casual','Lamb sausages (saucisson de brebis) with potato gratin dauphinois','complement','Pierre Gonon Saint-Joseph''s Syrah bridges the lamb sausage and potato gratin; a humble northern Rhône expression for humble comfort','main','classic',1),
(426,'Domaine Gonon, Saint-Joseph Blanc, Marsanne','fish_course','Grilled river trout with walnut butter and verjuice','complement','Gonon Saint-Joseph Blanc''s Marsanne richness bridges the river trout; the walnut butter mirrors the wine''s own nutty character','fish_course','classic',1),
(427,'Santa Duc, Gigondas, Grandes Vignes, Grenache','game','Lièvre (hare) à la forcalquier with juniper and herbes de Provence','complement','Santa Duc Gigondas''s Grenache concentration bridges the hare; the Provençal herbs echo the wine''s garrigue character','main','classic',1),
(428,'Le Sang des Cailloux, Vacqueyras, concentrated Grenache','casual','Grilled merguez sausages with Provençal ratatouille and aïoli','complement','Le Sang des Cailloux''s concentrated Vacqueyras bridges the merguez and ratatouille; a garrigue wine for a garrigue table','casual','classic',1),
(429,'Château d''Aquéria, Tavel Rosé, Grenache rosé','casual','Grilled rouget (red mullet) with tapenade and Provençal herbs','complement','Tavel Rosé''s Grenache depth bridges the rouget; a southern rosé for a southern fish — Provence in a glass and on a plate','casual','classic',1),
(430,'Joguet, Chinon Clos de la Dioterie, Cab Franc, Loire','game','Grilled rillons (Touraine pork belly chunks) with cornichons','complement','Joguet Clos de la Dioterie''s Loire Cab Franc bridges the rillons; a Touraine wine for the Touraine''s beloved pork speciality','casual','classic',1),
(431,'Pierre Breton, Bourgueil Franc de Pied, ungrafted','casual','Andouillette (tripe sausage) from Vouvray with Dijon mustard','complement','Breton Franc de Pied''s ungrafted Loire character bridges the andouillette; both express the Loire''s fearless artisan tradition','casual','classic',2),
(433,'DRC, Bourgogne Rouge, village level, access wine','casual','Coq au vin simple (village Burgundy chicken) with mushrooms','complement','DRC Bourgogne Rouge''s access to Domaine terroir bridges the everyday coq au vin; a humble preparation for a humble wine from the greatest estate','casual','established',2),
(434,'Château Moulin Haut-Laroque, Fronsac, Right Bank','casual','Entrecôte grillée bordelaise with shallot and red wine sauce','complement','Moulin Haut-Laroque''s Fronsac concentration bridges the entrecôte bordelaise; a Right Bank wine for a Right Bank tradition','main','classic',2),

-- More French classics (435-442)
(435,'Bouchard, Côte de Nuits-Villages, approachable','casual','Jambon persillé (parsley ham terrine) from Burgundy with Dijon mustard','complement','Bouchard Côte de Nuits-Villages bridges the jambon persillé; a regional wine for the region''s classic cold meat terrine','starter','classic',1),
(436,'Drouhin, Côte de Beaune-Villages, classic Burgundy','casual','Oeufs en meurette (poached eggs in Burgundy red wine sauce)','complement','Drouhin Côte de Beaune-Villages bridges the oeufs en meurette; the same Burgundy appellation wine in the sauce and in the glass','casual','classic',1),
(437,'Pichon Comtesse de Lalande, Pauillac, second growth','celebration','Agneau de Pauillac (Pauillac lamb) roasted with Médoc garlic','complement','Pichon Comtesse''s Pauillac second growth belongs with Pauillac lamb; the appellation''s wine with the appellation''s lamb tradition','celebration','classic',1),
(438,'Château Lynch-Bages, Pauillac, second growth, robust','celebration','Rack of Médoc spring lamb with lamb jus and Pauillac mint sauce','complement','Lynch-Bages''s powerful Pauillac belongs with the Médoc spring lamb rack; a second growth for the most celebrated local pairing','celebration','classic',1),
(439,'Guigal, Côtes du Rhône Rouge, accessible, everyday','casual','Daube provençale (Provençal beef stew) with olives and orange peel','complement','Guigal Côtes du Rhône bridges the daube provençale; a Rhône garrigue wine for the Provence slow stew','main','classic',2),
(441,'Beaucastel, Châteauneuf Blanc, Roussanne, complex','fish_course','Lobster à la Provençale with saffron and Châteauneuf Blanc sauce','complement','Beaucastel Blanc''s Roussanne complexity elevates the Provençal lobster; the wine in the sauce creates direct flavour unity','fish_course','classic',1),
(442,'Henry Marionnet, Touraine Sauvignon Blanc, Loire','seafood','Rillettes de sardines maison with sourdough toast and lemon','complement','Marionnet Touraine Sauvignon''s bright Loire acidity bridges the sardine rillettes; a fresh Loire white for a Loire coastal starter','starter','established',2),

-- Greek extra (445-446)
(445,'Lyrarakis, Dafni, Cretan white, aromatic','seafood','Cretan dakos salad with dried bread, tomato, feta and olive oil','complement','Lyrarakis Dafni''s aromatic freshness bridges the Cretan dakos; a Crete wine for a Crete table — the island''s simplest pleasure','casual','classic',1),
(446,'Douloufakis, Dafnios Red, Kotsifali-Mandilaria, Crete','casual','Lamb with stamnagathi (wild Cretan chicory) and olive oil-braised','complement','Dafnios Red''s Cretan character bridges the slow-braised lamb with wild chicory; a Cretan wine for a Cretan mountain tradition','main','classic',1),

-- BC Okanagan extra (447-452)
(447,'Garry Oaks, Gewurztraminer, Salt Spring, BC','casual','Roti with Okanagan peach chutney and BC goat cheese','complement','Garry Oaks Gewurztraminer''s aromatic freshness bridges the peach chutney and goat cheese; a Gulf Island white for a Gulf Island table','casual','suggested',2),
(448,'Fort Berens, Riesling, Lillooet, BC interior','seafood','BC spot prawns with ginger, lemon and Riesling butter sauce','complement','Fort Berens Riesling''s Lillooet mineral bridges the spot prawns; the Riesling in the sauce creates a BC interior terroir loop','fish_course','established',2),
(449,'Recline Ridge, Bacchus, Shuswap, BC','casual','BC spot prawn tacos with mango salsa and lime crema','complement','Recline Ridge Bacchus''s aromatic freshness bridges the prawn tacos; the Shuswap''s crisp grape for a Pacific Northwest coastal casual','casual','suggested',2),
(450,'Hillside Estate, Muscat Ottonel, Naramata, BC','casual','Okanagan stone fruit pavlova with peach, cherry and cream','complement','Hillside Muscat Ottonel''s floral sweetness bridges the stone fruit pavlova; both are expressions of the Okanagan''s summer abundance','dessert','established',2),
(451,'Moon Curser, Tannat, Osoyoos, BC black wine','game','Elk osso buco with Black Sage desert herbs and celeriac purée','complement','Moon Curser Tannat''s Osoyoos intensity bridges the elk osso buco; a rare BC grape for BC''s wildest game preparation','main','established',2),
(452,'Thornhaven, Gewurztraminer, Summerland, BC','casual','Thai green mango salad with shrimp, peanut and lime','bridge','Thornhaven Gewurztraminer''s Summerland spice bridges the Thai mango salad; a BC aromatic wine for Southeast Asian heat','casual','established',2),

-- WA extra wines (453-458)
(453,'Wilridge, Rattlesnake Hills, Syrah, WA','casual','Slow-smoked lamb shoulder with za''atar and pomegranate molasses','complement','Wilridge Rattlesnake Hills Syrah bridges the smoked lamb with za''atar; a Washington Syrah for Middle Eastern-spiced lamb','casual','established',2),
(454,'Destiny Ridge, Wahluke Slope, Cabernet Sauvignon','casual','Columbia Valley grilled flat iron steak with Walla Walla onion rings','complement','Destiny Ridge Wahluke Cab bridges the grilled flat iron; a Wahluke wine for the Columbia Valley''s own beef tradition','casual','established',2),
(455,'Ancient Lakes, Columbia Valley, Riesling, crisp','seafood','Dungeness crab legs with Riesling clarified butter and chive','complement','Ancient Lakes Riesling''s Columbia Valley acidity bridges the Dungeness crab; the Riesling clarified butter creates unity','fish_course','established',2),
(456,'Fielding Hills, Lake Chelan, Syrah, WA','casual','Lake Chelan apple-smoked pork belly with cherry BBQ glaze','complement','Fielding Hills Chelan Syrah bridges the apple-smoked pork belly; Lake Chelan apples and Syrah fruit from the same shoreline','casual','established',2),
(457,'Naches Heights, Cabernet Franc, WA appellation','casual','Walla Walla sweet onion and roasted pepper flatbread with goat cheese','complement','Naches Heights Cab Franc''s herbal WA character bridges the sweet onion flatbread; Cab Franc''s herbal note suits roasted peppers','casual','suggested',2),
(458,'Snipes Family, Old Vine Grenache, Yakima, WA','casual','Columbia Valley lamb meatballs with tomato, herbs and yogurt','complement','Snipes Old Vine Grenache''s warmth bridges the lamb meatballs and tomato; old vines from Yakima''s oldest vineyard site','casual','established',2),

-- Oregon extra wines (459-464)
(459,'Ledger David, Southern Oregon, Merlot','casual','Southern Oregon grass-fed beef burger with Rogue Creamery Bleu','complement','Ledger David Merlot''s Southern Oregon approachability bridges the beef burger with blue cheese; a Medford wine for a Medford day','casual','suggested',2),
(460,'Eyrie Vineyards, Original Vines, Pinot Gris, Dundee','seafood','Dungeness crab salad with fennel, citrus and Oregon hazelnuts','complement','Eyrie Original Vines Pinot Gris bridges the Dungeness crab salad; the Dundee Hills pioneer''s white for Oregon''s coastal prize','fish_course','classic',2),
(461,'Cristom, Mt. Jefferson, Pinot Noir, Eola-Amity','game','Willamette Valley roasted quail with Oregon chanterelle and cherry jus','complement','Cristom Mt. Jefferson''s Eola elevation bridges the roasted quail; the chanterelle mirrors the volcanic soil character','main','classic',2),
(462,'Bradley Vineyards, Elkton, Pinot Gris, Southern Oregon','seafood','Southern Oregon albacore tuna poke with Umpqua sesame and avocado','complement','Bradley Elkton Pinot Gris''s Southern Oregon freshness bridges the albacore poke; the Umpqua Valley''s own Pacific fish','casual','suggested',2),
(463,'Abacela, Tempranillo Estate, Umpqua','casual','Garlic-roasted Umpqua lamb chops with Rioja-style potatoes','complement','Abacela Tempranillo''s Umpqua expression bridges the Spanish-seasoned lamb; Oregon as Rioja — the same grape, the same lamb pairing','main','established',2),
(464,'Cowhorn, Spiral 36, Southern Oregon, Rhône blend','casual','Roasted Umpqua chicken with herbes de Provence and grilled asparagus','complement','Cowhorn Spiral 36''s Rhône blend bridges the Provençal chicken; a biodynamic Oregon Grenache blend for a Rhône-inspired dish','main','established',2),

-- German Rieslings additional (473-480)
(473,'Egon Müller, Scharzhofberger Auslese, Mosel, sweet','celebration','Foie gras mi-cuit with Scharzhofberger gelée and brioche','elevate','Egon Müller Auslese elevates the foie gras mi-cuit; the wine''s slate sweetness and the foie gras luxury align at the finest table','celebration','classic',1),
(474,'Prüm, Wehlener Sonnenuhr Spätlese, off-dry, Mosel','casual','Vietnamese spring rolls (gỏi cuốn) with mint, shrimp and hoisin','bridge','Prüm Spätlese''s off-dry slate mineral bridges the spring roll''s fresh herbs; off-dry Riesling for Vietnamese freshness','casual','established',2),
(475,'Fritz Haag, Brauneberger Juffer Auslese, dense, sweet','cheese','Cambozola (Blue Brie) with pear and walnut on dark rye','bridge','Fritz Haag Auslese''s dense Mosel sweetness bridges the Cambozola''s creamy blue salt; a German sweet wine for a German blue','cheese','established',2),
(476,'Dönnhoff, Oberhäuser Brücke Spätlese, Nahe, pure','casual','Alsatian tarte flambée with crème fraîche, bacon and onion','complement','Dönnhoff Spätlese''s Nahe purity bridges the tarte flambée''s cream and bacon; a German Riesling for an Alsace neighbour tradition','casual','established',2),
(477,'Breuer, Berg Schlossberg GG, Rheingau, dry, mineral','cheese','Bergkäse (Alpine mountain cheese) with dark bread and apple butter','complement','Breuer Berg Schlossberg GG''s Rheingau mineral bridges the Alpine Bergkäse; the mountain cheese for the mountain-facing vineyard','cheese','established',2),
(478,'Bürklin-Wolf, Kirchenstück GG, Pfalz, dry, complex','casual','Saumagen (Pfalz stuffed pig stomach) with sauerkraut and pretzel bread','complement','Kirchenstück GG is the Pfalz''s definitive wine; the Pfalz''s Saumagen is its definitive dish — a perfect regional pairing','main','classic',1),
(479,'Molitor, Zeltinger Sonnenuhr Auslese, Mosel, golden','cheese','Saint-Agur blue cheese with honeycomb and toasted brioche','bridge','Molitor Auslese''s golden sweetness bridges the Saint-Agur blue; a French blue for a German sweet wine','cheese','established',2),
(480,'Rebholz, Kastanienbusch GG, Pfalz, biodynamic, volcanic','fish_course','Freshwater pike-perch (Zander) with Riesling beurre blanc and chives','complement','Rebholz Kastanienbusch GG''s biodynamic Pfalz mineral bridges the Zander; a volcanic wine for the Rhine''s most prized river fish','fish_course','classic',1),

-- Austrian wines additional (481-486)
(481,'FX Pichler, Kellerberg GV Smaragd, Wachau, dry','celebration','Grillierte Waldviertler Forelle (whole grilled trout) with Smaragd sauce','elevate','FX Pichler Kellerberg GV elevates the Wachau trout; using the wine in the sauce creates a complete Wachau river experience','fish_course','classic',1),
(482,'Knoll, Loibenberg Riesling Smaragd, Wachau, mineral','celebration','Flusskrebse (Austrian river crayfish) with Riesling bisque and herbs','elevate','Knoll Loibenberg Smaragd''s Wachau mineral elevates the Austrian river crayfish; the Riesling bisque links directly to the glass','fish_course','classic',1),
(483,'Bründlmayer, Heiligenstein Riesling, Kamptal, volcanic','casual','Liptauer cheese spread (Paprika-Topfen) with rye bread and radishes','complement','Heiligenstein Riesling''s volcanic mineral bridges the Liptauer; a Heuriger classic of Kamptal wine and Austrian cheese spread','casual','classic',1),
(484,'Bründlmayer, Lamm GV Reserve, Kamptal, rich','cheese','Tiroler Bergkäse (Alpine mountain cheese) with mountain honey','complement','Lamm GV Reserve''s Kamptal richness bridges the Alpine Bergkäse; the mountain cheese for the reserve-level Grüner Veltliner','cheese','established',2),
(485,'Moric, Alte Reben Blaufränkisch, Burgenland, mineral','celebration','Esterhazy Rostbraten (pan-roasted beef with cream and onion) Burgenland style','complement','Moric Alte Reben''s Burgenland mineral belongs with the Esterházy estate''s roast beef tradition; Blaufränkisch for a grand Austrian table','celebration','classic',1),
(486,'Umathum, Hallebühl Blaufränkisch, Neusiedlersee','celebration','Burgenland Ganslessen (roast goose) with Blaukraut and Knödeln','complement','Umathum Hallebühl''s Neusiedlersee power belongs with the Burgenland roast goose; the November goose season''s definitive pairing','celebration','classic',1),

-- Portuguese wines additional (487-492)
(487,'Quinta do Vale Meão, Douro Superior, premium red','cheese','Queijo Picante (aged sharp cheese) with fig jam and Douro almonds','complement','Vale Meão''s Douro Superior structure bridges the sharp aged cheese; fig jam and almonds are the Douro''s own condiments','cheese','established',2),
(488,'Niepoort Charme Tinto, Douro, Bastardo-led, elegant','celebration','Lombinhos de vitela no Douro (veal tenderloin) with morel and Port sauce','elevate','Niepoort Charme''s Douro elegance elevates the veal tenderloin; the Port sauce echoes the Douro''s own fortified wine tradition','celebration','classic',1),
(489,'Soalheiro, Alvarinho, Monção e Melgaço, aromatic','casual','Mexilhões à Bulhão Pato (mussels with garlic, lemon and coriander)','complement','Soalheiro Alvarinho bridges the classic Portuguese mussels; a Minho wine for the Minho''s Atlantic shellfish tradition','casual','classic',1),
(490,'Esporão Reserva Tinto, Alentejo, warm, structured','cheese','Queijo Serpa (Alentejo sheep cheese) with black olive tapenade and bread','complement','Esporão Reserva''s Alentejo warmth bridges the Serpa sheep cheese; the region''s wine with the region''s own sheep cheese tradition','cheese','classic',1),
(491,'Luis Pato, Pé Franco, Bairrada, ungrafted, tannic','celebration','Leitão da Bairrada served à la table with its regional master chef','elevate','Pé Franco''s ungrafted Bairrada prestige belongs with a masterclass leitão; both represent Bairrada''s pinnacle craft and terroir','celebration','classic',1),
(492,'Quinta do Crasto, Reserva Old Vines, Douro, concentrated','cheese','Queijo do Pico (Azores cow cheese, DOP) with honey and walnuts','complement','Crasto Old Vines'' concentration bridges the Azorean Pico cheese; an island cheese for a mainland river wine — Portugal united','cheese','established',2)
;
COMMIT;
