BEGIN;
INSERT INTO pairing_intelligence
  (beverage_product_id, food_flavour_profile, food_category, food_description, pairing_type, flavour_logic, meal_context, confidence, authority_tier)
VALUES
-- BC wines (1, 3, 4, 6-28)
(1,'BC, Okanagan, Red Icon, bold','cheese','Aged BC gouda from farm house with Black Sage honey and walnuts','complement','Red Icon''s Black Sage intensity bridges the aged BC Gouda; local honey echoes the Okanagan desert''s floral warmth','cheese','established',2),
(3,'Osoyoos Larose, Bordeaux blend, BC premium','cheese','Quebec-aged cheddar (3-year) with quince paste and sourdough','complement','Osoyoos Larose''s Bordeaux structure bridges the aged Quebec cheddar; a cross-Canada pairing of prestige dairy and wine','cheese','established',2),
(4,'Meritage, Okanagan, Bordeaux blend','casual','Duck liver pâté with Okanagan cherry jam on toasted baguette','complement','Meritage''s Bordeaux blend suits the duck pâté and cherry jam; a BC winery''s French bistrot moment','casual','established',2),
(6,'Perpetua, Chardonnay, Nk''Mip, Osoyoos','cheese','BC Camembert-style cheese with apple and Okanagan honey','complement','Perpetua''s Burgundian Chardonnay bridges the BC Camembert; local apple and honey tie the Okanagan terroir together','cheese','established',2),
(7,'Stewart Family Reserve, Pinot Noir, Naramata','casual','BC charcuterie: rosemary salami, Okanagan dried cherries, sourdough','complement','Stewart Family Reserve Pinot bridges the BC charcuterie board; Naramata terroir for a Naramata Bench provisions selection','casual','established',2),
(8,'Platinum Block 2, Naramata, Pinot Noir','casual','Mushroom and black truffle bruschetta with Naramata thyme','complement','Platinum Block 2''s complexity bridges the black truffle mushroom bruschetta; Naramata volcanic soil for a foraged flavour','starter','established',2),
(9,'Unparalleled, Naramata, premium Pinot','celebration','Tasting menu at a Naramata Bench winery table with seasonal BC dishes','complement','Unparalleled''s premium expression belongs at the chef''s table; Naramata''s finest Pinot for Naramata''s finest tasting experience','celebration','classic',1),
(10,'Jackpot, Cabernet Franc, herbal, BC','casual','BC venison tartare with caper berries and smoked salt','complement','Jackpot Cab Franc''s herbal depth bridges the venison tartare''s mineral rawness; a BC herbal wine for BC wild game','starter','established',2),
(11,'Qwam Qwmt, Syrah, Black Sage, Okanagan','game','BC black bear slow-braised with juniper and root vegetables','complement','Qwam Qwmt Syrah''s northern Rhône peppery character bridges the braised bear; a BC wilderness pairing','main','adventurous',2),
(12,'Dead of Night, blend, bold, BC','beef','Okanagan beef osso buco with gremolata and saffron risotto','complement','Dead of Night''s bold BC red belongs with the osso buco''s gelatin richness; a winery dinner pairing of substance','main','established',2),
(13,'Signature, Naramata, structured blend','game','Grilled BC bison rib-eye with smoked bone marrow and chimichurri','complement','Signature''s structured complexity bridges the bison rib-eye''s lean richness; bone marrow softens the intensity','main','established',2),
(14,'Pinot Noir, Naramata, everyday, approachable','casual','BC mushroom and goat cheese flatbread with Naramata herbs','complement','Naramata Pinot''s approachable character bridges the mushroom and goat cheese flatbread; an easy winery picnic pairing','casual','established',2),
(15,'Hypothesis, blend, Okanagan, value','casual','BC smoked salmon and cream cheese bagel with pickled red onion','complement','Hypothesis Blend''s BC versatility bridges the smoked salmon bagel; a casual Okanagan wine for an everyday BC staple','casual','suggested',2),
(16,'CheckMate Queen Taken, Chardonnay, luxury','celebration','BC halibut en papillote with lemon, herbs and crab butter','complement','CheckMate Queen Taken elevates halibut en papillote; the crab butter bridges Burgundian structure and Pacific richness','fish_course','classic',1),
(17,'Cabernet Sauvignon, Columbia Valley, WA','casual','Columbia River steelhead with miso butter and pickled daikon','complement','Columbia Valley Cabernet''s warmth bridges the steelhead''s mineral richness; a river wine for a river fish','fish_course','established',2),
(18,'Cabernet Sauvignon, Black Sage, Okanagan','casual','Black Sage Road lamb chops with garlic and wild sage','complement','Black Sage Bench Cabernet bridges the Black Sage Road lamb with sage; the desert herb echoes in both wine and land','main','classic',1),
(19,'Perigee, Naramata, Bordeaux style','celebration','Beef Wellington with Okanagan black truffle and fois gras layer','complement','Perigee''s complexity suits the double-luxury Beef Wellington with black truffle; a celebration of Naramata''s ambition','celebration','established',2),
(20,'Cailloux, Syrah, Walla Walla, pepper','casual','Walla Walla sweet onion soup with Gruyère crostini','complement','Cailloux Syrah''s Walla Walla character bridges the Walla Walla onion soup; the same valley''s most loved vegetable','casual','established',2),
(21,'Chaleur Estate, Columbia Valley, Bordeaux blend','cheese','Aged Tillamook Cheddar with quince and dark muscadine grape','complement','Chaleur Estate''s Bordeaux character bridges the aged Tillamook Cheddar; a Columbia Valley wine for Oregon''s great dairy','cheese','established',2),
(22,'Champoux, Cab, Horse Heaven Hills','casual','Horse Heaven Hills smoked lamb ribs with sage and desert herbs','complement','Champoux''s Horse Heaven Hills origin bridges the smoked lamb; desert sage echoes both the wine''s mineral and the smoke','casual','established',2),
(23,'Old Vines, Wahluke, Cabernet','casual','Wahluke Slope roasted duck with Columbia Valley cherry compote','complement','Old Vines'' Wahluke concentration bridges the roast duck; the desert cherry compote connects to the Wahluke dark fruit','main','established',2),
(24,'Eroica, Riesling, Chateau Ste Michelle, off-dry','dessert','Peach tarte Tatin with Riesling cream and cardamom','complement','Eroica''s off-dry Riesling bridges the peach Tatin; the Riesling cream creates a wine-into-dessert flavour unity','dessert','established',2),
(25,'John Lewis, Syrah, Walla Walla, intense','casual','Lamb merguez sausage with harissa, roasted peppers and couscous','complement','John Lewis Syrah''s intensity bridges the lamb merguez and harissa; a Walla Walla pepper wine for a North African-spiced lamb','casual','established',2),
(26,'Subduction Red, Columbia Valley, approachable','casual','Columbia Valley grain bowl with roasted beets, walnuts and goat cheese','complement','Subduction Red''s accessible Columbia Valley character bridges the grain bowl''s earthy depth; a wine for the valley''s produce','casual','suggested',2),
(27,'CMS Red, Helix, Columbia Valley, everyday','casual','Pepperoni and mozzarella pizza with black olives','complement','CMS Red''s everyday accessibility makes it the perfect pizza wine; a Columbia Valley red for the casual American table','casual','established',2),
(28,'Chester-Kidder, Champoux, premium blend','beef','Dry-aged Champoux-region beef tomahawk with bordelaise','complement','Chester-Kidder''s premium Champoux site belongs with the dry-aged tomahawk; a single-vineyard wine for a single-cut celebration','main','classic',1),

-- Oregon wines (29-39)
(29,'Dundee Hills, Pinot Noir, volcanic','cheese','Willamette Valley Willamette Diary Havarti with Oregon cherry jam','complement','Dundee Hills Pinot''s volcanic character bridges the Oregon Havarti and cherry jam; a local valley pairing of dairy and wine','cheese','classic',2),
(30,'Original Vines, Chehalem, old vine','casual','Grilled Oregon coho salmon with fennel and Chehalem herb salsa','complement','Original Vines'' old-vine character bridges the coho salmon and fennel; both come from Chehalem Mountain''s influence','fish_course','classic',2),
(31,'Avni, Chehalem, floral Pinot','casual','Oregon dungeness crab cakes with tarragon aioli','complement','Avni Pinot''s floral Chehalem character bridges the dungeness crab cake; a mountain wine for a Pacific coast shellfish','fish_course','established',2),
(32,'Seven Springs, limestone, Eola-Amity','casual','Oregon hazelnut-crusted halibut with Pinot beurre blanc','complement','Seven Springs'' limestone Pinot bridges the hazelnut halibut; Oregon hazelnuts echo the wine''s nutty soil character','fish_course','established',2),
(33,'Casteel Reserve, WA-OR, complex Pinot','celebration','Willamette Valley heritage turkey with Pinot pan jus and hazelnuts','complement','Casteel Reserve''s complexity belongs with a holiday bird; hazelnuts and Pinot are Willamette''s signature combination','celebration','classic',2),
(34,'Eileen, Carlton, Pinot, single vineyard','casual','Pan-roasted Oregon quail with Cascade blackberry and sage','complement','Eileen Vineyard''s Carlton character bridges the roasted quail and Cascade blackberry; a vineyard wine for a vineyard farm','main','classic',2),
(35,'Beaux Frères, Ribbon Ridge, powerful Pinot','cheese','Aged Rogue Creamery Crater Lake Blue with Ribbon Ridge pear','complement','Beaux Frères''s powerful Ribbon Ridge bridges the aged blue cheese and local pear; a great wine for a great cheese','cheese','established',2),
(36,'Old Stones, mineral, Pinot Noir','casual','Willamette Valley wild mushroom bisque with truffle oil and chives','complement','Old Stones'' mineral character bridges the wild mushroom bisque; both express the Willamette valley floor''s earthy depth','casual','established',2),
(37,'Savoya, volcanic, Eola-Amity Pinot','celebration','Savoya Ranch spring lamb rack with Eola cherry reduction and herbs','complement','Savoya Vineyard''s volcanic site belongs with the ranch''s own spring lamb; a farm-to-table terroir pairing','main','classic',2),
(38,'Elizabeth''s Reserve, Ponzi, Chehalem','casual','Oregon venison burger with Pinot reduction and Cascade goat cheese','complement','Elizabeth''s Reserve Pinot bridges the Oregon venison burger; a Willamette wine for a Willamette game occasion','casual','established',2),
(39,'Tempranillo Reserve, Abacela, Umpqua','cheese','Manchego-style Oregon sheep cheese with membrillo and Marcona almonds','complement','Abacela Tempranillo''s Spanish variety in Oregon bridges the Manchego-style sheep cheese; the Umpqua valley as Rioja West','cheese','established',2),

-- Flagship wines (175-182)
(175,'Opus One 2019, Napa, Bordeaux blend','celebration','Wagyu beef tartare with truffle and gold leaf on brioche toast','complement','Opus One''s Napa Bordeaux prestige belongs with the wagyu tartare; both are expressions of luxury at the highest table','starter','classic',1),
(176,'Ridge Monte Bello, Santa Cruz, Cabernet','cheese','Point Reyes Toma with Okanagan quince paste and walnut bread','complement','Ridge Monte Bello''s complexity bridges the aged Toma; a California mountain wine for California''s finest aged cheese','cheese','classic',1),
(177,'Penfolds Grange, South Australia, Shiraz icon','celebration','Roast saddle of lamb with Australian bush tomato jus and native herbs','complement','Penfolds Grange belongs with Australia''s finest table; the indigenous bush tomato sauce echoes the wine''s sun-ripened depth','main','classic',1),
(178,'Henschke Hill of Grace, Eden Valley, Shiraz','celebration','Dry-aged Australian Wagyu beef côte de boeuf with bordelaise','complement','Hill of Grace''s single-vineyard Eden Valley prestige belongs with the finest Australian beef; both are national icons','main','classic',1),
(179,'Cloudy Bay, Sauvignon Blanc, Marlborough','cheese','Fresh chèvre with NZ honey, toasted seeds and fresh herbs','complement','Cloudy Bay''s bright Marlborough Sauvignon bridges the fresh chèvre; both express clean herbaceous freshness','cheese','classic',1),
(180,'Felton Road Block 3, Central Otago, Pinot Noir','celebration','Central Otago wild venison with Pinot reduction and wild mushrooms','complement','Felton Road Block 3''s elevation character belongs with the local wild venison; the same landscape elevated','main','classic',1),
(181,'Catena Zapata Adrianna Malbec, Mendoza, high altitude','celebration','Argentine asado: prime beef rib-eye with chimichurri and salt','complement','Catena Zapata''s Adrianna altitude belongs with the Argentine asado; Mendoza''s greatest Malbec for Argentina''s national meal','main','classic',1),
(182,'Sadie Columella, Swartland, old vines','cheese','Karoo lamb and aged Huguenot cheese with dried apricot','complement','Sadie Columella''s Swartland depth bridges the Karoo lamb and aged cheese; South Africa''s finest wine for its finest pantry','cheese','classic',1),

-- DRC / Burgundy (191-202)
(191,'DRC, Romanée-Conti, monopole, pinnacle','celebration','White truffle (Périgord) risotto with aged Parmesan and gold leaf','elevate','La Romanée-Conti elevates the white truffle risotto; the world''s greatest wine for the world''s most expensive fungus','celebration','classic',1),
(192,'DRC, La Tâche, Monopole, grand cru','celebration','Whole roasted Bresse chicken with DRC-braised morel jus','elevate','La Tâche''s complexity belongs with Bresse chicken and morel jus; the Domaine''s prestige for France''s greatest poultry','celebration','classic',1),
(193,'Rousseau, Chambertin, grand cru, powerful','celebration','Jugged hare à la royale with foie gras and truffles','complement','Rousseau Chambertin''s grand cru power bridges the lièvre à la royale; Burgundy''s most regal preparation for the region''s greatest wine','celebration','classic',1),
(194,'Roumier, Musigny, grand cru, silk','celebration','Wild duck (canard sauvage) with Musigny sauce and cèpes','complement','Roumier Musigny''s silky grand cru bridges the wild duck; Chambolle''s feminine wine for delicate game','celebration','classic',1),
(195,'Leflaive, Montrachet, white grand cru','celebration','Homard à la presse (pressed lobster) with Montrachet cream','elevate','Leflaive Montrachet elevates the homard à la presse; the world''s greatest white wine for the world''s most classical dish','celebration','classic',1),
(196,'Coche-Dury, Meursault Perrières, 1er cru','fish_course','Turbot en croûte with Meursault butter sauce and black truffle','elevate','Coche-Dury Perrières elevates the turbot en croûte; the premier cru''s complexity for a grand fish preparation','fish_course','classic',1),
(197,'Raveneau, Chablis Grand Cru Les Clos','fish_course','Langoustines rôties with Chablis beurre blanc and herb oil','complement','Raveneau Les Clos''s mineral grand cru bridges the langoustines; the classic Chablis and shellfish affinity at its peak','fish_course','classic',1),
(198,'Mugnier, Musigny, grand cru, elegant','celebration','Bécasse rôtie (roast woodcock) with toast and blood sauce','complement','Mugnier Musigny''s supreme elegance bridges the roast woodcock; the most delicate game for the most elegant Pinot','celebration','classic',1),
(199,'Jadot, Chambertin Clos de Bèze, grand cru','celebration','Whole roasted pigeon (pigeonneaux rôtis) with Pinot reduction','complement','Jadot Chambertin Clos de Bèze belongs with roast pigeon; a grand cru for the classic Burgundian game pairing','celebration','classic',1),
(200,'Dauvissat, Chablis 1er Cru La Forest, limestone','fish_course','Huîtres gratinées with champagne and shallot cream','complement','Dauvissat La Forest''s Kimmeridgian limestone bridges the gratin oyster; premier cru Chablis for an oyster tradition','fish_course','classic',1),
(201,'Roulot, Meursault Les Charmes, 1er cru','cheese','Comté 30-month with walnut bread and pear mostarda','complement','Roulot Charmes''s Meursault depth bridges the aged Comté; a premier cru from Meursault for the region''s milk heritage','cheese','classic',1),
(202,'Faiveley, Corton-Charlemagne, grand cru','celebration','Slow-poached turbot with Corton-Charlemagne reduction and caviar','elevate','Faiveley Corton-Charlemagne elevates the slow-poached turbot; the grand cru''s power for the grandest preparation','celebration','classic',1),

-- Bordeaux left bank + right bank (223-232)
(223,'Lafite Rothschild, Pauillac, first growth','celebration','Lamb saddle with morille sauce and Lafite reduction — château dinner','elevate','Château Lafite Rothschild elevates the lamb saddle; the first growth''s pencil-cedar structure bridges the spring lamb','celebration','classic',1),
(224,'Mouton Rothschild, Pauillac, first growth','celebration','Côte de boeuf Wagyu with Mouton-braised shallots and marrow','complement','Mouton Rothschild''s Pauillac first growth belongs with the finest beef; the shallot jus braised in the wine creates unity','celebration','classic',1),
(225,'Château Latour, Pauillac, first growth, structure','celebration','Leg of Pauillac lamb with rosemary and garlic confit','complement','Château Latour''s iron structure belongs with Pauillac lamb; the château''s appellation is named for the wine','celebration','classic',1),
(226,'Château Margaux, Margaux, first growth, elegant','celebration','Saddle of Médoc lamb with Margaux sauce and truffle','elevate','Château Margaux elevates the saddle of lamb; the first growth''s perfumed elegance for the most delicate lamb preparation','celebration','classic',1),
(227,'Château Haut-Brion, Graves, first growth','celebration','Whole roasted Pauillac lamb with Bordeaux red wine sauce','complement','Haut-Brion''s Graves first growth belongs with roasted lamb; the Graves terroir and the lamb tradition are inseparable','celebration','classic',1),
(228,'Château Pétrus, Pomerol, Merlot, icon','celebration','Beef tenderloin en croûte with black truffle and foie gras duxelles','elevate','Pétrus elevates the tenderloin en croûte with truffle; the most hedonistic Pomerol for the most indulgent preparation','celebration','classic',1),
(229,'Cheval Blanc, Saint-Émilion, first growth B','celebration','Roast duck with Cheval Blanc sauce and cèpes and pommes sarladaises','complement','Cheval Blanc''s Saint-Émilion blend bridges the roast duck and cèpes; the château''s Cab Franc structure suits delicate game','celebration','classic',1),
(230,'Pavillon Blanc, Margaux, Sauvignon Blanc','fish_course','Sole meunière with lemon beurre noisette and capers','complement','Pavillon Blanc''s Margaux Sauvignon bridges the sole meunière; a Bordeaux white for the classic French fish preparation','fish_course','classic',1),
(231,'Léoville Las Cases, Saint-Julien, grand cru','celebration','Rack of Pauillac lamb with herbes de Provence and Bordelaise jus','complement','Léoville Las Cases''s Saint-Julien structure belongs with the rack of lamb; the finest preparation for a second growth','celebration','classic',2),
(232,'Cos d''Estournel, Saint-Estèphe, second growth','beef','Entrecôte bordelaise with marrow, shallot and red wine sauce','complement','Cos d''Estournel''s Saint-Estèphe power bridges the entrecôte bordelaise; the sauce made with the same Médoc appellation wine','main','classic',1),

-- Rhône (233-240)
(233,'Guigal, La Mouline, Côte-Rôtie, white Viognier','game','Roast partridge with white Viognier jus and fresh thyme','complement','La Mouline''s Viognier co-ferment bridges the roast partridge; the white wine in the jus echoes the wine''s aromatic lift','main','classic',1),
(234,'Guigal, La Landonne, Côte-Rôtie, masculine','beef','Côte de boeuf grillée with Côte-Rôtie sauce and bone marrow','complement','La Landonne''s powerful Côte-Rôtie belongs with the côte de boeuf; the most masculine Guigal for the most substantial cut','main','classic',1),
(235,'Chave, Hermitage Rouge, Syrah, granite','game','Hare civet with blood sauce and fresh pasta','complement','Chave Hermitage''s granite Syrah bridges the hare civet''s blood depth; Hermitage''s power for the most robust game preparation','main','classic',1),
(236,'Jaboulet, La Chapelle, Hermitage, prestige','lamb','Gigot d''agneau à la Provençale with olives and thyme','complement','La Chapelle''s Hermitage prestige bridges the lamb gigot; Provençal herbs and olives reflect the granite hillside''s warmth','main','classic',1),
(237,'Clape, Cornas, Syrah, granite, intense','game','Wild boar (sanglier) bourguignon with lardons and wild mushrooms','complement','Clape Cornas''s intense granite Syrah bridges the wild boar bourguignon; a granitic wine for the most rustic game preparation','main','classic',1),
(238,'Château Rayas, Châteauneuf, Grenache, sandstone','celebration','Lamb in a wood-fired oven (gigot d''agneau au bois) with herbs','complement','Château Rayas''s sandy Châteauneuf Grenache bridges the wood-fired lamb; both come from the garrigue and the flame','celebration','classic',1),
(239,'Beaucastel, Châteauneuf, multi-cépage','game','Sanglier (wild boar) daube with olives and herbes de Provence','complement','Beaucastel''s multi-cépage Châteauneuf bridges the wild boar daube; the garrigue complexity matches the Provençal herb character','main','classic',1),
(240,'Vernay, Coteau de Vernon, Condrieu, Viognier','cheese','Saint-Félicien cheese with quince jelly and walnut bread','complement','Vernay Coteau de Vernon''s great Condrieu bridges the Saint-Félicien; the apricot Viognier character suits the creamy washed rind','cheese','classic',1),

-- Loire (299-306)
(299,'Dagueneau, Pouilly-Fumé Silex, flint, mineral','cheese','Crottin de Chavignol (young) with flint honey and black pepper','complement','Dagueneau Silex''s flint mineral character belongs with Crottin de Chavignol; the Loire''s greatest Sauvignon and its greatest cheese','cheese','classic',1),
(300,'Dagueneau, Pouilly-Fumé Pur Sang, pure','seafood','Pike-perch (sandre) with Loire butter sauce and shallots','complement','Pur Sang''s mineral purity bridges the Loire pike-perch; Dagueneau''s wine for the Loire''s own river fish','fish_course','classic',1),
(301,'Huet, Vouvray Le Mont Sec, dry, chenin','fish_course','Rillettes de Tours (pork rillettes) with cornichons and sourdough','complement','Huet Vouvray Sec''s mineral depth and acidity bridges the rich pork rillettes; a dry Loire white for the Touraine''s own pork classic','starter','classic',1),
(302,'Huet, Vouvray Clos du Bourg, demi-sec, chenin','cheese','Époisses AOP washed rind with dark bread and walnut','complement','Huet Demi-Sec''s off-dry richness bridges Époisses''s intense washed rind; the residual sweetness tames the stinky cheese','cheese','classic',1),
(303,'Coulée de Serrant, Savennières, biodynamic','fish_course','Sole normande with mushrooms, oysters and cream sauce','complement','Nicolas Joly''s Coulée de Serrant bridges the sole normande''s cream; a great biodynamic chenin for Normandy''s complex fish dish','fish_course','classic',1),
(304,'Cotat, Sancerre Les Monts Damnés, mineral','cheese','Crottin de Chavignol aged (affiné) with quince and walnuts','complement','Cotat Monts Damnés''s powerful mineral Sancerre bridges the aged Crottin; a great wine for the Loire''s classic cheese','cheese','classic',1),
(305,'Vacheron, Sancerre Les Romains, biodynamic','seafood','Asparagus with Sancerre beurre blanc and smoked trout roe','complement','Vacheron Romains''s biodynamic Sancerre bridges the asparagus and beurre blanc; the wine in the sauce creates unity','starter','classic',1),
(306,'Pépière, Muscadet Clisson, granite, sur lie','seafood','Moules marinières (mussels in white wine) with sourdough bread','complement','Pépière Clisson''s Muscadet character bridges the moules marinières; drinking the wine used in the broth is Nantais tradition','main','classic',1),

-- Alsace (307-316)
(307,'Trimbach, Clos Sainte Hune, Riesling, great','fish_course','John Dory with Riesling beurre blanc and Alsace Choucroute julienne','complement','Clos Sainte Hune elevates John Dory; the Riesling in the beurre blanc creates a direct wine-to-sauce flavour link','fish_course','classic',1),
(308,'Trimbach, Frédéric Émile, Riesling, mineral','fish_course','Grilled sea bass with lemon oil and fennel fronds','complement','Frédéric Émile''s mineral depth bridges the sea bass; Alsace Riesling''s dry mineral acidity is the classic fish companion','fish_course','classic',1),
(309,'Zind-Humbrecht, Clos Windsbuhl, Riesling, grand','cheese','Munster AOP (young) with caraway seeds and dark bread','complement','Windsbuhl''s grand Riesling bridges the Munster; the Alsace tradition of the region''s wine with the region''s cheese','cheese','classic',1),
(310,'Zind-Humbrecht, Pinot Gris Hengst, rich','main','Foie gras mi-cuit with Hengst Vendange Tardive gelée','complement','Hengst Pinot Gris''s grand cru richness bridges the foie gras mi-cuit; Alsace Pinot Gris is the classical foie gras companion','starter','classic',1),
(311,'Weinbach, Riesling Schlossberg, grand cru, elegant','fish_course','Tarte flambée (Flammkuche) with smoked salmon and crème fraîche','complement','Weinbach Schlossberg''s elegant Riesling bridges the smoked salmon tarte flambée; an Alsace wine for an Alsace dish','casual','classic',1),
(312,'Hugel, Riesling Jubilee, Alsace, classic','fish_course','River trout à l''alsacienne with lardons, Riesling and onions','complement','Hugel Jubilee Riesling bridges the trout à l''alsacienne; the Riesling in the sauce creates a traditional flavour loop','fish_course','classic',1),
(314,'Trimbach, Gewurztraminer Seigneurs, intense','cheese','Munster AOP (affiné) with cumin seed bread and white wine','complement','Seigneurs de Ribeaupierre''s intense Gewurztraminer bridges the affiné Munster; the intensity matches the pungency','cheese','classic',1),
(315,'Ostertag, Muenchberg Grand Cru, Riesling, volcanic','fish_course','Langoustines à l''alsacienne with Riesling bisque and chervil','complement','Ostertag Muenchberg''s volcanic Riesling bridges the langoustines in bisque; the wine in the bisque creates direct unity','fish_course','classic',1),
(316,'Marcel Deiss, Bergheim, field blend, terroir','casual','Choucroute garnie alsacienne with smoked pork and Montbéliard sausage','complement','Marcel Deiss''s field blend bridges the choucroute garnie; the Alsace wine for the Alsace''s defining slow-cooked tradition','main','classic',1),

-- Piemonte Barolo/Barbaresco (325-333)
(325,'Gaja, Barbaresco, iconic, modern','cheese','Castelmagno cheese with acacia honey and walnut bread','complement','Gaja Barbaresco''s modern Piemonte prestige bridges the Castelmagno; the Piemontese blue-veined cheese for the Piemontese icon','cheese','classic',1),
(326,'Gaja, Sorì Tildìn, single vineyard Barbaresco','celebration','Tajarin with white truffle (tartufo bianco) and butter','elevate','Sori Tildin''s single-vineyard complexity elevates tajarin with white truffle; Alba''s greatest wine for Alba''s greatest truffle','celebration','classic',1),
(327,'Bruno Giacosa, Barolo Falletto, Serralunga, classic','game','Lepre in civet (Piemontese hare stew) with polenta','complement','Giacosa Falletto''s classic Barolo bridges the hare civet; a Piemontese wine for Piemonte''s most traditional game stew','main','classic',1),
(328,'Conterno, Monfortino, Riserva, legend, power','celebration','Finanziera (Piemontese offal stew) with calf''s head and sweet-sour sauce','complement','Monfortino''s legendary power belongs with the finanziera; both are time-intensive expressions of Piemontese tradition','celebration','classic',1),
(329,'Bartolo Mascarello, Barolo, traditional, pure','game','Salsiccia di Bra cruda (raw Bra sausage) with crostini and Barolo','complement','Bartolo Mascarello''s traditional Barolo belongs with the Bra raw sausage; a Piemontese artisan wine for an artisan charcuterie','starter','classic',1),
(330,'Vietti, Barolo Castiglione, approachable Barolo','casual','Tajarin al ragù di carne (egg pasta with meat ragù) from La Morra','complement','Vietti Castiglione''s approachable Barolo bridges the tajarin ragù; a Barolo for the everyday La Morra table pairing','main','classic',1),
(331,'G.D. Vajra, Barolo Bricco delle Viole, perfumed','casual','Battuta di fassone (Piemontese beef tartare) with truffle shavings','complement','Vajra Bricco delle Viole''s elevation and perfume bridges the raw fassone beef; the violet scent of the wine suits the purity of raw beef','starter','classic',1),
(332,'Roagna, Barbaresco Crichet Pajé, old vines','game','Cinghiale (wild boar) stufato with olives and herb polenta','complement','Roagna Crichet Pajé''s old vine depth bridges the wild boar stufato; a powerful wine for the Langhe''s wildest game','main','classic',2),
(333,'Ceretto, Barolo Bricco Rocche, landmark','celebration','Risotto al Barolo with Castelmagno and marrow bone','complement','Ceretto Bricco Rocche''s landmark status belongs with the risotto al Barolo; cooking with the same wine creates a unified table','celebration','classic',1)
;
COMMIT;
