#!/usr/bin/env python3
"""
Terminal 4 — Batch 8: Pairing intelligence for products 192, 198–222, 224, 226, 230–232, 236, 247–269
Covers: Remaining Burgundy, Bordeaux, Rhône, Japanese teas, Chinese/Taiwanese teas
"""
import psycopg2

CONN = "postgres://provenance_tester_1:GBN1MbQJMbe_7Ze2Is6dZQSK4hGwXkbW@localhost:15432/provenance_tester_1?sslmode=disable"

PAIRINGS = [
    # ── DRC La Tâche Grand Cru (192) ────────────────────────────────────────────
    {"beverage_product_id": 192, "beverage_category": "wine_still",
     "beverage_style": "Grand Cru Pinot Noir — Vosne-Romanée, DRC monopole",
     "beverage_description": "Silky, aromatic, complex — violet, sanguine, dried cherry, forest floor, ethereal tannin",
     "food_category": "game_bird", "food_flavour_profile": "savoury-earthy",
     "food_description": "Roasted squab pigeon — thyme jus, ceps, truffle oil, silver butter",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "La Tâche's haunting violet and forest aromatics mirror the savouriness of squab. The wine's silky tannin supports without dominating the delicate game.",
     "confidence": "classic", "confidence_rationale": "Classic grand cru and game pairing — time-honoured French tradition",
     "authority_tier": 1, "source_text": "DRC service recommendations; Sommelier Society of France guidelines"},
    {"beverage_product_id": 192, "beverage_category": "wine_still",
     "beverage_style": "Grand Cru Pinot Noir — La Tâche monopole",
     "beverage_description": "Profound, silken Burgundy — dried rose, tea, iron, dark cherry, long ethereal finish",
     "food_category": "truffle", "food_flavour_profile": "earthy-umami",
     "food_description": "Périgord black truffle pasta — hand-cut tagliolini, unsalted butter, Parmigiano, shaved truffle",
     "pairing_type": "elevate", "meal_context": "main",
     "flavour_logic": "Truffle's earthy, musty-umami notes amplify the forest-floor complexity in La Tâche. The wine's intensity can hold its own against the most pungent truffle.",
     "confidence": "classic", "confidence_rationale": "The canonical Burgundy and truffle marriage — celebrated for centuries in Périgord and Burgundy alike",
     "authority_tier": 1, "source_text": "Daniel Boulud; Frédéric Bau truffle service notes"},

    # ── Domaine J.-F. Mugnier Musigny (198) ─────────────────────────────────────
    {"beverage_product_id": 198, "beverage_category": "wine_still",
     "beverage_style": "Grand Cru Pinot Noir — Chambolle-Musigny, Mugnier estate",
     "beverage_description": "Ethereal, lacy, fine-boned — raspberry, violet, cool forest, crystalline tannin",
     "food_category": "poultry_fine", "food_flavour_profile": "delicate-herbal",
     "food_description": "Poularde de Bresse en vessie — classic bladder-roasted Bresse chicken with foie gras stuffing",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Musigny's ethereal delicacy demands equal finesse in the kitchen. Bresse chicken's incomparable fat and texture matches without overwhelming the wine's lace-like structure.",
     "confidence": "classic", "confidence_rationale": "Historical pairing from Chambolle restaurant tradition",
     "authority_tier": 1, "source_text": "Jacques Mugnier service recommendations; Paul Bocuse Bresse chicken pairing tradition"},
    {"beverage_product_id": 198, "beverage_category": "wine_still",
     "beverage_style": "Musigny Grand Cru — finest Chambolle expression",
     "beverage_description": "Silk and iron — violet, rose petal, raspberry, wet stone, exceptionally long finish",
     "food_category": "mushroom_luxury", "food_flavour_profile": "earthy-delicate",
     "food_description": "Morilles à la crème — morel mushrooms in crème fraîche, vin jaune, tarragon, on brioche toast",
     "pairing_type": "elevate", "meal_context": "starter",
     "flavour_logic": "Morel's earthy, nutty, cream-driven character amplifies the soil and forest notes in Musigny without competing with its ethereal red fruit.",
     "confidence": "established", "confidence_rationale": "Mushroom-Burgundy pairing well established in regional Burgundian gastronomy",
     "authority_tier": 2, "source_text": "Les Amis du Vin Bourgogne mushroom-Pinot affinity notes"},

    # ── Maison Louis Jadot Chambertin Clos de Bèze (199) ────────────────────────
    {"beverage_product_id": 199, "beverage_category": "wine_still",
     "beverage_style": "Grand Cru Pinot Noir — Gevrey-Chambertin, Jadot Clos de Bèze",
     "beverage_description": "Powerful, structured Burgundy — dark cherry, cedar, iron, licorice, substantial tannin backbone",
     "food_category": "lamb_luxury", "food_flavour_profile": "rich-herbal",
     "food_description": "Rack of Pyrenean lamb — herb crust (rosemary, thyme, Dijon), roasted garlic confit, sauce périgueux",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Chambertin Clos de Bèze's more structured character vs. Musigny suits the weight of lamb. Herbaceous crust echoes the wine's garrigue notes; périgueux sauce bridges the truffle-earthiness.",
     "confidence": "classic", "confidence_rationale": "Gevrey-Chambertin and lamb is a time-honoured pairing at Burgundy tables",
     "authority_tier": 1, "source_text": "Maison Jadot service recommendations; Marc Chevillon pairing guide"},
    {"beverage_product_id": 199, "beverage_category": "wine_still",
     "beverage_style": "Chambertin Clos de Bèze — Jadot négociant grand cru",
     "beverage_description": "Structured, age-worthy Chambertin — iron, licorice, cherry stone, long dark finish",
     "food_category": "beef_luxury", "food_flavour_profile": "savoury-rich",
     "food_description": "Boeuf en daube Bourguignonne — slow-braised beef short rib in Gevrey-Chambertin, lardons, carrots, pearl onions",
     "pairing_type": "bridge", "meal_context": "main",
     "flavour_logic": "Cooking with Chambertin and pairing with Chambertin creates seamless integration. The braise absorbs the wine's iron and cherry, reflecting it back with amplified depth.",
     "confidence": "classic", "confidence_rationale": "Regional Burgundian cooking tradition — using village wine in the braise, serving grand cru with it",
     "authority_tier": 1, "source_text": "Cuisine Bourguignonne tradition; Georges Blanc pairing notes"},

    # ── Domaine René & Vincent Dauvissat Chablis (200) ───────────────────────────
    {"beverage_product_id": 200, "beverage_category": "wine_still",
     "beverage_style": "Premier Cru Chablis — La Forest, Kimmeridgian limestone",
     "beverage_description": "Steel, oyster shell, green apple, lemon pith, mineral austerity — electric precision",
     "food_category": "oyster", "food_flavour_profile": "briny-mineral",
     "food_description": "Fines de Claires oysters (n°2) — served natural, with lemon, shallot mignonette",
     "pairing_type": "bridge", "meal_context": "aperitif",
     "flavour_logic": "The limestone beneath Chablis vineyards is the same Kimmeridgian formation full of ancient oyster fossils. Wine and food share the same mineral origin — a literal geological bridge.",
     "confidence": "classic", "confidence_rationale": "Chablis and oysters — the most famous geological pairing in French gastronomy",
     "authority_tier": 1, "source_text": "Dauvissat family notes; Jancis Robinson — Chablis/oyster origin story"},
    {"beverage_product_id": 200, "beverage_category": "wine_still",
     "beverage_style": "Premier Cru Chablis — La Forest, complex mineral Chardonnay",
     "beverage_description": "Tightly wound, mineral, citrus-driven — oyster shell, green pear, chalky texture",
     "food_category": "seafood_delicate", "food_flavour_profile": "clean-briny",
     "food_description": "Coquilles Saint-Jacques — hand-dived scallops, seared, champagne beurre blanc, micro herbs",
     "pairing_type": "complement", "meal_context": "fish_course",
     "flavour_logic": "Chablis acidity cuts the scallop's natural sweetness. The beurre blanc bridges the wine's mineral register to the scallop's delicate oceanic character.",
     "confidence": "classic", "confidence_rationale": "Classic French fish course and Chablis pairing",
     "authority_tier": 1, "source_text": "Guy Savoy; Frédéric Anton fish-Chablis pairing canon"},

    # ── Domaine Guy Roulot Meursault Les Charmes (201) ──────────────────────────
    {"beverage_product_id": 201, "beverage_category": "wine_still",
     "beverage_style": "Premier Cru Meursault — Les Charmes, Roulot domaine",
     "beverage_description": "Hazelnut, butter, lemon curd, white flower, nectarine — silky, long, textured",
     "food_category": "lobster", "food_flavour_profile": "rich-sweet",
     "food_description": "Homard breton — poached lobster tail, bisque velouté, tarragon cream, finger lime",
     "pairing_type": "elevate", "meal_context": "fish_course",
     "flavour_logic": "Meursault's signature hazelnut butter note becomes transformative when paired with lobster. The wine's texture matches the richness; its acidity lifts the bisque.",
     "confidence": "classic", "confidence_rationale": "Meursault and lobster — canonical Burgundy white and shellfish pairing",
     "authority_tier": 1, "source_text": "Domaine Roulot service notes; Alain Ducasse lobster pairings"},
    {"beverage_product_id": 201, "beverage_category": "wine_still",
     "beverage_style": "Meursault Les Charmes — buttery, textured premier cru white",
     "beverage_description": "Rich, supple, nutty white Burgundy — toasted hazelnuts, stone fruit, cream, mineral base",
     "food_category": "fish_luxury", "food_flavour_profile": "rich-oaky",
     "food_description": "Wild halibut — pan-roasted, cauliflower mousseline, brown butter, capers, lemon",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Halibut's firm, meaty white flesh supports the weight of Meursault. Brown butter sauce echoes the wine's hazelnut note exactly, creating seamless harmony.",
     "confidence": "classic", "confidence_rationale": "Rich white fish with Côte de Beaune white Burgundy — textbook French pairing",
     "authority_tier": 1, "source_text": "Guy Savoy; Michel Bras white Burgundy pairing tradition"},

    # ── Domaine Faiveley Corton-Charlemagne (202) ────────────────────────────────
    {"beverage_product_id": 202, "beverage_category": "wine_still",
     "beverage_style": "Grand Cru White Burgundy — Corton-Charlemagne, Faiveley",
     "beverage_description": "Powerful, structured Chardonnay — white mineral, almond, ginger, citrus zest, long finish",
     "food_category": "fish_meaty", "food_flavour_profile": "rich-delicate",
     "food_description": "Turbot rôti — roasted whole turbot, hollandaise, sea vegetables, lemon butter sauce",
     "pairing_type": "complement", "meal_context": "fish_course",
     "flavour_logic": "Corton-Charlemagne is the most powerful white Burgundy and requires the king of flatfish to match it. Turbot's density and hollandaise match the wine's muscle.",
     "confidence": "classic", "confidence_rationale": "Classic grand cru white and king flatfish pairing — Alain Ducasse tradition",
     "authority_tier": 1, "source_text": "Faiveley service guide; Alain Ducasse turbot pairing tradition"},
    {"beverage_product_id": 202, "beverage_category": "wine_still",
     "beverage_style": "Corton-Charlemagne Grand Cru — minerally powerful Chardonnay",
     "beverage_description": "Grand cru Chardonnay — almond, white mineral, lemon oil, ginger, stone fruit, austere length",
     "food_category": "veal", "food_flavour_profile": "delicate-rich",
     "food_description": "Veau de lait rôti — milk-fed veal, morels, vin blanc cream sauce, asparagus",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Corton-Charlemagne's power supports veal — itself the most delicate red-meat. Morel sauce and cream bring earthy-dairy notes that mirror the wine's mineral-almond axis.",
     "confidence": "established", "confidence_rationale": "White Burgundy grand cru with veal — established in classic French service",
     "authority_tier": 2, "source_text": "Classic French service canon; Pierre Gagnaire pairing notes"},

    # ── JAPANESE TEAS (203-222) ─────────────────────────────────────────────────
    # Ippodo Ummon Ceremonial Matcha (203)
    {"beverage_product_id": 203, "beverage_category": "tea",
     "beverage_style": "Ceremonial grade matcha — Ippodo, Kyoto Uji",
     "beverage_description": "Vibrant green, thick umami, vegetal sweetness, long persistent finish — no bitterness",
     "food_category": "wagashi_traditional", "food_flavour_profile": "sweet-delicate",
     "food_description": "Nerikiri wagashi — hand-shaped bean paste confection, seasonal motif (sakura, maple, or snow)",
     "pairing_type": "contrast", "meal_context": "dessert",
     "flavour_logic": "The sweetness of nerikiri bean paste creates perfect counterpoint to matcha's umami-bitter intensity. The traditional Japanese sweet bridge makes every sip of matcha more vivid.",
     "confidence": "classic", "confidence_rationale": "The canonical Japanese tea ceremony pairing — sweet wagashi before ceremonial matcha",
     "authority_tier": 1, "source_text": "Urasenke School of Chanoyu; Ippodo Tea Co. ceremonial service notes"},
    {"beverage_product_id": 203, "beverage_category": "tea",
     "beverage_style": "Ceremonial grade matcha — thick, umami-intense",
     "beverage_description": "Dark jade, oceanic umami, sweet grass, long finish with zero astringency",
     "food_category": "chocolate", "food_flavour_profile": "bitter-sweet",
     "food_description": "Valrhona Dulcey 32% blond chocolate — caramel, biscuit, vanilla — as a praline or tablette",
     "pairing_type": "contrast", "meal_context": "pre_dessert",
     "flavour_logic": "Blond chocolate's buttery caramel sweetness creates beautiful contrast with ceremonial matcha's green umami bitterness. Less confrontational than dark chocolate — harmony through difference.",
     "confidence": "suggested", "confidence_rationale": "Modern Japanese-French pâtisserie integration explored by Pâtisserie Sadaharu Aoki",
     "authority_tier": 2, "source_text": "Sadaharu Aoki, Paris; Bellocq tea pairing notes"},

    # Marukyu Koyamaen Wako Ceremonial Matcha (205)
    {"beverage_product_id": 205, "beverage_category": "tea",
     "beverage_style": "Ceremonial grade matcha — Marukyu Koyamaen, Uji",
     "beverage_description": "Intensely green, umami-forward, complex sweet finish, very fine powder texture",
     "food_category": "mochi", "food_flavour_profile": "sweet-neutral",
     "food_description": "Warabi mochi — bracken starch jelly, kinako dusting, kuromitsu syrup",
     "pairing_type": "contrast", "meal_context": "dessert",
     "flavour_logic": "Warabi mochi's soft neutral sweetness and kinako (roasted soy) toasty note creates a gentle platform for ceremonial matcha to shine. Kuromitsu adds depth.",
     "confidence": "classic", "confidence_rationale": "Traditional Japanese sweet mochi and tea pairing",
     "authority_tier": 1, "source_text": "Marukyu Koyamaen service notes; Kyoto tea house tradition"},

    # Kyoto Obubu Okumidori Single-Cultivar Matcha (208)
    {"beverage_product_id": 208, "beverage_category": "tea",
     "beverage_style": "Single-cultivar Okumidori matcha — Kyoto Obubu",
     "beverage_description": "Bright, grassy, sweet umami, cultivar-specific nori note, clean finish",
     "food_category": "cheese_fresh", "food_flavour_profile": "mild-creamy",
     "food_description": "Fresh ricotta — drizzled with acacia honey, lemon zest, crushed pistachio",
     "pairing_type": "contrast", "meal_context": "dessert",
     "flavour_logic": "Fresh ricotta's creamy neutrality creates a dairy canvas for matcha's oceanic-vegetal notes. Honey bridges the sweetness gap; pistachio adds corresponding earthiness.",
     "confidence": "suggested", "confidence_rationale": "Modern Japanese-Italian fusion pairing — Obubu's international collaboration context",
     "authority_tier": 2, "source_text": "Obubu Tea Farm international pairing events; Bellocq tea guides"},

    # Ippodo Gyokuro Sayamakaori (210)
    {"beverage_product_id": 210, "beverage_category": "tea",
     "beverage_style": "Gyokuro — shade-grown, Ippodo, Kyoto Uji",
     "beverage_description": "Intensely sweet, thick liquor, seaweed-umami, low astringency, cool brewing temperature",
     "food_category": "sashimi_delicate", "food_flavour_profile": "oceanic-clean",
     "food_description": "Hirame (flounder) sashimi — thin-sliced, ponzu, micro shiso, yuzu zest",
     "pairing_type": "complement", "meal_context": "starter",
     "flavour_logic": "Gyokuro's seaweed-umami register matches flounder's delicate oceanic sweetness. Both cool and refined — gyokuro's low bitterness won't overpower the fish.",
     "confidence": "established", "confidence_rationale": "Japanese fine dining pairing of gyokuro with delicate white fish",
     "authority_tier": 1, "source_text": "Ippodo Tea pairing guide; Japanese sommelier association (SAKE SERVICE RESEARCH) pairing notes"},
    {"beverage_product_id": 210, "beverage_category": "tea",
     "beverage_style": "Premium gyokuro — thick, sweet, ocean-umami",
     "beverage_description": "Dark jade, silky, long savouriness — edamame, sweet seaweed, zero bitterness",
     "food_category": "egg_luxury", "food_flavour_profile": "rich-umami",
     "food_description": "Chawanmushi — silken egg custard with Hokkaido uni, dashi broth, yuzu foam, mitsuba",
     "pairing_type": "elevate", "meal_context": "starter",
     "flavour_logic": "Chawanmushi shares gyokuro's umami depth and silky texture. Uni amplifies the oceanic note in both food and tea simultaneously. Supreme umami harmony.",
     "confidence": "suggested", "confidence_rationale": "High-end Japanese kaiseki pairing concept from omakase context",
     "authority_tier": 2, "source_text": "Narisawa; Ippodo Tea kaiseki pairing seminars"},

    # Marukyu Koyamaen Gyokuro Unkaku (211)
    {"beverage_product_id": 211, "beverage_category": "tea",
     "beverage_style": "Gyokuro Unkaku — premium Marukyu, super-shade grown",
     "beverage_description": "Almost opaque dark-green liquor — extreme umami, thick, sweet, green ocean depth",
     "food_category": "wagashi_traditional", "food_flavour_profile": "sweet-delicate",
     "food_description": "Higashi — dry wagashi, powdered sugar pressed sweets, very lightly sweetened",
     "pairing_type": "contrast", "meal_context": "dessert",
     "flavour_logic": "Dry higashi's light sugar provides the sweet contrast to gyokuro's deep umami without overpowering. The dryness complements gyokuro's thick sweetness — not competing.",
     "confidence": "classic", "confidence_rationale": "Traditional higashi served with high-grade gyokuro in Japanese tea ceremony",
     "authority_tier": 1, "source_text": "Marukyu Koyamaen tea school; Urasenke higashi-gyokuro pairing"},

    # Ippodo Sencha Shogyokuro (213)
    {"beverage_product_id": 213, "beverage_category": "tea",
     "beverage_style": "Premium sencha — Ippodo, Kyoto Uji, first flush",
     "beverage_description": "Bright green, grassy-marine, crisp acidity, balanced astringency, clean mineral finish",
     "food_category": "sushi", "food_flavour_profile": "clean-marine",
     "food_description": "Nigiri omakase — seasonal Edomae-style, vinegared sushi rice, soy, wasabi",
     "pairing_type": "cleanse", "meal_context": "any",
     "flavour_logic": "Sencha's tannin and grassiness cleanse the palate between courses of oily fish, clearing residual fat while complementing rice vinegar with its own acidity.",
     "confidence": "established", "confidence_rationale": "Traditional Japanese sushi bar sencha service — Edomae sushiya often serve hojicha or sencha throughout",
     "authority_tier": 1, "source_text": "Jiro Ono (Sukiyabashi Jiro) service philosophy; Ippodo Tea sushi pairing"},
    {"beverage_product_id": 213, "beverage_category": "tea",
     "beverage_style": "Premium first flush sencha — grassy, clean, umami",
     "beverage_description": "Vivid green, steamed hay, sweet grass, ocean mineral, moderate astringency",
     "food_category": "vegetable_japanese", "food_flavour_profile": "earthy-delicate",
     "food_description": "Agedashi tofu — silken tofu, dashi broth, grated daikon, bonito flake, nori",
     "pairing_type": "complement", "meal_context": "starter",
     "flavour_logic": "Sencha's grassiness and dashi-like umami mirrors the bonito-dashi broth in agedashi tofu. Shared Japanese flavour language creates natural resonance.",
     "confidence": "established", "confidence_rationale": "Classical Japanese small plate and sencha pairing at izakaya and ryokan",
     "authority_tier": 2, "source_text": "Japanese tea guide (NHK World); Ippodo pairing notes for savory courses"},

    # Nishide Honyama Fukamushi Sencha (215)
    {"beverage_product_id": 215, "beverage_category": "tea",
     "beverage_style": "Fukamushi deep-steamed sencha — Shizuoka, Honyama",
     "beverage_description": "Cloudy green, thick, less astringent, forest, sweet grass, lower altitude terroir",
     "food_category": "tempura", "food_flavour_profile": "light-crispy",
     "food_description": "Shiso and prawn tempura — light batter, tempura dipping sauce (tentsuyu), grated daikon",
     "pairing_type": "cleanse", "meal_context": "main",
     "flavour_logic": "Deep-steamed sencha's reduced astringency and thick texture makes it ideal during frying — it cleanses oil without the harshness of standard sencha. The grassiness enhances shiso.",
     "confidence": "suggested", "confidence_rationale": "Fukamushi sencha and tempura — modern Japanese pairings explored by Shizuoka producers",
     "authority_tier": 2, "source_text": "Nishide Honyama tea estate pairing guide; Japanese Tea Export Council"},

    # Ippodo Uji Hojicha (218)
    {"beverage_product_id": 218, "beverage_category": "tea",
     "beverage_style": "Hojicha — roasted green tea, Ippodo Uji",
     "beverage_description": "Caramel, toasted rice, warm spice, low tannin, amber colour — accessible, soothing",
     "food_category": "chocolate_dark", "food_flavour_profile": "bitter-roasted",
     "food_description": "Hojicha panna cotta — hojicha-infused cream, roasted sesame, caramel sauce",
     "pairing_type": "complement", "meal_context": "dessert",
     "flavour_logic": "Hojicha's roasted, caramel character makes it the most food-friendly Japanese tea. Mirroring it back in the panna cotta creates a layered, tightly integrated dessert course.",
     "confidence": "established", "confidence_rationale": "Hojicha dessert pairings increasingly common in modern Japanese-French pâtisserie",
     "authority_tier": 2, "source_text": "Pâtisserie Sadaharu Aoki hojicha pastry programme; Ippodo Tea dessert guide"},
    {"beverage_product_id": 218, "beverage_category": "tea",
     "beverage_style": "Roasted hojicha — warm, low caffeine, nutty caramel",
     "beverage_description": "Warm amber, toasted grain, caramel, gentle tannin, almost coffee-like warmth",
     "food_category": "savoury_snack", "food_flavour_profile": "umami-salty",
     "food_description": "Onigiri — rice ball with umeboshi or salted salmon filling, nori wrapper",
     "pairing_type": "complement", "meal_context": "casual",
     "flavour_logic": "Hojicha is Japan's most casual, everyday food pairing tea. Onigiri with salty umeboshi or salmon is the archetypal comfort pairing — warm, everyday, deeply Japanese.",
     "confidence": "classic", "confidence_rationale": "The everyday Japanese pairing — hojicha and onigiri consumed across Japan daily",
     "authority_tier": 1, "source_text": "Japanese food culture; convenience store tea pairing canon (Ogawa Coffee research)"},

    # Yamamotoyama Genmaicha (219)
    {"beverage_product_id": 219, "beverage_category": "tea",
     "beverage_style": "Genmaicha — green tea with toasted rice, Yamamotoyama",
     "beverage_description": "Toasted rice, grassy green, nutty, warm, low astringency — approachable Japanese green",
     "food_category": "japanese_breakfast", "food_flavour_profile": "savoury-neutral",
     "food_description": "Tamago kake gohan — raw egg over steamed rice, soy sauce, nori, sesame",
     "pairing_type": "complement", "meal_context": "any",
     "flavour_logic": "Genmaicha's toasted rice note resonates perfectly with the starchy warmth of plain Japanese rice. Egg and soy add protein-umami that bridges the tea's green-grain duality.",
     "confidence": "classic", "confidence_rationale": "Traditional Japanese morning rice and genmaicha pairing — common across Japanese households",
     "authority_tier": 1, "source_text": "Japanese food culture; Yamamotoyama heritage pairing tradition"},

    # Kagoshima Chiran Tamaryokucha (220)
    {"beverage_product_id": 220, "beverage_category": "tea",
     "beverage_style": "Tamaryokucha (Guricha) — Kagoshima Chiran, curled leaf",
     "beverage_description": "Unusual sweet-tartness, citrus, clean floral, unusual in Japanese tea canon",
     "food_category": "citrus_dessert", "food_flavour_profile": "tart-sweet",
     "food_description": "Yuzu tart — custard cream with yuzu curd, shortcrust pastry, edible flowers",
     "pairing_type": "complement", "meal_context": "dessert",
     "flavour_logic": "Tamaryokucha's unusual citrus note and tartness creates affinity with yuzu's bright acidity. Both share a citrus-floral axis rare in Japanese teas — complementary and unusual.",
     "confidence": "suggested", "confidence_rationale": "Modern Japanese-French fusion pairing — tamaryokucha's unusual profile invites contemporary pairings",
     "authority_tier": 2, "source_text": "Kagoshima Tea Federation pairing seminars"},

    # ── BORDEAUX REMAINING (224, 226, 230, 231, 232) ─────────────────────────────
    # Château Mouton Rothschild (224)
    {"beverage_product_id": 224, "beverage_category": "wine_still",
     "beverage_style": "Pauillac Premier Cru — Mouton Rothschild",
     "beverage_description": "Cabernet-dominant — blackcurrant, pencil shavings, cassis, tobacco, cedar, powerful structured tannin",
     "food_category": "lamb_luxury", "food_flavour_profile": "rich-herbal",
     "food_description": "Saddle of Pyrenean lamb — herb-roasted, rosemary jus, Provençal gratin, roasted garlic",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Mouton's Cabernet intensity demands equal weight in the dish. Lamb is the classic Pauillac partner — the richness, herbs, and fat balance the wine's powerful tannin.",
     "confidence": "classic", "confidence_rationale": "Pauillac and lamb — the classic regional pairing of Bordeaux",
     "authority_tier": 1, "source_text": "Mouton Rothschild estate serving recommendations; classic Bordeaux service canon"},
    {"beverage_product_id": 224, "beverage_category": "wine_still",
     "beverage_style": "Mouton Rothschild — artist label bottle, first growth Pauillac",
     "beverage_description": "Intense blackcurrant, graphite, cedar, dense tannin — profound age-worthy Cabernet Sauvignon-dominant blend",
     "food_category": "beef_wagyu", "food_flavour_profile": "rich-mineral",
     "food_description": "Prime-aged beef fillet — 45-day dry-aged, bone marrow crust, truffle jus, potato gratin Dauphinois",
     "pairing_type": "elevate", "meal_context": "main",
     "flavour_logic": "Aged beef's mineral depth and marrow richness mirrors Mouton's graphite-cassis intensity. The truffle jus bridges the earthy tertiary notes developing in the wine.",
     "confidence": "classic", "confidence_rationale": "Great Bordeaux with premium beef — celebrated globally from Noma to Paris",
     "authority_tier": 1, "source_text": "Gordon Ramsay; Joël Robuchon Bordeaux pairing tradition"},

    # Château Margaux Grand Vin (226)
    {"beverage_product_id": 226, "beverage_category": "wine_still",
     "beverage_style": "Margaux Premier Cru — Grand Vin, feminine and silky",
     "beverage_description": "Violets, roses, black cherry, refined tannin — the most feminine of the five first growths",
     "food_category": "poultry_luxury", "food_flavour_profile": "delicate-herbal",
     "food_description": "Pigeon au sang — classic pressed pigeon, blood sauce, foie gras, pomme soufflée",
     "pairing_type": "elevate", "meal_context": "main",
     "flavour_logic": "Margaux's silky, floral-violet profile finds its finest expression with pressed pigeon's concentrated iron-blood flavours. The wine's elegance ensures neither dominates.",
     "confidence": "classic", "confidence_rationale": "Château Margaux and pigeon — classic Parisian grand restaurant pairing",
     "authority_tier": 1, "source_text": "Alain Ducasse; La Tour d'Argent pigeon and Margaux tradition"},
    {"beverage_product_id": 226, "beverage_category": "wine_still",
     "beverage_style": "Château Margaux — floral, precise Cabernet from Margaux appellation",
     "beverage_description": "Rose, violet, black cherry, pencil lead — fragrant first growth, longer finish than any",
     "food_category": "venison", "food_flavour_profile": "gamey-herbal",
     "food_description": "Roe deer loin — gently pink, blackberry and elderberry reduction, celeriac purée, wild mushrooms",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Margaux's floral violet notes lift the gamey-iron quality of venison into elegance. Blackberry reduction mirrors the wine's dark fruit; celeriac echoes its mineral backbone.",
     "confidence": "established", "confidence_rationale": "Grand cru Bordeaux and venison — established in haute cuisine pairing tradition",
     "authority_tier": 1, "source_text": "Hélène Darroze; Bordeaux grand cru and game pairings"},

    # Pavillon Blanc de Château Margaux (230)
    {"beverage_product_id": 230, "beverage_category": "wine_still",
     "beverage_style": "Sauvignon Blanc — Margaux estate white, non-appellation Bordeaux",
     "beverage_description": "Refined, mineral, citrus-driven Sauvignon Blanc — less typical Loire pungency, more Bordeaux elegance",
     "food_category": "seafood_luxury", "food_flavour_profile": "mineral-clean",
     "food_description": "Gilt-head bream — whole roasted, fennel, Noilly Prat, fine herbs, sea vegetables",
     "pairing_type": "complement", "meal_context": "fish_course",
     "flavour_logic": "Pavillon Blanc's refined Sauvignon Blanc character makes it ideal with sea bream's clean, mineral flesh. Fennel and Noilly create the anise bridge the wine's herbs suggest.",
     "confidence": "classic", "confidence_rationale": "Classic Bordeaux dry white and fine fish pairing",
     "authority_tier": 1, "source_text": "Château Margaux service notes; classic Bordeaux white fish pairing canon"},

    # Léoville Las Cases Grand Clos (231)
    {"beverage_product_id": 231, "beverage_category": "wine_still",
     "beverage_style": "Saint-Julien Second Growth — Léoville Las Cases, Super Second",
     "beverage_description": "Austere, precise Cabernet — cedar box, dark cassis, graphite, exceptional balance, 'Super Second' quality",
     "food_category": "duck_confit", "food_flavour_profile": "rich-savoury",
     "food_description": "Duck confit — slow-rendered in own fat, crispy skin, Sarladaise potatoes, haricots verts",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Las Cases' precision and structure requires a dish with natural fat to soften its austere tannin in youth. Duck confit provides that richness while its savouriness matches the wine's intensity.",
     "confidence": "established", "confidence_rationale": "Saint-Julien and duck confit — classic Gascon-Bordelais pairing",
     "authority_tier": 2, "source_text": "Bordeaux service tradition; Gascony-Bordeaux food pairing alignment"},

    # Cos d'Estournel (232)
    {"beverage_product_id": 232, "beverage_category": "wine_still",
     "beverage_style": "Saint-Estèphe Second Growth — Cos d'Estournel",
     "beverage_description": "Dark, tannic, structured Saint-Estèphe — blackberry, iron, tobacco, structured tannin, highest Merlot of Left Bank firsts",
     "food_category": "beef_braised", "food_flavour_profile": "rich-savoury",
     "food_description": "Wagyu beef shin — 24-hour braise in Cos d'Estournel, mushroom duxelles, bone marrow, truffle",
     "pairing_type": "bridge", "meal_context": "main",
     "flavour_logic": "Braising in Cos d'Estournel and serving the same wine creates a seamless bridge. The wine softens in the braise while the finished dish reflects back its blackberry-truffle character.",
     "confidence": "established", "confidence_rationale": "Cook-with-the-wine-serve-the-wine pairing principle — amplification through repetition",
     "authority_tier": 2, "source_text": "Cos d'Estournel hospitality table tradition; Bordeaux chef pairing notes"},

    # ── Jaboulet La Chapelle Hermitage (236) ────────────────────────────────────
    {"beverage_product_id": 236, "beverage_category": "wine_still",
     "beverage_style": "Hermitage Rouge — Jaboulet La Chapelle, Northern Rhône Syrah",
     "beverage_description": "Iron, olive, smoked meat, black pepper, violets — powerful structured Northern Rhône Syrah",
     "food_category": "lamb_rack", "food_flavour_profile": "herbal-smoky",
     "food_description": "Rack of lamb — herb and hazelnut crust, olive tapenade, grilled courgette, jus gras",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Hermitage's iron and smoked meat character resonates with lamb's mineral richness. Herb crust echoes the wine's tapenade-olive note; olive tapenade creates explicit bridge.",
     "confidence": "classic", "confidence_rationale": "Hermitage Rouge and lamb — the great Northern Rhône pairing",
     "authority_tier": 1, "source_text": "Jaboulet estate service notes; Northern Rhône food pairing tradition"},
    {"beverage_product_id": 236, "beverage_category": "wine_still",
     "beverage_style": "La Chapelle Hermitage — powerful, long-lived Syrah from Tain l'Hermitage",
     "beverage_description": "Black olive, smoked bacon, violets, crème de cassis — dense, age-worthy, 20-year potential",
     "food_category": "game_red", "food_flavour_profile": "gamey-rich",
     "food_description": "Wild boar stew — slow-braised, juniper berries, red wine, root vegetables, gremolata",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Wild boar's gamey intensity meets Hermitage's muscular, spicy Syrah as equals. Juniper's resinous note mirrors the wine's peppery-spiced character beautifully.",
     "confidence": "established", "confidence_rationale": "Northern Rhône Syrah and game — Ardèche hunting tradition pairing",
     "authority_tier": 2, "source_text": "Northern Rhône hunting lodge tradition; Michel Chapoutier game pairing notes"},

    # ── PU-ERH TEAS (247-251) ───────────────────────────────────────────────────
    # Dayi 7542 Sheng Raw Pu-erh (247)
    {"beverage_product_id": 247, "beverage_category": "tea",
     "beverage_style": "Sheng (raw) pu-erh cake — Dayi 7542 benchmark blend",
     "beverage_description": "Young: bitter, floral, camphor, green; aged: earth, autumn leaves, mushroom, complex sweetness",
     "food_category": "dim_sum", "food_flavour_profile": "savoury-oily",
     "food_description": "Yum cha dim sum — char siu bao, har gow, siu mai, rice noodle rolls, turnip cake",
     "pairing_type": "cleanse", "meal_context": "any",
     "flavour_logic": "Sheng pu-erh's polyphenol-rich bitterness cuts through the oils and fats in Cantonese dim sum. The traditional yum cha service (literally 'drink tea') is built around this pairing.",
     "confidence": "classic", "confidence_rationale": "The foundation of Cantonese yum cha culture — tea and dim sum are inseparable",
     "authority_tier": 1, "source_text": "Hong Kong yum cha tradition; Tea Handbook of Cantonese Tea Service"},
    {"beverage_product_id": 247, "beverage_category": "tea",
     "beverage_style": "Aged sheng pu-erh — complex, earthy, aged fermentation",
     "beverage_description": "Aged: forest floor, dried longan, camphor, ancient earth — remarkable complexity in old cakes",
     "food_category": "aged_cheese", "food_flavour_profile": "complex-funky",
     "food_description": "Époisses de Bourgogne — washed rind, intensely pungent, creamy, straw-yellow",
     "pairing_type": "complement", "meal_context": "cheese",
     "flavour_logic": "Both aged pu-erh and Époisses develop extraordinary complexity through microbial fermentation over years. The shared transformation aesthetic creates a global fermentation summit.",
     "confidence": "adventurous", "confidence_rationale": "Cross-cultural fermentation pairing — East-West aged ferment combination",
     "authority_tier": 3, "source_text": "Max McCalman cheese + tea pairing explorations; Rare Tea Company pairings"},

    # Dayi 7572 Shou Ripe Pu-erh (248)
    {"beverage_product_id": 248, "beverage_category": "tea",
     "beverage_style": "Shou (ripe) pu-erh — wet-pile fermented, dark, earthy",
     "beverage_description": "Deep mahogany, wet earth, mushroom, longan sweetness, smooth texture — no bitterness",
     "food_category": "chinese_roast", "food_flavour_profile": "savoury-caramelised",
     "food_description": "Cantonese roast duck — char siu-glazed, crispy skin, plum sauce, mantou buns",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Shou pu-erh's earthy, smooth, fungal complexity is the traditional accompaniment to oily Cantonese roast meats. The dark liquor and duck fat create deep savoury resonance.",
     "confidence": "classic", "confidence_rationale": "Traditional Cantonese roast duck with shou pu-erh — Hong Kong restaurant culture",
     "authority_tier": 1, "source_text": "Cantonese restaurant tea service tradition; Hong Kong Tea Council"},
    {"beverage_product_id": 248, "beverage_category": "tea",
     "beverage_style": "Ripe pu-erh — dark, smooth, digestive",
     "beverage_description": "Wet earth, mushroom, dark molasses, smooth with no bitterness — digestive powerhouse",
     "food_category": "chocolate_dark", "food_flavour_profile": "bitter-intense",
     "food_description": "Valrhona Guanaja 70% dark chocolate — intense, long bitter finish, red fruit notes",
     "pairing_type": "complement", "meal_context": "dessert",
     "flavour_logic": "Shou pu-erh's earthy depth mirrors dark chocolate's bitter-roast complexity. Both are acquired tastes with time-developed complexity — they share a fermentation and ageing register.",
     "confidence": "established", "confidence_rationale": "Pu-erh and dark chocolate pairing explored widely in Yunnan and tea bars globally",
     "authority_tier": 2, "source_text": "Yunnan Sourcing tea pairing notes; TeaVivre dark chocolate pairing guide"},

    # Yunnan Sourcing Yiwu Ancient Tree Sheng Pu-erh (249)
    {"beverage_product_id": 249, "beverage_category": "tea",
     "beverage_style": "Single-origin Yiwu ancient tree sheng pu-erh",
     "beverage_description": "Gentle, floral, apricot, aged honeysuckle — more elegant than typical sheng, from thousand-year trees",
     "food_category": "honey_dessert", "food_flavour_profile": "floral-sweet",
     "food_description": "Baklava — walnuts, pistachios, phyllo, wildflower honey, orange blossom syrup",
     "pairing_type": "complement", "meal_context": "dessert",
     "flavour_logic": "Yiwu ancient tree's floral-honey profile resonates with baklava's honey and nut sweetness. The tea's gentle bitterness cleanses the pastry's sticky richness between bites.",
     "confidence": "suggested", "confidence_rationale": "Cross-cultural pairing: Yunnan ancient tree pu-erh and Middle Eastern pastry — both honey-forward",
     "authority_tier": 3, "source_text": "Yunnan Sourcing international pairing explorations; New York tea salon pairings"},

    # ── WUYI ROCK OOLONGS (252-254) ──────────────────────────────────────────────
    # Da Hong Pao Rock Oolong (252)
    {"beverage_product_id": 252, "beverage_category": "tea",
     "beverage_style": "Zhengyan Da Hong Pao rock oolong — Wuyi Shan",
     "beverage_description": "Roasted, dark, mineral rock-base note (yancha), dried plum, orchid, charcoal, persistent finish",
     "food_category": "beef_aged", "food_flavour_profile": "savoury-mineral",
     "food_description": "Dry-aged prime rib — 60-day dry-aged, au jus, Yorkshire pudding, roasted bone marrow",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Da Hong Pao's mineral 'rock taste' (yanwei) pairs with the mineral depth of aged beef. Both have extended production processes creating complex Maillard/fermentation flavour development.",
     "confidence": "adventurous", "confidence_rationale": "East-West premium pairing concept based on mineral and fermentation parallels",
     "authority_tier": 3, "source_text": "World Tea Forum Wuyi oolong pairing explorations; contemporary tea sommelier pairings"},
    {"beverage_product_id": 252, "beverage_category": "tea",
     "beverage_style": "Da Hong Pao — high-fire charcoal roasted Wuyi oolong",
     "beverage_description": "Dark, roasted, mineral — orchid sweetness beneath charcoal, dried longan, long aftertaste",
     "food_category": "mushroom_dried", "food_flavour_profile": "earthy-umami",
     "food_description": "Dried shiitake congee — rice porridge with reconstituted shiitake, ginger, sesame oil, scallion",
     "pairing_type": "complement", "meal_context": "any",
     "flavour_logic": "Da Hong Pao's roasted-earthy character mirrors shiitake's deep forest umami. Both tea and mushroom share Maillard roast-earth notes — natural resonance across registers.",
     "confidence": "established", "confidence_rationale": "Classic Chinese tea house pairing — rock oolong and dried mushroom congee",
     "authority_tier": 2, "source_text": "Wuyi Shan tea culture; Fujian cuisine mushroom-yancha pairing tradition"},

    # Rou Gui Cinnamon Rock Oolong (254)
    {"beverage_product_id": 254, "beverage_category": "tea",
     "beverage_style": "Rou Gui rock oolong — Wuyi, spicy, cinnamon-forward",
     "beverage_description": "Distinctive cinnamon-spice aroma, roasted, mineral — more aromatic and pungent than other rock oolongs",
     "food_category": "pork_five_spice", "food_flavour_profile": "spiced-rich",
     "food_description": "Red-braised pork belly (hong shao rou) — Sichuan peppercorn, star anise, cinnamon, soy, rock sugar",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Rou Gui (cinnamon) and red-braised pork's five-spice profile share the same cinnamon-spice register. The tea cuts the pork fat; spice harmonics amplify in both directions.",
     "confidence": "established", "confidence_rationale": "Classic Fujian-style pairing — spiced oolong with red-braised pork",
     "authority_tier": 2, "source_text": "Fujian cuisine and Wuyi oolong pairing tradition; Yunnan Sourcing pairing guide"},

    # ── SILVER NEEDLE & WHITE TEAS (256-257) ────────────────────────────────────
    # Song Tea Fuding Bai Hao Yin Zhen (256)
    {"beverage_product_id": 256, "beverage_category": "tea",
     "beverage_style": "Fuding Silver Needle white tea — Song Tea & Ceramics",
     "beverage_description": "Ultra-delicate — snow, peach blossom, white melon, honeydew, feather-light sweetness",
     "food_category": "seafood_delicate", "food_flavour_profile": "delicate-sweet",
     "food_description": "Dungeness crab chawanmushi — steamed egg custard, crab, dashi, yuzu foam",
     "pairing_type": "complement", "meal_context": "starter",
     "flavour_logic": "Silver Needle's gossamer delicacy requires an equally gentle food partner. Crab chawanmushi's silky sweetness won't compete; both share melon and oceanic sweetness.",
     "confidence": "suggested", "confidence_rationale": "Modern high-end pairing: Chinese silver needle with Japanese technique",
     "authority_tier": 2, "source_text": "Song Tea & Ceramics tasting notes; Peter Luger tea pairing explorations"},
    {"beverage_product_id": 256, "beverage_category": "tea",
     "beverage_style": "Silver Needle — the most delicate of all white teas",
     "beverage_description": "White peach, snow, honeydew, green floral — barely there, ethereal",
     "food_category": "fruit_delicate", "food_flavour_profile": "floral-sweet",
     "food_description": "White peach sorbet — Prunus persica, elderflower, champagne, mint chiffonade",
     "pairing_type": "complement", "meal_context": "pre_dessert",
     "flavour_logic": "The shared white peach note between Silver Needle and the sorbet creates a pure complement at the dessert interlude. Both expressions of the same fruit flavour — one frozen, one infused.",
     "confidence": "established", "confidence_rationale": "Silver Needle and white peach — the fruit-tea complement most often cited in tea pairing literature",
     "authority_tier": 2, "source_text": "Rare Tea Company; Sarah Maclean tea pairing notes"},

    # ── TIEGUANYIN (258-259) ─────────────────────────────────────────────────────
    # Song Tea Anxi Tieguanyin Charcoal Roasted (258)
    {"beverage_product_id": 258, "beverage_category": "tea",
     "beverage_style": "Traditional charcoal-roasted Tieguanyin — Anxi, Song Tea",
     "beverage_description": "Roasted orchid, caramel, stone fruit, honey, long toasted finish — very different from jade style",
     "food_category": "pork_roasted", "food_flavour_profile": "caramelised-savoury",
     "food_description": "Peking duck — two service: pancakes/hoisin/scallion, then duck carcass congee",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Charcoal-roasted Tieguanyin's caramel-roast notes perfectly match Peking duck's lacquered skin and hoisin sweetness. The orchid note cuts through duck fat with elegance.",
     "confidence": "established", "confidence_rationale": "Traditional Northern Chinese roast duck and oolong tea — Cantonese and Fujian service tradition",
     "authority_tier": 2, "source_text": "Beijing Quanjude service tradition; Song Tea pairing notes"},

    # Song Tea Tieguanyin Jade Green (259)
    {"beverage_product_id": 259, "beverage_category": "tea",
     "beverage_style": "Modern jade green Tieguanyin — light oxidised, floral",
     "beverage_description": "Bright green, fresh orchid flower, milky sweet, lightly oxidised — very popular modern style",
     "food_category": "seafood_steamed", "food_flavour_profile": "clean-sweet",
     "food_description": "Steamed rock cod — ginger, scallion, soy, sesame oil — classic Cantonese steamed fish",
     "pairing_type": "complement", "meal_context": "fish_course",
     "flavour_logic": "Jade Tieguanyin's fresh floral sweetness matches steamed fish's clean, delicate character. The orchid note complements ginger and scallion without competing.",
     "confidence": "classic", "confidence_rationale": "Traditional Cantonese steamed fish and light oolong — a time-honoured pairing",
     "authority_tier": 1, "source_text": "Cantonese tea service tradition; Hong Kong restaurant culture"},

    # ── LONGJING DRAGON WELL (260-262) ──────────────────────────────────────────
    # West Lake Longjing Mingqian (260)
    {"beverage_product_id": 260, "beverage_category": "tea",
     "beverage_style": "Pre-Qingming Longjing Dragon Well — highest tribute grade",
     "beverage_description": "Chestnut, fresh grass, butter, clean sweetness — jade green with the tightest flat needle shape",
     "food_category": "shrimp_hangzhou", "food_flavour_profile": "clean-sweet",
     "food_description": "Longjing river shrimp (龙井虾仁) — Hangzhou speciality, blanched river shrimp, Longjing leaves, rice wine",
     "pairing_type": "bridge", "meal_context": "main",
     "flavour_logic": "Longjing tea shrimp is the most famous Chinese tea-in-cooking recipe. The same tea cooked into the dish and served alongside creates perfect circular integration.",
     "confidence": "classic", "confidence_rationale": "Longjing shrimp is the iconic Hangzhou regional dish — inseparable from Dragon Well tea",
     "authority_tier": 1, "source_text": "Hangzhou culinary tradition; Lou Wai Lou restaurant; Chinese Tea Classic — Lu Yu"},
    {"beverage_product_id": 260, "beverage_category": "tea",
     "beverage_style": "Longjing Mingqian — the pinnacle of Chinese green tea",
     "beverage_description": "Buttery chestnut, grass, fleeting sweetness — demanding impeccable water temperature control",
     "food_category": "tofu_silken", "food_flavour_profile": "delicate-neutral",
     "food_description": "Mapo tofu — Sichuan silken tofu, doubanjiang, Sichuan pepper, ground pork, sesame oil",
     "pairing_type": "cleanse", "meal_context": "main",
     "flavour_logic": "The grassy, buttery Longjing cleanses the mouth between bites of fiery Mapo Tofu, providing cooling contrast to Sichuan mala heat. The tea's gentle sweetness recalibrates the palate.",
     "confidence": "suggested", "confidence_rationale": "Green tea and spicy Chinese food pairing — widely explored in Sichuan-Zhejiang fusion contexts",
     "authority_tier": 3, "source_text": "Regional Chinese tea culture pairing explorations"},

    # ── PHOENIX DANCONG (263-265) ────────────────────────────────────────────────
    # Phoenix Mi Lan Xiang Honey Orchid (263)
    {"beverage_product_id": 263, "beverage_category": "tea",
     "beverage_style": "Mi Lan Xiang (Honey Orchid) Dancong — Phoenix Mountain",
     "beverage_description": "Sweet orchid, honey, lychee, tropical fruit — seductive aromatic, medium oxidation",
     "food_category": "fruit_tropical", "food_flavour_profile": "floral-tropical",
     "food_description": "Lychee panna cotta — coconut cream, lychee rose water gel, fresh passion fruit",
     "pairing_type": "complement", "meal_context": "dessert",
     "flavour_logic": "Mi Lan Xiang's lychee-honey aromatics have perfect affinity with the dessert's shared lychee note. The orchid floral ties the panna cotta's rose water note in a harmonious floral-tropical pairing.",
     "confidence": "established", "confidence_rationale": "Honey Orchid Dancong and lychee — shared aromatic profile, established in Teahouse pairings in Guangdong and Hong Kong",
     "authority_tier": 2, "source_text": "Chaozhou teahouse tradition; Guangdong tea pairing culture"},
    {"beverage_product_id": 263, "beverage_category": "tea",
     "beverage_style": "Honey Orchid Dancong — premium single-cultivar Phoenix oolong",
     "beverage_description": "Honey, orchid, mango, tropical sweetness — very high aroma, medium body",
     "food_category": "seafood_grilled", "food_flavour_profile": "light-aromatic",
     "food_description": "Grilled tiger prawns — lemongrass, coconut milk marinade, nam jim, micro herbs",
     "pairing_type": "complement", "meal_context": "starter",
     "flavour_logic": "Mi Lan Xiang's tropical aromatic resonates with lemongrass and coconut's Southeast Asian profile. Both share floral sweetness; the tea's honey note mirrors the coconut richness.",
     "confidence": "suggested", "confidence_rationale": "Phoenix Dancong and Thai-style seafood — modern cross-cultural pairing",
     "authority_tier": 2, "source_text": "David Lai (Ooteas) pairing explorations; Phoenix Dancong international pairing events"},

    # Ya Shi Xiang Duck Shit Dancong (264)
    {"beverage_product_id": 264, "beverage_category": "tea",
     "beverage_style": "Ya Shi Xiang (Duck Shit) Dancong — intensely aromatic single cultivar",
     "beverage_description": "Intensely aromatic — gardenia, wet stone, faint barnyard, floral-mineral, unusual complexity",
     "food_category": "cheese_washed", "food_flavour_profile": "funky-aromatic",
     "food_description": "Taleggio — Italian washed rind, barnyard, slightly funky, fatty, melting texture",
     "pairing_type": "complement", "meal_context": "cheese",
     "flavour_logic": "Ya Shi Xiang's legendary slight barnyard-floral note finds natural affinity with Taleggio's washed-rind funk. Both intensely aromatic; both acquired tastes with curious names.",
     "confidence": "adventurous", "confidence_rationale": "Unconventional pairing — both prized for unusual aromas that challenge and reward",
     "authority_tier": 3, "source_text": "World Tea Expo pairing exploration; Rare Tea Company cheese pairing guide"},

    # Floating Leaves Tea Fenghuang Old Bush (266)
    {"beverage_product_id": 266, "beverage_category": "tea",
     "beverage_style": "Old bush Fenghuang Dancong — multi-cultivar blend, Seattle import",
     "beverage_description": "Complex layered aromatics — stone fruit, wildflower, mineral, oak-like depth from old bush",
     "food_category": "fruit_stone", "food_flavour_profile": "stone_fruit",
     "food_description": "White nectarine tarte tatin — caramelised stone fruit, crème fraîche, candied almonds",
     "pairing_type": "complement", "meal_context": "dessert",
     "flavour_logic": "Old bush Dancong's stone fruit note matches caramelised nectarine's sweet-acid profile. The tea's wildflower aromatics mirror the tarte's floral pastry register.",
     "confidence": "suggested", "confidence_rationale": "Old bush oolong and stone fruit dessert — aromatic resonance pairing",
     "authority_tier": 2, "source_text": "Floating Leaves Tea pairing notes; Wes Schilling tea pairing guide"},

    # Rishi Tea Pu-erh Dante Blend (267)
    {"beverage_product_id": 267, "beverage_category": "tea",
     "beverage_style": "Blended ripe pu-erh — Rishi Tea accessible format",
     "beverage_description": "Smooth, earthy, digestive — accessible pu-erh with rounded profile and lower price point",
     "food_category": "chocolate_milk", "food_flavour_profile": "sweet-dairy",
     "food_description": "Milk chocolate truffles — ganache centre, dusted with cocoa, slight sea salt",
     "pairing_type": "complement", "meal_context": "dessert",
     "flavour_logic": "Blended ripe pu-erh's smooth earthy character balances milk chocolate's sweetness without overpowering. More accessible than premium aged pu-erh, ideal for introduction to the pairing.",
     "confidence": "established", "confidence_rationale": "Ripe pu-erh and chocolate — widely accessible pairing in Western tea culture",
     "authority_tier": 2, "source_text": "Rishi Tea pairing notes; American tea culture pairing explorations"},

    # Rishi Organic Wuyi Black (Lapsang Souchong) (269)
    {"beverage_product_id": 269, "beverage_category": "tea",
     "beverage_style": "Wuyi Lapsang Souchong — pine-smoked black tea, Rishi",
     "beverage_description": "Pine smoke, dried longan, whisky peat-like note — intensely smoky, complex, polarising",
     "food_category": "smoked_protein", "food_flavour_profile": "smoky-savoury",
     "food_description": "Cold-smoked Pacific salmon — with cream cheese, preserved lemon, caperberries, pumpernickel",
     "pairing_type": "complement", "meal_context": "starter",
     "flavour_logic": "Lapsang Souchong's pine smoke harmonic with the smoke register of cold-smoked salmon is a famous pairing — both carry woodland smoke notes that amplify each other.",
     "confidence": "classic", "confidence_rationale": "Lapsang Souchong and smoked salmon — the most widely cited tea-food pairing in British food culture",
     "authority_tier": 1, "source_text": "Fortnum & Mason; Twinings pairing tradition; Heston Blumenthal Lapsang Souchong smoking experiments"},
    {"beverage_product_id": 269, "beverage_category": "tea",
     "beverage_style": "Lapsang Souchong — pine-smoked Wuyi black",
     "beverage_description": "Deep pine smoke, dried fruit, dark molasses note beneath the smoke",
     "food_category": "scotch_eggs", "food_flavour_profile": "savoury-smoky",
     "food_description": "Smoked duck egg Scotch egg — smoked duck egg, rare quail centre, black pepper crust, HP sauce",
     "pairing_type": "complement", "meal_context": "amuse",
     "flavour_logic": "Lapsang Souchong's smoke character creates a thematic pairing with smoked egg. Both carry smokehouse aromatics; the tea's dried fruit base contrasts the eggy richness.",
     "confidence": "established", "confidence_rationale": "British smoked food culture and Lapsang Souchong — smoked protein and smoky tea natural harmony",
     "authority_tier": 2, "source_text": "Rare Tea Company UK; Heston Blumenthal smoked tea experiments"},
]

SQL = """
INSERT INTO pairing_intelligence (
    beverage_product_id, beverage_category, beverage_style, beverage_description,
    food_category, food_flavour_profile, food_description,
    pairing_type, meal_context, flavour_logic,
    confidence, confidence_rationale, authority_tier, source_text
) VALUES (
    %(beverage_product_id)s, %(beverage_category)s, %(beverage_style)s, %(beverage_description)s,
    %(food_category)s, %(food_flavour_profile)s, %(food_description)s,
    %(pairing_type)s, %(meal_context)s, %(flavour_logic)s,
    %(confidence)s, %(confidence_rationale)s, %(authority_tier)s, %(source_text)s
) RETURNING id, beverage_product_id
"""

conn = psycopg2.connect(CONN)
inserted = 0

for p in PAIRINGS:
    try:
        cur = conn.cursor()
        cur.execute(SQL, p)
        result = cur.fetchone()
        conn.commit()
        if result:
            inserted += 1
            print(f"  INSERT pairing id={result[0]}: bev={result[1]} + {p['food_description'][:50]}")
    except Exception as e:
        conn.rollback()
        print(f"  ERROR bev={p['beverage_product_id']}: {e}")

conn.close()
print(f"\nDone. {inserted} pairings inserted.")
