#!/usr/bin/env python3
"""
Terminal 4 — Batch 11: Remaining pairing intelligence for products without pairings:
178 (Henschke), 181 (Catena Fortuna Terrae), 182 (Sadie Columella), 300 (Dagueneau),
308 (Trimbach), 309 (Zind-Humbrecht), 316 (Marcel Deiss), 319 (Hine XO),
322 (Ricard Pastis), 324 (Lemorton Calvados), 333 (Ceretto Barolo), 336 (Ornellaia),
347 (Fernet-Branca), 352 (Pingus), 359 (Lustau Palo Cortado), 361 (Equipo Amontillado),
366 (Plomari Ouzo)
"""
import psycopg2

CONN = "postgres://provenance_tester_1:GBN1MbQJMbe_7Ze2Is6dZQSK4hGwXkbW@localhost:15432/provenance_tester_1?sslmode=disable"

PAIRINGS = [
    # Henschke Hill of Grace Shiraz (178)
    {"beverage_product_id": 178, "beverage_category": "wine_still",
     "beverage_style": "Eden Valley single-vineyard Shiraz — Henschke, pre-1860 vines",
     "beverage_description": "Iron, earth, dark chocolate, smoked violet, exceptional density — from the world's oldest Shiraz vines",
     "food_category": "lamb_roast", "food_flavour_profile": "rich-herbal",
     "food_description": "Roasted leg of Barossa lamb — slow-roasted, rosemary and garlic, jus gras, roasted root vegetables",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Hill of Grace's extraordinary density requires equally weighty food. Barossa lamb's regional provenance creates a place-based bridge — Eden Valley Shiraz with Barossa lamb is a portrait of South Australia.",
     "confidence": "classic", "confidence_rationale": "Single-vineyard Australian Shiraz with regional lamb — the iconic SA pairing",
     "authority_tier": 1, "source_text": "Henschke estate serving recommendations; South Australian food and wine regional tradition"},
    {"beverage_product_id": 178, "beverage_category": "wine_still",
     "beverage_style": "Hill of Grace — old vine Shiraz from the oldest Shiraz in the world",
     "beverage_description": "Dark chocolate, smoked earth, aged leather, magnificent tannic structure, decades of potential",
     "food_category": "beef_aged", "food_flavour_profile": "rich-mineral",
     "food_description": "Dry-aged prime rib — 45-day aged, bone-in, charred exterior, pink centre, bone marrow butter",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "The iron-mineral character of aged beef meets the dark chocolate-iron intensity of ancient vine Shiraz. Both have depth achieved through extended time — aged beef and century-old vine Shiraz.",
     "confidence": "established", "confidence_rationale": "Premium aged beef and old vine Shiraz — establishment pairing at Australia's finest restaurants",
     "authority_tier": 2, "source_text": "Attica; Brae restaurant wine list pairings; Australian fine dining Shiraz tradition"},

    # Catena Zapata Adrianna Vineyard Fortuna Terrae Malbec (181)
    {"beverage_product_id": 181, "beverage_category": "wine_still",
     "beverage_style": "Adrianna Vineyard Malbec — Gualtallary, 1,450m elevation, calcareous soils",
     "beverage_description": "Precise, mineral, high-acid Malbec — violet, graphite, limestone, extraordinary elegance for Argentina",
     "food_category": "beef_asado", "food_flavour_profile": "smoky-rich",
     "food_description": "Argentine asado — grass-fed short rib (costillas de res) over quebracho wood embers, chimichurri, provoleta",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "The Adrianna Vineyard's high-altitude freshness and limestone minerality makes it Argentina's most elegant Malbec. Asado over quebracho wood creates a smoky, rustic counterpoint that grounds the wine's aristocratic precision.",
     "confidence": "classic", "confidence_rationale": "Argentine asado and Malbec — the foundational national pairing; Adrianna's elevation adds complexity",
     "authority_tier": 1, "source_text": "Catena Zapata estate pairing notes; Argentine asado tradition"},
    {"beverage_product_id": 181, "beverage_category": "wine_still",
     "beverage_style": "Fortuna Terrae Malbec — Adrianna calcareous single block, world's highest",
     "beverage_description": "Mineral, precise, violet-dark cherry, graphite, freshness unusual for Mendoza — cool climate high altitude expression",
     "food_category": "lamb_patagonian", "food_flavour_profile": "gamey-herbal",
     "food_description": "Patagonian lamb — Cordero al palo (whole spit-roasted), merquén spice, roasted garlic",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Patagonian lamb's gamey, wild character meets the Adrianna's mineral precision. The cool Patagonian pasture-raised lamb mirrors the high-altitude freshness of the wine. Argentine provenance alignment.",
     "confidence": "established", "confidence_rationale": "High-altitude Malbec with Patagonian lamb — the premium Argentine food and wine pairing",
     "authority_tier": 2, "source_text": "Bodega Catena Zapata; Argentine premium dining tradition (Tegui, Buenos Aires)"},

    # Sadie Family Columella (182)
    {"beverage_product_id": 182, "beverage_category": "wine_still",
     "beverage_style": "Columella — Syrah-dominant Cape blend, Swartland old vine",
     "beverage_description": "Iron, olive, pepper, garrigue, dark berry — Northern Rhône meets the Cape; elegant, structured",
     "food_category": "lamb_spiced", "food_flavour_profile": "rich-spiced",
     "food_description": "Lamb sosaties — skewered and marinated in apricot-curry baste, grilled over wood coals, atjar",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Columella's Swartland Syrah-Mourvèdre intensity mirrors Cape Malay sosaties' complex spice-fruit baste. The wine's olive-iron note with apricot sweetness creates Cape culinary synergy.",
     "confidence": "established", "confidence_rationale": "Cape blend and Cape Malay cooking — the great South African food and wine meeting point",
     "authority_tier": 2, "source_text": "Sadie Family Wines serving notes; South African wine and food pairing tradition (Greenhouse, Cape Town)"},
    {"beverage_product_id": 182, "beverage_category": "wine_still",
     "beverage_style": "Sadie Columella — world-class Cape Syrah-dominant blend from Swartland granite",
     "beverage_description": "Deep purple, iron filings, black olive, violets, wild mountain herbs — age-worthy, structured",
     "food_category": "game_red", "food_flavour_profile": "gamey-earthy",
     "food_description": "Springbok loin — pan-seared, rooibos and berry jus, sweet potato, biltong dust",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Springbok's lean, dark, minerally gaminess pairs exquisitely with Columella's iron-herb-dark berry. Rooibos jus bridges the Cape botanical register in both wine and dish.",
     "confidence": "established", "confidence_rationale": "Cape fine wine and springbok game — prestigious South African fine dining pairing",
     "authority_tier": 1, "source_text": "La Colombe; The Test Kitchen Cape Town pairing tradition"},

    # Didier Dagueneau Pouilly-Fumé Pur Sang (300)
    {"beverage_product_id": 300, "beverage_category": "wine_still",
     "beverage_style": "Pouilly-Fumé — Dagueneau Pur Sang, old vine Sauvignon Blanc, silex soils",
     "beverage_description": "Gunflint, electric precision, white flowers, citrus zest — the most mineral Sauvignon Blanc on earth",
     "food_category": "shellfish_cold", "food_flavour_profile": "mineral-briny",
     "food_description": "Gillardeau oysters (G5) — served natural, shallot mignonette, lemon, black bread",
     "pairing_type": "bridge", "meal_context": "aperitif",
     "flavour_logic": "Dagueneau Pur Sang's silex (flint) soils produce Sauvignon Blanc with gunsmoke and sea-mineral notes that mirror the oyster's briny mineral iodine exactly. The definitive flint-on-flint pairing.",
     "confidence": "classic", "confidence_rationale": "The Loire's most celebrated mineral Sauvignon and oysters — legendary pairing from Dagueneau's own service",
     "authority_tier": 1, "source_text": "Louis-Benjamin Dagueneau estate recommendations; Loire Valley oyster-wine tradition"},
    {"beverage_product_id": 300, "beverage_category": "wine_still",
     "beverage_style": "Pur Sang Pouilly-Fumé — silex terroir, old vine, biodynamic",
     "beverage_description": "Gunflint smoke, green apple, white citrus, electric mineral precision — 10-year ageing potential",
     "food_category": "fish_delicate", "food_flavour_profile": "delicate-mineral",
     "food_description": "Beurre blanc de anguille — smoked eel in beurre blanc, dill, caviar, savoury choux",
     "pairing_type": "complement", "meal_context": "fish_course",
     "flavour_logic": "The smoked eel's smoky, rich, oily character is counterbalanced by Pur Sang's knife-edge acidity and flinty mineral. Caviar amplifies the briny mineral note already present in the Sauvignon.",
     "confidence": "established", "confidence_rationale": "Loire Sauvignon Blanc with smoked fish — classic French fish course pairing",
     "authority_tier": 2, "source_text": "Classic French fish course wine pairings; Loire fine dining tradition"},

    # Trimbach Riesling Cuvée Frédéric Émile (308)
    {"beverage_product_id": 308, "beverage_category": "wine_still",
     "beverage_style": "Alsace Grand Cru Riesling — Trimbach, Rangen and Geisberg blend, CFF benchmark",
     "beverage_description": "Petrol, citrus, mineral slate, steely acid — the great aged Alsace Riesling; extraordinary longevity",
     "food_category": "pork_choucroute", "food_flavour_profile": "rich-fermented",
     "food_description": "Choucroute garnie Alsacienne — fermented Alsatian sauerkraut, smoked pork, Montbéliard sausage, Strasbourg sausage, boiled potato",
     "pairing_type": "bridge", "meal_context": "main",
     "flavour_logic": "CFF Riesling is the definitive Alsatian wine for Alsatian food. Its acidity cuts the pork fat; its mineral precision contrasts the fermented sauerkraut; its petrol-flint note bridges the smoked charcuterie.",
     "confidence": "classic", "confidence_rationale": "The most celebrated Alsatian food and wine pairing — Choucroute Garnie with great Riesling is Alsace's culinary identity",
     "authority_tier": 1, "source_text": "Trimbach estate tradition; Maison Kammerzell Strasbourg wine service; Alsatian gastronomy canon"},
    {"beverage_product_id": 308, "beverage_category": "wine_still",
     "beverage_style": "CFF Riesling — 10-year aged, petrol, minerality, extraordinary precision",
     "beverage_description": "Classic Alsace Riesling with age — kerosene, citrus oil, mineral slate, enormous length",
     "food_category": "fish_rich", "food_flavour_profile": "rich-smoky",
     "food_description": "Truite au Riesling — trout poached in Riesling, cream, shallots, mushrooms, flamed parsley",
     "pairing_type": "bridge", "meal_context": "fish_course",
     "flavour_logic": "Cooking trout in Riesling and then drinking Riesling alongside creates a virtuous cycle — the wine's mineral notes are absorbed by the fish, reflected back in the cream sauce.",
     "confidence": "classic", "confidence_rationale": "Classic Alsatian technique of Riesling-in-the-sauce served with Riesling in the glass",
     "authority_tier": 1, "source_text": "Alsatian fish cooking tradition; Auberge de l'Ill wine service"},

    # Zind-Humbrecht Riesling Clos Windsbuhl (309)
    {"beverage_product_id": 309, "beverage_category": "wine_still",
     "beverage_style": "Grand Cru Riesling — Zind-Humbrecht, Clos Windsbuhl, clay-limestone, biodynamic",
     "beverage_description": "Stony, precise, citrus flower, ginger spice, extraordinary mineral tension — biodynamic old vine intensity",
     "food_category": "shellfish_cooked", "food_flavour_profile": "sweet-mineral",
     "food_description": "Langoustines à la crème d'Alsace — sautéed langoustine tails, Alsace cream sauce, tarragon, finger lemon",
     "pairing_type": "complement", "meal_context": "fish_course",
     "flavour_logic": "Clos Windsbuhl's ginger-mineral note creates perfect affinity with langoustine's subtle sweetness. Cream sauce gives the wine's density something to rest against. Tarragon bridges the herbal register.",
     "confidence": "established", "confidence_rationale": "Alsace grand cru Riesling with langoustine — prestigious Alsatian restaurant pairing",
     "authority_tier": 2, "source_text": "Zind-Humbrecht estate pairing notes; Olivier Nasti (Chambard) Alsace wine service"},

    # Marcel Deiss Bergheim (316)
    {"beverage_product_id": 316, "beverage_category": "wine_still",
     "beverage_style": "Alsace village wine — Marcel Deiss, Bergheim, field blend, multiple varieties co-fermented",
     "beverage_description": "Complex, textured, floral, spice, terroir-led — the field blend approach makes this harder to categorise but extraordinary",
     "food_category": "poultry_roasted", "food_flavour_profile": "rich-complex",
     "food_description": "Poulet rôti aux aromates — whole roasted chicken, herb butter, garlic, shallot, pan jus, endive gratin",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Deiss's field blend complexity (Riesling, Pinot Gris, Gewürztraminer, Muscat co-fermented) suits the layered complexity of roast chicken. No single varietal dominates — both food and wine are about ensemble harmony.",
     "confidence": "suggested", "confidence_rationale": "Jean-Michel Deiss's field blend philosophy pairs best with classically prepared poultry — the ultimate foil for complexity",
     "authority_tier": 2, "source_text": "Marcel Deiss estate philosophy; Jean-Michel Deiss serving recommendations"},

    # Hine Antique XO Premier Cru Cognac (319)
    {"beverage_product_id": 319, "beverage_category": "spirits_brandy",
     "beverage_style": "Premier Cru Cognac — Hine Antique XO, Grande Champagne, old reserve",
     "beverage_description": "Dried apricot, rancio, spiced orange, toasted oak, crystallised ginger — Grande Champagne elegance",
     "food_category": "chocolate_dark", "food_flavour_profile": "bitter-sweet",
     "food_description": "Valrhona Manjari 64% dark chocolate — Madagascar, red fruit, intense bitter-sweet, bright acidity",
     "pairing_type": "complement", "meal_context": "digestif",
     "flavour_logic": "XO Cognac's dried apricot and rancio complexity meets Madagascar chocolate's red fruit-bitter. The oak integration in both Cognac and chocolate creates a shared resonance of wood-tannin ageing.",
     "confidence": "classic", "confidence_rationale": "Cognac XO and dark chocolate — the classic digestif pairing at French grand restaurants",
     "authority_tier": 1, "source_text": "BNIC Cognac pairing guide; Hine estate recommendations; classic French digestif service"},
    {"beverage_product_id": 319, "beverage_category": "spirits_brandy",
     "beverage_style": "Hine Antique XO — Grande Champagne premier cru Cognac",
     "beverage_description": "Complex, multi-decade aged Cognac — citrus peel, beeswax, spiced wood, velvet texture",
     "food_category": "dessert_french", "food_flavour_profile": "rich-caramel",
     "food_description": "Tarte Tatin — caramelised Granny Smith apple, puff pastry, crème fraîche",
     "pairing_type": "complement", "meal_context": "dessert",
     "flavour_logic": "XO Cognac's orchard fruit complexity and caramel notes create affinity with tarte Tatin's caramelised apple. The crème fraîche mirrors the Cognac's dairy-cream register in the barrel.",
     "confidence": "established", "confidence_rationale": "Classic French apple dessert and Cognac — natural Charente and Normandy convergence",
     "authority_tier": 2, "source_text": "French classic dessert pairing tradition; BNIC complementary notes"},

    # Ricard Pastis de Marseille (322)
    {"beverage_product_id": 322, "beverage_category": "spirits_liqueur",
     "beverage_style": "Pastis — Ricard, anise-liquorice aperitif, 5:1 water dilution, Provence",
     "beverage_description": "Anise, star anise, liquorice, pastis aroma — transforms from amber to cloudy white on dilution (louche)",
     "food_category": "seafood_provencal", "food_flavour_profile": "anise-fresh",
     "food_description": "Brandade de morue — Provençal salt cod purée with olive oil, garlic, lemon, served with grilled toast",
     "pairing_type": "complement", "meal_context": "aperitif",
     "flavour_logic": "Pastis and Provençal food is inseparable. Brandade's salt cod, garlic, and olive oil are the food equivalent of pastis's terroir. Both are quintessentially Marseillais.",
     "confidence": "classic", "confidence_rationale": "Pastis and Provençal food — the foundational aperitif-food pairing of southern France",
     "authority_tier": 1, "source_text": "Ricard company history; Marseille food culture; Provence aperitif tradition"},
    {"beverage_product_id": 322, "beverage_category": "spirits_liqueur",
     "beverage_style": "Pastis de Marseille — anise aperitif, served 5:1 with water",
     "beverage_description": "Anise-forward, liquorice, dilution creates louche — Provence in a glass",
     "food_category": "seafood_grilled", "food_flavour_profile": "anise-rich",
     "food_description": "Grilled sea bass (loup de mer) — fennel fronds, pastis beurre blanc, lemon, fleur de sel",
     "pairing_type": "bridge", "meal_context": "fish_course",
     "flavour_logic": "Pastis beurre blanc in the sauce is the ultimate circular bridge — cooking with pastis and drinking pastis. Anise-fennel food register mirrored exactly by the aperitif.",
     "confidence": "established", "confidence_rationale": "Classic Provençal fish and pastis pairing — the fennel-anise bridge is geographic and flavour-based",
     "authority_tier": 2, "source_text": "Provençal cuisine tradition; Gérald Passedat (Le Petit Nice) Pastis pairing notes"},

    # Lemorton Calvados Domfrontais 15 Year (324)
    {"beverage_product_id": 324, "beverage_category": "spirits_brandy",
     "beverage_style": "Calvados Domfrontais — Lemorton, aged 15 years, pear-dominant Domfrontais style",
     "beverage_description": "Ripe pear, baked apple, caramel, vanilla oak — lighter than Pays d'Auge, pear-primary Normandy character",
     "food_category": "cheese_camembert", "food_flavour_profile": "funky-creamy",
     "food_description": "Camembert de Normandie — raw milk, authentic PDO, runny interior, earthy white rind",
     "pairing_type": "complement", "meal_context": "cheese",
     "flavour_logic": "Calvados and Camembert is the quintessential Norman pairing — both from the same hedgerow-orcharded landscape. The brandy's pear-caramel cuts through the cheese's fat and amplifies the earthy-butter note.",
     "confidence": "classic", "confidence_rationale": "Calvados and Norman cheese — the great Normandy food pairing, as regional as Burgundy-Pinot or Loire-Chenin",
     "authority_tier": 1, "source_text": "Bureau National Interprofessionnel du Calvados (BNIC); Norman food tradition"},
    {"beverage_product_id": 324, "beverage_category": "spirits_brandy",
     "beverage_style": "15-year Calvados Domfrontais — Lemorton, pear-dominated aged Calvados",
     "beverage_description": "Baked pear, caramel, gentle oak, floral — Domfrontais style, Perry pear-dominant variety",
     "food_category": "apple_dessert", "food_flavour_profile": "sweet-buttery",
     "food_description": "Trou Normand — apple sorbet with a shot of Calvados, between courses palate cleanser",
     "pairing_type": "bridge", "meal_context": "pre_dessert",
     "flavour_logic": "Trou Normand (the 'Norman hole') is the traditional Norman intermezzo — Calvados poured over apple sorbet clears the palate. The Calvados IS the course: spirit and food unified.",
     "confidence": "classic", "confidence_rationale": "The Trou Normand is the canonical Norman intermezzo service — unchanged for centuries",
     "authority_tier": 1, "source_text": "Norman dining tradition; Escoffier — Le Guide Culinaire trou normand; BNIC service notes"},

    # Ceretto Barolo Bricco Rocche (333)
    {"beverage_product_id": 333, "beverage_category": "wine_still",
     "beverage_style": "Barolo DOCG — Ceretto, Bricco Rocche single vineyard, Castiglione Falletto",
     "beverage_description": "Rose, tar, dried cherry, iron, long-structured tannin — classic Castiglione Falletto Barolo from prestigious cru",
     "food_category": "truffle_white", "food_flavour_profile": "earthy-luxurious",
     "food_description": "Tajarin al tartufo bianco — hand-cut Piemontese egg pasta, shaved Alba white truffle, Parmigiano, unsalted butter",
     "pairing_type": "elevate", "meal_context": "main",
     "flavour_logic": "White truffle and Barolo is the most celebrated pairing in Italian gastronomy — the wine's rose and earth notes echo and amplify the truffle's garlic-honey-earth complexity. Both are from Alba's rolling hills.",
     "confidence": "classic", "confidence_rationale": "Barolo and white truffle — the canonical Piemontese pairing, celebrated in October at the Alba Truffle Fair",
     "authority_tier": 1, "source_text": "Ristorante Il Centro (Priocca); La Contea (Neive) Barolo-truffle pairing tradition; Ceretto estate service"},
    {"beverage_product_id": 333, "beverage_category": "wine_still",
     "beverage_style": "Bricco Rocche Barolo — Ceretto, structured Castiglione Falletto cru",
     "beverage_description": "Tar and roses, cherry stone, iron, mineral — classical Barolo demanding patience but rewarding greatly",
     "food_category": "braised_beef", "food_flavour_profile": "rich-savoury",
     "food_description": "Brasato al Barolo — beef cheek braised in Barolo, porcini, rosemary, cinnamon, served with polenta",
     "pairing_type": "bridge", "meal_context": "main",
     "flavour_logic": "Brasato al Barolo cooks with the wine itself — the braise absorbs Barolo's tannin-fruit character and reflects it back in the sauce. Serving Barolo alongside creates a virtuous circle of amplification.",
     "confidence": "classic", "confidence_rationale": "Brasato al Barolo — the most iconic Piemontese dish, inseparable from the wine that gives it its name",
     "authority_tier": 1, "source_text": "Piemontese culinary tradition; Slow Food Presidia; Ceretto winery bistro menu"},

    # Ornellaia Bolgheri Superiore (336)
    {"beverage_product_id": 336, "beverage_category": "wine_still",
     "beverage_style": "Bolgheri Superiore — Ornellaia, Cabernet Sauvignon dominant, Super Tuscan",
     "beverage_description": "Cassis, tobacco, cedar, dried herbs, silky tannin — the most complete Super Tuscan, Bordeaux-style from Tuscan coast",
     "food_category": "beef_bistecca", "food_flavour_profile": "rich-mineral",
     "food_description": "Bistecca alla Fiorentina — T-bone from Chianina beef, 1.2kg, rare, sea salt, rosemary, lemon",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Ornellaia's Cabernet-Merlot blend brings Bordeaux structure to meet Tuscany's supreme steak. The mineral, lean Chianina beef and the wine's cassis-cedar create the great Tuscan red meat pairing.",
     "confidence": "classic", "confidence_rationale": "Super Tuscan and Bistecca Fiorentina — the iconic Tuscan fine dining pairing",
     "authority_tier": 1, "source_text": "Ornellaia estate recommendations; Buca Mario, Florence; Tuscan fine dining tradition"},
    {"beverage_product_id": 336, "beverage_category": "wine_still",
     "beverage_style": "Ornellaia — Bolgheri's finest, Cabernet Sauvignon-Merlot-Cabernet Franc blend",
     "beverage_description": "Profound, cedar-cassis, graphite, long and structured — Ornellaia is the benchmark Bolgheri expression",
     "food_category": "lamb_chops", "food_flavour_profile": "herbal-charred",
     "food_description": "Scottadito lamb chops — small Tuscan lamb ribs, chargrilled, herbed salt, lemon, roasted peppers",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Ornellaia's Tuscan-Bordeaux hybrid character suits the rustic-elegant lamb chops. The charred herb crust echoes the wine's cedar-herb notes; the lamb fat softens the structured tannin.",
     "confidence": "established", "confidence_rationale": "Tuscan coastal red wine and lamb — established at the Bolgheri wine estate restaurants",
     "authority_tier": 2, "source_text": "Ornellaia estate restaurant La Trattoria di Ornellaia pairing notes"},

    # Fernet-Branca (347)
    {"beverage_product_id": 347, "beverage_category": "spirits_liqueur",
     "beverage_style": "Fernet-Branca — Italian amaro, 27 herbs and spices, Milan, 39% ABV",
     "beverage_description": "Menthol, gentian, myrrh, saffron, intense bitterness, eucalyptus — polarising, acquired taste",
     "food_category": "espresso_coffee", "food_flavour_profile": "bitter-roasted",
     "food_description": "Double espresso — Lavazza ristretto, served with glass of water",
     "pairing_type": "complement", "meal_context": "digestif",
     "flavour_logic": "Fernet-Branca and espresso (a Fernet-espresso or 'correto') is the classic Argentine and Italian digestif ritual. The coffee's roast bitterness mirrors Fernet's herbal intensity. Both are post-meal digestive aids.",
     "confidence": "classic", "confidence_rationale": "Fernet-Branca and espresso — the canonical Italian digestif service and Argentine cultural ritual",
     "authority_tier": 1, "source_text": "Fernet-Branca history; Argentine Fernet culture (national #1 spirit 55% market share); Milan bar tradition"},
    {"beverage_product_id": 347, "beverage_category": "spirits_liqueur",
     "beverage_style": "Fernet-Branca — bitter digestivo amaro, the world's most famous amaro",
     "beverage_description": "Menthol, eucalyptus, iron, herbs, saffron — cleansing, digestive, demanding",
     "food_category": "chocolate_mint", "food_flavour_profile": "bitter-mint",
     "food_description": "After Eight mints — dark chocolate-mint ganache, thin wafer coating",
     "pairing_type": "complement", "meal_context": "digestif",
     "flavour_logic": "Fernet's eucalyptus-menthol note is mirrored exactly in peppermint chocolate. Both are digestive — the mint assists digestion, the Fernet's bitter herbs stimulate the stomach lining. Convergence at the end of service.",
     "confidence": "established", "confidence_rationale": "Bitter amaro and mint chocolate — after-dinner convergence of digestive flavours",
     "authority_tier": 2, "source_text": "Italian digestivo service tradition; amaro and chocolate pairing explorations"},

    # Dominio de Pingus Pingus (352)
    {"beverage_product_id": 352, "beverage_category": "wine_still",
     "beverage_style": "Ribera del Duero — Pingus, Tempranillo vino de garaje, Denmark/Spain",
     "beverage_description": "Extraordinary concentration — dark plum, graphite, tobacco, Mediterranean herb, 25-year ageing potential",
     "food_category": "lamb_roast", "food_flavour_profile": "rich-herbal",
     "food_description": "Lechazo asado — suckling lamb roasted in a wood-fired oven, simple salt seasoning, roasting juices only",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Pingus's extraordinary Tempranillo concentration demands the simplest, purest food. Lechazo — milk-fed suckling lamb, nothing else — lets the wine's complexity lead without competition.",
     "confidence": "classic", "confidence_rationale": "Lechazo asado and Ribera del Duero — the great Castilian food and wine pairing, from Segovia to Burgos",
     "authority_tier": 1, "source_text": "Dominio de Pingus serving recommendations; Mesón de Cándido Segovia tradition"},
    {"beverage_product_id": 352, "beverage_category": "wine_still",
     "beverage_style": "Pingus — Peter Sisseck's icon wine, Spain's 100-point garage wine",
     "beverage_description": "Profound, complex, cassis, graphite, truffle, dried herbs — Spain's most concentrated collectible wine",
     "food_category": "beef_aged", "food_flavour_profile": "mineral-rich",
     "food_description": "Chuletón de buey — Basque Country aged beef chop (buey = retired dairy cow), charcoal-grilled, served on the bone",
     "pairing_type": "elevate", "meal_context": "main",
     "flavour_logic": "The extraordinary depth of aged Basque beef chop (buey) requires Spain's most profound wine to match it. Pingus's graphite-dark plum intensity elevates the mineral beef to its finest expression.",
     "confidence": "established", "confidence_rationale": "Chuletón and great Ribera del Duero — the prestige Spanish beef and wine pairing",
     "authority_tier": 2, "source_text": "Restaurante Elkano (Getaria); Asador Etxebarri Pingus pairing tradition"},

    # Lustau Peninsula Palo Cortado (359)
    {"beverage_product_id": 359, "beverage_category": "wine_fortified",
     "beverage_style": "Palo Cortado — Lustau Peninsula, Jerez DO, dry, oxidatively aged",
     "beverage_description": "Nutty, hazelnut, orange peel, dried fig, elegant dryness — rare Sherry type, Amontillado nose + Oloroso palate",
     "food_category": "cheese_manchego", "food_flavour_profile": "nutty-crystalline",
     "food_description": "Aged Manchego (12+ months) — firm, crystalline, lanolin, hazelnut, paired with quince membrillo",
     "pairing_type": "complement", "meal_context": "cheese",
     "flavour_logic": "Palo Cortado's hazelnut-orange peel note mirrors aged Manchego's lanolin and crystalline hazelnut exactly. Quince membrillo bridges the wine's dried fruit register with sweetness that makes both shine.",
     "confidence": "classic", "confidence_rationale": "Palo Cortado and aged Manchego — the quintessential Spanish cheese and Sherry pairing",
     "authority_tier": 1, "source_text": "Lustau estate recommendations; Jancis Robinson Sherry pairing guide; Julian Jeffs — Sherry"},
    {"beverage_product_id": 359, "beverage_category": "wine_fortified",
     "beverage_style": "Palo Cortado — dry, hazelnut-rich, rare Sherry style",
     "beverage_description": "Nutty, elegant, complex — Amontillado aromatics with Oloroso body; a rare, intermediate Sherry type",
     "food_category": "foie_gras", "food_flavour_profile": "rich-sweet",
     "food_description": "Terrina de foie gras — cold-pressed, Sauternes jelly, brioche, fleur de sel",
     "pairing_type": "complement", "meal_context": "starter",
     "flavour_logic": "The Palo Cortado's nutty dryness creates contrast with foie gras's unctuousness while mirroring the Sauternes jelly's dried fruit register. An unexpected and sophisticated starter pairing.",
     "confidence": "adventurous", "confidence_rationale": "Dry Sherry and foie gras — cross-cultural pairing concept; traditionally Sauternes but Palo Cortado challenges and rewards",
     "authority_tier": 3, "source_text": "Heston Blumenthal Sherry and foie pairing explorations; modern Sherry gastronomy"},

    # Equipo Navazos La Bota de Amontillado (361)
    {"beverage_product_id": 361, "beverage_category": "wine_fortified",
     "beverage_style": "Amontillado — Equipo Navazos La Bota, single cask, en rama, Sherry DO",
     "beverage_description": "Extraordinary depth — roasted hazelnuts, tobacco leaf, dried orange, iodine, infinite length",
     "food_category": "consomme", "food_flavour_profile": "umami-intense",
     "food_description": "Consommé de boeuf — crystal clear double-reduced beef consommé, quail egg, truffle oil, micro chervil",
     "pairing_type": "complement", "meal_context": "amuse",
     "flavour_logic": "Amontillado's savoury, umami-rich complexity mirrors consommé's concentrated beef umami at its most refined. Both are products of extraordinary time and skill — long barrel ageing and patient reduction.",
     "confidence": "established", "confidence_rationale": "Aged Amontillado Sherry and consommé — the Sherry gastronomy pairing explored at Arzak and other San Sebastián restaurants",
     "authority_tier": 2, "source_text": "Arzak Sherry pairing; Fernando Hidalgo Juan Ramón Guillermo service notes; Sherry gastronomy San Sebastián"},
    {"beverage_product_id": 361, "beverage_category": "wine_fortified",
     "beverage_style": "La Bota Amontillado — en rama, single cask, maximum complexity",
     "beverage_description": "The most intense, complex dry Sherry — hazelnut, tobacco, iodine, infinite drying finish, decades in the barrel",
     "food_category": "iberico_ham", "food_flavour_profile": "rich-nutty",
     "food_description": "Jamón Ibérico de Bellota — Pata Negra, 36-month cured, razor-sliced at 3mm, at room temperature",
     "pairing_type": "complement", "meal_context": "aperitif",
     "flavour_logic": "Amontillado and Jamón Ibérico is the quintessential Jerezano pairing — the nutty intensity of hazelnut Sherry with the nutty-mineral-sweet fat of acorn-fed ham. Both are products of southern Spain's sun and time.",
     "confidence": "classic", "confidence_rationale": "Amontillado and Jamón Ibérico — the definitive Jerez pairing, served at every bodega tasting in Spain",
     "authority_tier": 1, "source_text": "Equipo Navazos pairing notes; Jerezano food culture; CRDO Jerez pairing tradition"},

    # Plomari Original Ouzo (366)
    {"beverage_product_id": 366, "beverage_category": "spirits_liqueur",
     "beverage_style": "Ouzo — Plomari Isidoros Arvanitis, Lesvos island, anise-distilled spirit",
     "beverage_description": "Clean anise, white flowers, fennel — transforms to milky white (louche) with ice water; Aegean aperitif ritual",
     "food_category": "mezedes", "food_flavour_profile": "anise-briny",
     "food_description": "Greek mezedes — taramosalata, tzatziki, grilled octopus, saganaki, spanakopita, olives and feta",
     "pairing_type": "complement", "meal_context": "aperitif",
     "flavour_logic": "Ouzo and mezedes is the fundamental Greek aperitif ritual — the anise-herbal spirit amplifies the olive oil, herbs, and seafood of the small plates. The louche (milky dilution) signals the meal has begun.",
     "confidence": "classic", "confidence_rationale": "Ouzo and mezedes — the foundational Greek aperitif culture, unchanged for centuries",
     "authority_tier": 1, "source_text": "Greek Ministry of Rural Development Ouzo PDO rules; Lesvos Ouzo tradition; Plomari estate culture"},
    {"beverage_product_id": 366, "beverage_category": "spirits_liqueur",
     "beverage_style": "Plomari Ouzo — Lesvos, clean anise, served over ice with cold water",
     "beverage_description": "Anise, star anise, fennel — neat (amber) or with ice/water (milky white louche), always chilled",
     "food_category": "grilled_fish", "food_flavour_profile": "clean-smoky",
     "food_description": "Grilled whole Aegean sea bream (tsipoura) — charcoal, lemon, oregano, olive oil, Greek salad",
     "pairing_type": "complement", "meal_context": "main",
     "flavour_logic": "Ouzo's anise-fennel character is the traditional accompaniment to grilled Aegean fish — the spirit's clean herbal cuts through the charcoal smoke while amplifying the Mediterranean herbs dressing the fish.",
     "confidence": "classic", "confidence_rationale": "Ouzo and grilled fish — the essential Greek island dining ritual, from Mykonos to Lesvos",
     "authority_tier": 1, "source_text": "Greek island fishing culture; Plomari village seafood tradition"},
]

SQL = """
INSERT INTO pairing_intelligence (
    beverage_product_id, beverage_category, beverage_style, beverage_description,
    food_category, food_flavour_profile, food_description,
    pairing_type, meal_context, flavour_logic,
    confidence, confidence_rationale, authority_tier, source_text
) VALUES (
    %(beverage_product_id)s, %(beverage_category)s, %(beverage_style)s, %(beverage_description)s,
    %(food_category)s, %(food_flavour_profile)s, %(food_description)s,
    %(pairing_type)s, %(meal_context)s, %(flavour_logic)s,
    %(confidence)s, %(confidence_rationale)s, %(authority_tier)s, %(source_text)s
) RETURNING id, beverage_product_id
"""

conn = psycopg2.connect(CONN)
inserted = 0

for p in PAIRINGS:
    try:
        cur = conn.cursor()
        cur.execute(SQL, p)
        result = cur.fetchone()
        conn.commit()
        if result:
            inserted += 1
            print(f"  INSERT pairing id={result[0]}: bev={result[1]} + {p['food_description'][:50]}")
    except Exception as e:
        conn.rollback()
        print(f"  ERROR bev={p['beverage_product_id']}: {e}")

conn.close()
print(f"\nDone. {inserted} pairings inserted.")
